# Generated by Django 5.2.6 on 2025-10-21 06:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Project", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="signatories",
            name="email",
            field=models.EmailField(
                default="",
                help_text="Email address for sending payment certificates",
                max_length=255,
            ),
            preserve_default=False,
        ),
    ]
