# Generated by Django 5.2.6 on 2025-10-02 14:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Project", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="description",
            field=models.TextField(default=""),
            preserve_default=False,
        ),
    ]
