# Generated by Django 5.2.6 on 2025-11-24 13:33

from django.db import migrations


def populate_portfolios(apps, schema_editor):
    """
    Create a portfolio for each Account and link their projects to it.
    """
    Account = apps.get_model("Account", "Account")
    Portfolio = apps.get_model("Project", "Portfolio")
    Project = apps.get_model("Project", "Project")

    # Iterate through all accounts
    for account in Account.objects.all():
        # Create a new portfolio for this account
        portfolio = Portfolio.objects.create()

        # Add the account to the portfolio's users
        portfolio.users.add(account)

        # Find all projects linked to this account and link them to the portfolio
        projects = Project.objects.filter(account=account)
        for project in projects:
            project.portfolio = portfolio
            project.save()


def reverse_populate_portfolios(apps, schema_editor):
    """
    Reverse the portfolio population by unlinking projects and deleting portfolios.
    """
    Portfolio = apps.get_model("Project", "Portfolio")
    Project = apps.get_model("Project", "Project")

    # Unlink all projects from portfolios
    Project.objects.all().update(portfolio=None)

    # Delete all portfolios
    Portfolio.objects.all().delete()


class Migration(migrations.Migration):
    dependencies = [
        ("Project", "0005_portfolio_project_portfolio"),
        ("Account", "0001_initial"),  # Ensure Account app is available
    ]

    operations = [
        migrations.RunPython(populate_portfolios, reverse_populate_portfolios),
    ]
