# Generated by Django 5.2.6 on 2025-11-24 13:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Project", "0006_create_portfolios"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="portfolio",
            name="users",
            field=models.ManyToManyField(
                null=True, related_name="portfolios", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
