# Generated by Django 5.2.6 on 2025-11-25 08:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Project", "0007_alter_portfolio_users"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="end_date",
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name="project",
            name="start_date",
            field=models.DateField(null=True),
        ),
        migrations.CreateModel(
            name="PlannedValue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When this record was created"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="When this record was last modified"
                    ),
                ),
                (
                    "deleted",
                    models.BooleanField(default=False, help_text="Soft delete flag"),
                ),
                ("period", models.DateField()),
                ("value", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="planned_values",
                        to="Project.project",
                    ),
                ),
            ],
            options={
                "verbose_name": "Planned Value",
                "verbose_name_plural": "Planned Values",
                "ordering": ["period"],
                "unique_together": {("project", "period")},
            },
        ),
    ]
