# Generated by Django 5.2.6 on 2025-12-01 14:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Project", "0010_add_final_payment_certificate_and_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="advance_payment_percentage",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Advance payment percentage",
                max_digits=5,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="advance_recovery_percentage",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Advance recovery percentage per certificate",
                max_digits=5,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="approved_extension_days",
            field=models.IntegerField(
                default=0, help_text="Total approved extension of time in days"
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="contract_duration_days",
            field=models.IntegerField(
                blank=True,
                help_text="Original contract duration in calendar days",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="contractual_completion_date",
            field=models.DateField(
                blank=True, help_text="Original contractual completion date", null=True
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="contractual_start_date",
            field=models.DateField(
                blank=True, help_text="Contractual/possession start date", null=True
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="defects_liability_period",
            field=models.IntegerField(
                blank=True, help_text="Defects liability period in months", null=True
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="final_completion_date",
            field=models.DateField(
                blank=True,
                help_text="Final completion date (end of defects liability)",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="practical_completion_date",
            field=models.DateField(
                blank=True, help_text="Date of practical completion", null=True
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="retention_limit_percentage",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Retention limit as percentage of contract value",
                max_digits=5,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="retention_percentage",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Retention percentage (e.g., 10.00 for 10%)",
                max_digits=5,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="retention_release_practical",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Percentage of retention released at practical completion",
                max_digits=5,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="revised_completion_date",
            field=models.DateField(
                blank=True,
                help_text="Current revised completion date (after extensions)",
                null=True,
            ),
        ),
    ]
