# Generated by Django 5.2.6 on 2025-12-03 09:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Project", "0011_project_advance_payment_percentage_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Milestone",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When this record was created"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="When this record was last modified"
                    ),
                ),
                (
                    "deleted",
                    models.BooleanField(default=False, help_text="Soft delete flag"),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Milestone name/description", max_length=255
                    ),
                ),
                (
                    "planned_date",
                    models.DateField(
                        help_text="Original planned/baseline completion date"
                    ),
                ),
                (
                    "forecast_date",
                    models.DateField(
                        blank=True,
                        help_text="Current forecast completion date",
                        null=True,
                    ),
                ),
                (
                    "reason_for_change",
                    models.TextField(
                        blank=True, help_text="Reason for change in forecast date"
                    ),
                ),
                (
                    "sequence",
                    models.PositiveIntegerField(
                        default=0, help_text="Order of milestone in project timeline"
                    ),
                ),
                (
                    "is_completed",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this milestone has been completed",
                    ),
                ),
                (
                    "actual_date",
                    models.DateField(
                        blank=True,
                        help_text="Actual completion date (when completed)",
                        null=True,
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        help_text="Project this milestone belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="milestones",
                        to="Project.project",
                    ),
                ),
            ],
            options={
                "verbose_name": "Milestone",
                "verbose_name_plural": "Milestones",
                "ordering": ["project", "sequence", "planned_date"],
                "unique_together": {("project", "name")},
            },
        ),
    ]
