# Generated by Django 5.2.6 on 2025-12-03 12:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Project", "0012_milestone"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="signatories",
            options={
                "ordering": ["sequence_number"],
                "verbose_name": "Signatory",
                "verbose_name_plural": "Signatories",
            },
        ),
        migrations.RemoveField(
            model_name="signatories",
            name="email",
        ),
        migrations.RemoveField(
            model_name="signatories",
            name="name",
        ),
        migrations.RemoveField(
            model_name="signatories",
            name="title",
        ),
        migrations.AddField(
            model_name="signatories",
            name="sequence_number",
            field=models.PositiveIntegerField(default="1"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="signatories",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="signatories",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="signatories",
            index=models.Index(
                fields=["project", "sequence_number"],
                name="Project_sig_project_fccd96_idx",
            ),
        ),
    ]
