# Generated by Django 5.2.6 on 2025-12-03 12:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Project", "0013_alter_signatories_options_remove_signatories_email_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="signatories",
            name="role",
            field=models.CharField(default="", max_length=50),
            preserve_default=False,
        ),
    ]
