# Generated by Django 5.2.6 on 2025-12-03 13:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Project", "0014_signatories_role"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="client_representative",
            field=models.ForeignKey(
                blank=True,
                help_text="Client Representative",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="client_rep_projects",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="contractor",
            field=models.ForeignKey(
                blank=True,
                help_text="Contractor responsible for the project",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="contractor_projects",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="lead_consultant",
            field=models.ForeignKey(
                blank=True,
                help_text="Lead Consultant (e.g., Principal Agent)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="lead_consultant_projects",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="quantity_surveyor",
            field=models.ForeignKey(
                blank=True,
                help_text="Quantity Surveyor for the project",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="qs_projects",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
