# Generated by Django 6.0 on 2025-12-10 06:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import app.Project.models.document_models


class Migration(migrations.Migration):
    dependencies = [
        ("Project", "0017_add_work_completed_percent"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ProjectDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When this record was created"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="When this record was last modified"
                    ),
                ),
                (
                    "deleted",
                    models.BooleanField(default=False, help_text="Soft delete flag"),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            (
                                "CONTRACT_DOCUMENTS",
                                "Contract Documents & Appointment Letters",
                            ),
                            (
                                "STAGE_GATE_APPROVAL",
                                "Stage Gate Approval Documentation",
                            ),
                        ],
                        help_text="Category of the document",
                        max_length=30,
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Document title or description", max_length=255
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        help_text="The uploaded document file",
                        upload_to=app.Project.models.document_models.ProjectDocument.upload_to,
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Additional notes about the document",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        help_text="Project this document belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to="Project.project",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who uploaded this document",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="uploaded_project_documents",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Project Document",
                "verbose_name_plural": "Project Documents",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["project", "category"],
                        name="Project_pro_project_3c2a88_idx",
                    ),
                    models.Index(
                        fields=["category"], name="Project_pro_categor_434883_idx"
                    ),
                ],
            },
        ),
    ]
