# Generated by Django 6.0 on 2025-12-10 08:17

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Project', '0019_alter_projectdocument_category'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Risk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When this record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When this record was last modified')),
                ('deleted', models.BooleanField(default=False, help_text='Soft delete flag')),
                ('risk_number', models.PositiveIntegerField(editable=False, help_text='Auto-generated risk number within the project')),
                ('risk_name', models.CharField(help_text='Short name/title for the risk', max_length=255)),
                ('description', models.TextField(help_text='Detailed description of the risk')),
                ('time_impact_start', models.DateField(blank=True, help_text='Start date of potential time impact', null=True)),
                ('time_impact_end', models.DateField(blank=True, help_text='End date of potential time impact', null=True)),
                ('cost_impact', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Potential cost impact in currency', max_digits=15)),
                ('probability', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Probability of risk occurring (0-100%)', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('is_active', models.BooleanField(default=True, help_text='Whether the risk is active or resolved')),
                ('resolved_date', models.DateField(blank=True, help_text='Date when the risk was resolved', null=True)),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this risk', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_risks', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(help_text='Project this risk belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='risks', to='Project.project')),
                ('resolved_by', models.ForeignKey(blank=True, help_text='User who resolved this risk', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_risks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Risk',
                'verbose_name_plural': 'Risks',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['project', 'is_active'], name='Project_ris_project_013550_idx'), models.Index(fields=['project', 'risk_number'], name='Project_ris_project_97e55e_idx')],
                'unique_together': {('project', 'risk_number')},
            },
        ),
    ]
