# Generated by Django 6.0 on 2025-12-11 07:50

import app.Project.models.compliance_models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Project', '0020_risk'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdministrativeCompliance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When this record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When this record was last modified')),
                ('deleted', models.BooleanField(default=False, help_text='Soft delete flag')),
                ('item_type', models.CharField(choices=[('CERTIFICATE', 'Certificate'), ('FORECAST', 'Forecast'), ('VARIATION', 'Variation'), ('CORRESPONDENCE', 'Correspondence'), ('INSTRUCTION', 'Site Instruction'), ('CLAIM', 'Claim'), ('OTHER', 'Other')], help_text='Type of administrative item', max_length=20)),
                ('reference_number', models.CharField(blank=True, default='', help_text='Reference number for this item', max_length=100)),
                ('description', models.CharField(help_text='Description of the item', max_length=500)),
                ('submission_due_date', models.DateField(blank=True, help_text='Due date for submission', null=True)),
                ('submission_date', models.DateField(blank=True, help_text='Actual submission date', null=True)),
                ('approval_due_date', models.DateField(blank=True, help_text='Due date for approval', null=True)),
                ('approval_date', models.DateField(blank=True, help_text='Actual approval date', null=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('UNDER_REVIEW', 'Under Review'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('OVERDUE', 'Overdue')], default='DRAFT', help_text='Current status', max_length=20)),
                ('notes', models.TextField(blank=True, default='', help_text='Additional notes')),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this item', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_administrative_compliance_items', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(help_text='Project this compliance item belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='administrative_compliance_items', to='Project.project')),
                ('responsible_party', models.ForeignKey(blank=True, help_text='Person responsible for this item', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='administrative_compliance_responsibilities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Administrative Compliance',
                'verbose_name_plural': 'Administrative Compliance Items',
                'ordering': ['submission_due_date', '-created_at'],
                'indexes': [models.Index(fields=['project', 'item_type'], name='Project_adm_project_8c966b_idx'), models.Index(fields=['project', 'status'], name='Project_adm_project_d72dcc_idx'), models.Index(fields=['submission_due_date'], name='Project_adm_submiss_fc936f_idx')],
            },
        ),
        migrations.CreateModel(
            name='ContractualCompliance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When this record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When this record was last modified')),
                ('deleted', models.BooleanField(default=False, help_text='Soft delete flag')),
                ('obligation_description', models.CharField(help_text='Description of the contractual obligation', max_length=500)),
                ('contract_reference', models.CharField(blank=True, default='', help_text='Reference to contract clause or section', max_length=100)),
                ('due_date', models.DateField(blank=True, help_text='Due date for this obligation', null=True)),
                ('frequency', models.CharField(choices=[('ONCE', 'Once-off'), ('DAILY', 'Daily'), ('WEEKLY', 'Weekly'), ('FORTNIGHTLY', 'Fortnightly'), ('MONTHLY', 'Monthly'), ('QUARTERLY', 'Quarterly'), ('ANNUALLY', 'Annually'), ('AS_REQUIRED', 'As Required')], default='ONCE', help_text='Frequency of this compliance activity', max_length=20)),
                ('expiry_date', models.DateField(blank=True, help_text='Expiry date where applicable', null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('OVERDUE', 'Overdue'), ('NOT_APPLICABLE', 'Not Applicable')], default='PENDING', help_text='Current status of this compliance item', max_length=20)),
                ('notes', models.TextField(blank=True, default='', help_text='Additional notes about this compliance item')),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this compliance item', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_contractual_compliance_items', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(help_text='Project this compliance item belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='contractual_compliance_items', to='Project.project')),
                ('responsible_party', models.ForeignKey(blank=True, help_text='Contractor or consultant responsible for this obligation', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contractual_compliance_responsibilities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Contractual Compliance',
                'verbose_name_plural': 'Contractual Compliance Items',
                'ordering': ['due_date', '-created_at'],
                'indexes': [models.Index(fields=['project', 'status'], name='Project_con_project_eecb27_idx'), models.Index(fields=['responsible_party'], name='Project_con_respons_5ae135_idx'), models.Index(fields=['due_date'], name='Project_con_due_dat_6ed873_idx')],
            },
        ),
        migrations.CreateModel(
            name='FinalAccountCompliance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When this record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When this record was last modified')),
                ('deleted', models.BooleanField(default=False, help_text='Soft delete flag')),
                ('document_type', models.CharField(choices=[('AS_BUILT_DRAWINGS', 'As-Built Drawings'), ('OPERATION_MANUAL', 'Operation & Maintenance Manual'), ('WARRANTY_CERTIFICATE', 'Warranty Certificate'), ('TEST_CERTIFICATE', 'Test Certificate'), ('COMPLIANCE_CERTIFICATE', 'Compliance Certificate'), ('OCCUPANCY_CERTIFICATE', 'Occupancy Certificate'), ('TRAINING_RECORD', 'Training Record'), ('SPARE_PARTS_LIST', 'Spare Parts List'), ('GUARANTEE', 'Guarantee'), ('OTHER', 'Other')], help_text='Type of document', max_length=30)),
                ('description', models.CharField(help_text='Description of the document', max_length=500)),
                ('test_date', models.DateField(blank=True, help_text='Date of test/inspection where applicable', null=True)),
                ('submission_date', models.DateField(blank=True, help_text='Date document was submitted', null=True)),
                ('approval_date', models.DateField(blank=True, help_text='Date document was approved', null=True)),
                ('status', models.CharField(choices=[('REQUIRED', 'Required'), ('REQUESTED', 'Requested'), ('SUBMITTED', 'Submitted'), ('UNDER_REVIEW', 'Under Review'), ('APPROVED', 'Approved'), ('NOT_APPLICABLE', 'Not Applicable')], default='REQUIRED', help_text='Current status', max_length=20)),
                ('file', models.FileField(blank=True, help_text='Attached document file', null=True, upload_to=app.Project.models.compliance_models.FinalAccountCompliance.upload_to)),
                ('notes', models.TextField(blank=True, default='', help_text='Additional notes')),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this item', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_final_account_compliance_items', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(help_text='Project this document belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='final_account_compliance_items', to='Project.project')),
                ('responsible_party', models.ForeignKey(blank=True, help_text='Person responsible for providing this document', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='final_account_compliance_responsibilities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Final Account Compliance',
                'verbose_name_plural': 'Final Account Compliance Items',
                'ordering': ['document_type', '-created_at'],
                'indexes': [models.Index(fields=['project', 'document_type'], name='Project_fin_project_174309_idx'), models.Index(fields=['project', 'status'], name='Project_fin_project_7a7b64_idx')],
            },
        ),
    ]
