# Generated by Django 5.2.6 on 2025-12-12 08:13

from decimal import Decimal

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Project", "0021_compliance_management"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="risk",
            name="category",
            field=models.CharField(
                choices=[
                    ("CONSULTANT", "Consultant"),
                    ("CLIENT", "Client"),
                    ("CONTRACTOR", "Contractor"),
                    ("COMMUNITY", "Community"),
                    ("LABOUR", "Labour"),
                    ("OTHER", "Other"),
                ],
                default="OTHER",
                help_text="Category identifying the source of the risk",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="ProjectImpact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When this record was created"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="When this record was last modified"
                    ),
                ),
                (
                    "deleted",
                    models.BooleanField(default=False, help_text="Soft delete flag"),
                ),
                (
                    "jobs_created",
                    models.PositiveIntegerField(
                        default=0, help_text="Number of jobs created"
                    ),
                ),
                (
                    "jobs_retained",
                    models.PositiveIntegerField(
                        default=0, help_text="Number of jobs retained"
                    ),
                ),
                (
                    "job_demographic",
                    models.CharField(
                        choices=[
                            ("YOUTH", "Youth"),
                            ("WOMEN", "Women"),
                            ("DISABLED", "People with Disabilities"),
                            ("MILITARY_VETERAN", "Military Veteran"),
                            ("GENERAL", "General"),
                        ],
                        default="GENERAL",
                        help_text="Primary demographic for jobs",
                        max_length=20,
                    ),
                ),
                (
                    "poverty_beneficiaries",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Number of poverty eradication beneficiaries",
                    ),
                ),
                (
                    "poverty_spend",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Amount spent on poverty eradication initiatives",
                        max_digits=15,
                    ),
                ),
                (
                    "local_subcontract_count",
                    models.PositiveIntegerField(
                        default=0, help_text="Number of local subcontracts awarded"
                    ),
                ),
                (
                    "local_subcontract_value",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Total value of local subcontracts",
                        max_digits=15,
                    ),
                ),
                (
                    "local_spend_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Amount spent locally",
                        max_digits=15,
                    ),
                ),
                (
                    "local_spend_percentage",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Percentage of total spend that is local",
                        max_digits=5,
                    ),
                ),
                (
                    "locality",
                    models.CharField(
                        choices=[
                            ("LOCAL", "Local"),
                            ("MUNICIPALITY", "Municipality"),
                            ("PROVINCE", "Province"),
                            ("NATIONAL", "National"),
                        ],
                        default="LOCAL",
                        help_text="Locality level for this impact record",
                        max_length=20,
                    ),
                ),
                (
                    "demographic",
                    models.CharField(
                        choices=[
                            ("YOUTH", "Youth"),
                            ("WOMEN", "Women"),
                            ("DISABLED", "People with Disabilities"),
                            ("MILITARY_VETERAN", "Military Veteran"),
                            ("GENERAL", "General"),
                        ],
                        default="GENERAL",
                        help_text="Primary demographic for this impact record",
                        max_length=20,
                    ),
                ),
                (
                    "investment_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Total investment amount",
                        max_digits=15,
                    ),
                ),
                (
                    "return_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Total return amount",
                        max_digits=15,
                    ),
                ),
                (
                    "period_start",
                    models.DateField(
                        blank=True,
                        help_text="Start date of the impact period",
                        null=True,
                    ),
                ),
                (
                    "period_end",
                    models.DateField(
                        blank=True, help_text="End date of the impact period", null=True
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Additional notes about this impact record",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who created this record",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_impacts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        help_text="Project this impact record belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="impacts",
                        to="Project.project",
                    ),
                ),
            ],
            options={
                "verbose_name": "Project Impact",
                "verbose_name_plural": "Project Impacts",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["project", "locality"],
                        name="Project_pro_project_ab6dcd_idx",
                    ),
                    models.Index(
                        fields=["project", "demographic"],
                        name="Project_pro_project_291c2a_idx",
                    ),
                ],
            },
        ),
    ]
