# Generated by Django 5.2.6 on 2026-01-15 16:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Project", "0023_project_account_to_users_m2m"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="project",
            name="client_representative",
        ),
        migrations.RemoveField(
            model_name="project",
            name="contractor",
        ),
        migrations.RemoveField(
            model_name="project",
            name="lead_consultant",
        ),
        migrations.RemoveField(
            model_name="project",
            name="quantity_surveyor",
        ),
        migrations.AddField(
            model_name="project",
            name="client_representatives",
            field=models.ManyToManyField(
                blank=True,
                help_text="Client Representatives",
                related_name="client_rep_projects",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="contractors",
            field=models.ManyToManyField(
                blank=True,
                help_text="Contractors responsible for the project",
                related_name="contractor_projects",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="lead_consultants",
            field=models.ManyToManyField(
                blank=True,
                help_text="Lead Consultants (e.g., Principal Agents)",
                related_name="lead_consultant_projects",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="quantity_surveyors",
            field=models.ManyToManyField(
                blank=True,
                help_text="Quantity Surveyors for the project",
                related_name="qs_projects",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
