# Generated by Django 5.2.6 on 2026-01-22 08:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Project", "0024_remove_project_client_representative_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ProjectRole",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("Admin", "Admin"),
                            ("User", "User"),
                            ("Contractor", "Contractor"),
                            ("Client", "Client"),
                            ("Consultant", "Consultant"),
                            ("Quantity Surveyor", "Quantity Surveyor"),
                            ("Client Representative", "Client Representative"),
                            ("Lead Consultant", "Lead Consultant"),
                        ],
                        max_length=255,
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="project_roles",
                        to="Project.project",
                    ),
                ),
                (
                    "users",
                    models.ManyToManyField(
                        help_text="Users who have access to this project role",
                        related_name="project_roles",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Project Role",
                "verbose_name_plural": "Project Roles",
            },
        ),
    ]
