# Generated by Django 5.2.6 on 2026-01-22 08:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Project", "0025_projectrole"),
    ]

    operations = [
        migrations.AlterField(
            model_name="projectrole",
            name="role",
            field=models.CharField(
                choices=[
                    ("Admin", "Admin"),
                    ("User", "User"),
                    ("Portfolio Manager", "Portfolio Manager"),
                    ("Portfolio User", "Portfolio User"),
                    ("Contractor", "Contractor"),
                    ("Client", "Client"),
                    ("Consultant", "Consultant"),
                    ("Quantity Surveyor", "Quantity Surveyor"),
                    ("Client Representative", "Client Representative"),
                    ("Lead Consultant", "Lead Consultant"),
                ],
                max_length=255,
            ),
        ),
    ]
