# Generated by Django 5.2.6 on 2026-01-22 09:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Project", "0026_alter_projectrole_role"),
    ]

    operations = [
        migrations.AddField(
            model_name="projectrole",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                default="2026-01-01",
                help_text="When this record was created",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="projectrole",
            name="deleted",
            field=models.BooleanField(default=False, help_text="Soft delete flag"),
        ),
        migrations.AddField(
            model_name="projectrole",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, help_text="When this record was last modified"
            ),
        ),
    ]
