# Generated by Django 5.2.6 on 2026-01-23 14:12

from django.db import migrations


def migrate_project_roles(apps, schema_editor):
    """Migrate ProjectRole from ManyToMany to ForeignKey."""
    # Data migration would go here if we had preserved the old M2M data
    # For now, this is a placeholder since the data migration needs to be done manually
    # or with a more complex migration that preserves the old relationships
    pass


class Migration(migrations.Migration):
    dependencies = [
        ("Project", "0028_remove_projectrole_users_projectrole_user_and_more"),
    ]

    operations = [
        migrations.RunPython(migrate_project_roles, migrations.RunPython.noop),
    ]
