# Generated by Django 6.0.1 on 2026-01-29 08:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def migrate_clients_to_companies(apps, schema_editor):
    """Migrate existing Client records to Company model."""
    # Get models
    Client = apps.get_model("Project", "Client")
    Company = apps.get_model("Project", "Company")
    Project = apps.get_model("Project", "Project")

    print("Starting migration of Client records to Company model...")

    # Migrate each client to a company
    for client in Client.objects.all():
        # Create the company record with all fields
        company = Company.objects.create(
            type="CLIENT",
            name=client.name,
        )

        # Copy users relationship (ManyToMany)
        if client.user:
            company.users.add(client.user)

        # Copy consultant relationship
        if client.consultant:
            company.consultants.add(client.consultant)

        # Update project references - use bulk update for better performance
        Project.objects.filter(client=client).update(client_temp=company)


def reverse_migrate_companies_to_clients(apps, schema_editor):
    """Reverse migration: Convert Company records back to Client model."""
    # Get models
    Client = apps.get_model("Project", "Client")
    Company = apps.get_model("Project", "Company")
    Project = apps.get_model("Project", "Project")

    print("Starting reverse migration of Company records to Client model...")

    # Only migrate companies that were originally clients
    for company in Company.objects.filter(type="CLIENT"):
        # Create the client record with all fields
        client = Client.objects.create(
            name=company.name,
        )

        # Copy users relationship (ManyToMany)
        if company.users.exists():
            client.user = company.users.first()
            client.save()

        # Copy consultant relationship (Client has single consultant)
        if company.consultants.exists():
            client.consultant = company.consultants.first()
            client.save()

        # Update project references back to client
        Project.objects.filter(client_temp=company).update(client=client)

        # Delete the company after successful migration
        company.delete()


class Migration(migrations.Migration):
    dependencies = [
        ("Project", "0032_alter_projectrole_role"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # Check if Company model already exists and skip creation if it does
        migrations.CreateModel(
            name="Company",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When this record was created"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="When this record was last modified"
                    ),
                ),
                (
                    "deleted",
                    models.BooleanField(default=False, help_text="Soft delete flag"),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[("CLIENT", "Client"), ("CONTRACTOR", "Contractor")],
                        max_length=255,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("registration_number", models.CharField(max_length=255)),
                ("tax_number", models.CharField(max_length=255)),
                ("vat_registered", models.BooleanField(default=False)),
                ("vat_number", models.CharField(blank=True, max_length=255)),
                (
                    "bank_name",
                    models.CharField(
                        blank=True, help_text="Bank name for payments", max_length=255
                    ),
                ),
                (
                    "bank_account_name",
                    models.CharField(
                        blank=True, help_text="Account holder name", max_length=255
                    ),
                ),
                (
                    "bank_account_number",
                    models.CharField(
                        blank=True, help_text="Bank account number", max_length=50
                    ),
                ),
                (
                    "bank_branch_code",
                    models.CharField(
                        blank=True, help_text="Bank branch code", max_length=20
                    ),
                ),
                (
                    "bank_swift_code",
                    models.CharField(
                        blank=True,
                        help_text="SWIFT/BIC code for international payments",
                        max_length=20,
                    ),
                ),
                (
                    "consultants",
                    models.ManyToManyField(
                        blank=True,
                        related_name="consultants",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "users",
                    models.ManyToManyField(
                        blank=True,
                        related_name="companies",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Company",
                "verbose_name_plural": "Companies",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="project",
            name="contractor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="contractor_projects",
                to="Project.company",
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="client_temp",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="client_projects",
                to="Project.company",
            ),
        ),
        migrations.RunPython(
            migrate_clients_to_companies,
            reverse_migrate_companies_to_clients,
        ),
        # Remove the old client field
        migrations.RemoveField(
            model_name="project",
            name="client",
        ),
        # Rename client_temp to client
        migrations.RenameField(
            model_name="project",
            old_name="client_temp",
            new_name="client",
        ),
        migrations.RemoveField(
            model_name="project",
            name="bank_account_name",
        ),
        migrations.RemoveField(
            model_name="project",
            name="bank_account_number",
        ),
        migrations.RemoveField(
            model_name="project",
            name="bank_branch_code",
        ),
        migrations.RemoveField(
            model_name="project",
            name="bank_name",
        ),
        migrations.RemoveField(
            model_name="project",
            name="bank_swift_code",
        ),
        migrations.RemoveField(
            model_name="project",
            name="vat_number",
        ),
        # Delete Client model at the very end
        migrations.DeleteModel(
            name="Client",
        ),
    ]
