# Generated by Django 6.0.1 on 2026-01-30 09:48

from django.db import migrations, models

import app.Project.models.company_models


class Migration(migrations.Migration):
    dependencies = [
        ("Project", "0033_remove_project_bank_account_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="company",
            name="logo",
            field=models.ImageField(
                blank=True,
                help_text="Company logo (recommended size: 200x200px)",
                null=True,
                upload_to=app.Project.models.company_models.company_logo_upload_path,
            ),
        ),
    ]
