# Generated by Django 6.0.1 on 2026-02-02 07:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Project", "0034_company_logo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="company",
            name="tax_number",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
