# Generated by Django 6.0.2 on 2026-02-24 19:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Project", "0038_administrativecompliancedialog_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="description",
            field=models.TextField(blank=True),
        ),
    ]
