# Generated by Django 6.0.2 on 2026-02-24 19:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Project", "0039_alter_project_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="end_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="project",
            name="start_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
