# Generated by Django 6.0.2 on 2026-02-26 19:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Project", "0040_alter_project_end_date_alter_project_start_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="projectrole",
            name="role",
            field=models.CharField(
                choices=[
                    ("Admin", "Admin"),
                    ("User", "User"),
                    ("Client", "Client"),
                    ("Consultant", "Consultant"),
                    ("Portfolio Manager", "Portfolio Manager"),
                    ("Portfolio User", "Portfolio User"),
                    ("Contractor BOQ", "Contractor BOQ"),
                    ("Additional Line Items", "Additional Line Items"),
                    ("Contract Variations", "Contract Variations"),
                    ("Correspondence", "Correspondence"),
                    ("Contract Documents", "Contract Documents"),
                    ("Stage Gate Approvals", "Stage Gate Approvals"),
                    ("Other Documents", "Other Documents"),
                    ("Forecast Hub", "Forecast Hub"),
                    ("Cost Forecasts", "Cost Forecasts"),
                    ("Time Forecasts", "Time Forecasts"),
                    ("Cashflow Forecasts", "Cashflow Forecasts"),
                    ("Earned Values", "Earned Values"),
                    ("Risk Management", "Risk Management"),
                    ("Payment Certificates", "Payment Certificates"),
                    ("Claims", "Claims"),
                    ("Advance Payments", "Advance Payments"),
                    ("Retention", "Retention"),
                    ("Materials On Site", "Materials On Site"),
                    ("Escalation", "Escalation"),
                    ("Special Items", "Special Items"),
                    ("Early Warnings", "Early Warnings"),
                    ("Compliance", "Compliance"),
                    ("Expenditure Management", "Expenditure Management"),
                    ("Materials Management", "Materials Management"),
                ],
                max_length=255,
            ),
        ),
    ]
