# Generated by Django 6.0.2 on 2026-02-26 20:07

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Project', '0041_alter_projectrole_role'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='risk',
            name='Project_ris_project_013550_idx',
        ),
        migrations.AddField(
            model_name='risk',
            name='date',
            field=models.DateField(auto_now_add=True, default='2026-02-26', help_text='Date this risk was raised'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='risk',
            name='date_closed',
            field=models.DateField(blank=True, editable=False, help_text='Date this risk was closed (auto-set)', null=True),
        ),
        migrations.AddField(
            model_name='risk',
            name='mitigation_action',
            field=models.TextField(blank=True, help_text='Actions to mitigate this risk'),
        ),
        migrations.AddField(
            model_name='risk',
            name='raised_by',
            field=models.ForeignKey(blank=True, editable=False, help_text='User who raised this risk', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='raised_risks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='risk',
            name='reference_number',
            field=models.CharField(default='abc', editable=False, help_text='Auto-generated reference number', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='risk',
            name='status',
            field=models.CharField(choices=[('OPEN', 'Open'), ('CLOSED', 'Closed')], default='OPEN', help_text='Current status of this risk', max_length=10),
        ),
        migrations.AddField(
            model_name='risk',
            name='time_impact_days',
            field=models.PositiveIntegerField(default=0, help_text='Potential time impact in days'),
        ),
        migrations.AlterField(
            model_name='risk',
            name='created_by',
            field=models.ForeignKey(blank=True, editable=False, help_text='User who created this risk', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_risks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='risk',
            name='description',
            field=models.TextField(help_text='Description of risk'),
        ),
        migrations.AlterField(
            model_name='risk',
            name='is_active',
            field=models.BooleanField(default=True, editable=False, help_text='Whether the risk is active (derived from status)'),
        ),
        migrations.AlterField(
            model_name='risk',
            name='probability',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Probability of impact occurring (0-100%)', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='risk',
            name='resolved_by',
            field=models.ForeignKey(blank=True, editable=False, help_text='User who resolved this risk', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_risks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='risk',
            name='resolved_date',
            field=models.DateField(blank=True, editable=False, help_text='Date when the risk was resolved', null=True),
        ),
        migrations.AddIndex(
            model_name='risk',
            index=models.Index(fields=['project', 'status'], name='Project_ris_project_613cf8_idx'),
        ),
        migrations.RemoveField(
            model_name='risk',
            name='category',
        ),
        migrations.RemoveField(
            model_name='risk',
            name='risk_name',
        ),
        migrations.RemoveField(
            model_name='risk',
            name='time_impact_end',
        ),
        migrations.RemoveField(
            model_name='risk',
            name='time_impact_start',
        ),
    ]
