# Generated by Django 6.0.2 on 2026-03-02 19:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Project", "0042_update_risk_model"),
    ]

    operations = [
        migrations.AddField(
            model_name="risk",
            name="category",
            field=models.CharField(
                choices=[
                    ("CONSULTANT", "Consultant"),
                    ("CLIENT", "Client"),
                    ("CONTRACTOR", "Contractor"),
                    ("COMMUNITY", "Community"),
                    ("LABOUR", "Labour"),
                    ("OTHER", "Other"),
                ],
                default="OTHER",
                help_text="Category identifying the source of the risk",
                max_length=20,
            ),
        ),
    ]
