# Generated by Django 6.0.3 on 2026-03-16 18:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Project", "0047_projectsubcategory_project_sub_category"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProjectDiscipline",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When this record was created"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="When this record was last modified"
                    ),
                ),
                (
                    "deleted",
                    models.BooleanField(default=False, help_text="Soft delete flag"),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Discipline name (e.g., Civil, Electrical, Mechanical)",
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Optional description of the discipline"
                    ),
                ),
            ],
            options={
                "verbose_name": "Project Discipline",
                "verbose_name_plural": "Project Disciplines",
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="project",
            name="discipline",
            field=models.ForeignKey(
                blank=True,
                help_text="Project discipline",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="projects",
                to="Project.projectdiscipline",
            ),
        ),
    ]
