# Generated by Django 6.0.3 on 2026-03-18 07:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Project", "0048_projectdiscipline_project_discipline"),
    ]

    operations = [
        migrations.RenameField(
            model_name="project",
            old_name="category",
            new_name="project_category",
        ),
        migrations.RenameField(
            model_name="project",
            old_name="discipline",
            new_name="project_discipline",
        ),
        migrations.RenameField(
            model_name="project",
            old_name="sub_category",
            new_name="project_sub_category",
        ),
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When this record was created"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="When this record was last modified"
                    ),
                ),
                (
                    "deleted",
                    models.BooleanField(default=False, help_text="Soft delete flag"),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Category name (e.g., Construction, Engineering)",
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Optional description of the category"
                    ),
                ),
                (
                    "projects",
                    models.ForeignKey(
                        blank=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="categories",
                        to="Project.project",
                    ),
                ),
            ],
            options={
                "verbose_name": "Project Category",
                "verbose_name_plural": "Project Categories",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Discipline",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When this record was created"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="When this record was last modified"
                    ),
                ),
                (
                    "deleted",
                    models.BooleanField(default=False, help_text="Soft delete flag"),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Discipline name (e.g., Civil, Electrical, Mechanical)",
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Optional description of the discipline"
                    ),
                ),
                (
                    "projects",
                    models.ForeignKey(
                        blank=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="disciplines",
                        to="Project.project",
                    ),
                ),
            ],
            options={
                "verbose_name": "Project Discipline",
                "verbose_name_plural": "Project Disciplines",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="SubCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When this record was created"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="When this record was last modified"
                    ),
                ),
                (
                    "deleted",
                    models.BooleanField(default=False, help_text="Soft delete flag"),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Subcategory name (e.g., Top Structures, Drawings)",
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Optional description of the subcategory"
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        blank=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subcategories",
                        to="Project.project",
                    ),
                ),
            ],
            options={
                "verbose_name": "Project Sub Category",
                "verbose_name_plural": "Project Sub Categories",
                "ordering": ["name"],
            },
        ),
    ]
