# Generated by Django 6.0.3 on 2026-03-18 17:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Project", "0051_milestone_project_category_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="name",
            field=models.CharField(
                help_text="Category name (e.g., Construction, Engineering)",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="discipline",
            name="name",
            field=models.CharField(
                help_text="Discipline name (e.g., Civil, Electrical, Mechanical)",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="subcategory",
            name="name",
            field=models.CharField(
                help_text="Subcategory name (e.g., Top Structures, Drawings)",
                max_length=100,
            ),
        ),
    ]
