# Generated by Django 6.0.3 on 2026-03-19 08:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Project", "0052_alter_category_name_alter_discipline_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="projectdocument",
            name="project_category",
            field=models.ForeignKey(
                blank=True,
                help_text="Project category (e.g., Education, Health, Roads)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="documents",
                to="Project.category",
            ),
        ),
        migrations.AlterField(
            model_name="projectdocument",
            name="project_discipline",
            field=models.ForeignKey(
                blank=True,
                help_text="Project discipline",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="documents",
                to="Project.discipline",
            ),
        ),
        migrations.AlterField(
            model_name="projectdocument",
            name="project_sub_category",
            field=models.ForeignKey(
                blank=True,
                help_text="Project category (e.g., Education, Health, Roads)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="documents",
                to="Project.subcategory",
            ),
        ),
    ]
