# Generated by Django 6.0.3 on 2026-03-21 18:44

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("Project", "0054_subcategory_category_group"),
    ]

    operations = [
        migrations.RenameField(
            model_name="category",
            old_name="projects",
            new_name="project",
        ),
        migrations.RenameField(
            model_name="discipline",
            old_name="projects",
            new_name="project",
        ),
    ]
