# Generated by Django 6.0.3 on 2026-03-21 21:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Project", "0056_milestone_project_group_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="group",
            name="sub_category",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="groups",
                to="Project.subcategory",
            ),
        ),
    ]
