# Generated by Django 6.0.3 on 2026-03-22 18:21

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("Project", "0058_alter_subcategory_category"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={
                "ordering": ["name"],
                "verbose_name": "Level 1",
                "verbose_name_plural": "Level 1",
            },
        ),
        migrations.AlterModelOptions(
            name="discipline",
            options={
                "ordering": ["name"],
                "verbose_name": "Level 4",
                "verbose_name_plural": "Level 4",
            },
        ),
        migrations.AlterModelOptions(
            name="group",
            options={
                "ordering": ["name"],
                "verbose_name": "Level 3",
                "verbose_name_plural": "Level 3",
            },
        ),
        migrations.AlterModelOptions(
            name="subcategory",
            options={
                "ordering": ["name"],
                "verbose_name": "Level 2",
                "verbose_name_plural": "Level 2",
            },
        ),
    ]
