# Generated by Django 6.0.3 on 2026-03-22 18:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Project", "0059_alter_category_options_alter_discipline_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="end_date",
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name="category",
            name="start_date",
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name="group",
            name="end_date",
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name="group",
            name="start_date",
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name="subcategory",
            name="end_date",
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name="subcategory",
            name="start_date",
            field=models.DateField(null=True),
        ),
    ]
