# Generated by Django 6.0.3 on 2026-03-22 19:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "Project",
            "0060_category_end_date_category_start_date_group_end_date_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="budget",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="group",
            name="budget",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="subcategory",
            name="budget",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
    ]
