# Generated by Django 6.0.3 on 2026-03-31 07:57

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("Project", "0061_category_budget_group_budget_subcategory_budget"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="portfolio",
            options={"base_manager_name": "objects"},
        ),
    ]
