# Generated by Django 5.2.12 on 2026-03-25 09:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Project", "0061_category_budget_group_budget_subcategory_budget"),
    ]

    operations = [
        migrations.CreateModel(
            name="DailyProduction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When this record was created"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="When this record was last modified"
                    ),
                ),
                (
                    "deleted",
                    models.BooleanField(default=False, help_text="Soft delete flag"),
                ),
                (
                    "notes",
                    models.TextField(blank=True, help_text="Optional remarks/notes"),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="daily_productions",
                        to="Project.project",
                    ),
                ),
            ],
            options={
                "verbose_name": "Daily Production",
                "verbose_name_plural": "Daily Productions",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ProductionPlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When this record was created"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="When this record was last modified"
                    ),
                ),
                (
                    "deleted",
                    models.BooleanField(default=False, help_text="Soft delete flag"),
                ),
                ("activity", models.CharField(max_length=255)),
                ("start_date", models.DateField()),
                ("finish_date", models.DateField()),
                ("quantity", models.DecimalField(decimal_places=2, max_digits=15)),
                ("unit", models.CharField(max_length=50)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="production_plans",
                        to="Project.project",
                    ),
                ),
            ],
            options={
                "verbose_name": "Production Plan",
                "verbose_name_plural": "Production Plans",
                "ordering": ["start_date"],
            },
        ),
    ]
