# Generated by Django 5.2.12 on 2026-03-25 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Project", "0062_dailyproduction_productionplan"),
    ]

    operations = [
        migrations.AddField(
            model_name="productionplan",
            name="duration",
            field=models.IntegerField(default=0, help_text="Duration in days"),
        ),
    ]
