# Generated by Django 5.2.12 on 2026-03-25 12:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Project", "0063_productionplan_duration"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductionResource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When this record was created"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="When this record was last modified"
                    ),
                ),
                (
                    "deleted",
                    models.BooleanField(default=False, help_text="Soft delete flag"),
                ),
                (
                    "resource_type",
                    models.CharField(
                        choices=[
                            ("LABOUR", "Labour"),
                            ("PLANT", "Plant/Equipment"),
                            ("RESOURCE", "Other Resource"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="e.g., Skilled, Bobcat, Diesel", max_length=255
                    ),
                ),
                (
                    "number",
                    models.DecimalField(decimal_places=2, default=1, max_digits=10),
                ),
                (
                    "days",
                    models.DecimalField(decimal_places=2, default=1, max_digits=10),
                ),
                ("rate", models.DecimalField(decimal_places=2, max_digits=15)),
                (
                    "total_cost",
                    models.DecimalField(
                        decimal_places=2, editable=False, max_digits=15
                    ),
                ),
                (
                    "production_plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="resources",
                        to="Project.productionplan",
                    ),
                ),
            ],
            options={
                "verbose_name": "Production Resource",
                "verbose_name_plural": "Production Resources",
            },
        ),
    ]
