# Generated by Django 5.2.12 on 2026-03-25 22:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Project", "0064_productionresource"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="lead_consultant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="lead_consultant_projects",
                to="Project.company",
            ),
        ),
        migrations.AlterField(
            model_name="company",
            name="type",
            field=models.CharField(
                choices=[
                    ("CLIENT", "Client"),
                    ("CONTRACTOR", "Contractor"),
                    ("LEAD_CONSULTANT", "Lead Consultant"),
                ],
                max_length=255,
            ),
        ),
    ]
