# Generated by Django 5.2.12 on 2026-03-27 00:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Project", "0065_project_lead_consultant_alter_company_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productionresource",
            name="resource_type",
            field=models.CharField(
                choices=[("LABOUR", "Labour"), ("PLANT", "Plant/Equipment")],
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="DailyActivityReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When this record was created"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="When this record was last modified"
                    ),
                ),
                (
                    "deleted",
                    models.BooleanField(default=False, help_text="Soft delete flag"),
                ),
                ("date", models.DateField()),
                (
                    "notes",
                    models.TextField(
                        blank=True, help_text="Optional site-wide remarks"
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="daily_reports",
                        to="Project.project",
                    ),
                ),
            ],
            options={
                "verbose_name": "Daily Activity Report",
                "verbose_name_plural": "Daily Activity Reports",
                "ordering": ["-date", "-created_at"],
                "unique_together": {("project", "date")},
            },
        ),
        migrations.CreateModel(
            name="DailyActivityEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When this record was created"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="When this record was last modified"
                    ),
                ),
                (
                    "deleted",
                    models.BooleanField(default=False, help_text="Soft delete flag"),
                ),
                (
                    "quantity",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "production_plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="daily_entries",
                        to="Project.productionplan",
                    ),
                ),
                (
                    "report",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="entries",
                        to="Project.dailyactivityreport",
                    ),
                ),
            ],
            options={
                "verbose_name": "Daily Activity Entry",
                "verbose_name_plural": "Daily Activity Entries",
            },
        ),
        migrations.CreateModel(
            name="DailyLabourUsage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When this record was created"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="When this record was last modified"
                    ),
                ),
                (
                    "deleted",
                    models.BooleanField(default=False, help_text="Soft delete flag"),
                ),
                ("number", models.IntegerField(default=1)),
                (
                    "hours",
                    models.DecimalField(decimal_places=2, default=8, max_digits=5),
                ),
                (
                    "entry",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="labour_usage",
                        to="Project.dailyactivityentry",
                    ),
                ),
                (
                    "resource",
                    models.ForeignKey(
                        limit_choices_to={"resource_type": "LABOUR"},
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Project.productionresource",
                    ),
                ),
            ],
            options={
                "verbose_name": "Daily Labour Usage",
                "verbose_name_plural": "Daily Labour Usages",
            },
        ),
        migrations.CreateModel(
            name="DailyPlantUsage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When this record was created"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="When this record was last modified"
                    ),
                ),
                (
                    "deleted",
                    models.BooleanField(default=False, help_text="Soft delete flag"),
                ),
                ("number", models.IntegerField(default=1)),
                (
                    "hours",
                    models.DecimalField(decimal_places=2, default=8, max_digits=5),
                ),
                (
                    "entry",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="plant_usage",
                        to="Project.dailyactivityentry",
                    ),
                ),
                (
                    "resource",
                    models.ForeignKey(
                        limit_choices_to={"resource_type": "PLANT"},
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Project.productionresource",
                    ),
                ),
            ],
            options={
                "verbose_name": "Daily Plant Usage",
                "verbose_name_plural": "Daily Plant Usages",
            },
        ),
    ]
