# Generated by Django 5.2.12 on 2026-03-27 10:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Project", "0066_alter_productionresource_resource_type_and_more"),
        (
            "SiteManagement",
            "0011_alter_plantequipment_equipment_name_planttype_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="productionresource",
            name="plant_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="production_resources",
                to="SiteManagement.planttype",
            ),
        ),
        migrations.AddField(
            model_name="productionresource",
            name="skill_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="production_resources",
                to="SiteManagement.skilltype",
            ),
        ),
    ]
