# Generated by Django 6.0.3 on 2026-04-02 07:54

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("Project", "0063_category_install_only_category_preliminaries_and_more"),
        ("Project", "0068_productionplan_is_archived_and_more"),
    ]

    operations = []
