# Generated by Django 5.2.12 on 2026-04-12 10:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import app.Project.models.entity_definitions


class Migration(migrations.Migration):
    dependencies = [
        ("Project", "0069_merge_20260402_0954"),
        (
            "SiteManagement",
            "0011_alter_plantequipment_equipment_name_planttype_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="JournalEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When this record was created"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="When this record was last modified"
                    ),
                ),
                (
                    "deleted",
                    models.BooleanField(default=False, help_text="Soft delete flag"),
                ),
                ("date", models.DateField(help_text="Transaction date")),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("MATERIAL", "Material"),
                            ("LABOUR", "Labour"),
                            ("SUBCONTRACTOR", "Subcontractor"),
                            ("OVERHEAD", "Overhead"),
                            ("PLANT", "Plant"),
                            ("REVENUE", "Revenue"),
                            ("OTHER", "Other"),
                        ],
                        help_text="Category of transaction",
                        max_length=50,
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        help_text="Description of transaction", max_length=255
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, help_text="Total amount", max_digits=12
                    ),
                ),
                (
                    "transaction_type",
                    models.CharField(
                        choices=[("DEBIT", "Revenue"), ("CREDIT", "Expense")],
                        default="DEBIT",
                        max_length=10,
                    ),
                ),
                (
                    "source_log_id",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="ID of the source log (Daily Diary, etc.)",
                        null=True,
                    ),
                ),
                (
                    "source_log_type",
                    models.CharField(
                        blank=True,
                        help_text="Type of the source daily log",
                        max_length=100,
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        help_text="Project this journal entry belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="journal_entries",
                        to="Project.project",
                    ),
                ),
            ],
            options={
                "verbose_name": "Journal Entry",
                "verbose_name_plural": "Journal Entries",
                "ordering": ["-date", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="LabourEntity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When this record was created"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="When this record was last modified"
                    ),
                ),
                (
                    "deleted",
                    models.BooleanField(default=False, help_text="Soft delete flag"),
                ),
                ("name", models.CharField(help_text="Entity name", max_length=255)),
                (
                    "reference_no",
                    models.CharField(
                        blank=True,
                        help_text="Unique reference number",
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "unit",
                    models.CharField(
                        blank=True, help_text="Unit of measure", max_length=50
                    ),
                ),
                (
                    "rate",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Rate per unit",
                        max_digits=12,
                    ),
                ),
                (
                    "expense_code",
                    models.CharField(
                        choices=[
                            ("OPEX", "Operating Expenses"),
                            ("COS", "Cost of Sales"),
                        ],
                        default="COS",
                        help_text="Accounting classification",
                        max_length=20,
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, help_text="General description"),
                ),
                (
                    "person_name",
                    models.CharField(help_text="Worker name", max_length=255),
                ),
                (
                    "id_number",
                    models.CharField(
                        blank=True, help_text="ID/Passport number", max_length=100
                    ),
                ),
                (
                    "trade",
                    models.CharField(
                        blank=True, help_text="Trade/Specialty", max_length=100
                    ),
                ),
                (
                    "date_joined",
                    models.DateField(
                        blank=True, help_text="Date joined project", null=True
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        help_text="Project this entity belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_entities",
                        to="Project.project",
                    ),
                ),
                (
                    "skill_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="labour_entities",
                        to="SiteManagement.skilltype",
                    ),
                ),
            ],
            options={
                "verbose_name": "Labour Entity",
                "verbose_name_plural": "Labour Entities",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="LabourCostTracker",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When this record was created"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="When this record was last modified"
                    ),
                ),
                (
                    "deleted",
                    models.BooleanField(default=False, help_text="Soft delete flag"),
                ),
                ("date", models.DateField(help_text="Date of monitoring")),
                (
                    "id_number",
                    models.CharField(
                        blank=True, help_text="Worker's ID number", max_length=100
                    ),
                ),
                (
                    "amount_of_days",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Amount of days worked",
                        max_digits=12,
                    ),
                ),
                (
                    "salary",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Daily salary/rate",
                        max_digits=12,
                    ),
                ),
                (
                    "task_activity",
                    models.TextField(blank=True, help_text="Specific task or activity"),
                ),
                (
                    "remarks",
                    models.TextField(blank=True, help_text="Additional remarks"),
                ),
                (
                    "project",
                    models.ForeignKey(
                        help_text="Project this cost log belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="labour_cost_logs",
                        to="Project.project",
                    ),
                ),
                (
                    "labour_entity",
                    models.ForeignKey(
                        help_text="Link to master labour definition",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cost_logs",
                        to="Project.labourentity",
                    ),
                ),
            ],
            options={
                "verbose_name": "Labour Cost Tracker",
                "verbose_name_plural": "Labour Cost Trackers",
                "ordering": ["-date", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="MaterialEntity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When this record was created"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="When this record was last modified"
                    ),
                ),
                (
                    "deleted",
                    models.BooleanField(default=False, help_text="Soft delete flag"),
                ),
                ("name", models.CharField(help_text="Entity name", max_length=255)),
                (
                    "reference_no",
                    models.CharField(
                        blank=True,
                        help_text="Unique reference number",
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "unit",
                    models.CharField(
                        blank=True, help_text="Unit of measure", max_length=50
                    ),
                ),
                (
                    "rate",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Rate per unit",
                        max_digits=12,
                    ),
                ),
                (
                    "expense_code",
                    models.CharField(
                        choices=[
                            ("OPEX", "Operating Expenses"),
                            ("COS", "Cost of Sales"),
                        ],
                        default="COS",
                        help_text="Accounting classification",
                        max_length=20,
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, help_text="General description"),
                ),
                (
                    "supplier",
                    models.CharField(
                        blank=True, help_text="Preferred supplier", max_length=255
                    ),
                ),
                (
                    "items_received",
                    models.TextField(blank=True, help_text="Detailed items/specs"),
                ),
                ("invoice_number", models.CharField(blank=True, max_length=100)),
                (
                    "quantity",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Estimated quantity",
                        max_digits=12,
                    ),
                ),
                (
                    "date_received",
                    models.DateField(
                        blank=True, help_text="Initial receipt date", null=True
                    ),
                ),
                (
                    "invoice_attachment",
                    models.FileField(
                        blank=True,
                        help_text="Attach a copy of the invoice (PDF or Image)",
                        null=True,
                        upload_to=app.Project.models.entity_definitions.material_entity_invoice_path,
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        help_text="Project this entity belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_entities",
                        to="Project.project",
                    ),
                ),
            ],
            options={
                "verbose_name": "Material Entity",
                "verbose_name_plural": "Material Entities",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="MaterialCostTracker",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When this record was created"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="When this record was last modified"
                    ),
                ),
                (
                    "deleted",
                    models.BooleanField(default=False, help_text="Soft delete flag"),
                ),
                ("date", models.DateField(help_text="Date of monitoring")),
                (
                    "invoice_number",
                    models.CharField(
                        blank=True,
                        help_text="Invoice number for the transaction",
                        max_length=100,
                    ),
                ),
                (
                    "quantity",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Quantity of material used/bought",
                        max_digits=12,
                    ),
                ),
                (
                    "rate",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Rate per unit",
                        max_digits=12,
                    ),
                ),
                (
                    "intended_usage",
                    models.TextField(
                        blank=True, help_text="Intended usage for this material"
                    ),
                ),
                (
                    "comments",
                    models.TextField(blank=True, help_text="Additional comments"),
                ),
                (
                    "project",
                    models.ForeignKey(
                        help_text="Project this cost log belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="material_cost_logs",
                        to="Project.project",
                    ),
                ),
                (
                    "material_entity",
                    models.ForeignKey(
                        help_text="Link to master material definition",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cost_logs",
                        to="Project.materialentity",
                    ),
                ),
            ],
            options={
                "verbose_name": "Material Cost Tracker",
                "verbose_name_plural": "Material Cost Trackers",
                "ordering": ["-date", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="OverheadEntity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When this record was created"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="When this record was last modified"
                    ),
                ),
                (
                    "deleted",
                    models.BooleanField(default=False, help_text="Soft delete flag"),
                ),
                ("name", models.CharField(help_text="Entity name", max_length=255)),
                (
                    "reference_no",
                    models.CharField(
                        blank=True,
                        help_text="Unique reference number",
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "unit",
                    models.CharField(
                        blank=True, help_text="Unit of measure", max_length=50
                    ),
                ),
                (
                    "rate",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Rate per unit",
                        max_digits=12,
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, help_text="General description"),
                ),
                (
                    "category",
                    models.CharField(
                        blank=True,
                        help_text="Overhead category (e.g., Office, Site)",
                        max_length=100,
                    ),
                ),
                (
                    "expense_code",
                    models.CharField(
                        choices=[
                            ("OPEX", "Operating Expenses"),
                            ("COS", "Cost of Sales"),
                        ],
                        default="OPEX",
                        help_text="Accounting classification",
                        max_length=20,
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        help_text="Project this entity belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_entities",
                        to="Project.project",
                    ),
                ),
            ],
            options={
                "verbose_name": "Overhead Entity",
                "verbose_name_plural": "Overhead Entities",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="OverheadCostTracker",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When this record was created"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="When this record was last modified"
                    ),
                ),
                (
                    "deleted",
                    models.BooleanField(default=False, help_text="Soft delete flag"),
                ),
                ("date", models.DateField(help_text="Date of monitoring")),
                (
                    "amount_of_days",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Amount of days tracked",
                        max_digits=12,
                    ),
                ),
                (
                    "rate",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Daily rate/cost",
                        max_digits=12,
                    ),
                ),
                (
                    "remarks",
                    models.TextField(blank=True, help_text="Additional remarks"),
                ),
                (
                    "project",
                    models.ForeignKey(
                        help_text="Project this cost log belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="overhead_cost_logs",
                        to="Project.project",
                    ),
                ),
                (
                    "overhead_entity",
                    models.ForeignKey(
                        help_text="Link to master overhead definition",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cost_logs",
                        to="Project.overheadentity",
                    ),
                ),
            ],
            options={
                "verbose_name": "Overhead Cost Tracker",
                "verbose_name_plural": "Overhead Cost Trackers",
                "ordering": ["-date", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PlantEntity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When this record was created"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="When this record was last modified"
                    ),
                ),
                (
                    "deleted",
                    models.BooleanField(default=False, help_text="Soft delete flag"),
                ),
                ("name", models.CharField(help_text="Entity name", max_length=255)),
                (
                    "reference_no",
                    models.CharField(
                        blank=True,
                        help_text="Unique reference number",
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "unit",
                    models.CharField(
                        blank=True, help_text="Unit of measure", max_length=50
                    ),
                ),
                (
                    "rate",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Rate per unit",
                        max_digits=12,
                    ),
                ),
                (
                    "expense_code",
                    models.CharField(
                        choices=[
                            ("OPEX", "Operating Expenses"),
                            ("COS", "Cost of Sales"),
                        ],
                        default="COS",
                        help_text="Accounting classification",
                        max_length=20,
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, help_text="General description"),
                ),
                (
                    "specific_info",
                    models.TextField(
                        blank=True, help_text="Specific machine info (S/N, etc.)"
                    ),
                ),
                ("supplier", models.CharField(blank=True, max_length=255)),
                (
                    "breakdown_status",
                    models.CharField(
                        choices=[
                            ("OPERATIONAL", "Operational"),
                            ("BREAKDOWN", "Breakdown"),
                            ("UNDER_MAINTENANCE", "Under Maintenance"),
                            ("RETIRED", "Retired"),
                        ],
                        default="OPERATIONAL",
                        help_text="Current breakdown status",
                        max_length=20,
                    ),
                ),
                (
                    "date",
                    models.DateField(blank=True, help_text="Record date", null=True),
                ),
                (
                    "plant_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="plant_entities",
                        to="SiteManagement.planttype",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        help_text="Project this entity belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_entities",
                        to="Project.project",
                    ),
                ),
            ],
            options={
                "verbose_name": "Plant Entity",
                "verbose_name_plural": "Plant Entities",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="PlantCostTracker",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When this record was created"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="When this record was last modified"
                    ),
                ),
                (
                    "deleted",
                    models.BooleanField(default=False, help_text="Soft delete flag"),
                ),
                ("date", models.DateField(help_text="Date of usage")),
                (
                    "usage_hours",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Total usage hours",
                        max_digits=10,
                    ),
                ),
                (
                    "hourly_rate",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Hourly rate",
                        max_digits=12,
                    ),
                ),
                (
                    "breakdown_status",
                    models.CharField(
                        blank=True,
                        help_text="Breakdown status during tracking",
                        max_length=50,
                    ),
                ),
                (
                    "maintenance_done",
                    models.TextField(blank=True, help_text="Maintenance performed"),
                ),
                (
                    "remarks",
                    models.TextField(blank=True, help_text="Additional remarks"),
                ),
                (
                    "project",
                    models.ForeignKey(
                        help_text="Project this cost log belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="plant_cost_logs",
                        to="Project.project",
                    ),
                ),
                (
                    "plant_entity",
                    models.ForeignKey(
                        help_text="Link to master plant definition",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cost_logs",
                        to="Project.plantentity",
                    ),
                ),
            ],
            options={
                "verbose_name": "Plant Cost Tracker",
                "verbose_name_plural": "Plant Cost Trackers",
                "ordering": ["-date", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SubcontractorEntity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When this record was created"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="When this record was last modified"
                    ),
                ),
                (
                    "deleted",
                    models.BooleanField(default=False, help_text="Soft delete flag"),
                ),
                ("name", models.CharField(help_text="Entity name", max_length=255)),
                (
                    "reference_no",
                    models.CharField(
                        blank=True,
                        help_text="Unique reference number",
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "unit",
                    models.CharField(
                        blank=True, help_text="Unit of measure", max_length=50
                    ),
                ),
                (
                    "rate",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Rate per unit",
                        max_digits=12,
                    ),
                ),
                (
                    "expense_code",
                    models.CharField(
                        choices=[
                            ("OPEX", "Operating Expenses"),
                            ("COS", "Cost of Sales"),
                        ],
                        default="COS",
                        help_text="Accounting classification",
                        max_length=20,
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, help_text="General description"),
                ),
                ("trade", models.CharField(blank=True, max_length=100)),
                ("scope", models.TextField(blank=True, help_text="Scope of work")),
                ("start_date", models.DateField(blank=True, null=True)),
                ("planned_finish_date", models.DateField(blank=True, null=True)),
                ("actual_finish_date", models.DateField(blank=True, null=True)),
                (
                    "project",
                    models.ForeignKey(
                        help_text="Project this entity belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_entities",
                        to="Project.project",
                    ),
                ),
            ],
            options={
                "verbose_name": "Subcontractor Entity",
                "verbose_name_plural": "Subcontractor Entities",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="SubcontractorCostTracker",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When this record was created"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="When this record was last modified"
                    ),
                ),
                (
                    "deleted",
                    models.BooleanField(default=False, help_text="Soft delete flag"),
                ),
                ("date", models.DateField(help_text="Date of monitoring")),
                (
                    "reference_no",
                    models.CharField(
                        blank=True,
                        help_text="Reference number for the transaction",
                        max_length=100,
                    ),
                ),
                (
                    "amount_of_days",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Number of days/units tracked",
                        max_digits=12,
                    ),
                ),
                (
                    "rate",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Rate per day/unit",
                        max_digits=12,
                    ),
                ),
                (
                    "task",
                    models.TextField(blank=True, help_text="Specific task or scope"),
                ),
                (
                    "hours_worked",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Hours worked",
                        max_digits=10,
                    ),
                ),
                (
                    "remarks",
                    models.TextField(blank=True, help_text="Additional remarks"),
                ),
                (
                    "project",
                    models.ForeignKey(
                        help_text="Project this cost log belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subcontractor_cost_logs",
                        to="Project.project",
                    ),
                ),
                (
                    "subcontractor_entity",
                    models.ForeignKey(
                        help_text="Link to master subcontractor definition",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cost_logs",
                        to="Project.subcontractorentity",
                    ),
                ),
            ],
            options={
                "verbose_name": "Subcontractor Cost Tracker",
                "verbose_name_plural": "Subcontractor Cost Trackers",
                "ordering": ["-date", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="UnitOfMeasure",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When this record was created"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="When this record was last modified"
                    ),
                ),
                (
                    "deleted",
                    models.BooleanField(default=False, help_text="Soft delete flag"),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Full name of the unit (e.g., Kilogram)",
                        max_length=100,
                    ),
                ),
                (
                    "short_name",
                    models.CharField(
                        help_text="Abbreviation (e.g., kg)", max_length=20
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("WEIGHT", "Weight/Mass"),
                            ("VOLUME", "Volume"),
                            ("LENGTH", "Length"),
                            ("AREA", "Area"),
                            ("TIME", "Time"),
                            ("COUNT", "Count/Quantity"),
                            ("OTHER", "Other"),
                        ],
                        default="OTHER",
                        help_text="The type of measurement this unit represents",
                        max_length=20,
                    ),
                ),
                (
                    "conversion_factor",
                    models.DecimalField(
                        decimal_places=6,
                        default=1.0,
                        help_text="Multiplier to convert this unit to the reference unit",
                        max_digits=12,
                    ),
                ),
                (
                    "reference_unit",
                    models.ForeignKey(
                        blank=True,
                        help_text="The base unit this unit is relative to. If null, this is the base unit.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sub_units",
                        to="Project.unitofmeasure",
                    ),
                ),
            ],
            options={
                "verbose_name": "Unit of Measure",
                "verbose_name_plural": "Units of Measure",
                "ordering": ["category", "name"],
            },
        ),
        migrations.AddField(
            model_name="subcontractorentity",
            name="unit_of_measure",
            field=models.ForeignKey(
                blank=True,
                help_text="Centralized unit of measure",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_entities",
                to="Project.unitofmeasure",
            ),
        ),
        migrations.AddField(
            model_name="plantentity",
            name="unit_of_measure",
            field=models.ForeignKey(
                blank=True,
                help_text="Centralized unit of measure",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_entities",
                to="Project.unitofmeasure",
            ),
        ),
        migrations.AddField(
            model_name="overheadentity",
            name="unit_of_measure",
            field=models.ForeignKey(
                blank=True,
                help_text="Centralized unit of measure",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_entities",
                to="Project.unitofmeasure",
            ),
        ),
        migrations.AddField(
            model_name="materialentity",
            name="unit_of_measure",
            field=models.ForeignKey(
                blank=True,
                help_text="Centralized unit of measure",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_entities",
                to="Project.unitofmeasure",
            ),
        ),
        migrations.AddField(
            model_name="labourentity",
            name="unit_of_measure",
            field=models.ForeignKey(
                blank=True,
                help_text="Centralized unit of measure",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_entities",
                to="Project.unitofmeasure",
            ),
        ),
        migrations.CreateModel(
            name="ProjectReportSummary",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When this record was created"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="When this record was last modified"
                    ),
                ),
                (
                    "deleted",
                    models.BooleanField(default=False, help_text="Soft delete flag"),
                ),
                ("period_start", models.DateField()),
                ("period_end", models.DateField()),
                (
                    "project_status_summary",
                    models.TextField(
                        blank=True,
                        help_text="Overall status of the project for this period",
                    ),
                ),
                (
                    "key_achievements",
                    models.TextField(
                        blank=True, help_text="Major achievements during this period"
                    ),
                ),
                (
                    "current_focus",
                    models.TextField(
                        blank=True,
                        help_text="Current areas of focus for the next period",
                    ),
                ),
                (
                    "hsq_summary",
                    models.TextField(
                        blank=True, help_text="Health, Safety, and Quality summary"
                    ),
                ),
                (
                    "recommendations",
                    models.TextField(
                        blank=True, help_text="Recommendations for the project"
                    ),
                ),
                (
                    "contractor_summary",
                    models.TextField(
                        blank=True,
                        help_text="Contractor's summary of work and concerns",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_report_summaries",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="report_summaries",
                        to="Project.project",
                    ),
                ),
            ],
            options={
                "verbose_name": "Project Report Summary",
                "verbose_name_plural": "Project Report Summaries",
                "ordering": ["-period_end"],
                "unique_together": {("project", "period_start", "period_end")},
            },
        ),
        migrations.AlterField(
            model_name="subcontractorcosttracker",
            name="subcontractor_entity",
            field=models.ForeignKey(
                blank=True,
                help_text="Link to master subcontractor definition",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cost_logs",
                to="Project.subcontractorentity",
            ),
        ),
    ]
