# Generated by Django 6.0.3 on 2026-04-08 18:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Project", "0069_merge_20260402_0954"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ProjectReportSummary",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When this record was created"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="When this record was last modified"
                    ),
                ),
                (
                    "deleted",
                    models.BooleanField(default=False, help_text="Soft delete flag"),
                ),
                ("period_start", models.DateField()),
                ("period_end", models.DateField()),
                (
                    "project_status_summary",
                    models.TextField(
                        blank=True,
                        help_text="Overall status of the project for this period",
                    ),
                ),
                (
                    "key_achievements",
                    models.TextField(
                        blank=True, help_text="Major achievements during this period"
                    ),
                ),
                (
                    "current_focus",
                    models.TextField(
                        blank=True,
                        help_text="Current areas of focus for the next period",
                    ),
                ),
                (
                    "hsq_summary",
                    models.TextField(
                        blank=True, help_text="Health, Safety, and Quality summary"
                    ),
                ),
                (
                    "recommendations",
                    models.TextField(
                        blank=True, help_text="Recommendations for the project"
                    ),
                ),
                (
                    "contractor_summary",
                    models.TextField(
                        blank=True,
                        help_text="Contractor's summary of work and concerns",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_report_summaries",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="report_summaries",
                        to="Project.project",
                    ),
                ),
            ],
            options={
                "verbose_name": "Project Report Summary",
                "verbose_name_plural": "Project Report Summaries",
                "ordering": ["-period_end"],
                "unique_together": {("project", "period_start", "period_end")},
            },
        ),
    ]
