# Generated by Django 5.2.12 on 2026-04-06 12:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Project", "0069_merge_20260402_0954"),
        (
            "SiteManagement",
            "0011_alter_plantequipment_equipment_name_planttype_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="LabourEntity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When this record was created"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="When this record was last modified"
                    ),
                ),
                (
                    "deleted",
                    models.BooleanField(default=False, help_text="Soft delete flag"),
                ),
                ("name", models.CharField(help_text="Entity name", max_length=255)),
                (
                    "reference_no",
                    models.CharField(
                        blank=True,
                        help_text="Unique reference number",
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "unit",
                    models.CharField(
                        blank=True, help_text="Unit of measure", max_length=50
                    ),
                ),
                (
                    "rate",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Rate per unit",
                        max_digits=12,
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, help_text="General description"),
                ),
                (
                    "person_name",
                    models.CharField(help_text="Worker name", max_length=255),
                ),
                (
                    "id_number",
                    models.CharField(
                        blank=True, help_text="ID/Passport number", max_length=100
                    ),
                ),
                (
                    "trade",
                    models.CharField(
                        blank=True, help_text="Trade/Specialty", max_length=100
                    ),
                ),
                (
                    "date_joined",
                    models.DateField(
                        blank=True, help_text="Date joined project", null=True
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        help_text="Project this entity belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_entities",
                        to="Project.project",
                    ),
                ),
                (
                    "skill_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="labour_entities",
                        to="SiteManagement.skilltype",
                    ),
                ),
            ],
            options={
                "verbose_name": "Labour Entity",
                "verbose_name_plural": "Labour Entities",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="MaterialEntity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When this record was created"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="When this record was last modified"
                    ),
                ),
                (
                    "deleted",
                    models.BooleanField(default=False, help_text="Soft delete flag"),
                ),
                ("name", models.CharField(help_text="Entity name", max_length=255)),
                (
                    "reference_no",
                    models.CharField(
                        blank=True,
                        help_text="Unique reference number",
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "unit",
                    models.CharField(
                        blank=True, help_text="Unit of measure", max_length=50
                    ),
                ),
                (
                    "rate",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Rate per unit",
                        max_digits=12,
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, help_text="General description"),
                ),
                (
                    "supplier",
                    models.CharField(
                        blank=True, help_text="Preferred supplier", max_length=255
                    ),
                ),
                (
                    "items_received",
                    models.TextField(blank=True, help_text="Detailed items/specs"),
                ),
                ("invoice_number", models.CharField(blank=True, max_length=100)),
                (
                    "quantity",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Estimated quantity",
                        max_digits=12,
                    ),
                ),
                (
                    "date_received",
                    models.DateField(
                        blank=True, help_text="Initial receipt date", null=True
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        help_text="Project this entity belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_entities",
                        to="Project.project",
                    ),
                ),
            ],
            options={
                "verbose_name": "Material Entity",
                "verbose_name_plural": "Material Entities",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="OverheadEntity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When this record was created"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="When this record was last modified"
                    ),
                ),
                (
                    "deleted",
                    models.BooleanField(default=False, help_text="Soft delete flag"),
                ),
                ("name", models.CharField(help_text="Entity name", max_length=255)),
                (
                    "reference_no",
                    models.CharField(
                        blank=True,
                        help_text="Unique reference number",
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "unit",
                    models.CharField(
                        blank=True, help_text="Unit of measure", max_length=50
                    ),
                ),
                (
                    "rate",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Rate per unit",
                        max_digits=12,
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, help_text="General description"),
                ),
                (
                    "category",
                    models.CharField(
                        blank=True, help_text="Overhead category", max_length=100
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        help_text="Project this entity belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_entities",
                        to="Project.project",
                    ),
                ),
            ],
            options={
                "verbose_name": "Overhead Entity",
                "verbose_name_plural": "Overhead Entities",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="PlantEntity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When this record was created"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="When this record was last modified"
                    ),
                ),
                (
                    "deleted",
                    models.BooleanField(default=False, help_text="Soft delete flag"),
                ),
                ("name", models.CharField(help_text="Entity name", max_length=255)),
                (
                    "reference_no",
                    models.CharField(
                        blank=True,
                        help_text="Unique reference number",
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "unit",
                    models.CharField(
                        blank=True, help_text="Unit of measure", max_length=50
                    ),
                ),
                (
                    "rate",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Rate per unit",
                        max_digits=12,
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, help_text="General description"),
                ),
                (
                    "specific_info",
                    models.TextField(
                        blank=True, help_text="Specific machine info (S/N, etc.)"
                    ),
                ),
                ("supplier", models.CharField(blank=True, max_length=255)),
                (
                    "breakdown_status",
                    models.CharField(
                        blank=True, help_text="Current status", max_length=100
                    ),
                ),
                (
                    "date",
                    models.DateField(blank=True, help_text="Record date", null=True),
                ),
                (
                    "plant_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="plant_entities",
                        to="SiteManagement.planttype",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        help_text="Project this entity belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_entities",
                        to="Project.project",
                    ),
                ),
            ],
            options={
                "verbose_name": "Plant Entity",
                "verbose_name_plural": "Plant Entities",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="SubcontractorEntity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When this record was created"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="When this record was last modified"
                    ),
                ),
                (
                    "deleted",
                    models.BooleanField(default=False, help_text="Soft delete flag"),
                ),
                ("name", models.CharField(help_text="Entity name", max_length=255)),
                (
                    "reference_no",
                    models.CharField(
                        blank=True,
                        help_text="Unique reference number",
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "unit",
                    models.CharField(
                        blank=True, help_text="Unit of measure", max_length=50
                    ),
                ),
                (
                    "rate",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Rate per unit",
                        max_digits=12,
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, help_text="General description"),
                ),
                ("trade", models.CharField(blank=True, max_length=100)),
                ("scope", models.TextField(blank=True, help_text="Scope of work")),
                ("start_date", models.DateField(blank=True, null=True)),
                ("planned_finish_date", models.DateField(blank=True, null=True)),
                ("actual_finish_date", models.DateField(blank=True, null=True)),
                (
                    "project",
                    models.ForeignKey(
                        help_text="Project this entity belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_entities",
                        to="Project.project",
                    ),
                ),
            ],
            options={
                "verbose_name": "Subcontractor Entity",
                "verbose_name_plural": "Subcontractor Entities",
                "ordering": ["name"],
            },
        ),
    ]
