# Generated by Django 5.2.12 on 2026-04-01 03:30

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Project", "0069_merge_20260401_0529"),
    ]

    operations = [
        migrations.CreateModel(
            name="LabourCostLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When this record was created"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="When this record was last modified"
                    ),
                ),
                (
                    "deleted",
                    models.BooleanField(default=False, help_text="Soft delete flag"),
                ),
                ("worker_name", models.CharField(max_length=255)),
                (
                    "worker_id",
                    models.CharField(
                        blank=True, default="", help_text="Employee ID", max_length=50
                    ),
                ),
                (
                    "days",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Amount of days",
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "salary_rate",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Salary/Rate",
                        max_digits=15,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "total_cost",
                    models.DecimalField(
                        decimal_places=2, editable=False, max_digits=15
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="labour_cost_logs",
                        to="Project.project",
                    ),
                ),
            ],
            options={
                "verbose_name": "Labour Cost Log",
                "verbose_name_plural": "Labour Cost Logs",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="OverheadCostLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When this record was created"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="When this record was last modified"
                    ),
                ),
                (
                    "deleted",
                    models.BooleanField(default=False, help_text="Soft delete flag"),
                ),
                ("description", models.CharField(max_length=255)),
                (
                    "days",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Amount of days",
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "rate",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Rate",
                        max_digits=15,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "total_cost",
                    models.DecimalField(
                        decimal_places=2, editable=False, max_digits=15
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="overhead_costs",
                        to="Project.project",
                    ),
                ),
            ],
            options={
                "verbose_name": "Overhead Cost Log",
                "verbose_name_plural": "Overhead Cost Logs",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SubcontractorCostLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When this record was created"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="When this record was last modified"
                    ),
                ),
                (
                    "deleted",
                    models.BooleanField(default=False, help_text="Soft delete flag"),
                ),
                ("subcontractor_name", models.CharField(max_length=255)),
                (
                    "reference_no",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                (
                    "days",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Amount of days",
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "rate",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Daily rate",
                        max_digits=15,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "total_cost",
                    models.DecimalField(
                        decimal_places=2, editable=False, max_digits=15
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subcontractor_costs",
                        to="Project.project",
                    ),
                ),
            ],
            options={
                "verbose_name": "Subcontractor Cost Log",
                "verbose_name_plural": "Subcontractor Cost Logs",
                "ordering": ["-created_at"],
            },
        ),
    ]
