# Generated by Django 5.2.12 on 2026-04-07 01:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Project", "0070_labourentity_materialentity_overheadentity_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="plantentity",
            name="breakdown_status",
            field=models.CharField(
                choices=[
                    ("OPERATIONAL", "Operational"),
                    ("BREAKDOWN", "Breakdown"),
                    ("UNDER_MAINTENANCE", "Under Maintenance"),
                    ("RETIRED", "Retired"),
                ],
                default="OPERATIONAL",
                help_text="Current breakdown status",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="JournalEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When this record was created"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="When this record was last modified"
                    ),
                ),
                (
                    "deleted",
                    models.BooleanField(default=False, help_text="Soft delete flag"),
                ),
                ("date", models.DateField(help_text="Transaction date")),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("MATERIAL", "Material"),
                            ("LABOUR", "Labour"),
                            ("SUBCONTRACTOR", "Subcontractor"),
                            ("OVERHEAD", "Overhead"),
                            ("PLANT", "Plant"),
                            ("OTHER", "Other"),
                        ],
                        help_text="Category of transaction",
                        max_length=50,
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        help_text="Description of transaction", max_length=255
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, help_text="Total amount", max_digits=12
                    ),
                ),
                (
                    "transaction_type",
                    models.CharField(
                        choices=[("DEBIT", "Debit"), ("CREDIT", "Credit")],
                        default="DEBIT",
                        max_length=10,
                    ),
                ),
                (
                    "source_log_id",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="ID of the source log (Daily Diary, etc.)",
                        null=True,
                    ),
                ),
                (
                    "source_log_type",
                    models.CharField(
                        blank=True,
                        help_text="Type of the source daily log",
                        max_length=100,
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        help_text="Project this journal entry belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="journal_entries",
                        to="Project.project",
                    ),
                ),
            ],
            options={
                "verbose_name": "Journal Entry",
                "verbose_name_plural": "Journal Entries",
                "ordering": ["-date", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="LabourCostTracker",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When this record was created"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="When this record was last modified"
                    ),
                ),
                (
                    "deleted",
                    models.BooleanField(default=False, help_text="Soft delete flag"),
                ),
                ("date", models.DateField(help_text="Date of monitoring")),
                (
                    "id_number",
                    models.CharField(
                        blank=True, help_text="Worker's ID number", max_length=100
                    ),
                ),
                (
                    "amount_of_days",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Amount of days worked",
                        max_digits=12,
                    ),
                ),
                (
                    "salary",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Daily salary/rate",
                        max_digits=12,
                    ),
                ),
                (
                    "labour_entity",
                    models.ForeignKey(
                        help_text="Link to master labour definition",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cost_logs",
                        to="Project.labourentity",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        help_text="Project this cost log belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="labour_cost_logs",
                        to="Project.project",
                    ),
                ),
            ],
            options={
                "verbose_name": "Labour Cost Tracker",
                "verbose_name_plural": "Labour Cost Trackers",
                "ordering": ["-date", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="OverheadCostTracker",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When this record was created"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="When this record was last modified"
                    ),
                ),
                (
                    "deleted",
                    models.BooleanField(default=False, help_text="Soft delete flag"),
                ),
                ("date", models.DateField(help_text="Date of monitoring")),
                (
                    "amount_of_days",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Amount of days tracked",
                        max_digits=12,
                    ),
                ),
                (
                    "rate",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Daily rate/cost",
                        max_digits=12,
                    ),
                ),
                (
                    "overhead_entity",
                    models.ForeignKey(
                        help_text="Link to master overhead definition",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cost_logs",
                        to="Project.overheadentity",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        help_text="Project this cost log belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="overhead_cost_logs",
                        to="Project.project",
                    ),
                ),
            ],
            options={
                "verbose_name": "Overhead Cost Tracker",
                "verbose_name_plural": "Overhead Cost Trackers",
                "ordering": ["-date", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SubcontractorCostTracker",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When this record was created"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="When this record was last modified"
                    ),
                ),
                (
                    "deleted",
                    models.BooleanField(default=False, help_text="Soft delete flag"),
                ),
                ("date", models.DateField(help_text="Date of monitoring")),
                (
                    "reference_no",
                    models.CharField(
                        blank=True,
                        help_text="Reference number for the transaction",
                        max_length=100,
                    ),
                ),
                (
                    "amount_of_days",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Number of days/units tracked",
                        max_digits=12,
                    ),
                ),
                (
                    "rate",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Rate per day/unit",
                        max_digits=12,
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        help_text="Project this cost log belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subcontractor_cost_logs",
                        to="Project.project",
                    ),
                ),
                (
                    "subcontractor_entity",
                    models.ForeignKey(
                        help_text="Link to master subcontractor definition",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cost_logs",
                        to="Project.subcontractorentity",
                    ),
                ),
            ],
            options={
                "verbose_name": "Subcontractor Cost Tracker",
                "verbose_name_plural": "Subcontractor Cost Trackers",
                "ordering": ["-date", "-created_at"],
            },
        ),
    ]
