# Generated by Django 5.2.12 on 2026-04-12 22:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("BillOfQuantities", "0024_alter_specialitemtransaction_special_item_type"),
        ("Project", "0071_journalentry_labourentity_labourcosttracker_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="productionplan",
            name="bill",
            field=models.ForeignKey(
                default=1,
                help_text="The BOQ Bill this plan belongs to",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="production_plans",
                to="BillOfQuantities.bill",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="productionplan",
            name="package",
            field=models.ForeignKey(
                default=1,
                help_text="The BOQ Package this plan belongs to",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="production_plans",
                to="BillOfQuantities.package",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="productionplan",
            name="structure",
            field=models.ForeignKey(
                default=1,
                help_text="The building or structure this plan belongs to",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="production_plans",
                to="BillOfQuantities.structure",
            ),
            preserve_default=False,
        ),
    ]
