# Generated by Django 5.2.12 on 2026-04-07 03:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Project", "0071_alter_plantentity_breakdown_status_journalentry_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="MaterialCostTracker",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When this record was created"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="When this record was last modified"
                    ),
                ),
                (
                    "deleted",
                    models.BooleanField(default=False, help_text="Soft delete flag"),
                ),
                ("date", models.DateField(help_text="Date of monitoring")),
                (
                    "invoice_number",
                    models.CharField(
                        blank=True,
                        help_text="Invoice number for the transaction",
                        max_length=100,
                    ),
                ),
                (
                    "quantity",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Quantity of material used/bought",
                        max_digits=12,
                    ),
                ),
                (
                    "rate",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Rate per unit",
                        max_digits=12,
                    ),
                ),
                (
                    "material_entity",
                    models.ForeignKey(
                        help_text="Link to master material definition",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cost_logs",
                        to="Project.materialentity",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        help_text="Project this cost log belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="material_cost_logs",
                        to="Project.project",
                    ),
                ),
            ],
            options={
                "verbose_name": "Material Cost Tracker",
                "verbose_name_plural": "Material Cost Trackers",
                "ordering": ["-date", "-created_at"],
            },
        ),
    ]
