# Generated by Django 6.0.4 on 2026-04-14 11:22

from django.db import migrations


def handle_orphaned_material_cost_trackers(apps, schema_editor):
    """
    Handle MaterialCostTracker records with null material_entity.
    These records may cause RelatedObjectDoesNotExist errors.
    """
    MaterialCostTracker = apps.get_model("Project", "MaterialCostTracker")
    MaterialEntity = apps.get_model("Project", "MaterialEntity")

    # Find all MaterialCostTracker records with null material_entity
    orphaned_trackers = MaterialCostTracker.objects.filter(material_entity__isnull=True)

    if orphaned_trackers.exists():
        # Create a default MaterialEntity for orphaned records
        default_entity, created = MaterialEntity.objects.get_or_create(
            name="Unknown Material",
            defaults={
                "supplier": "Unknown",
                "rate": 0,
                "unit": "unit",
            },
        )

        # Link all orphaned trackers to the default entity
        orphaned_trackers.update(material_entity=default_entity)


class Migration(migrations.Migration):
    dependencies = [
        ("Project", "0071_journalentry_labourentity_labourcosttracker_and_more"),
    ]

    operations = [
        migrations.RunPython(
            handle_orphaned_material_cost_trackers, migrations.RunPython.noop
        ),
    ]
