# Generated by Django 5.2.12 on 2026-04-13 09:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("BillOfQuantities", "0024_alter_specialitemtransaction_special_item_type"),
        ("Project", "0072_productionplan_bill_productionplan_package_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="productionplan",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                help_text="Parent activity for nesting",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="children",
                to="Project.productionplan",
            ),
        ),
        migrations.AlterField(
            model_name="productionplan",
            name="bill",
            field=models.ForeignKey(
                blank=True,
                help_text="The BOQ Bill this plan belongs to",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="production_plans",
                to="BillOfQuantities.bill",
            ),
        ),
        migrations.AlterField(
            model_name="productionplan",
            name="package",
            field=models.ForeignKey(
                blank=True,
                help_text="The BOQ Package this plan belongs to",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="production_plans",
                to="BillOfQuantities.package",
            ),
        ),
    ]
