# Generated by Django 6.0.4 on 2026-04-14 11:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Project", "0072_fix_orphaned_material_cost_trackers"),
    ]

    operations = [
        migrations.AlterField(
            model_name="materialcosttracker",
            name="material_entity",
            field=models.ForeignKey(
                blank=True,
                help_text="Link to master material definition",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="cost_logs",
                to="Project.materialentity",
            ),
        ),
    ]
