# Generated by Django 5.2.12 on 2026-04-07 04:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Project", "0072_materialcosttracker"),
    ]

    operations = [
        migrations.CreateModel(
            name="PlantCostTracker",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When this record was created"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="When this record was last modified"
                    ),
                ),
                (
                    "deleted",
                    models.BooleanField(default=False, help_text="Soft delete flag"),
                ),
                ("date", models.DateField(help_text="Date of usage")),
                (
                    "usage_hours",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Total usage hours",
                        max_digits=10,
                    ),
                ),
                (
                    "hourly_rate",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Hourly rate",
                        max_digits=12,
                    ),
                ),
                (
                    "plant_entity",
                    models.ForeignKey(
                        help_text="Link to master plant definition",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cost_logs",
                        to="Project.plantentity",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        help_text="Project this cost log belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="plant_cost_logs",
                        to="Project.project",
                    ),
                ),
            ],
            options={
                "verbose_name": "Plant Cost Tracker",
                "verbose_name_plural": "Plant Cost Trackers",
                "ordering": ["-date", "-created_at"],
            },
        ),
    ]
