# Generated by Django 5.2.12 on 2026-04-13 10:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Project", "0073_productionplan_parent_alter_productionplan_bill_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productionplan",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                help_text="Parent activity for nesting",
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="children",
                to="Project.productionplan",
            ),
        ),
        migrations.CreateModel(
            name="PlanDependency",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When this record was created"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="When this record was last modified"
                    ),
                ),
                (
                    "deleted",
                    models.BooleanField(default=False, help_text="Soft delete flag"),
                ),
                (
                    "predecessor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="successors",
                        to="Project.productionplan",
                    ),
                ),
                (
                    "successor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="predecessors",
                        to="Project.productionplan",
                    ),
                ),
            ],
            options={
                "verbose_name": "Plan Dependency",
                "verbose_name_plural": "Plan Dependencies",
                "unique_together": {("predecessor", "successor")},
            },
        ),
    ]
