# Generated by Django 5.2.12 on 2026-04-18 16:05

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Project", "0073_make_material_entity_nullable"),
        ("estimator", "0011_boqitem_plant_prelim_specs"),
    ]

    operations = [
        migrations.CreateModel(
            name="PlanDependency",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When this record was created"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="When this record was last modified"
                    ),
                ),
                (
                    "deleted",
                    models.BooleanField(default=False, help_text="Soft delete flag"),
                ),
            ],
            options={
                "verbose_name": "Plan Dependency",
                "verbose_name_plural": "Plan Dependencies",
            },
        ),
        migrations.RemoveConstraint(
            model_name="productionplan",
            name="unique_plan_activity_date",
        ),
        migrations.AddField(
            model_name="dailyactivityentry",
            name="hours_on_activity",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Total hours spent on this activity",
                max_digits=5,
            ),
        ),
        migrations.AddField(
            model_name="dailyplantusage",
            name="quantity",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Production quantity achieved by this specific plant resource.",
                max_digits=12,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
        migrations.AddField(
            model_name="productionplan",
            name="bill_no",
            field=models.CharField(
                blank=True,
                help_text="Manual bill no or inherited from Activity",
                max_length=200,
            ),
        ),
        migrations.AddField(
            model_name="productionplan",
            name="labour_activity",
            field=models.ForeignKey(
                blank=True,
                help_text="The Labor Specification this plan belongs to",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="production_plans",
                to="estimator.projectlabourspecification",
            ),
        ),
        migrations.AddField(
            model_name="productionplan",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                help_text="Parent activity for nesting",
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="children",
                to="Project.productionplan",
            ),
        ),
        migrations.AddField(
            model_name="productionplan",
            name="plant_specification",
            field=models.ForeignKey(
                blank=True,
                help_text="Optional Plant Specification for this plan",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="production_plans",
                to="estimator.projectplantspecification",
            ),
        ),
        migrations.AddField(
            model_name="productionplan",
            name="plant_types",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Cached list of plant types from BOQ",
            ),
        ),
        migrations.AddField(
            model_name="productionplan",
            name="section",
            field=models.CharField(
                blank=True,
                help_text="Manual section or inherited from Activity",
                max_length=200,
            ),
        ),
        migrations.AlterField(
            model_name="productionplan",
            name="activity",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddConstraint(
            model_name="productionplan",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_archived", False)),
                fields=("project", "section", "bill_no", "activity", "start_date"),
                name="unique_plan_activity_date",
            ),
        ),
        migrations.AddField(
            model_name="plandependency",
            name="predecessor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="successors",
                to="Project.productionplan",
            ),
        ),
        migrations.AddField(
            model_name="plandependency",
            name="successor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="predecessors",
                to="Project.productionplan",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="plandependency",
            unique_together={("predecessor", "successor")},
        ),
    ]
