# Generated by Django 6.0.1 on 2026-04-19 13:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import app.core.Utilities.models


class Migration(migrations.Migration):
    dependencies = [
        ("Project", "0073_make_material_entity_nullable"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="OrderAmendment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="created at"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
                ("deleted", models.DateTimeField(blank=True, null=True)),
                (
                    "amendment_number",
                    models.CharField(
                        help_text="Amendment number (e.g., 1, 2, A, B)", max_length=50
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Short name for the amendment", max_length=200
                    ),
                ),
                (
                    "description",
                    models.TextField(help_text="Detailed description of the amendment"),
                ),
                (
                    "justification",
                    models.TextField(
                        blank=True, help_text="Justification for the amendment"
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("scope_change", "Scope Change"),
                            ("design_change", "Design Change"),
                            ("rate_adjustment", "Rate Adjustment"),
                            ("quantity_variance", "Quantity Variance"),
                            ("delay_costs", "Delay Costs"),
                            ("other", "Other"),
                        ],
                        default="other",
                        help_text="Category of the amendment",
                        max_length=50,
                    ),
                ),
                (
                    "variation_amount",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Variation amount in project currency (positive or negative)",
                        max_digits=15,
                    ),
                ),
                (
                    "date_approved",
                    models.DateField(
                        blank=True,
                        help_text="Date the amendment was approved",
                        null=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                        ],
                        default="pending",
                        help_text="Current status of the amendment",
                        max_length=20,
                    ),
                ),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Person who approved the amendment",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_amendments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        help_text="Project this amendment belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="order_amendments",
                        to="Project.project",
                    ),
                ),
            ],
            options={
                "ordering": ["amendment_number"],
                "verbose_name": "Order Amendment",
                "verbose_name_plural": "Order Amendments",
            },
            bases=(app.core.Utilities.models.BaseModel, models.Model),
        ),
        migrations.AddConstraint(
            model_name="orderamendment",
            constraint=models.UniqueConstraint(
                fields=("project", "amendment_number"),
                name="unique_amendment_number_per_project",
            ),
        ),
    ]
