# Generated by Django 5.2.12 on 2026-04-07 13:28

from django.db import migrations, models

import app.Project.profitability.materials.models


class Migration(migrations.Migration):
    dependencies = [
        ("Project", "0073_plantcosttracker"),
    ]

    operations = [
        migrations.AddField(
            model_name="materialcosttracker",
            name="invoice_attachment",
            field=models.FileField(
                blank=True,
                help_text="Attach a copy of the invoice (PDF or Image)",
                null=True,
                upload_to=app.Project.profitability.materials.models.material_invoice_upload_path,
            ),
        ),
    ]
