# Generated by Django 5.2.12 on 2026-04-20 06:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Project", "0074_plandependency_and_more"),
        ("estimator", "0011_boqitem_plant_prelim_specs"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="productionplan",
            name="unique_plan_activity_date",
        ),
        migrations.AddField(
            model_name="productionplan",
            name="daily_rate",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Daily production rate",
                max_digits=10,
            ),
        ),
        migrations.AlterField(
            model_name="productionplan",
            name="finish_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="productionplan",
            name="start_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name="productionplan",
            constraint=models.UniqueConstraint(
                fields=("project", "section", "bill_no", "activity", "start_date"),
                name="unique_plan_activity_date",
            ),
        ),
    ]
