# Generated by Django 5.2.12 on 2026-04-14 01:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("BillOfQuantities", "0024_alter_specialitemtransaction_special_item_type"),
        ("Project", "0074_alter_productionplan_parent_plandependency"),
    ]

    operations = [
        migrations.AddField(
            model_name="productionplan",
            name="line_item",
            field=models.ForeignKey(
                blank=True,
                help_text="The BOQ Line Item (Trade Code) this plan belongs to",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="production_plans",
                to="BillOfQuantities.lineitem",
            ),
        ),
        migrations.AddField(
            model_name="productionplan",
            name="trade_code",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="productionplan",
            name="activity",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
