# Generated by Django 5.2.12 on 2026-04-07 13:50

from django.db import migrations, models

import app.Project.models.entity_definitions


class Migration(migrations.Migration):
    dependencies = [
        ("Project", "0074_materialcosttracker_invoice_attachment"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="materialcosttracker",
            name="invoice_attachment",
        ),
        migrations.AddField(
            model_name="materialentity",
            name="invoice_attachment",
            field=models.FileField(
                blank=True,
                help_text="Attach a copy of the invoice (PDF or Image)",
                null=True,
                upload_to=app.Project.models.entity_definitions.material_entity_invoice_path,
            ),
        ),
    ]
