# Generated by Django 6.0.3 on 2026-04-20 08:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Project", "0074_orderamendment"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="orderamendment",
            name="unique_amendment_number_per_project",
        ),
        migrations.AlterField(
            model_name="orderamendment",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, help_text="When this record was created"
            ),
        ),
        migrations.AlterField(
            model_name="orderamendment",
            name="deleted",
            field=models.BooleanField(default=False, help_text="Soft delete flag"),
        ),
        migrations.AlterField(
            model_name="orderamendment",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, help_text="When this record was last modified"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="orderamendment",
            unique_together={("project", "amendment_number")},
        ),
    ]
