# Generated by Django 5.2.12 on 2026-04-08 04:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Project", "0075_remove_materialcosttracker_invoice_attachment_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="UnitOfMeasure",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When this record was created"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="When this record was last modified"
                    ),
                ),
                (
                    "deleted",
                    models.BooleanField(default=False, help_text="Soft delete flag"),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Full name of the unit (e.g., Kilogram)",
                        max_length=100,
                    ),
                ),
                (
                    "short_name",
                    models.CharField(
                        help_text="Abbreviation (e.g., kg)", max_length=20
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("WEIGHT", "Weight/Mass"),
                            ("VOLUME", "Volume"),
                            ("LENGTH", "Length"),
                            ("AREA", "Area"),
                            ("TIME", "Time"),
                            ("COUNT", "Count/Quantity"),
                            ("OTHER", "Other"),
                        ],
                        default="OTHER",
                        help_text="The type of measurement this unit represents",
                        max_length=20,
                    ),
                ),
                (
                    "conversion_factor",
                    models.DecimalField(
                        decimal_places=6,
                        default=1.0,
                        help_text="Multiplier to convert this unit to the reference unit",
                        max_digits=12,
                    ),
                ),
                (
                    "reference_unit",
                    models.ForeignKey(
                        blank=True,
                        help_text="The base unit this unit is relative to. If null, this is the base unit.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sub_units",
                        to="Project.unitofmeasure",
                    ),
                ),
            ],
            options={
                "verbose_name": "Unit of Measure",
                "verbose_name_plural": "Units of Measure",
                "ordering": ["category", "name"],
            },
        ),
    ]
