# Generated by Django 5.2.12 on 2026-04-14 02:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Project", "0075_productionplan_line_item_productionplan_trade_code_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="productionplan",
            name="trade_code",
        ),
    ]
