# Generated by Django 5.2.12 on 2026-04-19 21:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Project", "0075_remove_productionplan_unique_plan_activity_date_and_more"),
        ("estimator", "0011_boqitem_plant_prelim_specs"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="productionplan",
            name="unique_plan_activity_date",
        ),
        migrations.AddConstraint(
            model_name="productionplan",
            constraint=models.UniqueConstraint(
                fields=("project", "section", "bill_no", "activity", "start_date"),
                name="unique_plan_activity_date",
            ),
        ),
    ]
