# Generated by Django 5.2.12 on 2026-04-08 06:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Project", "0076_unitofmeasure"),
    ]

    operations = [
        migrations.AddField(
            model_name="labourentity",
            name="unit_of_measure",
            field=models.ForeignKey(
                blank=True,
                help_text="Centralized unit of measure",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_entities",
                to="Project.unitofmeasure",
            ),
        ),
        migrations.AddField(
            model_name="materialentity",
            name="unit_of_measure",
            field=models.ForeignKey(
                blank=True,
                help_text="Centralized unit of measure",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_entities",
                to="Project.unitofmeasure",
            ),
        ),
        migrations.AddField(
            model_name="overheadentity",
            name="unit_of_measure",
            field=models.ForeignKey(
                blank=True,
                help_text="Centralized unit of measure",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_entities",
                to="Project.unitofmeasure",
            ),
        ),
        migrations.AddField(
            model_name="plantentity",
            name="unit_of_measure",
            field=models.ForeignKey(
                blank=True,
                help_text="Centralized unit of measure",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_entities",
                to="Project.unitofmeasure",
            ),
        ),
        migrations.AddField(
            model_name="subcontractorentity",
            name="unit_of_measure",
            field=models.ForeignKey(
                blank=True,
                help_text="Centralized unit of measure",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_entities",
                to="Project.unitofmeasure",
            ),
        ),
    ]
