# Generated by Django 5.2.12 on 2026-04-15 12:06

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("Project", "0073_make_material_entity_nullable"),
        ("Project", "0076_remove_productionplan_trade_code"),
    ]

    operations = []
