# Generated by Django 6.0.3 on 2026-04-20 12:15

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("Project", "0074_orderamendment"),
        ("Project", "0076_remove_milestone_project_sub_category_and_more"),
    ]

    operations = []
