# Generated by Django 6.0.3 on 2026-04-20 12:45

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("Project", "0074_plandependency_and_more"),
        (
            "Project",
            "0077_merge_0074_orderamendment_0076_remove_milestone_project_sub_category_and_more",
        ),
    ]

    operations = []
