# Generated by Django 5.2.12 on 2026-04-09 05:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Project", "0077_labourentity_unit_of_measure_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="journalentry",
            name="category",
            field=models.CharField(
                choices=[
                    ("MATERIAL", "Material"),
                    ("LABOUR", "Labour"),
                    ("SUBCONTRACTOR", "Subcontractor"),
                    ("OVERHEAD", "Overhead"),
                    ("PLANT", "Plant"),
                    ("REVENUE", "Revenue"),
                    ("OTHER", "Other"),
                ],
                help_text="Category of transaction",
                max_length=50,
            ),
        ),
    ]
