# Generated by Django 5.2.12 on 2026-04-15 12:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Project", "0077_merge_20260415_1406"),
        ("estimator", "0011_boqitem_plant_prelim_specs"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="productionplan",
            name="unique_plan_activity_date",
        ),
        migrations.RemoveField(
            model_name="productionplan",
            name="bill",
        ),
        migrations.RemoveField(
            model_name="productionplan",
            name="line_item",
        ),
        migrations.RemoveField(
            model_name="productionplan",
            name="package",
        ),
        migrations.RemoveField(
            model_name="productionplan",
            name="structure",
        ),
        migrations.AddField(
            model_name="productionplan",
            name="bill_no",
            field=models.CharField(
                blank=True,
                help_text="Manual bill no or inherited from Estimator",
                max_length=200,
            ),
        ),
        migrations.AddField(
            model_name="productionplan",
            name="estimator_item",
            field=models.ForeignKey(
                blank=True,
                help_text="The Estimator BOQ Item this plan belongs to",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="production_plans",
                to="estimator.boqitem",
            ),
        ),
        migrations.AddField(
            model_name="productionplan",
            name="section",
            field=models.CharField(
                blank=True,
                help_text="Manual section or inherited from Estimator",
                max_length=200,
            ),
        ),
        migrations.AddConstraint(
            model_name="productionplan",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_archived", False)),
                fields=("project", "section", "bill_no", "activity", "start_date"),
                name="unique_plan_activity_date",
            ),
        ),
    ]
