# Generated by Django 5.2.12 on 2026-04-16 05:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Project", "0078_remove_productionplan_unique_plan_activity_date_and_more"),
        ("estimator", "0011_boqitem_plant_prelim_specs"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="productionplan",
            name="estimator_item",
        ),
        migrations.AddField(
            model_name="productionplan",
            name="labour_activity",
            field=models.ForeignKey(
                blank=True,
                help_text="The Labor Specification this plan belongs to",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="production_plans",
                to="estimator.projectlabourspecification",
            ),
        ),
        migrations.AlterField(
            model_name="productionplan",
            name="bill_no",
            field=models.CharField(
                blank=True,
                help_text="Manual bill no or inherited from Activity",
                max_length=200,
            ),
        ),
        migrations.AlterField(
            model_name="productionplan",
            name="section",
            field=models.CharField(
                blank=True,
                help_text="Manual section or inherited from Activity",
                max_length=200,
            ),
        ),
    ]
