# Generated by Django 6.0.3 on 2026-04-20 12:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Project', '0078_merge_0074_plandependency_and_more_0077_merge_0074_orderamendment_0076'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='users',
            field=models.ManyToManyField(blank=True, related_name='portfolios', to=settings.AUTH_USER_MODEL),
        ),
    ]
