# Generated by Django 5.2.12 on 2026-04-09 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Project", "0078_alter_journalentry_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="overheadentity",
            name="expense_code",
            field=models.CharField(
                choices=[("OPEX", "Operating Expenses"), ("COS", "Cost of Sales")],
                default="OPEX",
                help_text="Accounting classification",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="overheadentity",
            name="category",
            field=models.CharField(
                blank=True,
                help_text="Overhead category (e.g., Office, Site)",
                max_length=100,
            ),
        ),
    ]
