# Generated by Django 5.2.12 on 2026-04-16 10:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Project", "0079_remove_productionplan_estimator_item_and_more"),
        ("estimator", "0011_boqitem_plant_prelim_specs"),
    ]

    operations = [
        migrations.AddField(
            model_name="productionplan",
            name="plant_specification",
            field=models.ForeignKey(
                blank=True,
                help_text="The Plant Specification used for this plan",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="production_plans",
                to="estimator.projectplantspecification",
            ),
        ),
    ]
