# Generated by Django 5.2.12 on 2026-04-10 01:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Project", "0079_overheadentity_expense_code_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="labourentity",
            name="expense_code",
            field=models.CharField(
                choices=[("OPEX", "Operating Expenses"), ("COS", "Cost of Sales")],
                default="COS",
                help_text="Accounting classification",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="materialentity",
            name="expense_code",
            field=models.CharField(
                choices=[("OPEX", "Operating Expenses"), ("COS", "Cost of Sales")],
                default="COS",
                help_text="Accounting classification",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="plantentity",
            name="expense_code",
            field=models.CharField(
                choices=[("OPEX", "Operating Expenses"), ("COS", "Cost of Sales")],
                default="COS",
                help_text="Accounting classification",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="subcontractorentity",
            name="expense_code",
            field=models.CharField(
                choices=[("OPEX", "Operating Expenses"), ("COS", "Cost of Sales")],
                default="COS",
                help_text="Accounting classification",
                max_length=20,
            ),
        ),
    ]
