# Generated by Django 5.2.12 on 2026-04-21 12:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Project", "0080_remove_productionplan_unique_plan_activity_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="journalentry",
            name="transaction_type",
            field=models.CharField(
                choices=[("DEBIT", "Expense"), ("CREDIT", "Revenue")],
                default="DEBIT",
                max_length=10,
            ),
        ),
        migrations.CreateModel(
            name="ProfitabilityBaseline",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When this record was created"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="When this record was last modified"
                    ),
                ),
                (
                    "deleted",
                    models.BooleanField(default=False, help_text="Soft delete flag"),
                ),
                (
                    "cost_of_sales_percent",
                    models.DecimalField(
                        decimal_places=2,
                        default=60.0,
                        help_text="Targeted Cost of Sales as a percentage of revenue",
                        max_digits=5,
                    ),
                ),
                (
                    "operating_expenses_percent",
                    models.DecimalField(
                        decimal_places=2,
                        default=12.0,
                        help_text="Targeted Operating Expenses as a percentage of revenue",
                        max_digits=5,
                    ),
                ),
                (
                    "net_profit_percent",
                    models.DecimalField(
                        decimal_places=2,
                        default=28.0,
                        help_text="Targeted Net Profit as a percentage of revenue",
                        max_digits=5,
                    ),
                ),
                (
                    "project",
                    models.OneToOneField(
                        help_text="Project these baseline assumptions belong to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profitability_baseline",
                        to="Project.project",
                    ),
                ),
            ],
            options={
                "verbose_name": "Profitability Baseline",
                "verbose_name_plural": "Profitability Baselines",
            },
        ),
    ]
