# Generated by Django 5.2.12 on 2026-04-21 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Project", "0080_remove_productionplan_unique_plan_activity_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="journalentry",
            name="transaction_type",
            field=models.CharField(
                choices=[("DEBIT", "Expense"), ("CREDIT", "Revenue")],
                default="DEBIT",
                max_length=10,
            ),
        ),
    ]
