# Generated by Django 5.2.12 on 2026-04-21 00:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Project", "0080_remove_productionplan_unique_plan_activity_date_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="is_demo",
            field=models.BooleanField(
                default=False,
                help_text="Demo project: visible to all logged-in users but read-only for non-staff",
            ),
        ),
    ]
