# Generated by Django 5.2.12 on 2026-04-10 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Project", "0070_projectreportsummary"),
        ("Project", "0080_labourentity_expense_code_and_more"),
    ]

    operations = []
