# Generated by Django 5.2.12 on 2026-04-16 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Project", "0080_productionplan_plant_specification"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="productionplan",
            name="plant_specification",
        ),
    ]
