# Generated by Django 5.2.12 on 2026-04-21 12:15

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("Project", "0081_alter_journalentry_transaction_type_and_more"),
        ("Project", "0081_project_is_demo"),
    ]

    operations = []

