# Generated by Django 5.2.12 on 2026-04-11 22:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Project", "0081_merge_20260410_1313"),
    ]

    operations = [
        migrations.AddField(
            model_name="materialcosttracker",
            name="comments",
            field=models.TextField(blank=True, help_text="Additional comments"),
        ),
        migrations.AddField(
            model_name="materialcosttracker",
            name="intended_usage",
            field=models.TextField(
                blank=True, help_text="Intended usage for this material"
            ),
        ),
        migrations.AddField(
            model_name="overheadcosttracker",
            name="remarks",
            field=models.TextField(blank=True, help_text="Additional remarks"),
        ),
    ]
