# Generated by Django 5.2.12 on 2026-04-17 21:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Project", "0082_add_plant_spec_to_plan"),
    ]

    operations = [
        migrations.AddField(
            model_name="dailyactivityentry",
            name="hours_on_activity",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Total hours spent on this activity",
                max_digits=5,
            ),
        ),
        migrations.AddField(
            model_name="dailyplantusage",
            name="quantity",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Production quantity achieved by this specific plant resource.",
                max_digits=12,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
    ]
