# Generated by Django 5.2.12 on 2026-04-11 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Project", "0082_materialcosttracker_comments_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="labourcosttracker",
            name="remarks",
            field=models.TextField(blank=True, help_text="Additional remarks"),
        ),
        migrations.AddField(
            model_name="labourcosttracker",
            name="task_activity",
            field=models.TextField(blank=True, help_text="Specific task or activity"),
        ),
        migrations.AddField(
            model_name="plantcosttracker",
            name="breakdown_status",
            field=models.CharField(
                blank=True, help_text="Breakdown status during tracking", max_length=50
            ),
        ),
        migrations.AddField(
            model_name="plantcosttracker",
            name="maintenance_done",
            field=models.TextField(blank=True, help_text="Maintenance performed"),
        ),
        migrations.AddField(
            model_name="plantcosttracker",
            name="remarks",
            field=models.TextField(blank=True, help_text="Additional remarks"),
        ),
        migrations.AddField(
            model_name="subcontractorcosttracker",
            name="hours_worked",
            field=models.DecimalField(
                decimal_places=2, default=0, help_text="Hours worked", max_digits=10
            ),
        ),
        migrations.AddField(
            model_name="subcontractorcosttracker",
            name="remarks",
            field=models.TextField(blank=True, help_text="Additional remarks"),
        ),
        migrations.AddField(
            model_name="subcontractorcosttracker",
            name="task",
            field=models.TextField(blank=True, help_text="Specific task or scope"),
        ),
    ]
