# Generated by Django 5.2.12 on 2026-04-23 18:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Project", "0082_alter_journalentry_transaction_type_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="productionplan",
            name="is_leaf",
            field=models.BooleanField(
                default=True,
                help_text="True if this is a work activity, False for structural headers.",
            ),
        ),
        migrations.AddField(
            model_name="productionplan",
            name="node_type",
            field=models.CharField(
                choices=[
                    ("SECTION", "Section Header"),
                    ("BILL", "Bill Header"),
                    ("ACTIVITY", "Work Activity"),
                ],
                default="ACTIVITY",
                max_length=20,
            ),
        ),
    ]
