# Generated by Django 5.2.12 on 2026-04-24 13:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Project", "0083_productionplan_is_leaf_productionplan_node_type"),
        ("estimator", "0012_remove_projectplantspecification_plant_type_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="dailyplantusage",
            name="plant_type",
            field=models.ForeignKey(
                blank=True,
                help_text="The master plant cost record from the specification.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="usages",
                to="estimator.projectplantcost",
            ),
        ),
        migrations.AlterField(
            model_name="dailyplantusage",
            name="resource",
            field=models.ForeignKey(
                blank=True,
                help_text="Legacy: The specific plant resource allocated to the plan.",
                limit_choices_to={"resource_type": "PLANT"},
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="Project.productionresource",
            ),
        ),
    ]
