# Generated by Django 5.2.12 on 2026-04-17 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Project", "0083_dailyactivityentry_hours_on_activity_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="productionplan",
            name="plant_types",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Cached list of plant types from BOQ",
            ),
        ),
    ]
