# Generated by Django 5.2.12 on 2026-05-04 01:35

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Project", "0084_project_stage"),
    ]

    operations = [
        migrations.AddField(
            model_name="dailyactivityentry",
            name="date",
            field=models.DateField(
                blank=True, default=django.utils.timezone.now, null=True
            ),
        ),
        migrations.AddField(
            model_name="dailyactivityentry",
            name="notes",
            field=models.TextField(
                blank=True, help_text="Optional activity-specific remarks"
            ),
        ),
        migrations.AddField(
            model_name="dailyactivityentry",
            name="project",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="daily_entries",
                to="Project.project",
            ),
        ),
        migrations.AlterField(
            model_name="dailyactivityentry",
            name="report",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="entries",
                to="Project.dailyactivityreport",
            ),
        ),
    ]
