# Generated by Django 5.2.12 on 2026-05-04 01:36

from django.db import migrations


def migrate_report_to_entry(apps, schema_editor):
    DailyActivityReport = apps.get_model("Project", "DailyActivityReport")
    DailyActivityEntry = apps.get_model("Project", "DailyActivityEntry")
    for report in DailyActivityReport.objects.all():
        DailyActivityEntry.objects.filter(report=report).update(
            project=report.project,
            date=report.date,
            notes=report.notes
        )


class Migration(migrations.Migration):

    dependencies = [
        ("Project", "0085_dailyactivityentry_date_dailyactivityentry_notes_and_more"),
    ]

    operations = [
        migrations.RunPython(migrate_report_to_entry),
    ]
