# Generated by Django 5.2.12 on 2026-05-06 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Project", "0085_remove_dailyactivityentry_report_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="productionplan",
            name="crew_count",
            field=models.DecimalField(
                decimal_places=2,
                default=1,
                help_text="Number of crews/resources assigned (multiplier)",
                max_digits=5,
            ),
        ),
    ]
