# Generated by Django 5.2.12 on 2026-05-04 01:41

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Project", "0086_migrate_activity_report_data"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="dailyactivityentry",
            name="report",
        ),
        migrations.AlterField(
            model_name="dailyactivityentry",
            name="date",
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="dailyactivityentry",
            name="project",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="daily_entries",
                to="Project.project",
            ),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name="DailyActivityReport",
        ),
    ]
