# Generated by Django 5.2.12 on 2026-05-11 14:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Project", "0086_productionplan_crew_count"),
    ]

    operations = [
        migrations.AddField(
            model_name="milestone",
            name="project_sub_category",
            field=models.ForeignKey(
                blank=True,
                help_text="WBS Level 2 classification",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="milestones",
                to="Project.subcategory",
            ),
        ),
        migrations.AlterField(
            model_name="productionplan",
            name="crew_count",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                default=1,
                help_text="Number of crews/resources assigned (multiplier)",
                max_digits=5,
            ),
        ),
    ]
