# Generated by Django 5.2.12 on 2026-05-16 15:06

import django.db.models.deletion
from django.db import migrations, models

import app.Project.documents.document_models


class Migration(migrations.Migration):
    dependencies = [
        ("Project", "0087_milestone_project_sub_category_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Drawing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When this record was created"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="When this record was last modified"
                    ),
                ),
                (
                    "deleted",
                    models.BooleanField(default=False, help_text="Soft delete flag"),
                ),
                (
                    "drawing_number",
                    models.CharField(
                        help_text="Unique identifier for the drawing", max_length=100
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Title or name of the drawing", max_length=255
                    ),
                ),
                (
                    "revision_number",
                    models.CharField(
                        help_text="Current revision number (e.g., A, 01, Rev 1)",
                        max_length=50,
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        help_text="The uploaded drawing file (PDF, CAD, etc.)",
                        upload_to=app.Project.documents.document_models.Drawing.upload_to,
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Additional notes about the drawing",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        help_text="Project category (Level 1)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="drawings",
                        to="Project.category",
                    ),
                ),
                (
                    "discipline",
                    models.ForeignKey(
                        blank=True,
                        help_text="Professional discipline this drawing belongs to",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="drawings",
                        to="Project.discipline",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        help_text="Parent drawing for nested hierarchy",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to="Project.drawing",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        help_text="Project this drawing belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="drawings",
                        to="Project.project",
                    ),
                ),
                (
                    "sub_category",
                    models.ForeignKey(
                        blank=True,
                        help_text="Project sub-category (Level 2)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="drawings",
                        to="Project.subcategory",
                    ),
                ),
            ],
            options={
                "verbose_name": "Drawing",
                "verbose_name_plural": "Drawings",
                "ordering": ["drawing_number"],
                "indexes": [
                    models.Index(
                        fields=["project", "drawing_number"],
                        name="Project_dra_project_2c3b51_idx",
                    ),
                    models.Index(
                        fields=["discipline"], name="Project_dra_discipl_7bee85_idx"
                    ),
                ],
            },
        ),
    ]
