# Generated by Django 5.2.12 on 2026-06-05 05:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Project", "0088_drawing"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="certificate_layout",
            field=models.CharField(
                choices=[("STANDARD", "Standard"), ("VALTERRA_RPM", "Valterra/RPM")],
                default="STANDARD",
                help_text="Select the layout style for payment certificates",
                max_length=50,
            ),
        ),
    ]
