# Generated by Django 5.2.12 on 2026-06-08 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Project", "0089_project_certificate_layout"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="column_config",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Custom configuration for report columns (name, visibility, and order)",
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="certificate_layout",
            field=models.CharField(
                choices=[
                    ("STANDARD", "Standard"),
                    ("VALTERRA_RPM", "Valterra/RPM"),
                    ("LEPHADIMISHA", "Lephadimisha BOQ Report"),
                ],
                default="STANDARD",
                help_text="Select the layout style for payment certificates",
                max_length=50,
            ),
        ),
    ]
