# Generated by Django 5.2.12 on 2026-06-12 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Project", "0090_project_column_config_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="project",
            name="certificate_layout",
        ),
    ]
