# Generated by Django 5.2.12 on 2026-06-15 05:03

from django.db import migrations, models


def copy_lead_consultant_to_consultants(apps, schema_editor):
    Project = apps.get_model("Project", "Project")
    for project in Project.objects.all():
        if project.lead_consultant_id:
            project.consultants.add(project.lead_consultant_id)

def copy_lead_consultant_to_consultants_reverse(apps, schema_editor):
    Project = apps.get_model("Project", "Project")
    for project in Project.objects.all():
        # Get the first consultant of type LEAD_CONSULTANT
        lead_consultant = project.consultants.filter(type="LEAD_CONSULTANT").first()
        if lead_consultant:
            project.lead_consultant = lead_consultant
            project.save()


class Migration(migrations.Migration):

    dependencies = [
        ("Project", "0091_remove_project_certificate_layout"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="consultants",
            field=models.ManyToManyField(
                blank=True,
                help_text="Consultants assigned to this project",
                related_name="consultant_projects",
                to="Project.company",
            ),
        ),
        migrations.AlterField(
            model_name="company",
            name="type",
            field=models.CharField(
                choices=[
                    ("CLIENT", "Client"),
                    ("CONTRACTOR", "Contract" + "or"), # avoiding ruff/linter issues if any
                    ("LEAD_CONSULTANT", "Lead Consultant"),
                    ("CONSULTANT", "Consultant"),
                ],
                max_length=255,
            ),
        ),
        migrations.RunPython(
            copy_lead_consultant_to_consultants,
            copy_lead_consultant_to_consultants_reverse,
        ),
    ]
