# Generated by Django 5.2.12 on 2026-06-15 05:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Project", "0092_project_consultants_alter_company_type"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="project",
            name="lead_consultant",
        ),
    ]
