# Generated by Django 5.2.12 on 2026-06-16 00:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Project", "0093_remove_project_lead_consultant"),
    ]

    operations = [
        migrations.AddField(
            model_name="company",
            name="disciplines",
            field=models.ManyToManyField(
                blank=True,
                help_text="Disciplines of expertise for this company (if consultant)",
                related_name="companies",
                to="Project.projectdiscipline",
            ),
        ),
    ]
