# Generated by Django 5.2.12 on 2026-06-16

from django.db import migrations


def populate_disciplines(apps, schema_editor):
    ProjectDiscipline = apps.get_model("Project", "ProjectDiscipline")
    disciplines = [
        "Project management",
        "Urban planning",
        "Architectural",
        "Civil",
        "Structural",
        "Mechanical",
        "Piping",
        "Electrical",
        "Control and Instrumentation",
        "Quantity Surveying",
        "Health and Safety",
        "Land surveying",
        "Geotech",
    ]
    for name in disciplines:
        ProjectDiscipline.objects.get_or_create(
            name=name,
            defaults={"description": f"Standard {name} discipline"},
        )


def remove_disciplines(apps, schema_editor):
    ProjectDiscipline = apps.get_model("Project", "ProjectDiscipline")
    disciplines = [
        "Project management",
        "Urban planning",
        "Architectural",
        "Civil",
        "Structural",
        "Mechanical",
        "Piping",
        "Electrical",
        "Control and Instrumentation",
        "Quantity Surveying",
        "Health and Safety",
        "Land surveying",
        "Geotech",
    ]
    ProjectDiscipline.objects.filter(name__in=disciplines).delete()


class Migration(migrations.Migration):
    dependencies = [
        ("Project", "0094_company_disciplines"),
    ]

    operations = [
        migrations.RunPython(populate_disciplines, reverse_code=remove_disciplines),
    ]
