# Generated by Django 5.2.12 on 2026-06-16 07:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Project", "0095_populate_standard_disciplines"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ProjectCompanyUserRole",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When this record was created"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="When this record was last modified"
                    ),
                ),
                (
                    "deleted",
                    models.BooleanField(default=False, help_text="Soft delete flag"),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("Admin", "Admin"),
                            ("Supervisor", "Supervisor"),
                            ("Capturer", "Capturer"),
                        ],
                        default="Capturer",
                        help_text="Stakeholder role (Admin, Supervisor, Capturer)",
                        max_length=50,
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        help_text="The stakeholder company associated with this role",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="project_company_user_roles",
                        to="Project.company",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        help_text="The project associated with this stakeholder role",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="project_company_user_roles",
                        to="Project.project",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="The user assigned to this role",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="project_company_user_roles",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Project Company User Role",
                "verbose_name_plural": "Project Company User Roles",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("project", "company", "user"),
                        name="unique_project_company_user_role",
                    )
                ],
            },
        ),
    ]
