# Generated by Django 5.2.12 on 2026-06-19 15:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Project", "0096_projectcompanyuserrole"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="cover_page_config",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Custom configuration for cover page report, headers and titles",
            ),
        ),
    ]
