# Generated by Django 5.2.12 on 2026-06-21 22:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Project", "0097_project_cover_page_config"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="drawing",
            name="parent",
        ),
        migrations.AddField(
            model_name="drawing",
            name="group",
            field=models.ForeignKey(
                blank=True,
                help_text="Project group (Level 3)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="drawings",
                to="Project.group",
            ),
        ),
    ]
