# Generated by Django 5.2.12 on 2026-06-22 10:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Project", "0098_remove_drawing_parent_drawing_group"),
    ]

    operations = [
        migrations.CreateModel(
            name="DrawingType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When this record was created"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="When this record was last modified"
                    ),
                ),
                (
                    "deleted",
                    models.BooleanField(default=False, help_text="Soft delete flag"),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Drawing type name (e.g., Tender, Construction, Information, Shop)",
                        max_length=100,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Optional description of the drawing type"
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="drawing_types",
                        to="Project.project",
                    ),
                ),
            ],
            options={
                "verbose_name": "Drawing Type",
                "verbose_name_plural": "Drawing Types",
                "ordering": ["name"],
                "unique_together": {("project", "name")},
            },
        ),
        migrations.AddField(
            model_name="drawing",
            name="drawing_type",
            field=models.ForeignKey(
                blank=True,
                help_text="Type of the drawing",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="drawings",
                to="Project.drawingtype",
            ),
        ),
    ]
