# Generated by Django 5.2.12 on 2026-06-22 11:24

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("Project", "0099_drawing_type_model"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="discipline",
            unique_together={("project", "name")},
        ),
    ]
