# Generated by Django 5.2.12 on 2026-06-24 19:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Project", "0100_discipline_unique_together"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="disciplines",
            field=models.ManyToManyField(
                blank=True,
                help_text="Disciplines assigned to this WBS Level 1",
                related_name="categories",
                to="Project.discipline",
            ),
        ),
        migrations.AddField(
            model_name="group",
            name="disciplines",
            field=models.ManyToManyField(
                blank=True,
                help_text="Disciplines assigned to this WBS Level 3",
                related_name="groups",
                to="Project.discipline",
            ),
        ),
        migrations.AddField(
            model_name="subcategory",
            name="disciplines",
            field=models.ManyToManyField(
                blank=True,
                help_text="Disciplines assigned to this WBS Level 2",
                related_name="subcategories",
                to="Project.discipline",
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="description",
            field=models.TextField(blank=True, help_text="Optional description "),
        ),
        migrations.AlterField(
            model_name="projectcategory",
            name="description",
            field=models.TextField(blank=True, help_text="Optional description "),
        ),
        migrations.AlterField(
            model_name="projectsubcategory",
            name="description",
            field=models.TextField(blank=True, help_text="Optional description "),
        ),
    ]
