# Generated by Django 5.2.12 on 2026-06-25 05:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Project", "0101_category_disciplines_group_disciplines_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="end_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="category",
            name="start_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="group",
            name="end_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="group",
            name="start_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="subcategory",
            name="end_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="subcategory",
            name="start_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
