# Generated by Django 5.2.12 on 2026-06-29 06:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Project", "0102_alter_category_end_date_alter_category_start_date_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="projectdocument",
            name="document_number",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Unique identifier for the document",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="projectdocument",
            name="group",
            field=models.ForeignKey(
                blank=True,
                help_text="Project group (Level 3)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="documents",
                to="Project.group",
            ),
        ),
        migrations.AddField(
            model_name="projectdocument",
            name="revision_number",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Current revision number (e.g., A, 01, Rev 1)",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="projectdocument",
            name="sub_category",
            field=models.ForeignKey(
                blank=True,
                help_text="Project sub-category (Level 2)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="documents",
                to="Project.subcategory",
            ),
        ),
    ]
