# Generated by Django 5.2.12 on 2026-06-29 22:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Project", "0103_projectdocument_document_number_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ProjectGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When this record was created"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="When this record was last modified"
                    ),
                ),
                (
                    "deleted",
                    models.BooleanField(default=False, help_text="Soft delete flag"),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "projects",
                    models.ManyToManyField(
                        help_text="Projects in this group",
                        related_name="project_groups",
                        to="Project.project",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="User who owns this project group",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="project_groups",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Project Group",
                "verbose_name_plural": "Project Groups",
                "ordering": ["name"],
            },
        ),
    ]
