# Generated by Django 6.0.2 on 2026-02-22 13:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="LabourCrew",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("crew_type", models.CharField(max_length=100, unique=True)),
                ("crew_size", models.IntegerField(default=0)),
                ("skilled", models.IntegerField(default=0)),
                ("semi_skilled", models.IntegerField(default=0)),
                ("general", models.IntegerField(default=0)),
                (
                    "daily_production",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "skilled_rate",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "semi_skilled_rate",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "general_rate",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
            ],
            options={
                "verbose_name": "Labour Crew",
                "ordering": ["crew_type"],
            },
        ),
        migrations.CreateModel(
            name="Material",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("trade_name", models.CharField(blank=True, max_length=200)),
                ("material_code", models.CharField(max_length=100, unique=True)),
                ("unit", models.CharField(blank=True, max_length=20)),
                (
                    "market_rate",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("material_variety", models.CharField(blank=True, max_length=100)),
                ("market_spec", models.CharField(blank=True, max_length=100)),
            ],
            options={
                "ordering": ["material_code"],
            },
        ),
        migrations.CreateModel(
            name="Specification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("section", models.CharField(blank=True, max_length=100)),
                ("unit_label", models.CharField(default="m3", max_length=20)),
                ("name", models.CharField(max_length=100)),
                (
                    "boq_quantity",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
            ],
            options={
                "ordering": ["section", "name"],
            },
        ),
        migrations.CreateModel(
            name="TradeCode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("prefix", models.CharField(max_length=20)),
                ("trade_name", models.CharField(max_length=100)),
            ],
            options={
                "ordering": ["prefix"],
            },
        ),
        migrations.CreateModel(
            name="LabourSpecification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("section", models.CharField(blank=True, max_length=100)),
                ("trade_name", models.CharField(blank=True, max_length=200)),
                ("name", models.CharField(max_length=200)),
                ("unit", models.CharField(blank=True, max_length=20)),
                (
                    "daily_production",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "team_mix",
                    models.DecimalField(decimal_places=4, default=1, max_digits=6),
                ),
                (
                    "site_factor",
                    models.DecimalField(decimal_places=4, default=1, max_digits=6),
                ),
                (
                    "tools_factor",
                    models.DecimalField(decimal_places=4, default=1, max_digits=6),
                ),
                (
                    "leadership_factor",
                    models.DecimalField(decimal_places=4, default=1, max_digits=6),
                ),
                (
                    "boq_quantity",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "crew",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="labour_specs",
                        to="estimator.labourcrew",
                    ),
                ),
            ],
            options={
                "verbose_name": "Labour Specification",
                "ordering": ["section", "name"],
            },
        ),
        migrations.CreateModel(
            name="BaselineBOQItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("section", models.CharField(blank=True, max_length=200)),
                ("bill_no", models.CharField(blank=True, max_length=200)),
                ("item_no", models.CharField(blank=True, max_length=20)),
                ("pay_ref", models.CharField(blank=True, max_length=50)),
                ("description", models.CharField(blank=True, max_length=500)),
                ("unit", models.CharField(blank=True, max_length=20)),
                (
                    "contract_quantity",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "contract_rate",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                ("is_section_header", models.BooleanField(default=False)),
                (
                    "material",
                    models.ForeignKey(
                        blank=True,
                        help_text="Direct material for items that don't use a specification",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="baseline_items",
                        to="estimator.material",
                    ),
                ),
                (
                    "specification",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="baseline_items",
                        to="estimator.specification",
                    ),
                ),
            ],
            options={
                "verbose_name": "Baseline BoQ Item",
                "verbose_name_plural": "Baseline BoQ Items",
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="SpecificationComponent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("label", models.CharField(max_length=100)),
                (
                    "qty_per_unit",
                    models.DecimalField(decimal_places=4, default=0, max_digits=10),
                ),
                ("sort_order", models.IntegerField(default=0)),
                (
                    "material",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="spec_components",
                        to="estimator.material",
                    ),
                ),
                (
                    "specification",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="spec_components",
                        to="estimator.specification",
                    ),
                ),
            ],
            options={
                "ordering": ["sort_order"],
            },
        ),
        migrations.AddField(
            model_name="specification",
            name="trade_code",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="specifications",
                to="estimator.tradecode",
            ),
        ),
        migrations.CreateModel(
            name="BOQItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("section", models.CharField(blank=True, max_length=200)),
                ("bill_no", models.CharField(blank=True, max_length=200)),
                ("item_no", models.CharField(blank=True, max_length=20)),
                ("pay_ref", models.CharField(blank=True, max_length=50)),
                ("description", models.CharField(blank=True, max_length=500)),
                ("unit", models.CharField(blank=True, max_length=20)),
                (
                    "contract_quantity",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "contract_rate",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "progress_quantity",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "forecast_quantity",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                ("is_section_header", models.BooleanField(default=False)),
                (
                    "labour_specification",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="boq_items",
                        to="estimator.labourspecification",
                    ),
                ),
                (
                    "material",
                    models.ForeignKey(
                        blank=True,
                        help_text="Direct material for items that don't use a specification",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="boq_items",
                        to="estimator.material",
                    ),
                ),
                (
                    "specification",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="boq_items",
                        to="estimator.specification",
                    ),
                ),
                (
                    "trade_code",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="boq_items",
                        to="estimator.tradecode",
                    ),
                ),
            ],
            options={
                "verbose_name": "BoQ Item",
                "verbose_name_plural": "BoQ Items",
                "ordering": ["id"],
            },
        ),
    ]
