# Generated by Django 6.0.2 on 2026-02-23 09:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estimator', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='baselineboqitem',
            name='labour_specification',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='baseline_items', to='estimator.labourspecification'),
        ),
        migrations.AddField(
            model_name='baselineboqitem',
            name='trade_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='baseline_items', to='estimator.tradecode'),
        ),
    ]
