# Generated by Django 6.0.2 on 2026-02-24 12:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("estimator", "0002_baselineboqitem_labour_specification_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="boqitem",
            name="labour_markup_pct",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AddField(
            model_name="boqitem",
            name="material_markup_pct",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AddField(
            model_name="boqitem",
            name="transport_pct",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
    ]
