# Generated by Django 6.0.3 on 2026-04-12 10:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Project", "0070_projectreportsummary"),
        ("estimator", "0009_project_assumptions"),
    ]

    operations = [
        migrations.CreateModel(
            name="SystemPlantCost",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, unique=True)),
                (
                    "hourly_production",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "hourly_rate",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
            ],
            options={
                "verbose_name": "System Plant Cost",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="SystemPreliminaryCost",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "preliminary_type",
                    models.CharField(
                        choices=[
                            ("fixed_contractual", "Fixed Contractual Requirements"),
                            ("fixed_facilities", "Fixed Facilities"),
                            ("time_contractual", "Time-Contractual Requirements"),
                            ("time_facilities", "Time-Facilities"),
                            ("time_small_tools", "Time-Small Tool Allowances"),
                            ("time_plant_equipment", "Time-Plant and Equipment"),
                            (
                                "time_company_overheads",
                                "Time-Company & Head Office Overheads",
                            ),
                            ("time_site_personnel", "Time-Site Personnel"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "sum_value",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Sum/lump sum value",
                        max_digits=12,
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "number_per_month",
                    models.DecimalField(
                        blank=True, decimal_places=2, default=0, max_digits=10
                    ),
                ),
                (
                    "monthly_rate",
                    models.DecimalField(
                        blank=True, decimal_places=2, default=0, max_digits=12
                    ),
                ),
                (
                    "months",
                    models.DecimalField(
                        blank=True, decimal_places=2, default=0, max_digits=6
                    ),
                ),
            ],
            options={
                "verbose_name": "System Preliminary Cost",
                "ordering": ["preliminary_type", "name"],
            },
        ),
        migrations.CreateModel(
            name="SystemPreliminarySpecification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("section", models.CharField(blank=True, max_length=100)),
                ("trade_name", models.CharField(blank=True, max_length=200)),
                ("name", models.CharField(max_length=200)),
                ("unit", models.CharField(blank=True, max_length=20)),
                (
                    "amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
            ],
            options={
                "verbose_name": "System Preliminary Specification",
                "ordering": ["section", "name"],
            },
        ),
        migrations.CreateModel(
            name="ProjectPlantCost",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "hourly_production",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "hourly_rate",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="estimator_plant_costs",
                        to="Project.project",
                    ),
                ),
                (
                    "source",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="project_copies",
                        to="estimator.systemplantcost",
                    ),
                ),
            ],
            options={
                "verbose_name": "Project Plant Cost",
                "ordering": ["name"],
                "unique_together": {("project", "name")},
            },
        ),
        migrations.CreateModel(
            name="SystemPlantSpecification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("section", models.CharField(blank=True, max_length=100)),
                ("trade_name", models.CharField(blank=True, max_length=200)),
                ("name", models.CharField(max_length=200)),
                ("unit", models.CharField(blank=True, max_length=20)),
                (
                    "daily_production",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "operator_factor",
                    models.DecimalField(decimal_places=4, default=1, max_digits=6),
                ),
                (
                    "site_factor",
                    models.DecimalField(decimal_places=4, default=1, max_digits=6),
                ),
                (
                    "plant_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="plant_specs",
                        to="estimator.systemplantcost",
                    ),
                ),
            ],
            options={
                "verbose_name": "System Plant Specification",
                "ordering": ["section", "name"],
            },
        ),
        migrations.CreateModel(
            name="ProjectPreliminaryCost",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "preliminary_type",
                    models.CharField(
                        choices=[
                            ("fixed_contractual", "Fixed Contractual Requirements"),
                            ("fixed_facilities", "Fixed Facilities"),
                            ("time_contractual", "Time-Contractual Requirements"),
                            ("time_facilities", "Time-Facilities"),
                            ("time_small_tools", "Time-Small Tool Allowances"),
                            ("time_plant_equipment", "Time-Plant and Equipment"),
                            (
                                "time_company_overheads",
                                "Time-Company & Head Office Overheads",
                            ),
                            ("time_site_personnel", "Time-Site Personnel"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "sum_value",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Sum/lump sum value",
                        max_digits=12,
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "number_per_month",
                    models.DecimalField(
                        blank=True, decimal_places=2, default=0, max_digits=10
                    ),
                ),
                (
                    "monthly_rate",
                    models.DecimalField(
                        blank=True, decimal_places=2, default=0, max_digits=12
                    ),
                ),
                (
                    "months",
                    models.DecimalField(
                        blank=True, decimal_places=2, default=0, max_digits=6
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="estimator_preliminary_costs",
                        to="Project.project",
                    ),
                ),
                (
                    "source",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="project_copies",
                        to="estimator.systempreliminarycost",
                    ),
                ),
            ],
            options={
                "verbose_name": "Project Preliminary Cost",
                "ordering": ["preliminary_type", "name"],
            },
        ),
        migrations.CreateModel(
            name="ProjectPlantSpecification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("section", models.CharField(blank=True, max_length=100)),
                ("trade_name", models.CharField(blank=True, max_length=200)),
                ("name", models.CharField(max_length=200)),
                ("unit", models.CharField(blank=True, max_length=20)),
                (
                    "daily_production",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "operator_factor",
                    models.DecimalField(decimal_places=4, default=1, max_digits=6),
                ),
                (
                    "site_factor",
                    models.DecimalField(decimal_places=4, default=1, max_digits=6),
                ),
                (
                    "plant_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="plant_specs",
                        to="estimator.projectplantcost",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="estimator_plant_specs",
                        to="Project.project",
                    ),
                ),
                (
                    "source",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="project_copies",
                        to="estimator.systemplantspecification",
                    ),
                ),
            ],
            options={
                "verbose_name": "Project Plant Specification",
                "ordering": ["section", "name"],
                "unique_together": {("project", "name")},
            },
        ),
        migrations.CreateModel(
            name="ProjectPreliminarySpecification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("section", models.CharField(blank=True, max_length=100)),
                ("trade_name", models.CharField(blank=True, max_length=200)),
                ("name", models.CharField(max_length=200)),
                ("unit", models.CharField(blank=True, max_length=20)),
                (
                    "amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="estimator_preliminary_specs",
                        to="Project.project",
                    ),
                ),
                (
                    "source",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="project_copies",
                        to="estimator.systempreliminaryspecification",
                    ),
                ),
            ],
            options={
                "verbose_name": "Project Preliminary Specification",
                "ordering": ["section", "name"],
                "unique_together": {("project", "name")},
            },
        ),
    ]
