# Generated by Django 6.0.3 on 2026-04-19 09:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("estimator", "0011_boqitem_plant_prelim_specs"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="projectplantspecification",
            name="plant_type",
        ),
        migrations.RemoveField(
            model_name="systemplantspecification",
            name="plant_type",
        ),
        migrations.CreateModel(
            name="ProjectPlantSpecificationComponent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "hours",
                    models.DecimalField(decimal_places=2, default=0, max_digits=6),
                ),
                ("sort_order", models.IntegerField(default=0)),
                (
                    "plant_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="spec_components",
                        to="estimator.projectplantcost",
                    ),
                ),
                (
                    "specification",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="components",
                        to="estimator.projectplantspecification",
                    ),
                ),
            ],
            options={
                "ordering": ["sort_order"],
            },
        ),
        migrations.CreateModel(
            name="SystemPlantSpecificationComponent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "hours",
                    models.DecimalField(decimal_places=2, default=0, max_digits=6),
                ),
                ("sort_order", models.IntegerField(default=0)),
                (
                    "plant_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="spec_components",
                        to="estimator.systemplantcost",
                    ),
                ),
                (
                    "specification",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="components",
                        to="estimator.systemplantspecification",
                    ),
                ),
            ],
            options={
                "ordering": ["sort_order"],
            },
        ),
    ]
