# Generated by Django 6.0.3 on 2026-05-01 14:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Project', '0084_project_stage'),
        ('estimator', '0013_preliminaryspec_link_costs'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContractorLabourCrew',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crew_type', models.CharField(max_length=100)),
                ('crew_size', models.IntegerField(default=0)),
                ('skilled', models.IntegerField(default=0)),
                ('semi_skilled', models.IntegerField(default=0)),
                ('general', models.IntegerField(default=0)),
                ('daily_production', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('skilled_rate', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('semi_skilled_rate', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('general_rate', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('company', models.ForeignKey(limit_choices_to={'type': 'CONTRACTOR'}, on_delete=django.db.models.deletion.CASCADE, related_name='estimator_labour_crews', to='Project.company')),
                ('source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contractor_copies', to='estimator.systemlabourcrew')),
            ],
            options={
                'verbose_name': 'Contractor Labour Crew',
                'ordering': ['crew_type'],
                'unique_together': {('company', 'crew_type')},
            },
        ),
        migrations.CreateModel(
            name='ContractorMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trade_name', models.CharField(blank=True, max_length=200)),
                ('material_code', models.CharField(max_length=100)),
                ('unit', models.CharField(blank=True, max_length=20)),
                ('market_rate', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('material_variety', models.CharField(blank=True, max_length=100)),
                ('market_spec', models.CharField(blank=True, max_length=100)),
                ('company', models.ForeignKey(limit_choices_to={'type': 'CONTRACTOR'}, on_delete=django.db.models.deletion.CASCADE, related_name='estimator_materials', to='Project.company')),
                ('source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contractor_copies', to='estimator.systemmaterial')),
            ],
            options={
                'ordering': ['material_code'],
                'unique_together': {('company', 'material_code')},
            },
        ),
        migrations.CreateModel(
            name='ContractorMaterialSpec',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('unit', models.CharField(default='m3', max_length=20)),
                ('company', models.ForeignKey(limit_choices_to={'type': 'CONTRACTOR'}, on_delete=django.db.models.deletion.CASCADE, related_name='estimator_material_specs', to='Project.company')),
                ('source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contractor_copies', to='estimator.systemmaterialspec')),
            ],
            options={
                'verbose_name': 'Contractor Material Spec',
                'verbose_name_plural': 'Contractor Material Specs',
                'ordering': ['name'],
                'unique_together': {('company', 'name')},
            },
        ),
        migrations.CreateModel(
            name='ContractorMaterialSpecComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100)),
                ('qty_per_unit', models.DecimalField(decimal_places=4, default=0, max_digits=10)),
                ('sort_order', models.IntegerField(default=0)),
                ('material', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contractor_spec_components', to='estimator.contractormaterial')),
                ('spec', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contractor_spec_components', to='estimator.contractormaterialspec')),
            ],
            options={
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='ContractorPlantCost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('hourly_production', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('hourly_rate', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('company', models.ForeignKey(limit_choices_to={'type': 'CONTRACTOR'}, on_delete=django.db.models.deletion.CASCADE, related_name='estimator_plant_costs', to='Project.company')),
                ('source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contractor_copies', to='estimator.systemplantcost')),
            ],
            options={
                'verbose_name': 'Contractor Plant Cost',
                'ordering': ['name'],
                'unique_together': {('company', 'name')},
            },
        ),
        migrations.CreateModel(
            name='ContractorPlantSpecification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(blank=True, max_length=100)),
                ('trade_name', models.CharField(blank=True, max_length=200)),
                ('name', models.CharField(max_length=200)),
                ('unit', models.CharField(blank=True, max_length=20)),
                ('daily_production', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('operator_factor', models.DecimalField(decimal_places=4, default=1, max_digits=6)),
                ('site_factor', models.DecimalField(decimal_places=4, default=1, max_digits=6)),
                ('company', models.ForeignKey(limit_choices_to={'type': 'CONTRACTOR'}, on_delete=django.db.models.deletion.CASCADE, related_name='estimator_plant_specs', to='Project.company')),
                ('source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contractor_copies', to='estimator.systemplantspecification')),
            ],
            options={
                'verbose_name': 'Contractor Plant Specification',
                'ordering': ['section', 'name'],
                'unique_together': {('company', 'name')},
            },
        ),
        migrations.CreateModel(
            name='ContractorPlantSpecificationComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hours', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('sort_order', models.IntegerField(default=0)),
                ('plant_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='spec_components', to='estimator.contractorplantcost')),
                ('specification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='components', to='estimator.contractorplantspecification')),
            ],
            options={
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='ContractorPreliminaryCost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('preliminary_type', models.CharField(choices=[('fixed_contractual', 'Fixed Contractual Requirements'), ('fixed_facilities', 'Fixed Facilities'), ('time_contractual', 'Time-Contractual Requirements'), ('time_facilities', 'Time-Facilities'), ('time_small_tools', 'Time-Small Tool Allowances'), ('time_plant_equipment', 'Time-Plant and Equipment'), ('time_company_overheads', 'Time-Company & Head Office Overheads'), ('time_site_personnel', 'Time-Site Personnel')], max_length=30)),
                ('sum_value', models.DecimalField(decimal_places=2, default=0, help_text='Sum/lump sum value', max_digits=12)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('number_per_month', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10)),
                ('monthly_rate', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12)),
                ('months', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=6)),
                ('company', models.ForeignKey(limit_choices_to={'type': 'CONTRACTOR'}, on_delete=django.db.models.deletion.CASCADE, related_name='estimator_preliminary_costs', to='Project.company')),
                ('source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contractor_copies', to='estimator.systempreliminarycost')),
            ],
            options={
                'verbose_name': 'Contractor Preliminary Cost',
                'ordering': ['preliminary_type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ContractorSpecification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(blank=True, max_length=100)),
                ('unit_label', models.CharField(default='m3', max_length=20)),
                ('name', models.CharField(max_length=100)),
                ('boq_quantity', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('company', models.ForeignKey(limit_choices_to={'type': 'CONTRACTOR'}, on_delete=django.db.models.deletion.CASCADE, related_name='estimator_specifications', to='Project.company')),
                ('contractor_spec', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contractor_specs', to='estimator.contractormaterialspec')),
                ('source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contractor_copies', to='estimator.systemspecification')),
            ],
            options={
                'ordering': ['section', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ContractorSpecificationComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100)),
                ('qty_per_unit', models.DecimalField(decimal_places=4, default=0, max_digits=10)),
                ('sort_order', models.IntegerField(default=0)),
                ('material', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='spec_components', to='estimator.contractormaterial')),
                ('specification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spec_components', to='estimator.contractorspecification')),
            ],
            options={
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='ContractorTradeCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prefix', models.CharField(max_length=20)),
                ('trade_name', models.CharField(max_length=100)),
                ('company', models.ForeignKey(limit_choices_to={'type': 'CONTRACTOR'}, on_delete=django.db.models.deletion.CASCADE, related_name='estimator_trade_codes', to='Project.company')),
                ('source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contractor_copies', to='estimator.systemtradecode')),
            ],
            options={
                'ordering': ['prefix'],
                'unique_together': {('company', 'prefix')},
            },
        ),
        migrations.AddField(
            model_name='contractorspecification',
            name='trade_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='specifications', to='estimator.contractortradecode'),
        ),
        migrations.CreateModel(
            name='ContractorLabourSpecification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(blank=True, max_length=100)),
                ('trade_name', models.CharField(blank=True, max_length=200)),
                ('name', models.CharField(max_length=200)),
                ('unit', models.CharField(blank=True, max_length=20)),
                ('daily_production', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('team_mix', models.DecimalField(decimal_places=4, default=1, max_digits=6)),
                ('site_factor', models.DecimalField(decimal_places=4, default=1, max_digits=6)),
                ('tools_factor', models.DecimalField(decimal_places=4, default=1, max_digits=6)),
                ('leadership_factor', models.DecimalField(decimal_places=4, default=1, max_digits=6)),
                ('boq_quantity', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('company', models.ForeignKey(limit_choices_to={'type': 'CONTRACTOR'}, on_delete=django.db.models.deletion.CASCADE, related_name='estimator_labour_specs', to='Project.company')),
                ('crew', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='labour_specs', to='estimator.contractorlabourcrew')),
                ('source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contractor_copies', to='estimator.systemlabourspecification')),
            ],
            options={
                'verbose_name': 'Contractor Labour Specification',
                'ordering': ['section', 'name'],
                'unique_together': {('company', 'name')},
            },
        ),
        migrations.CreateModel(
            name='ContractorPreliminarySpecification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(blank=True, max_length=100)),
                ('trade_name', models.CharField(blank=True, max_length=200)),
                ('name', models.CharField(max_length=200)),
                ('unit', models.CharField(blank=True, max_length=20)),
                ('preliminary_type', models.CharField(blank=True, choices=[('fixed_contractual', 'Fixed Contractual Requirements'), ('fixed_facilities', 'Fixed Facilities'), ('time_contractual', 'Time-Contractual Requirements'), ('time_facilities', 'Time-Facilities'), ('time_small_tools', 'Time-Small Tool Allowances'), ('time_plant_equipment', 'Time-Plant and Equipment'), ('time_company_overheads', 'Time-Company & Head Office Overheads'), ('time_site_personnel', 'Time-Site Personnel')], max_length=30)),
                ('company', models.ForeignKey(limit_choices_to={'type': 'CONTRACTOR'}, on_delete=django.db.models.deletion.CASCADE, related_name='estimator_preliminary_specs', to='Project.company')),
                ('source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contractor_copies', to='estimator.systempreliminaryspecification')),
            ],
            options={
                'verbose_name': 'Contractor Preliminary Specification',
                'ordering': ['section', 'name'],
                'unique_together': {('company', 'name')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='contractorspecification',
            unique_together={('company', 'name')},
        ),
    ]
