# Generated by Django 5.2.12 on 2026-05-03 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("estimator", "0013_preliminaryspec_link_costs"),
    ]

    operations = [
        migrations.AddField(
            model_name="projectlabourcrew",
            name="name",
            field=models.CharField(
                blank=True,
                help_text="Custom name for this crew (e.g. Team Alpha)",
                max_length=200,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="systemlabourcrew",
            name="name",
            field=models.CharField(
                blank=True,
                help_text="Custom name for this crew (e.g. Team Alpha)",
                max_length=200,
                null=True,
            ),
        ),
    ]
