# Generated by Django 5.2.12 on 2026-05-06 08:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("estimator", "0013_preliminaryspec_link_costs"),
    ]

    operations = [
        migrations.AddField(
            model_name="boqitem",
            name="crew_count",
            field=models.DecimalField(
                decimal_places=2,
                default=1,
                help_text="Multiplier for the number of crews working on this item.",
                max_digits=6,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
    ]
