# Generated by Django 6.0.3 on 2026-05-04 03:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Project", "0084_project_stage"),
        ("estimator", "0014_contractorlabourcrew_contractormaterial_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="boqitem",
            name="component",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.CreateModel(
            name="ContractorItemLibraryEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("accounts_code", models.CharField(blank=True, max_length=50)),
                ("component", models.CharField(blank=True, max_length=200)),
                ("description", models.CharField(max_length=500)),
                ("unit", models.CharField(blank=True, max_length=20)),
                ("display_order", models.IntegerField(default=0)),
                (
                    "company",
                    models.ForeignKey(
                        limit_choices_to={"type": "CONTRACTOR"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="estimator_library_entries",
                        to="Project.company",
                    ),
                ),
                (
                    "labour_spec",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="library_entries",
                        to="estimator.contractorlabourspecification",
                    ),
                ),
                (
                    "material_spec",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="library_entries",
                        to="estimator.contractormaterialspec",
                    ),
                ),
                (
                    "plant_spec",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="library_entries",
                        to="estimator.contractorplantspecification",
                    ),
                ),
                (
                    "preliminary_spec",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="library_entries",
                        to="estimator.contractorpreliminaryspecification",
                    ),
                ),
                (
                    "trade_code",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="library_entries",
                        to="estimator.contractortradecode",
                    ),
                ),
            ],
            options={
                "verbose_name": "Contractor Item Library Entry",
                "verbose_name_plural": "Contractor Item Library Entries",
                "ordering": ["display_order", "id"],
            },
        ),
        migrations.CreateModel(
            name="ProjectItemLibraryEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("accounts_code", models.CharField(blank=True, max_length=50)),
                ("component", models.CharField(blank=True, max_length=200)),
                ("description", models.CharField(max_length=500)),
                ("unit", models.CharField(blank=True, max_length=20)),
                ("display_order", models.IntegerField(default=0)),
                (
                    "labour_spec",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="library_entries",
                        to="estimator.projectlabourspecification",
                    ),
                ),
                (
                    "material_spec",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="library_entries",
                        to="estimator.projectspecification",
                    ),
                ),
                (
                    "plant_spec",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="library_entries",
                        to="estimator.projectplantspecification",
                    ),
                ),
                (
                    "preliminary_spec",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="library_entries",
                        to="estimator.projectpreliminaryspecification",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="estimator_library_entries",
                        to="Project.project",
                    ),
                ),
                (
                    "source_contractor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="project_copies",
                        to="estimator.contractoritemlibraryentry",
                    ),
                ),
                (
                    "trade_code",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="library_entries",
                        to="estimator.projecttradecode",
                    ),
                ),
            ],
            options={
                "verbose_name": "Project Item Library Entry",
                "verbose_name_plural": "Project Item Library Entries",
                "ordering": ["display_order", "id"],
            },
        ),
        migrations.AddField(
            model_name="boqitem",
            name="library_entry",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="boq_items",
                to="estimator.projectitemlibraryentry",
            ),
        ),
        migrations.CreateModel(
            name="SystemItemLibraryEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("accounts_code", models.CharField(blank=True, max_length=50)),
                ("component", models.CharField(blank=True, max_length=200)),
                ("description", models.CharField(max_length=500)),
                ("unit", models.CharField(blank=True, max_length=20)),
                ("display_order", models.IntegerField(default=0)),
                (
                    "labour_spec",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="library_entries",
                        to="estimator.systemlabourspecification",
                    ),
                ),
                (
                    "material_spec",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="library_entries",
                        to="estimator.systemmaterialspec",
                    ),
                ),
                (
                    "plant_spec",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="library_entries",
                        to="estimator.systemplantspecification",
                    ),
                ),
                (
                    "preliminary_spec",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="library_entries",
                        to="estimator.systempreliminaryspecification",
                    ),
                ),
                (
                    "trade_code",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="library_entries",
                        to="estimator.systemtradecode",
                    ),
                ),
            ],
            options={
                "verbose_name": "System Item Library Entry",
                "verbose_name_plural": "System Item Library Entries",
                "ordering": ["display_order", "id"],
            },
        ),
        migrations.AddField(
            model_name="projectitemlibraryentry",
            name="source_system",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="project_copies",
                to="estimator.systemitemlibraryentry",
            ),
        ),
        migrations.AddField(
            model_name="contractoritemlibraryentry",
            name="source",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="contractor_copies",
                to="estimator.systemitemlibraryentry",
            ),
        ),
        migrations.AddIndex(
            model_name="systemitemlibraryentry",
            index=models.Index(
                fields=["trade_code", "component"],
                name="estimator_s_trade_c_edc0cc_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="systemitemlibraryentry",
            index=models.Index(
                fields=["trade_code", "description"],
                name="estimator_s_trade_c_6e6ad8_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="projectitemlibraryentry",
            index=models.Index(
                fields=["project", "trade_code", "component"],
                name="estimator_p_project_152128_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="projectitemlibraryentry",
            index=models.Index(
                fields=["project", "trade_code", "description"],
                name="estimator_p_project_a0a392_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="contractoritemlibraryentry",
            index=models.Index(
                fields=["company", "trade_code", "component"],
                name="estimator_c_company_c59db2_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="contractoritemlibraryentry",
            index=models.Index(
                fields=["company", "trade_code", "description"],
                name="estimator_c_company_b105bf_idx",
            ),
        ),
    ]
