# Generated by Django 5.2.12 on 2026-05-04 01:35

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("estimator", "0014_projectlabourcrew_name_systemlabourcrew_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="projectlabourcrew",
            name="name",
        ),
        migrations.RemoveField(
            model_name="systemlabourcrew",
            name="name",
        ),
    ]
