# Generated by Django 6.0.3 on 2026-05-08 13:50

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("estimator", "0014_boqitem_crew_count"),
        ("estimator", "0015_boqitem_component_contractoritemlibraryentry_and_more"),
    ]

    operations = []
