# Generated by Django 6.0.3 on 2026-05-09 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estimator', '0017_projectlabourspecification_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractorlabourspecification',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='contractormaterialspec',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='contractorplantspecification',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='contractorpreliminaryspecification',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='contractorspecification',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='systemlabourspecification',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='systemmaterialspec',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='systemplantspecification',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='systempreliminaryspecification',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='systemspecification',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
