# Generated by Django 6.0.3 on 2026-05-10 14:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("estimator", "0018_contractorlabourspecification_is_active_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="contractormaterial",
            name="pack_cost",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name="contractormaterial",
            name="pack_qty",
            field=models.DecimalField(decimal_places=4, default=1, max_digits=12),
        ),
        migrations.AddField(
            model_name="projectmaterial",
            name="pack_cost",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name="projectmaterial",
            name="pack_qty",
            field=models.DecimalField(decimal_places=4, default=1, max_digits=12),
        ),
        migrations.AddField(
            model_name="systemmaterial",
            name="pack_cost",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name="systemmaterial",
            name="pack_qty",
            field=models.DecimalField(decimal_places=4, default=1, max_digits=12),
        ),
        migrations.AlterField(
            model_name="contractormaterial",
            name="market_rate",
            field=models.DecimalField(decimal_places=4, default=0, max_digits=14),
        ),
        migrations.AlterField(
            model_name="projectmaterial",
            name="market_rate",
            field=models.DecimalField(decimal_places=4, default=0, max_digits=14),
        ),
        migrations.AlterField(
            model_name="systemmaterial",
            name="market_rate",
            field=models.DecimalField(decimal_places=4, default=0, max_digits=14),
        ),
    ]
