# Generated by Django 6.0.3 on 2026-05-11 17:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("estimator", "0020_backfill_material_pack_cost"),
    ]

    operations = [
        migrations.AddField(
            model_name="contractoritemlibraryentry",
            name="item_code",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="projectitemlibraryentry",
            name="item_code",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="systemitemlibraryentry",
            name="item_code",
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
