# Generated by Django 6.0.3 on 2026-05-12 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estimator', '0021_contractoritemlibraryentry_item_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contractormaterial',
            name='material_code',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='projectmaterial',
            name='material_code',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='systemmaterial',
            name='material_code',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
