# Generated by Django 6.0.3 on 2026-05-14 05:37

from django.db import migrations, models
from django.db.models import F


def recompute_crew_sizes(apps, schema_editor):
    """Recompute crew_size = skilled + semi_skilled + general on all rows."""
    for model_name in ("SystemLabourCrew", "ContractorLabourCrew", "ProjectLabourCrew"):
        Model = apps.get_model("estimator", model_name)
        Model.objects.all().update(
            crew_size=F("skilled") + F("semi_skilled") + F("general"),
        )


class Migration(migrations.Migration):
    dependencies = [
        ("estimator", "0022_widen_material_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contractorlabourcrew",
            name="crew_size",
            field=models.IntegerField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name="projectlabourcrew",
            name="crew_size",
            field=models.IntegerField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name="systemlabourcrew",
            name="crew_size",
            field=models.IntegerField(default=0, editable=False),
        ),
        migrations.RunPython(recompute_crew_sizes, migrations.RunPython.noop),
    ]
