# Generated by Django 6.0.3 on 2026-06-04 07:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("estimator", "0027_dedupe_trade_codes_by_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="contractoritemlibraryentry",
            name="labour_plant_spec_name",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="contractoritemlibraryentry",
            name="material_spec_name",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="contractoritemlibraryentry",
            name="preliminary_spec_name",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="projectitemlibraryentry",
            name="labour_plant_spec_name",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="projectitemlibraryentry",
            name="material_spec_name",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="projectitemlibraryentry",
            name="preliminary_spec_name",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="systemitemlibraryentry",
            name="labour_plant_spec_name",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="systemitemlibraryentry",
            name="material_spec_name",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="systemitemlibraryentry",
            name="preliminary_spec_name",
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
