"""URL configuration for Site Management."""

from django.urls import path

from app.SiteManagement.views import (
    DailyDiaryCreateView,
    DailyDiaryDeleteView,
    DailyDiaryListView,
    DailyDiaryUpdateView,
    DelayLogCreateView,
    DelayLogDeleteView,
    DelayLogListView,
    DelayLogUpdateView,
    DeliveryTrackerCreateView,
    DeliveryTrackerDeleteView,
    DeliveryTrackerListView,
    DeliveryTrackerUpdateView,
    LabourLogCreateView,
    LabourLogDeleteView,
    LabourLogListView,
    LabourLogUpdateView,
    MaterialsLogCreateView,
    MaterialsLogDeleteView,
    MaterialsLogListView,
    MaterialsLogUpdateView,
    OffsiteLogCreateView,
    OffsiteLogDeleteView,
    OffsiteLogListView,
    OffsiteLogUpdateView,
    PhotoLogCreateView,
    PhotoLogDeleteView,
    PhotoLogListView,
    PhotoLogUpdateView,
    PlantEquipmentCreateView,
    PlantEquipmentDeleteView,
    PlantEquipmentListView,
    PlantEquipmentUpdateView,
    ProcurementTrackerCreateView,
    ProcurementTrackerDeleteView,
    ProcurementTrackerListView,
    ProcurementTrackerUpdateView,
    ProductivityLogCreateView,
    ProductivityLogDeleteView,
    ProductivityLogListView,
    ProductivityLogUpdateView,
    ProgressTrackerCreateView,
    ProgressTrackerDeleteView,
    ProgressTrackerListView,
    ProgressTrackerUpdateView,
    QualityControlCreateView,
    QualityControlDeleteView,
    QualityControlListView,
    QualityControlUpdateView,
    SafetyObservationCreateView,
    SafetyObservationDeleteView,
    SafetyObservationListView,
    SafetyObservationUpdateView,
    SiteManagementView,
    SnagListCreateView,
    SnagListDeleteView,
    SnagListListView,
    SnagListUpdateView,
    SubcontractorLogCreateView,
    SubcontractorLogDeleteView,
    SubcontractorLogListView,
    SubcontractorLogUpdateView,
)

app_name = "site_management"

urlpatterns = [
    # Site Management
    path(
        "project/<int:project_pk>/site-management/",
        SiteManagementView.as_view(),
        name="site-management",
    ),
    # Materials Log
    path(
        "project/<int:project_pk>/materials-log/",
        MaterialsLogListView.as_view(),
        name="materials-log-list",
    ),
    path(
        "project/<int:project_pk>/materials-log/create/",
        MaterialsLogCreateView.as_view(),
        name="materials-log-create",
    ),
    path(
        "project/<int:project_pk>/materials-log/<int:pk>/update/",
        MaterialsLogUpdateView.as_view(),
        name="materials-log-update",
    ),
    path(
        "project/<int:project_pk>/materials-log/<int:pk>/delete/",
        MaterialsLogDeleteView.as_view(),
        name="materials-log-delete",
    ),
    # Daily Diary
    path(
        "project/<int:project_pk>/daily-diary/",
        DailyDiaryListView.as_view(),
        name="daily-diary-list",
    ),
    path(
        "project/<int:project_pk>/daily-diary/create/",
        DailyDiaryCreateView.as_view(),
        name="daily-diary-create",
    ),
    path(
        "project/<int:project_pk>/daily-diary/<int:pk>/update/",
        DailyDiaryUpdateView.as_view(),
        name="daily-diary-update",
    ),
    path(
        "project/<int:project_pk>/daily-diary/<int:pk>/delete/",
        DailyDiaryDeleteView.as_view(),
        name="daily-diary-delete",
    ),
    # Productivity Log
    path(
        "project/<int:project_pk>/productivity-log/",
        ProductivityLogListView.as_view(),
        name="productivity-log-list",
    ),
    path(
        "project/<int:project_pk>/productivity-log/create/",
        ProductivityLogCreateView.as_view(),
        name="productivity-log-create",
    ),
    path(
        "project/<int:project_pk>/productivity-log/<int:pk>/update/",
        ProductivityLogUpdateView.as_view(),
        name="productivity-log-update",
    ),
    path(
        "project/<int:project_pk>/productivity-log/<int:pk>/delete/",
        ProductivityLogDeleteView.as_view(),
        name="productivity-log-delete",
    ),
    # Subcontractor Log
    path(
        "project/<int:project_pk>/subcontractor-log/",
        SubcontractorLogListView.as_view(),
        name="subcontractor-log-list",
    ),
    path(
        "project/<int:project_pk>/subcontractor-log/create/",
        SubcontractorLogCreateView.as_view(),
        name="subcontractor-log-create",
    ),
    path(
        "project/<int:project_pk>/subcontractor-log/<int:pk>/update/",
        SubcontractorLogUpdateView.as_view(),
        name="subcontractor-log-update",
    ),
    path(
        "project/<int:project_pk>/subcontractor-log/<int:pk>/delete/",
        SubcontractorLogDeleteView.as_view(),
        name="subcontractor-log-delete",
    ),
    # Snag List
    path(
        "project/<int:project_pk>/snag-list/",
        SnagListListView.as_view(),
        name="snag-list-list",
    ),
    path(
        "project/<int:project_pk>/snag-list/create/",
        SnagListCreateView.as_view(),
        name="snag-list-create",
    ),
    path(
        "project/<int:project_pk>/snag-list/<int:pk>/update/",
        SnagListUpdateView.as_view(),
        name="snag-list-update",
    ),
    path(
        "project/<int:project_pk>/snag-list/<int:pk>/delete/",
        SnagListDeleteView.as_view(),
        name="snag-list-delete",
    ),
    # Progress Tracker
    path(
        "project/<int:project_pk>/progress-tracker/",
        ProgressTrackerListView.as_view(),
        name="progress-tracker-list",
    ),
    path(
        "project/<int:project_pk>/progress-tracker/create/",
        ProgressTrackerCreateView.as_view(),
        name="progress-tracker-create",
    ),
    path(
        "project/<int:project_pk>/progress-tracker/<int:pk>/update/",
        ProgressTrackerUpdateView.as_view(),
        name="progress-tracker-update",
    ),
    path(
        "project/<int:project_pk>/progress-tracker/<int:pk>/delete/",
        ProgressTrackerDeleteView.as_view(),
        name="progress-tracker-delete",
    ),
    # Delay Log
    path(
        "project/<int:project_pk>/delay-log/",
        DelayLogListView.as_view(),
        name="delay-log-list",
    ),
    path(
        "project/<int:project_pk>/delay-log/create/",
        DelayLogCreateView.as_view(),
        name="delay-log-create",
    ),
    path(
        "project/<int:project_pk>/delay-log/<int:pk>/update/",
        DelayLogUpdateView.as_view(),
        name="delay-log-update",
    ),
    path(
        "project/<int:project_pk>/delay-log/<int:pk>/delete/",
        DelayLogDeleteView.as_view(),
        name="delay-log-delete",
    ),
    # Photo Log
    path(
        "project/<int:project_pk>/photo-log/",
        PhotoLogListView.as_view(),
        name="photo-log-list",
    ),
    path(
        "project/<int:project_pk>/photo-log/create/",
        PhotoLogCreateView.as_view(),
        name="photo-log-create",
    ),
    path(
        "project/<int:project_pk>/photo-log/<int:pk>/update/",
        PhotoLogUpdateView.as_view(),
        name="photo-log-update",
    ),
    path(
        "project/<int:project_pk>/photo-log/<int:pk>/delete/",
        PhotoLogDeleteView.as_view(),
        name="photo-log-delete",
    ),
    # Procurement Tracker
    path(
        "project/<int:project_pk>/procurement-tracker/",
        ProcurementTrackerListView.as_view(),
        name="procurement-tracker-list",
    ),
    path(
        "project/<int:project_pk>/procurement-tracker/create/",
        ProcurementTrackerCreateView.as_view(),
        name="procurement-tracker-create",
    ),
    path(
        "project/<int:project_pk>/procurement-tracker/<int:pk>/update/",
        ProcurementTrackerUpdateView.as_view(),
        name="procurement-tracker-update",
    ),
    path(
        "project/<int:project_pk>/procurement-tracker/<int:pk>/delete/",
        ProcurementTrackerDeleteView.as_view(),
        name="procurement-tracker-delete",
    ),
    # Delivery Tracker
    path(
        "project/<int:project_pk>/delivery-tracker/",
        DeliveryTrackerListView.as_view(),
        name="delivery-tracker-list",
    ),
    path(
        "project/<int:project_pk>/delivery-tracker/create/",
        DeliveryTrackerCreateView.as_view(),
        name="delivery-tracker-create",
    ),
    path(
        "project/<int:project_pk>/delivery-tracker/<int:pk>/update/",
        DeliveryTrackerUpdateView.as_view(),
        name="delivery-tracker-update",
    ),
    path(
        "project/<int:project_pk>/delivery-tracker/<int:pk>/delete/",
        DeliveryTrackerDeleteView.as_view(),
        name="delivery-tracker-delete",
    ),
    # Plant Equipment
    path(
        "project/<int:project_pk>/plant-equipment/",
        PlantEquipmentListView.as_view(),
        name="plant-equipment-list",
    ),
    path(
        "project/<int:project_pk>/plant-equipment/create/",
        PlantEquipmentCreateView.as_view(),
        name="plant-equipment-create",
    ),
    path(
        "project/<int:project_pk>/plant-equipment/<int:pk>/update/",
        PlantEquipmentUpdateView.as_view(),
        name="plant-equipment-update",
    ),
    path(
        "project/<int:project_pk>/plant-equipment/<int:pk>/delete/",
        PlantEquipmentDeleteView.as_view(),
        name="plant-equipment-delete",
    ),
    # Quality Control
    path(
        "project/<int:project_pk>/quality-control/",
        QualityControlListView.as_view(),
        name="quality-control-list",
    ),
    path(
        "project/<int:project_pk>/quality-control/create/",
        QualityControlCreateView.as_view(),
        name="quality-control-create",
    ),
    path(
        "project/<int:project_pk>/quality-control/<int:pk>/update/",
        QualityControlUpdateView.as_view(),
        name="quality-control-update",
    ),
    path(
        "project/<int:project_pk>/quality-control/<int:pk>/delete/",
        QualityControlDeleteView.as_view(),
        name="quality-control-delete",
    ),
    # Labour Log
    path(
        "project/<int:project_pk>/labour-log/",
        LabourLogListView.as_view(),
        name="labour-log-list",
    ),
    path(
        "project/<int:project_pk>/labour-log/create/",
        LabourLogCreateView.as_view(),
        name="labour-log-create",
    ),
    path(
        "project/<int:project_pk>/labour-log/<int:pk>/update/",
        LabourLogUpdateView.as_view(),
        name="labour-log-update",
    ),
    path(
        "project/<int:project_pk>/labour-log/<int:pk>/delete/",
        LabourLogDeleteView.as_view(),
        name="labour-log-delete",
    ),
    # Offsite Log
    path(
        "project/<int:project_pk>/offsite-log/",
        OffsiteLogListView.as_view(),
        name="offsite-log-list",
    ),
    path(
        "project/<int:project_pk>/offsite-log/create/",
        OffsiteLogCreateView.as_view(),
        name="offsite-log-create",
    ),
    path(
        "project/<int:project_pk>/offsite-log/<int:pk>/update/",
        OffsiteLogUpdateView.as_view(),
        name="offsite-log-update",
    ),
    path(
        "project/<int:project_pk>/offsite-log/<int:pk>/delete/",
        OffsiteLogDeleteView.as_view(),
        name="offsite-log-delete",
    ),
    # Safety Observation
    path(
        "project/<int:project_pk>/safety-observation/",
        SafetyObservationListView.as_view(),
        name="safety-observation-list",
    ),
    path(
        "project/<int:project_pk>/safety-observation/create/",
        SafetyObservationCreateView.as_view(),
        name="safety-observation-create",
    ),
    path(
        "project/<int:project_pk>/safety-observation/<int:pk>/update/",
        SafetyObservationUpdateView.as_view(),
        name="safety-observation-update",
    ),
    path(
        "project/<int:project_pk>/safety-observation/<int:pk>/delete/",
        SafetyObservationDeleteView.as_view(),
        name="safety-observation-delete",
    ),
]
