"""URL configuration for Site Management."""

from django.urls import path

from app.SiteManagement import views

app_name = "site_management"
_path_prefix = "site-management/"

urlpatterns = [
    # Site Management
    path(
        "project/<int:project_pk>/site-management/",
        views.SiteManagementView.as_view(),
        name="site-management",
    ),
    # Early Warnings
    path(
        "project/<int:project_pk>/early-warnings/",
        views.EarlyWarningListView.as_view(),
        name="early-warning-list",
    ),
    path(
        "project/<int:project_pk>/early-warnings/create/",
        views.EarlyWarningCreateView.as_view(),
        name="early-warning-create",
    ),
    path(
        "project/<int:project_pk>/early-warnings/<int:pk>/",
        views.EarlyWarningDetailView.as_view(),
        name="early-warning-detail",
    ),
    path(
        "project/<int:project_pk>/early-warnings/<int:pk>/update/",
        views.EarlyWarningUpdateView.as_view(),
        name="early-warning-update",
    ),
    path(
        "project/<int:project_pk>/early-warnings/<int:pk>/delete/",
        views.EarlyWarningDeleteView.as_view(),
        name="early-warning-delete",
    ),
    # Meetings
    path(
        "project/<int:project_pk>/meetings/",
        views.MeetingListView.as_view(),
        name="meeting-list",
    ),
    path(
        "project/<int:project_pk>/meetings/create/",
        views.MeetingCreateView.as_view(),
        name="meeting-create",
    ),
    path(
        "project/<int:project_pk>/meetings/<int:pk>/",
        views.MeetingDetailView.as_view(),
        name="meeting-detail",
    ),
    path(
        "project/<int:project_pk>/meetings/<int:pk>/update/",
        views.MeetingUpdateView.as_view(),
        name="meeting-update",
    ),
    path(
        "project/<int:project_pk>/meetings/<int:pk>/delete/",
        views.MeetingDeleteView.as_view(),
        name="meeting-delete",
    ),
    # Requests for Information
    path(
        "project/<int:project_pk>/rfis/",
        views.RFIListView.as_view(),
        name="rfi-list",
    ),
    path(
        "project/<int:project_pk>/rfis/create/",
        views.RFICreateView.as_view(),
        name="rfi-create",
    ),
    path(
        "project/<int:project_pk>/rfis/<int:pk>/",
        views.RFIDetailView.as_view(),
        name="rfi-detail",
    ),
    path(
        "project/<int:project_pk>/rfis/<int:pk>/update/",
        views.RFIUpdateView.as_view(),
        name="rfi-update",
    ),
    path(
        "project/<int:project_pk>/rfis/<int:pk>/delete/",
        views.RFIDeleteView.as_view(),
        name="rfi-delete",
    ),
    # Site Instructions
    path(
        "project/<int:project_pk>/site-instructions/",
        views.SiteInstructionListView.as_view(),
        name="site-instruction-list",
    ),
    path(
        "project/<int:project_pk>/site-instructions/create/",
        views.SiteInstructionCreateView.as_view(),
        name="site-instruction-create",
    ),
    path(
        "project/<int:project_pk>/site-instructions/<int:pk>/",
        views.SiteInstructionDetailView.as_view(),
        name="site-instruction-detail",
    ),
    path(
        "project/<int:project_pk>/site-instructions/<int:pk>/update/",
        views.SiteInstructionUpdateView.as_view(),
        name="site-instruction-update",
    ),
    path(
        "project/<int:project_pk>/site-instructions/<int:pk>/delete/",
        views.SiteInstructionDeleteView.as_view(),
        name="site-instruction-delete",
    ),
    # Bi-Weekly Safety Reports
    path(
        "project/<int:project_pk>/biweekly-safety/",
        views.BiWeeklySafetyReportListView.as_view(),
        name="biweekly-safety-list",
    ),
    path(
        "project/<int:project_pk>/biweekly-safety/create/",
        views.BiWeeklySafetyReportCreateView.as_view(),
        name="biweekly-safety-create",
    ),
    path(
        "project/<int:project_pk>/biweekly-safety/<int:pk>/update/",
        views.BiWeeklySafetyReportUpdateView.as_view(),
        name="biweekly-safety-update",
    ),
    path(
        "project/<int:project_pk>/biweekly-safety/<int:pk>/delete/",
        views.BiWeeklySafetyReportDeleteView.as_view(),
        name="biweekly-safety-delete",
    ),
    # Bi-Weekly Quality Reports
    path(
        "project/<int:project_pk>/biweekly-quality/",
        views.BiWeeklyQualityReportListView.as_view(),
        name="biweekly-quality-list",
    ),
    path(
        "project/<int:project_pk>/biweekly-quality/create/",
        views.BiWeeklyQualityReportCreateView.as_view(),
        name="biweekly-quality-create",
    ),
    path(
        "project/<int:project_pk>/biweekly-quality/<int:pk>/update/",
        views.BiWeeklyQualityReportUpdateView.as_view(),
        name="biweekly-quality-update",
    ),
    path(
        "project/<int:project_pk>/biweekly-quality/<int:pk>/delete/",
        views.BiWeeklyQualityReportDeleteView.as_view(),
        name="biweekly-quality-delete",
    ),
    # Materials Log
    path(
        "project/<int:project_pk>/materials-log/",
        views.MaterialsLogListView.as_view(),
        name="materials-log-list",
    ),
    path(
        "project/<int:project_pk>/materials-log/create/",
        views.MaterialsLogCreateView.as_view(),
        name="materials-log-create",
    ),
    path(
        "project/<int:project_pk>/materials-log/<int:pk>/update/",
        views.MaterialsLogUpdateView.as_view(),
        name="materials-log-update",
    ),
    path(
        "project/<int:project_pk>/materials-log/<int:pk>/delete/",
        views.MaterialsLogDeleteView.as_view(),
        name="materials-log-delete",
    ),
    # Daily Diary
    path(
        "project/<int:project_pk>/daily-diary/",
        views.DailyDiaryListView.as_view(),
        name="daily-diary-list",
    ),
    path(
        "project/<int:project_pk>/daily-diary/create/",
        views.DailyDiaryCreateView.as_view(),
        name="daily-diary-create",
    ),
    path(
        "project/<int:project_pk>/daily-diary/<int:pk>/update/",
        views.DailyDiaryUpdateView.as_view(),
        name="daily-diary-update",
    ),
    path(
        "project/<int:project_pk>/daily-diary/<int:pk>/delete/",
        views.DailyDiaryDeleteView.as_view(),
        name="daily-diary-delete",
    ),
    # Productivity Log
    path(
        "project/<int:project_pk>/productivity-log/",
        views.ProductivityLogListView.as_view(),
        name="productivity-log-list",
    ),
    path(
        "project/<int:project_pk>/productivity-log/create/",
        views.ProductivityLogCreateView.as_view(),
        name="productivity-log-create",
    ),
    path(
        "project/<int:project_pk>/productivity-log/<int:pk>/update/",
        views.ProductivityLogUpdateView.as_view(),
        name="productivity-log-update",
    ),
    path(
        "project/<int:project_pk>/productivity-log/<int:pk>/delete/",
        views.ProductivityLogDeleteView.as_view(),
        name="productivity-log-delete",
    ),
    # Subcontractor Log
    path(
        "project/<int:project_pk>/subcontractor-log/",
        views.SubcontractorLogListView.as_view(),
        name="subcontractor-log-list",
    ),
    path(
        "project/<int:project_pk>/subcontractor-log/create/",
        views.SubcontractorLogCreateView.as_view(),
        name="subcontractor-log-create",
    ),
    path(
        "project/<int:project_pk>/subcontractor-log/<int:pk>/update/",
        views.SubcontractorLogUpdateView.as_view(),
        name="subcontractor-log-update",
    ),
    path(
        "project/<int:project_pk>/subcontractor-log/<int:pk>/delete/",
        views.SubcontractorLogDeleteView.as_view(),
        name="subcontractor-log-delete",
    ),
    # Snag List
    path(
        "project/<int:project_pk>/snag-list/",
        views.SnagListListView.as_view(),
        name="snag-list-list",
    ),
    path(
        "project/<int:project_pk>/snag-list/create/",
        views.SnagListCreateView.as_view(),
        name="snag-list-create",
    ),
    path(
        "project/<int:project_pk>/snag-list/<int:pk>/update/",
        views.SnagListUpdateView.as_view(),
        name="snag-list-update",
    ),
    path(
        "project/<int:project_pk>/snag-list/<int:pk>/delete/",
        views.SnagListDeleteView.as_view(),
        name="snag-list-delete",
    ),
    # Progress Tracker
    path(
        "project/<int:project_pk>/progress-tracker/",
        views.ProgressTrackerListView.as_view(),
        name="progress-tracker-list",
    ),
    path(
        "project/<int:project_pk>/progress-tracker/create/",
        views.ProgressTrackerCreateView.as_view(),
        name="progress-tracker-create",
    ),
    path(
        "project/<int:project_pk>/progress-tracker/<int:pk>/update/",
        views.ProgressTrackerUpdateView.as_view(),
        name="progress-tracker-update",
    ),
    path(
        "project/<int:project_pk>/progress-tracker/<int:pk>/delete/",
        views.ProgressTrackerDeleteView.as_view(),
        name="progress-tracker-delete",
    ),
    # Delay Log
    path(
        "project/<int:project_pk>/delay-log/",
        views.DelayLogListView.as_view(),
        name="delay-log-list",
    ),
    path(
        "project/<int:project_pk>/delay-log/create/",
        views.DelayLogCreateView.as_view(),
        name="delay-log-create",
    ),
    path(
        "project/<int:project_pk>/delay-log/<int:pk>/update/",
        views.DelayLogUpdateView.as_view(),
        name="delay-log-update",
    ),
    path(
        "project/<int:project_pk>/delay-log/<int:pk>/delete/",
        views.DelayLogDeleteView.as_view(),
        name="delay-log-delete",
    ),
    # Photo Log
    path(
        "project/<int:project_pk>/photo-log/",
        views.PhotoLogListView.as_view(),
        name="photo-log-list",
    ),
    path(
        "project/<int:project_pk>/photo-log/create/",
        views.PhotoLogCreateView.as_view(),
        name="photo-log-create",
    ),
    path(
        "project/<int:project_pk>/photo-log/<int:pk>/update/",
        views.PhotoLogUpdateView.as_view(),
        name="photo-log-update",
    ),
    path(
        "project/<int:project_pk>/photo-log/<int:pk>/delete/",
        views.PhotoLogDeleteView.as_view(),
        name="photo-log-delete",
    ),
    # Procurement Tracker
    path(
        "project/<int:project_pk>/procurement-tracker/",
        views.ProcurementTrackerListView.as_view(),
        name="procurement-tracker-list",
    ),
    path(
        "project/<int:project_pk>/procurement-tracker/create/",
        views.ProcurementTrackerCreateView.as_view(),
        name="procurement-tracker-create",
    ),
    path(
        "project/<int:project_pk>/procurement-tracker/<int:pk>/update/",
        views.ProcurementTrackerUpdateView.as_view(),
        name="procurement-tracker-update",
    ),
    path(
        "project/<int:project_pk>/procurement-tracker/<int:pk>/delete/",
        views.ProcurementTrackerDeleteView.as_view(),
        name="procurement-tracker-delete",
    ),
    # Delivery Tracker
    path(
        "project/<int:project_pk>/delivery-tracker/",
        views.DeliveryTrackerListView.as_view(),
        name="delivery-tracker-list",
    ),
    path(
        "project/<int:project_pk>/delivery-tracker/create/",
        views.DeliveryTrackerCreateView.as_view(),
        name="delivery-tracker-create",
    ),
    path(
        "project/<int:project_pk>/delivery-tracker/<int:pk>/update/",
        views.DeliveryTrackerUpdateView.as_view(),
        name="delivery-tracker-update",
    ),
    path(
        "project/<int:project_pk>/delivery-tracker/<int:pk>/delete/",
        views.DeliveryTrackerDeleteView.as_view(),
        name="delivery-tracker-delete",
    ),
    # Plant Equipment
    path(
        "project/<int:project_pk>/plant-equipment/",
        views.PlantEquipmentListView.as_view(),
        name="plant-equipment-list",
    ),
    path(
        "project/<int:project_pk>/plant-equipment/create/",
        views.PlantEquipmentCreateView.as_view(),
        name="plant-equipment-create",
    ),
    path(
        "project/<int:project_pk>/plant-equipment/<int:pk>/update/",
        views.PlantEquipmentUpdateView.as_view(),
        name="plant-equipment-update",
    ),
    path(
        "project/<int:project_pk>/plant-equipment/<int:pk>/delete/",
        views.PlantEquipmentDeleteView.as_view(),
        name="plant-equipment-delete",
    ),
    # Quality Control
    path(
        "project/<int:project_pk>/quality-control/",
        views.QualityControlListView.as_view(),
        name="quality-control-list",
    ),
    path(
        "project/<int:project_pk>/quality-control/create/",
        views.QualityControlCreateView.as_view(),
        name="quality-control-create",
    ),
    path(
        "project/<int:project_pk>/quality-control/<int:pk>/update/",
        views.QualityControlUpdateView.as_view(),
        name="quality-control-update",
    ),
    path(
        "project/<int:project_pk>/quality-control/<int:pk>/delete/",
        views.QualityControlDeleteView.as_view(),
        name="quality-control-delete",
    ),
    # Labour Log
    path(
        "project/<int:project_pk>/labour-log/",
        views.LabourLogListView.as_view(),
        name="labour-log-list",
    ),
    path(
        "project/<int:project_pk>/labour-log/create/",
        views.LabourLogCreateView.as_view(),
        name="labour-log-create",
    ),
    path(
        "project/<int:project_pk>/labour-log/<int:pk>/update/",
        views.LabourLogUpdateView.as_view(),
        name="labour-log-update",
    ),
    path(
        "project/<int:project_pk>/labour-log/<int:pk>/delete/",
        views.LabourLogDeleteView.as_view(),
        name="labour-log-delete",
    ),
    # Offsite Log
    path(
        "project/<int:project_pk>/offsite-log/",
        views.OffsiteLogListView.as_view(),
        name="offsite-log-list",
    ),
    path(
        "project/<int:project_pk>/offsite-log/create/",
        views.OffsiteLogCreateView.as_view(),
        name="offsite-log-create",
    ),
    path(
        "project/<int:project_pk>/offsite-log/<int:pk>/update/",
        views.OffsiteLogUpdateView.as_view(),
        name="offsite-log-update",
    ),
    path(
        "project/<int:project_pk>/offsite-log/<int:pk>/delete/",
        views.OffsiteLogDeleteView.as_view(),
        name="offsite-log-delete",
    ),
    # Safety Observation
    path(
        "project/<int:project_pk>/safety-observation/",
        views.SafetyObservationListView.as_view(),
        name="safety-observation-list",
    ),
    path(
        "project/<int:project_pk>/safety-observation/create/",
        views.SafetyObservationCreateView.as_view(),
        name="safety-observation-create",
    ),
    path(
        "project/<int:project_pk>/safety-observation/<int:pk>/update/",
        views.SafetyObservationUpdateView.as_view(),
        name="safety-observation-update",
    ),
    path(
        "project/<int:project_pk>/safety-observation/<int:pk>/delete/",
        views.SafetyObservationDeleteView.as_view(),
        name="safety-observation-delete",
    ),
]
