from django.urls import path

from app.Project.views import (
    portfolio_views,
)

urlpatterns = [
    path(
        "dashboard/",
        portfolio_views.PortfolioDashboardView.as_view(),
        name="portfolio-dashboard",
    ),
    path(
        "reports/province/",
        portfolio_views.PortfolioProvinceSummaryView.as_view(),
        name="portfolio-province-summary",
    ),
    path(
        "province/<int:province_pk>/cover-page/",
        portfolio_views.ProvinceCoverPageView.as_view(),
        name="portfolio-province-cover-page",
    ),
    path(
        "province/<int:province_pk>/cover-page/xlsx/",
        portfolio_views.ProvinceCoverPageDownloadXLSXView.as_view(),
        name="portfolio-province-cover-page-xlsx",
    ),
    path(
        "province/<int:province_pk>/valuation-summary/",
        portfolio_views.ProvinceValuationSummaryView.as_view(),
        name="portfolio-province-valuation-summary",
    ),
    path(
        "province/<int:province_pk>/valuation-summary/xlsx/",
        portfolio_views.ProvinceValuationSummaryDownloadXLSXView.as_view(),
        name="portfolio-province-valuation-summary-xlsx",
    ),
    path(
        "reports/multi/cover-page/",
        portfolio_views.MultiProjectCoverPageView.as_view(),
        name="portfolio-multi-cover-page",
    ),
    path(
        "reports/multi/cover-page/xlsx/",
        portfolio_views.MultiProjectCoverPageDownloadXLSXView.as_view(),
        name="portfolio-multi-cover-page-xlsx",
    ),
    path(
        "reports/multi/valuation-summary/",
        portfolio_views.MultiProjectValuationSummaryView.as_view(),
        name="portfolio-multi-valuation-summary",
    ),
    path(
        "reports/multi/valuation-summary/xlsx/",
        portfolio_views.MultiProjectValuationSummaryDownloadXLSXView.as_view(),
        name="portfolio-multi-valuation-summary-xlsx",
    ),
    path(
        "reports/group/create/",
        portfolio_views.ProjectGroupCreateView.as_view(),
        name="portfolio-group-create",
    ),
    path(
        "reports/group/<int:group_pk>/delete/",
        portfolio_views.ProjectGroupDeleteView.as_view(),
        name="portfolio-group-delete",
    ),
    path(
        "reports/group/<int:group_pk>/cover-page/",
        portfolio_views.GroupCoverPageView.as_view(),
        name="portfolio-group-cover-page",
    ),
    path(
        "reports/group/<int:group_pk>/cover-page/xlsx/",
        portfolio_views.GroupCoverPageDownloadXLSXView.as_view(),
        name="portfolio-group-cover-page-xlsx",
    ),
    path(
        "reports/group/<int:group_pk>/valuation-summary/",
        portfolio_views.GroupValuationSummaryView.as_view(),
        name="portfolio-group-valuation-summary",
    ),
    path(
        "reports/group/<int:group_pk>/valuation-summary/xlsx/",
        portfolio_views.GroupValuationSummaryDownloadXLSXView.as_view(),
        name="portfolio-group-valuation-summary-xlsx",
    ),
    # New Portfolio Reports
    path(
        "reports/compliance/",
        portfolio_views.ComplianceReportView.as_view(),
        name="compliance-report",
    ),
    path(
        "reports/impact/",
        portfolio_views.ImpactReportView.as_view(),
        name="impact-report",
    ),
    path(
        "reports/risk/",
        portfolio_views.RiskReportView.as_view(),
        name="risk-report",
    ),
]
