"""URL configuration for Planning & Procurement app."""

from django.urls import path

from app.Planning.views import (
    DesignCategoryCreateView,
    DesignCategoryDeleteView,
    DesignCategoryFileUploadView,
    DesignCategoryUpdateView,
    DesignDevelopmentOverviewView,
    DesignDisciplineCreateView,
    DesignDisciplineDeleteView,
    DesignDisciplineFileUploadView,
    DesignDisciplineUpdateView,
    DesignGroupCreateView,
    DesignGroupDeleteView,
    DesignGroupFileUploadView,
    DesignGroupUpdateView,
    DesignListView,
    DesignSubCategoryCreateView,
    DesignSubCategoryDeleteView,
    DesignSubCategoryFileUploadView,
    DesignSubCategoryUpdateView,
    TenderDocumentationOverviewView,
    TenderDocumentCreateView,
    TenderDocumentDeleteView,
    TenderDocumentFileUploadView,
    TenderDocumentUpdateView,
    TenderProcessOverviewView,
    TenderProcessSectionCompleteAPIView,
    TenderProcessUpdateView,
    WorkPackageCreateView,
    WorkPackageDeleteView,
    WorkPackageDetailView,
    WorkPackageListView,
    WorkPackageProcessUpdateView,
    WorkPackageUpdateView,
)

app_name = "planning"

urlpatterns = [
    # Overview Pages
    path(
        "<int:project_pk>/overview/design-development/",
        DesignDevelopmentOverviewView.as_view(),
        name="design-development-overview",
    ),
    path(
        "<int:project_pk>/overview/tender-documentation/",
        TenderDocumentationOverviewView.as_view(),
        name="tender-documentation-overview",
    ),
    path(
        "<int:project_pk>/overview/tender-process/",
        TenderProcessOverviewView.as_view(),
        name="tender-process-overview",
    ),
    path(
        "<int:project_pk>/overview/tender-process/api/work-packages/<int:wp_pk>/section-complete/",
        TenderProcessSectionCompleteAPIView.as_view(),
        name="tender-process-section-complete-api",
    ),
    # Work Packages
    path(
        "<int:project_pk>/work-packages/",
        WorkPackageListView.as_view(),
        name="work-package-list",
    ),
    path(
        "<int:project_pk>/work-packages/create/",
        WorkPackageCreateView.as_view(),
        name="work-package-create",
    ),
    path(
        "<int:project_pk>/work-packages/<int:pk>/",
        WorkPackageDetailView.as_view(),
        name="work-package-detail",
    ),
    path(
        "<int:project_pk>/work-packages/<int:pk>/edit/",
        WorkPackageUpdateView.as_view(),
        name="work-package-update",
    ),
    path(
        "<int:project_pk>/work-packages/<int:pk>/delete/",
        WorkPackageDeleteView.as_view(),
        name="work-package-delete",
    ),
    path(
        "<int:project_pk>/work-packages/<int:pk>/edit-process/",
        WorkPackageProcessUpdateView.as_view(),
        name="work-package-edit-process",
    ),
    path(
        "<int:project_pk>/work-packages/<int:pk>/edit-tender-process/",
        TenderProcessUpdateView.as_view(),
        name="work-package-edit-tender-process",
    ),
    # Tender Documents
    path(
        "<int:project_pk>/work-packages/<int:wp_pk>/documents/create/",
        TenderDocumentCreateView.as_view(),
        name="tender-document-create",
    ),
    path(
        "<int:project_pk>/work-packages/<int:wp_pk>/documents/<int:pk>/edit/",
        TenderDocumentUpdateView.as_view(),
        name="tender-document-update",
    ),
    path(
        "<int:project_pk>/work-packages/<int:wp_pk>/documents/<int:pk>/delete/",
        TenderDocumentDeleteView.as_view(),
        name="tender-document-delete",
    ),
    path(
        "<int:project_pk>/work-packages/<int:wp_pk>/documents/<int:doc_pk>/upload/",
        TenderDocumentFileUploadView.as_view(),
        name="tender-document-upload",
    ),
    # Design Development
    path(
        "<int:project_pk>/work-packages/<int:pk>/design/",
        DesignListView.as_view(),
        name="design-list",
    ),
    # Design Category (L1)
    path(
        "<int:project_pk>/work-packages/<int:wp_pk>/design/category/create/",
        DesignCategoryCreateView.as_view(),
        name="design-category-create",
    ),
    path(
        "<int:project_pk>/work-packages/<int:wp_pk>/design/category/<int:design_pk>/upload/",
        DesignCategoryFileUploadView.as_view(),
        name="design-category-upload",
    ),
    path(
        "<int:project_pk>/work-packages/<int:wp_pk>/design/category/<int:pk>/edit/",
        DesignCategoryUpdateView.as_view(),
        name="design-category-edit",
    ),
    path(
        "<int:project_pk>/work-packages/<int:wp_pk>/design/category/<int:pk>/delete/",
        DesignCategoryDeleteView.as_view(),
        name="design-category-delete",
    ),
    # Design SubCategory (L2)
    path(
        "<int:project_pk>/work-packages/<int:wp_pk>/design/subcategory/create/",
        DesignSubCategoryCreateView.as_view(),
        name="design-subcategory-create",
    ),
    path(
        "<int:project_pk>/work-packages/<int:wp_pk>/design/subcategory/<int:design_pk>/upload/",
        DesignSubCategoryFileUploadView.as_view(),
        name="design-subcategory-upload",
    ),
    path(
        "<int:project_pk>/work-packages/<int:wp_pk>/design/subcategory/<int:pk>/edit/",
        DesignSubCategoryUpdateView.as_view(),
        name="design-subcategory-edit",
    ),
    path(
        "<int:project_pk>/work-packages/<int:wp_pk>/design/subcategory/<int:pk>/delete/",
        DesignSubCategoryDeleteView.as_view(),
        name="design-subcategory-delete",
    ),
    # Design Group (L3)
    path(
        "<int:project_pk>/work-packages/<int:wp_pk>/design/group/create/",
        DesignGroupCreateView.as_view(),
        name="design-group-create",
    ),
    path(
        "<int:project_pk>/work-packages/<int:wp_pk>/design/group/<int:design_pk>/upload/",
        DesignGroupFileUploadView.as_view(),
        name="design-group-upload",
    ),
    path(
        "<int:project_pk>/work-packages/<int:wp_pk>/design/group/<int:pk>/edit/",
        DesignGroupUpdateView.as_view(),
        name="design-group-edit",
    ),
    path(
        "<int:project_pk>/work-packages/<int:wp_pk>/design/group/<int:pk>/delete/",
        DesignGroupDeleteView.as_view(),
        name="design-group-delete",
    ),
    # Design Discipline (L4)
    path(
        "<int:project_pk>/work-packages/<int:wp_pk>/design/discipline/create/",
        DesignDisciplineCreateView.as_view(),
        name="design-discipline-create",
    ),
    path(
        "<int:project_pk>/work-packages/<int:wp_pk>/design/discipline/<int:design_pk>/upload/",
        DesignDisciplineFileUploadView.as_view(),
        name="design-discipline-upload",
    ),
    path(
        "<int:project_pk>/work-packages/<int:wp_pk>/design/discipline/<int:pk>/edit/",
        DesignDisciplineUpdateView.as_view(),
        name="design-discipline-edit",
    ),
    path(
        "<int:project_pk>/work-packages/<int:wp_pk>/design/discipline/<int:pk>/delete/",
        DesignDisciplineDeleteView.as_view(),
        name="design-discipline-delete",
    ),
]
