# Generated by Django 6.0.3 on 2026-03-22 19:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("Project", "0061_category_budget_group_budget_subcategory_budget"),
    ]

    operations = [
        migrations.CreateModel(
            name="DesignCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When this record was created"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="When this record was last modified"
                    ),
                ),
                (
                    "deleted",
                    models.BooleanField(default=False, help_text="Soft delete flag"),
                ),
                (
                    "stage",
                    models.CharField(
                        choices=[
                            ("DESIGN_CRITERIA", "Design Criteria"),
                            ("DESIGN_CALCULATIONS", "Design Calculations"),
                            ("SKETCHES", "Sketches"),
                        ],
                        default="DESIGN_CRITERIA",
                        help_text="Current design stage",
                        max_length=30,
                    ),
                ),
                (
                    "approved",
                    models.BooleanField(
                        default=False, help_text="Whether this design stage is approved"
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        help_text="L1 Category from project structure",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="design_categories",
                        to="Project.category",
                    ),
                ),
            ],
            options={
                "verbose_name": "Design Category (L1)",
                "verbose_name_plural": "Design Categories (L1)",
                "ordering": ["category__name", "stage"],
            },
        ),
        migrations.CreateModel(
            name="DesignCategoryFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When this record was created"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="When this record was last modified"
                    ),
                ),
                (
                    "deleted",
                    models.BooleanField(default=False, help_text="Soft delete flag"),
                ),
                (
                    "file",
                    models.FileField(
                        help_text="Uploaded design file",
                        upload_to="planning/design/category/",
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True,
                        help_text="Description of the uploaded file",
                        max_length=255,
                    ),
                ),
                (
                    "design_category",
                    models.ForeignKey(
                        help_text="Design category this file belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="files",
                        to="planning.designcategory",
                    ),
                ),
            ],
            options={
                "verbose_name": "Design Category File",
                "verbose_name_plural": "Design Category Files",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="DesignDiscipline",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When this record was created"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="When this record was last modified"
                    ),
                ),
                (
                    "deleted",
                    models.BooleanField(default=False, help_text="Soft delete flag"),
                ),
                (
                    "stage",
                    models.CharField(
                        choices=[
                            ("DESIGN_CRITERIA", "Design Criteria"),
                            ("DESIGN_CALCULATIONS", "Design Calculations"),
                            ("SKETCHES", "Sketches"),
                        ],
                        default="DESIGN_CRITERIA",
                        help_text="Current design stage",
                        max_length=30,
                    ),
                ),
                (
                    "approved",
                    models.BooleanField(
                        default=False, help_text="Whether this design stage is approved"
                    ),
                ),
                (
                    "discipline",
                    models.ForeignKey(
                        help_text="L4 Discipline from project structure",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="design_disciplines",
                        to="Project.discipline",
                    ),
                ),
            ],
            options={
                "verbose_name": "Design Discipline (L4)",
                "verbose_name_plural": "Design Disciplines (L4)",
                "ordering": ["discipline__name", "stage"],
            },
        ),
        migrations.CreateModel(
            name="DesignDisciplineFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When this record was created"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="When this record was last modified"
                    ),
                ),
                (
                    "deleted",
                    models.BooleanField(default=False, help_text="Soft delete flag"),
                ),
                (
                    "file",
                    models.FileField(
                        help_text="Uploaded design file",
                        upload_to="planning/design/discipline/",
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True,
                        help_text="Description of the uploaded file",
                        max_length=255,
                    ),
                ),
                (
                    "design_discipline",
                    models.ForeignKey(
                        help_text="Design discipline this file belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="files",
                        to="planning.designdiscipline",
                    ),
                ),
            ],
            options={
                "verbose_name": "Design Discipline File",
                "verbose_name_plural": "Design Discipline Files",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="DesignGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When this record was created"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="When this record was last modified"
                    ),
                ),
                (
                    "deleted",
                    models.BooleanField(default=False, help_text="Soft delete flag"),
                ),
                (
                    "stage",
                    models.CharField(
                        choices=[
                            ("DESIGN_CRITERIA", "Design Criteria"),
                            ("DESIGN_CALCULATIONS", "Design Calculations"),
                            ("SKETCHES", "Sketches"),
                        ],
                        default="DESIGN_CRITERIA",
                        help_text="Current design stage",
                        max_length=30,
                    ),
                ),
                (
                    "approved",
                    models.BooleanField(
                        default=False, help_text="Whether this design stage is approved"
                    ),
                ),
                (
                    "group",
                    models.ForeignKey(
                        help_text="L3 Group from project structure",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="design_groups",
                        to="Project.group",
                    ),
                ),
            ],
            options={
                "verbose_name": "Design Group (L3)",
                "verbose_name_plural": "Design Groups (L3)",
                "ordering": ["group__name", "stage"],
            },
        ),
        migrations.CreateModel(
            name="DesignGroupFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When this record was created"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="When this record was last modified"
                    ),
                ),
                (
                    "deleted",
                    models.BooleanField(default=False, help_text="Soft delete flag"),
                ),
                (
                    "file",
                    models.FileField(
                        help_text="Uploaded design file",
                        upload_to="planning/design/group/",
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True,
                        help_text="Description of the uploaded file",
                        max_length=255,
                    ),
                ),
                (
                    "design_group",
                    models.ForeignKey(
                        help_text="Design group this file belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="files",
                        to="planning.designgroup",
                    ),
                ),
            ],
            options={
                "verbose_name": "Design Group File",
                "verbose_name_plural": "Design Group Files",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="DesignSubCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When this record was created"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="When this record was last modified"
                    ),
                ),
                (
                    "deleted",
                    models.BooleanField(default=False, help_text="Soft delete flag"),
                ),
                (
                    "stage",
                    models.CharField(
                        choices=[
                            ("DESIGN_CRITERIA", "Design Criteria"),
                            ("DESIGN_CALCULATIONS", "Design Calculations"),
                            ("SKETCHES", "Sketches"),
                        ],
                        default="DESIGN_CRITERIA",
                        help_text="Current design stage",
                        max_length=30,
                    ),
                ),
                (
                    "approved",
                    models.BooleanField(
                        default=False, help_text="Whether this design stage is approved"
                    ),
                ),
                (
                    "sub_category",
                    models.ForeignKey(
                        help_text="L2 SubCategory from project structure",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="design_subcategories",
                        to="Project.subcategory",
                    ),
                ),
            ],
            options={
                "verbose_name": "Design SubCategory (L2)",
                "verbose_name_plural": "Design SubCategories (L2)",
                "ordering": ["sub_category__name", "stage"],
            },
        ),
        migrations.CreateModel(
            name="DesignSubCategoryFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When this record was created"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="When this record was last modified"
                    ),
                ),
                (
                    "deleted",
                    models.BooleanField(default=False, help_text="Soft delete flag"),
                ),
                (
                    "file",
                    models.FileField(
                        help_text="Uploaded design file",
                        upload_to="planning/design/subcategory/",
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True,
                        help_text="Description of the uploaded file",
                        max_length=255,
                    ),
                ),
                (
                    "design_sub_category",
                    models.ForeignKey(
                        help_text="Design subcategory this file belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="files",
                        to="planning.designsubcategory",
                    ),
                ),
            ],
            options={
                "verbose_name": "Design SubCategory File",
                "verbose_name_plural": "Design SubCategory Files",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="WorkPackage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When this record was created"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="When this record was last modified"
                    ),
                ),
                (
                    "deleted",
                    models.BooleanField(default=False, help_text="Soft delete flag"),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Name of the work package / contract", max_length=255
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Description of the work package"
                    ),
                ),
                (
                    "advert_start_date",
                    models.DateField(
                        blank=True, help_text="Advert start date", null=True
                    ),
                ),
                (
                    "advert_end_date",
                    models.DateField(
                        blank=True, help_text="Advert end date", null=True
                    ),
                ),
                (
                    "site_inspection_percentage",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Site inspection completion percentage",
                        max_digits=5,
                    ),
                ),
                (
                    "site_inspection_complete",
                    models.BooleanField(
                        default=False, help_text="Whether site inspection is complete"
                    ),
                ),
                (
                    "tender_close_percentage",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Tender close completion percentage",
                        max_digits=5,
                    ),
                ),
                (
                    "tender_close_complete",
                    models.BooleanField(
                        default=False, help_text="Whether tender close is complete"
                    ),
                ),
                (
                    "tender_evaluation_percentage",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Tender evaluation completion percentage",
                        max_digits=5,
                    ),
                ),
                (
                    "tender_evaluation_complete",
                    models.BooleanField(
                        default=False, help_text="Whether tender evaluation is complete"
                    ),
                ),
                (
                    "award_signing_percentage",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Award & contract signing completion percentage",
                        max_digits=5,
                    ),
                ),
                (
                    "award_signing_complete",
                    models.BooleanField(
                        default=False,
                        help_text="Whether award & contract signing is complete",
                    ),
                ),
                (
                    "mobilization_percentage",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Mobilization completion percentage",
                        max_digits=5,
                    ),
                ),
                (
                    "mobilization_complete",
                    models.BooleanField(
                        default=False, help_text="Whether mobilization is complete"
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        help_text="Project this work package belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="work_packages",
                        to="Project.project",
                    ),
                ),
            ],
            options={
                "verbose_name": "Work Package",
                "verbose_name_plural": "Work Packages",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="designsubcategory",
            name="work_package",
            field=models.ForeignKey(
                help_text="Work package this design subcategory belongs to",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="design_subcategories",
                to="planning.workpackage",
            ),
        ),
        migrations.AddField(
            model_name="designgroup",
            name="work_package",
            field=models.ForeignKey(
                help_text="Work package this design group belongs to",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="design_groups",
                to="planning.workpackage",
            ),
        ),
        migrations.AddField(
            model_name="designdiscipline",
            name="work_package",
            field=models.ForeignKey(
                help_text="Work package this design discipline belongs to",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="design_disciplines",
                to="planning.workpackage",
            ),
        ),
        migrations.AddField(
            model_name="designcategory",
            name="work_package",
            field=models.ForeignKey(
                help_text="Work package this design category belongs to",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="design_categories",
                to="planning.workpackage",
            ),
        ),
        migrations.CreateModel(
            name="TenderDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When this record was created"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="When this record was last modified"
                    ),
                ),
                (
                    "deleted",
                    models.BooleanField(default=False, help_text="Soft delete flag"),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Document category name", max_length=255
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        blank=True,
                        help_text="Uploaded tender document file",
                        null=True,
                        upload_to="planning/tender_documents/",
                    ),
                ),
                (
                    "percentage_completed",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Completion percentage for this document category",
                        max_digits=5,
                    ),
                ),
                (
                    "planned_date",
                    models.DateField(
                        blank=True, help_text="Planned completion date", null=True
                    ),
                ),
                (
                    "actual_date",
                    models.DateField(
                        blank=True, help_text="Actual completion date", null=True
                    ),
                ),
                (
                    "work_package",
                    models.ForeignKey(
                        help_text="Work package this document belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tender_documents",
                        to="planning.workpackage",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tender Document",
                "verbose_name_plural": "Tender Documents",
                "ordering": ["name"],
                "unique_together": {("work_package", "name")},
            },
        ),
    ]
