# Generated by Django 6.0.3 on 2026-03-24 08:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0005_designdiscipline_required_quantity_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tenderdocument',
            name='file',
        ),
        migrations.CreateModel(
            name='TenderDocumentFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When this record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When this record was last modified')),
                ('deleted', models.BooleanField(default=False, help_text='Soft delete flag')),
                ('file', models.FileField(help_text='Uploaded tender document file', upload_to='planning/tender_documents/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, help_text='Date and time when the file was uploaded')),
                ('tender_document', models.ForeignKey(help_text='Tender document this file belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='files', to='planning.tenderdocument')),
                ('uploaded_by', models.ForeignKey(blank=True, help_text='User who uploaded the file', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Tender Document File',
                'verbose_name_plural': 'Tender Document Files',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
