# Generated by Django 6.0.3 on 2026-03-24 08:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("planning", "0007_alter_tenderdocument_unique_together_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="tenderdocument",
            name="required_quantity",
            field=models.PositiveIntegerField(default=1),
        ),
    ]
