# Generated by Django 6.0.3 on 2026-03-25 07:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "planning",
            "0010_remove_workpackage_award_contract_signing_end_date_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="workpackage",
            name="conditions_of_contract",
            field=models.CharField(
                blank=True,
                choices=[
                    ("FIDIC", "FIDIC"),
                    ("NEC", "NEC"),
                    ("JBCC", "JBCC"),
                    ("CLIENT", "Client"),
                    ("OTHER", "Other - Specify"),
                ],
                help_text="Conditions of contract",
                max_length=32,
            ),
        ),
        migrations.AddField(
            model_name="workpackage",
            name="contract_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("LUMP_SUM", "Lump Sum"),
                    ("BOQ", "BoQ"),
                    ("ACTIVITY_SCHEDULE", "Activity Schedule"),
                    ("SCHEDULE_OF_RATES", "Schedule of Rates"),
                    ("OTHER", "Other - Specify"),
                ],
                help_text="Type of contract",
                max_length=32,
            ),
        ),
        migrations.AddField(
            model_name="workpackage",
            name="documentation_end_date",
            field=models.DateField(
                blank=True, help_text="Documentation phase end/finish date", null=True
            ),
        ),
        migrations.AddField(
            model_name="workpackage",
            name="documentation_start_date",
            field=models.DateField(
                blank=True, help_text="Documentation phase start date", null=True
            ),
        ),
        migrations.AddField(
            model_name="workpackage",
            name="execution_end_date",
            field=models.DateField(
                blank=True, help_text="Execution phase end/finish date", null=True
            ),
        ),
        migrations.AddField(
            model_name="workpackage",
            name="execution_start_date",
            field=models.DateField(
                blank=True, help_text="Execution phase start date", null=True
            ),
        ),
        migrations.AddField(
            model_name="workpackage",
            name="overall_end_date",
            field=models.DateField(
                blank=True, help_text="Overall package end/finish date", null=True
            ),
        ),
        migrations.AddField(
            model_name="workpackage",
            name="overall_start_date",
            field=models.DateField(
                blank=True, help_text="Overall package start date", null=True
            ),
        ),
        migrations.AddField(
            model_name="workpackage",
            name="procurement_strategy",
            field=models.CharField(
                blank=True,
                choices=[
                    ("SUPPLY", "Supply"),
                    ("INSTALL", "Install"),
                    ("SUPPLY_AND_INSTALL", "Supply & Install"),
                ],
                help_text="Procurement strategy",
                max_length=32,
            ),
        ),
        migrations.AddField(
            model_name="workpackage",
            name="tender_process_end_date",
            field=models.DateField(
                blank=True, help_text="Tender process phase end/finish date", null=True
            ),
        ),
        migrations.AddField(
            model_name="workpackage",
            name="tender_process_start_date",
            field=models.DateField(
                blank=True, help_text="Tender process phase start date", null=True
            ),
        ),
        migrations.AlterField(
            model_name="designcategory",
            name="stage",
            field=models.CharField(
                choices=[
                    ("DESIGN_CRITERIA", "Design Criteria"),
                    ("DRAWINGS", "Drawings"),
                    ("DOCUMENTS", "Documents"),
                ],
                default="DESIGN_CRITERIA",
                help_text="Current design stage",
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="designdiscipline",
            name="stage",
            field=models.CharField(
                choices=[
                    ("DESIGN_CRITERIA", "Design Criteria"),
                    ("DRAWINGS", "Drawings"),
                    ("DOCUMENTS", "Documents"),
                ],
                default="DESIGN_CRITERIA",
                help_text="Current design stage",
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="designgroup",
            name="stage",
            field=models.CharField(
                choices=[
                    ("DESIGN_CRITERIA", "Design Criteria"),
                    ("DRAWINGS", "Drawings"),
                    ("DOCUMENTS", "Documents"),
                ],
                default="DESIGN_CRITERIA",
                help_text="Current design stage",
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="designsubcategory",
            name="stage",
            field=models.CharField(
                choices=[
                    ("DESIGN_CRITERIA", "Design Criteria"),
                    ("DRAWINGS", "Drawings"),
                    ("DOCUMENTS", "Documents"),
                ],
                default="DESIGN_CRITERIA",
                help_text="Current design stage",
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="workpackage",
            name="applied_to_advert_end_date",
            field=models.DateField(blank=True, help_text="Advert end date", null=True),
        ),
        migrations.AlterField(
            model_name="workpackage",
            name="applied_to_advert_start_date",
            field=models.DateField(
                blank=True, help_text="Advert start date", null=True
            ),
        ),
    ]
