# Generated by Django 6.0.3 on 2026-03-25 07:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("planning", "0011_workpackage_conditions_of_contract_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="workpackage",
            name="applied_to_advert_start_date",
            field=models.DateField(
                blank=True,
                help_text="Advert start date",
                null=True,
                verbose_name="Advert Start Date",
            ),
        ),
    ]
