# Generated by Django 6.0.3 on 2026-03-25 07:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("planning", "0012_alter_workpackage_applied_to_advert_start_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="workpackage",
            name="applied_to_advert_end_date",
            field=models.DateField(
                blank=True,
                help_text="Advert end date",
                null=True,
                verbose_name="Advert End Date",
            ),
        ),
    ]
