# Generated by Django 6.0.3 on 2026-03-27 07:52

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("planning", "0013_alter_workpackage_applied_to_advert_end_date"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="designcategory",
            name="work_package",
        ),
        migrations.RemoveField(
            model_name="designdiscipline",
            name="work_package",
        ),
        migrations.RemoveField(
            model_name="designgroup",
            name="work_package",
        ),
        migrations.RemoveField(
            model_name="designsubcategory",
            name="work_package",
        ),
    ]
