# Generated by Django 6.0.3 on 2026-03-31 08:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("planning", "0015_categoryfile_disciplinefile_groupfile_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="workpackage",
            name="applied_to_advert_completed",
            field=models.BooleanField(
                default=False,
                help_text="Whether applied to advert milestone is completed",
                verbose_name="Advert Completed",
            ),
        ),
    ]
