# Generated by Django 6.0.3 on 2026-03-31 08:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("planning", "0016_alter_workpackage_applied_to_advert_completed"),
    ]

    operations = [
        migrations.AddField(
            model_name="workpackage",
            name="close_out_completed",
            field=models.BooleanField(
                default=False,
                help_text="Whether close out phase is completed",
                verbose_name="Close Out Completed",
            ),
        ),
        migrations.AddField(
            model_name="workpackage",
            name="close_out_end_date",
            field=models.DateField(
                blank=True, help_text="Close Out phase end date", null=True
            ),
        ),
        migrations.AddField(
            model_name="workpackage",
            name="close_out_start_date",
            field=models.DateField(
                blank=True, help_text="Close Out phase start date", null=True
            ),
        ),
        migrations.AddField(
            model_name="workpackage",
            name="pbs_attachment",
            field=models.FileField(
                blank=True,
                help_text="Package Breakdown Structure document",
                null=True,
                upload_to="planning/pbs/%Y/%m/",
            ),
        ),
        migrations.AddField(
            model_name="workpackage",
            name="pbs_end_date",
            field=models.DateField(
                blank=True,
                help_text="Package Breakdown Structure end date",
                null=True,
                verbose_name="PBS End Date",
            ),
        ),
        migrations.AddField(
            model_name="workpackage",
            name="pbs_start_date",
            field=models.DateField(
                blank=True,
                help_text="Package Breakdown Structure start date",
                null=True,
                verbose_name="PBS Start Date",
            ),
        ),
    ]
