# Generated by Django 5.2.12 on 2026-06-25 09:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("planning", "0017_workpackage_close_out_completed_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="designcategory",
            name="stage",
            field=models.CharField(
                choices=[
                    ("DESIGN_CRITERIA", "Design Criteria"),
                    ("DRAWINGS", "Drawings"),
                    ("DOCUMENTS", "Documents"),
                ],
                default="DESIGN_CRITERIA",
                help_text="Current design stage",
                max_length=30,
                verbose_name="Document",
            ),
        ),
        migrations.AlterField(
            model_name="designdiscipline",
            name="stage",
            field=models.CharField(
                choices=[
                    ("DESIGN_CRITERIA", "Design Criteria"),
                    ("DRAWINGS", "Drawings"),
                    ("DOCUMENTS", "Documents"),
                ],
                default="DESIGN_CRITERIA",
                help_text="Current design stage",
                max_length=30,
                verbose_name="Document",
            ),
        ),
        migrations.AlterField(
            model_name="designgroup",
            name="stage",
            field=models.CharField(
                choices=[
                    ("DESIGN_CRITERIA", "Design Criteria"),
                    ("DRAWINGS", "Drawings"),
                    ("DOCUMENTS", "Documents"),
                ],
                default="DESIGN_CRITERIA",
                help_text="Current design stage",
                max_length=30,
                verbose_name="Document",
            ),
        ),
        migrations.AlterField(
            model_name="designsubcategory",
            name="stage",
            field=models.CharField(
                choices=[
                    ("DESIGN_CRITERIA", "Design Criteria"),
                    ("DRAWINGS", "Drawings"),
                    ("DOCUMENTS", "Documents"),
                ],
                default="DESIGN_CRITERIA",
                help_text="Current design stage",
                max_length=30,
                verbose_name="Document",
            ),
        ),
    ]
