from django.urls import path

from . import views

urlpatterns = [
    path(
        "<int:project_pk>/dashboard/",
        views.ProductionDashboardView.as_view(),
        name="production-dashboard",
    ),
    path(
        "<int:project_pk>/planning/",
        views.ProductionPlanListView.as_view(),
        name="production-planning",
    ),
    path(
        "<int:project_pk>/planning/gantt/",
        views.ProductionPlanGanttView.as_view(),
        name="production-planning-gantt",
    ),
    path(
        "<int:project_pk>/planning/create/",
        views.ProductionPlanCreateView.as_view(),
        name="production-plan-create",
    ),
    path(
        "<int:project_pk>/planning/autofill/",
        views.ProductionPlanAutofillView.as_view(),
        name="production-plan-autofill",
    ),
    path(
        "<int:project_pk>/cost-breakdown/",
        views.ProductionCostBreakdownView.as_view(),
        name="production-cost-breakdown",
    ),
    path(
        "<int:project_pk>/cost-breakdown/<int:plan_pk>/",
        views.ProductionCostBreakdownDetailView.as_view(),
        name="production-cost-breakdown-detail",
    ),
    path(
        "<int:project_pk>/plan/<int:pk>/",
        views.ProductionPlanDetailView.as_view(),
        name="production-plan-detail",
    ),
    path(
        "<int:project_pk>/plan/<int:pk>/edit/",
        views.ProductionPlanUpdateView.as_view(),
        name="production-plan-edit",
    ),
    path(
        "<int:project_pk>/plan/<int:pk>/delete/",
        views.ProductionPlanDeleteView.as_view(),
        name="production-plan-delete",
    ),
    path(
        "<int:project_pk>/logs/",
        views.ProductivityLogsView.as_view(),
        name="production-list",
    ),
    path(
        "<int:project_pk>/tracking/",
        views.ProgressTrackingView.as_view(),
        name="production-tracking",
    ),
    path(
        "<int:project_pk>/resource/add/",
        views.ProductionResourceCreateView.as_view(),
        name="production-resource-add",
    ),
    path(
        "<int:project_pk>/progress-dashboard/",
        views.ProductionProgressDashboardView.as_view(),
        name="production-progress-dashboard",
    ),
    path(
        "<int:project_pk>/activity/<int:pk>/",
        views.ProductionActivityDetailView.as_view(),
        name="activity-detail",
    ),
    path(
        "<int:project_pk>/plan-productivity-dashboard/",
        views.PlanProductivityDashboardView.as_view(),
        name="plan-productivity-dashboard",
    ),
    path(
        "<int:project_pk>/forecast-dashboard/",
        views.ProductionForecastDashboardView.as_view(),
        name="production-forecast-dashboard",
    ),
    path(
        "<int:project_pk>/cashflow-forecast/",
        views.ProductionCashflowForecastView.as_view(),
        name="production-cashflow-forecast",
    ),
    path(
        "<int:project_pk>/performance-report/",
        views.ProductionPerformanceReportView.as_view(),
        name="performance-report",
    ),
    path(
        "<int:project_pk>/productivity-report/",
        views.ProductionProductivityReportView.as_view(),
        name="productivity-report",
    ),
    path(
        "<int:project_pk>/plan/<int:pk>/data/",
        views.ProductionPlanAjaxDetailView.as_view(),
        name="production-plan-data-ajax",
    ),
    path(
        "<int:project_pk>/ajax/bills/",
        views.GetProjectBillsAjaxView.as_view(),
        name="ajax-project-bills",
    ),
    path(
        "<int:project_pk>/ajax/items/",
        views.GetProjectItemsAjaxView.as_view(),
        name="ajax-project-items",
    ),
    path(
        "<int:project_pk>/ajax/labor-activities/",
        views.GetProjectLaborActivitiesAjaxView.as_view(),
        name="ajax-project-labor-activities",
    ),
    path(
        "<int:project_pk>/labor-activities/",
        views.LaborActivityListView.as_view(),
        name="labor-activity-list",
    ),
    path(
        "<int:project_pk>/labor-activities/detail/",
        views.LaborActivityDetailView.as_view(),
        name="labor-activity-detail",
    ),
    # Daily Log URLs
    path(
        "<int:project_pk>/daily-logs/",
        views.ProductionDailyLogListView.as_view(),
        name="production-daily-log-list",
    ),
    path(
        "<int:project_pk>/daily-logs/add/",
        views.ProductionDailyLogCreateView.as_view(),
        name="production-daily-log-create",
    ),
    path(
        "<int:project_pk>/daily-logs/<int:pk>/",
        views.ProductionDailyLogDetailView.as_view(),
        name="production-daily-log-detail",
    ),
    path(
        "<int:project_pk>/daily-logs/<int:pk>/edit/",
        views.ProductionDailyLogUpdateView.as_view(),
        name="production-daily-log-edit",
    ),
    path(
        "<int:project_pk>/daily-logs/<int:pk>/delete/",
        views.ProductionDailyLogDeleteView.as_view(),
        name="production-daily-log-delete",
    ),
    path(
        "<int:project_pk>/daily-logs/entry/<int:pk>/edit/",
        views.DailyActivityEntryUpdateView.as_view(),
        name="production-daily-log-entry-edit",
    ),
    path(
        "<int:project_pk>/ajax/daily-log-activity-data/",
        views.DailyLogActivityDataAjaxView.as_view(),
        name="ajax-daily-log-activity-data",
    ),
    path(
        "<int:project_pk>/plan/<int:pk>/refresh/",
        views.ProductionPlanRefreshAjaxView.as_view(),
        name="production-plan-refresh-ajax",
    ),
]
