from django.urls import path

from . import views

app_name = "estimator"

urlpatterns = [
    path("project/<int:project_pk>/", views.DashboardView.as_view(), name="dashboard"),
    path(
        "project/<int:project_pk>/assumptions/",
        views.ProjectAssumptionsView.as_view(),
        name="project_assumptions",
    ),
    path(
        "project/<int:project_pk>/assumptions/apply/",
        views.ApplyAssumptionsView.as_view(),
        name="apply_assumptions",
    ),
    path(
        "project/<int:project_pk>/baseline/",
        views.BaselineBoqView.as_view(),
        name="baseline",
    ),
    path(
        "project/<int:project_pk>/sync/", views.SyncBoqView.as_view(), name="sync_boq"
    ),
    path(
        "project/<int:project_pk>/initialize/",
        views.InitializeEstimatorView.as_view(),
        name="initialize_estimator",
    ),
    # Material Specs (simple definition)
    path(
        "project/<int:project_pk>/material-specs/",
        views.MaterialSpecListView.as_view(),
        name="material_specs",
    ),
    path(
        "project/<int:project_pk>/material-specs/upload/",
        views.MaterialSpecUploadView.as_view(),
        name="material_spec_upload",
    ),
    path(
        "project/<int:project_pk>/material-specs/download-template/",
        views.DownloadMaterialSpecTemplateView.as_view(),
        name="download_material_spec_template",
    ),
    # Material Estimator (calculator)
    path(
        "project/<int:project_pk>/specifications/",
        views.SpecificationListView.as_view(),
        name="specifications",
    ),
    # Material Costs
    path(
        "project/<int:project_pk>/materials/",
        views.MaterialsListView.as_view(),
        name="materials",
    ),
    path(
        "project/<int:project_pk>/materials/upload/",
        views.MaterialCostUploadView.as_view(),
        name="material_cost_upload",
    ),
    path(
        "project/<int:project_pk>/materials/download-template/",
        views.DownloadMaterialCostTemplateView.as_view(),
        name="download_material_cost_template",
    ),
    # Labour Specs (simple definition)
    path(
        "project/<int:project_pk>/labour-spec-defs/",
        views.LabourSpecDefListView.as_view(),
        name="labour_spec_defs",
    ),
    path(
        "project/<int:project_pk>/labour-spec-defs/upload/",
        views.LabourSpecUploadView.as_view(),
        name="labour_spec_upload",
    ),
    path(
        "project/<int:project_pk>/labour-spec-defs/download-template/",
        views.DownloadLabourSpecTemplateView.as_view(),
        name="download_labour_spec_template",
    ),
    # Labour Estimator (calculator — previously "Labour Specs")
    path(
        "project/<int:project_pk>/labour-specs/",
        views.LabourSpecificationListView.as_view(),
        name="labour_specs",
    ),
    # Labour Costs
    path(
        "project/<int:project_pk>/labour-costs/",
        views.LabourCostListView.as_view(),
        name="labour_costs",
    ),
    path(
        "project/<int:project_pk>/labour-costs/upload/",
        views.LabourCostUploadView.as_view(),
        name="labour_cost_upload",
    ),
    path(
        "project/<int:project_pk>/labour-costs/download-template/",
        views.DownloadLabourCostTemplateView.as_view(),
        name="download_labour_cost_template",
    ),
    # Trade Codes
    path(
        "project/<int:project_pk>/trade-codes/",
        views.TradeCodeListView.as_view(),
        name="trade_codes",
    ),
    path(
        "project/<int:project_pk>/trade-codes/upload/",
        views.TradeCodeUploadView.as_view(),
        name="trade_code_upload",
    ),
    path(
        "project/<int:project_pk>/trade-codes/download-template/",
        views.DownloadTradeCodeTemplateView.as_view(),
        name="download_trade_code_template",
    ),
    # Plant Costs
    path(
        "project/<int:project_pk>/plant-costs/",
        views.PlantCostListView.as_view(),
        name="plant_costs",
    ),
    path(
        "project/<int:project_pk>/plant-costs/upload/",
        views.PlantCostUploadView.as_view(),
        name="plant_cost_upload",
    ),
    path(
        "project/<int:project_pk>/plant-costs/download-template/",
        views.DownloadPlantCostTemplateView.as_view(),
        name="download_plant_cost_template",
    ),
    # Plant Specs (simple definition)
    path(
        "project/<int:project_pk>/plant-spec-defs/",
        views.PlantSpecDefListView.as_view(),
        name="plant_spec_defs",
    ),
    path(
        "project/<int:project_pk>/plant-spec-defs/upload/",
        views.PlantSpecUploadView.as_view(),
        name="plant_spec_upload",
    ),
    path(
        "project/<int:project_pk>/plant-spec-defs/download-template/",
        views.DownloadPlantSpecTemplateView.as_view(),
        name="download_plant_spec_template",
    ),
    # Preliminary Costs
    path(
        "project/<int:project_pk>/preliminary-costs/",
        views.PreliminaryCostListView.as_view(),
        name="preliminary_costs",
    ),
    path(
        "project/<int:project_pk>/preliminary-costs/upload/",
        views.PreliminaryCostUploadView.as_view(),
        name="preliminary_cost_upload",
    ),
    path(
        "project/<int:project_pk>/preliminary-costs/download-template/",
        views.DownloadPreliminaryCostTemplateView.as_view(),
        name="download_preliminary_cost_template",
    ),
    # Preliminary Specs (simple definition)
    path(
        "project/<int:project_pk>/preliminary-spec-defs/",
        views.PreliminarySpecDefListView.as_view(),
        name="preliminary_spec_defs",
    ),
    path(
        "project/<int:project_pk>/preliminary-spec-defs/upload/",
        views.PreliminarySpecUploadView.as_view(),
        name="preliminary_spec_upload",
    ),
    path(
        "project/<int:project_pk>/preliminary-spec-defs/download-template/",
        views.DownloadPreliminarySpecTemplateView.as_view(),
        name="download_preliminary_spec_template",
    ),
    path(
        "project/<int:project_pk>/import/",
        views.ExcelImportView.as_view(),
        name="import_excel",
    ),
    # Item Library
    path(
        "project/<int:project_pk>/item-library/",
        views.ItemLibraryListView.as_view(),
        name="item_library",
    ),
    path(
        "project/<int:project_pk>/item-library/upload/",
        views.ItemLibraryUploadView.as_view(),
        name="item_library_upload",
    ),
    path(
        "project/<int:project_pk>/item-library/download-template/",
        views.DownloadItemLibraryTemplateView.as_view(),
        name="download_item_library_template",
    ),
    path(
        "project/<int:project_pk>/item-library/create/",
        views.CreateItemLibraryEntryView.as_view(),
        name="item_library_create",
    ),
    path(
        "project/<int:project_pk>/item-library/<int:pk>/delete/",
        views.DeleteItemLibraryEntryView.as_view(),
        name="item_library_delete",
    ),
    path(
        "project/<int:project_pk>/item-library/reorder/",
        views.ReorderItemLibraryEntriesView.as_view(),
        name="item_library_reorder",
    ),
    path(
        "project/<int:project_pk>/item-library/bulk-delete/",
        views.BulkDeleteItemLibraryEntriesView.as_view(),
        name="item_library_bulk_delete",
    ),
    path(
        "project/<int:project_pk>/api/item-library/<int:pk>/update/",
        views.UpdateItemLibraryEntryView.as_view(),
        name="update_item_library_entry",
    ),
    path(
        "project/<int:project_pk>/boq/autofill-from-library/",
        views.AutofillBoqFromLibraryView.as_view(),
        name="autofill_boq_from_library",
    ),
    path(
        "project/<int:project_pk>/api/boq-item/<int:pk>/save-to-library/",
        views.SaveBoqRowToLibraryView.as_view(),
        name="save_boq_row_to_library",
    ),
    path(
        "project/<int:project_pk>/api/boq-item/<int:pk>/apply-library-entry/",
        views.ApplyLibraryEntryToBoqView.as_view(),
        name="apply_library_entry_to_boq",
    ),
    # System specs
    path(
        "project/<int:project_pk>/system-specs/",
        views.SystemMaterialSpecListView.as_view(),
        name="system_specs",
    ),
    path(
        "project/<int:project_pk>/system-specs/upload/",
        views.SystemSpecUploadView.as_view(),
        name="system_spec_upload",
    ),
    path(
        "project/<int:project_pk>/system-specs/download-template/",
        views.DownloadSystemSpecTemplateView.as_view(),
        name="download_system_spec_template",
    ),
    # AJAX
    path(
        "project/<int:project_pk>/api/boq-item/<int:pk>/update/",
        views.UpdateBoqItemView.as_view(),
        name="update_boq_item",
    ),
    path(
        "project/<int:project_pk>/api/material/<int:pk>/update/",
        views.UpdateMaterialView.as_view(),
        name="update_material",
    ),
    path(
        "project/<int:project_pk>/api/spec-component/<int:pk>/update/",
        views.UpdateSpecComponentView.as_view(),
        name="update_spec_component",
    ),
    path(
        "project/<int:project_pk>/api/spec/<int:pk>/components/add/",
        views.AddSpecComponentView.as_view(),
        name="add_spec_component",
    ),
    path(
        "project/<int:project_pk>/api/spec-component/<int:pk>/delete/",
        views.DeleteSpecComponentView.as_view(),
        name="delete_spec_component",
    ),
    path(
        "project/<int:project_pk>/api/spec/<int:pk>/delete/",
        views.DeleteSpecificationView.as_view(),
        name="delete_specification",
    ),
    path(
        "project/<int:project_pk>/api/spec/<int:pk>/update/",
        views.UpdateSpecificationView.as_view(),
        name="update_specification",
    ),
    path(
        "project/<int:project_pk>/api/labour-spec/<int:pk>/update/",
        views.UpdateLabourSpecView.as_view(),
        name="update_labour_spec",
    ),
    path(
        "project/<int:project_pk>/api/labour-crew/<int:pk>/update/",
        views.UpdateLabourCrewView.as_view(),
        name="update_labour_crew",
    ),
    path(
        "project/<int:project_pk>/api/system-spec-component/<int:pk>/update/",
        views.UpdateSystemSpecComponentView.as_view(),
        name="update_system_spec_component",
    ),
    path(
        "project/<int:project_pk>/api/plant-cost/<int:pk>/update/",
        views.UpdatePlantCostView.as_view(),
        name="update_plant_cost",
    ),
    path(
        "project/<int:project_pk>/api/plant-spec/<int:pk>/update/",
        views.UpdatePlantSpecView.as_view(),
        name="update_plant_spec",
    ),
    path(
        "project/<int:project_pk>/api/plant-spec/<int:pk>/components/add/",
        views.AddPlantSpecComponentView.as_view(),
        name="add_plant_spec_component",
    ),
    path(
        "project/<int:project_pk>/api/plant-spec-component/<int:pk>/update/",
        views.UpdatePlantSpecComponentView.as_view(),
        name="update_plant_spec_component",
    ),
    path(
        "project/<int:project_pk>/api/plant-spec-component/<int:pk>/delete/",
        views.DeletePlantSpecComponentView.as_view(),
        name="delete_plant_spec_component",
    ),
    path(
        "project/<int:project_pk>/api/plant-spec/<int:pk>/delete/",
        views.DeletePlantSpecificationView.as_view(),
        name="delete_plant_specification",
    ),
    path(
        "project/<int:project_pk>/api/preliminary-cost/<int:pk>/update/",
        views.UpdatePreliminaryCostView.as_view(),
        name="update_preliminary_cost",
    ),
    path(
        "project/<int:project_pk>/api/preliminary-spec/<int:pk>/update/",
        views.UpdatePreliminarySpecView.as_view(),
        name="update_preliminary_spec",
    ),
    path(
        "project/<int:project_pk>/api/bulk-markup/",
        views.BulkMarkupUpdateView.as_view(),
        name="bulk_markup_update",
    ),
    path(
        "project/<int:project_pk>/api/bulk-boq-specs/",
        views.BulkUpdateBoqSpecsView.as_view(),
        name="bulk_boq_specs_update",
    ),
    # Reports
    path(
        "project/<int:project_pk>/reports/",
        views.ReportsIndexView.as_view(),
        name="reports_index",
    ),
    path(
        "project/<int:project_pk>/reports/baseline-assessment/",
        views.PricedBoqReportView.as_view(),
        kwargs={"report_type": "baseline_assessment"},
        name="report_baseline_assessment",
    ),
    path(
        "project/<int:project_pk>/reports/progress-assessment/",
        views.PricedBoqReportView.as_view(),
        kwargs={"report_type": "progress_assessment"},
        name="report_progress_assessment",
    ),
    path(
        "project/<int:project_pk>/reports/forecast-assessment/",
        views.PricedBoqReportView.as_view(),
        kwargs={"report_type": "forecast_assessment"},
        name="report_forecast_assessment",
    ),
    path(
        "project/<int:project_pk>/reports/key-rates-assessment/",
        views.PricedBoqReportView.as_view(),
        kwargs={"report_type": "key_rates_assessment"},
        name="report_key_rates_assessment",
    ),
    path(
        "project/<int:project_pk>/reports/material-list-baseline/",
        views.MaterialListReportView.as_view(),
        kwargs={"variant": "baseline"},
        name="report_material_list_baseline",
    ),
    path(
        "project/<int:project_pk>/reports/material-list-progress/",
        views.MaterialListReportView.as_view(),
        kwargs={"variant": "progress"},
        name="report_material_list_progress",
    ),
    path(
        "project/<int:project_pk>/reports/material-list-forecast/",
        views.MaterialListReportView.as_view(),
        kwargs={"variant": "forecast"},
        name="report_material_list_forecast",
    ),
    path(
        "project/<int:project_pk>/reports/labour-list-baseline/",
        views.LabourListReportView.as_view(),
        kwargs={"variant": "baseline"},
        name="report_labour_list_baseline",
    ),
    path(
        "project/<int:project_pk>/reports/labour-list-progress/",
        views.LabourListReportView.as_view(),
        kwargs={"variant": "progress"},
        name="report_labour_list_progress",
    ),
    path(
        "project/<int:project_pk>/reports/labour-list-forecast/",
        views.LabourListReportView.as_view(),
        kwargs={"variant": "forecast"},
        name="report_labour_list_forecast",
    ),
    # Baseline Estimator (contract-rate) reports
    path(
        "project/<int:project_pk>/reports/material-list-baseline/contract/",
        views.MaterialListReportView.as_view(),
        kwargs={"variant": "baseline", "rate_type": "contract"},
        name="report_material_list_baseline_contract",
    ),
    path(
        "project/<int:project_pk>/reports/material-list-progress/contract/",
        views.MaterialListReportView.as_view(),
        kwargs={"variant": "progress", "rate_type": "contract"},
        name="report_material_list_progress_contract",
    ),
    path(
        "project/<int:project_pk>/reports/material-list-forecast/contract/",
        views.MaterialListReportView.as_view(),
        kwargs={"variant": "forecast", "rate_type": "contract"},
        name="report_material_list_forecast_contract",
    ),
    path(
        "project/<int:project_pk>/reports/labour-list-baseline/contract/",
        views.LabourListReportView.as_view(),
        kwargs={"variant": "baseline", "rate_type": "contract"},
        name="report_labour_list_baseline_contract",
    ),
    path(
        "project/<int:project_pk>/reports/labour-list-progress/contract/",
        views.LabourListReportView.as_view(),
        kwargs={"variant": "progress", "rate_type": "contract"},
        name="report_labour_list_progress_contract",
    ),
    path(
        "project/<int:project_pk>/reports/labour-list-forecast/contract/",
        views.LabourListReportView.as_view(),
        kwargs={"variant": "forecast", "rate_type": "contract"},
        name="report_labour_list_forecast_contract",
    ),
    # Plant Estimator (calculator)
    path(
        "project/<int:project_pk>/plant-specs/",
        views.PlantSpecificationListView.as_view(),
        name="plant_specs",
    ),
    # Prelim Estimator (calculator)
    path(
        "project/<int:project_pk>/prelim-specs/",
        views.PreliminarySpecificationListView.as_view(),
        name="prelim_specs",
    ),
    # Plant reports — new rates
    path(
        "project/<int:project_pk>/reports/plant-list-baseline/",
        views.PlantListReportView.as_view(),
        kwargs={"variant": "baseline"},
        name="report_plant_list_baseline",
    ),
    path(
        "project/<int:project_pk>/reports/plant-list-progress/",
        views.PlantListReportView.as_view(),
        kwargs={"variant": "progress"},
        name="report_plant_list_progress",
    ),
    path(
        "project/<int:project_pk>/reports/plant-list-forecast/",
        views.PlantListReportView.as_view(),
        kwargs={"variant": "forecast"},
        name="report_plant_list_forecast",
    ),
    # Plant reports — contract rates (Baseline Estimator)
    path(
        "project/<int:project_pk>/reports/plant-list-baseline/contract/",
        views.PlantListReportView.as_view(),
        kwargs={"variant": "baseline", "rate_type": "contract"},
        name="report_plant_list_baseline_contract",
    ),
    path(
        "project/<int:project_pk>/reports/plant-list-progress/contract/",
        views.PlantListReportView.as_view(),
        kwargs={"variant": "progress", "rate_type": "contract"},
        name="report_plant_list_progress_contract",
    ),
    path(
        "project/<int:project_pk>/reports/plant-list-forecast/contract/",
        views.PlantListReportView.as_view(),
        kwargs={"variant": "forecast", "rate_type": "contract"},
        name="report_plant_list_forecast_contract",
    ),
    # Prelim reports — new rates
    path(
        "project/<int:project_pk>/reports/prelim-list-baseline/",
        views.PreliminaryListReportView.as_view(),
        kwargs={"variant": "baseline"},
        name="report_prelim_list_baseline",
    ),
    path(
        "project/<int:project_pk>/reports/prelim-list-progress/",
        views.PreliminaryListReportView.as_view(),
        kwargs={"variant": "progress"},
        name="report_prelim_list_progress",
    ),
    path(
        "project/<int:project_pk>/reports/prelim-list-forecast/",
        views.PreliminaryListReportView.as_view(),
        kwargs={"variant": "forecast"},
        name="report_prelim_list_forecast",
    ),
    # Prelim reports — contract rates (Baseline Estimator)
    path(
        "project/<int:project_pk>/reports/prelim-list-baseline/contract/",
        views.PreliminaryListReportView.as_view(),
        kwargs={"variant": "baseline", "rate_type": "contract"},
        name="report_prelim_list_baseline_contract",
    ),
    path(
        "project/<int:project_pk>/reports/prelim-list-progress/contract/",
        views.PreliminaryListReportView.as_view(),
        kwargs={"variant": "progress", "rate_type": "contract"},
        name="report_prelim_list_progress_contract",
    ),
    path(
        "project/<int:project_pk>/reports/prelim-list-forecast/contract/",
        views.PreliminaryListReportView.as_view(),
        kwargs={"variant": "forecast", "rate_type": "contract"},
        name="report_prelim_list_forecast_contract",
    ),
    # ── Component / Skill aggregated reports (project-wide rollups) ──
    path(
        "project/<int:project_pk>/reports/material-components-baseline/",
        views.MaterialComponentReportView.as_view(),
        kwargs={"variant": "baseline"},
        name="report_material_components_baseline",
    ),
    path(
        "project/<int:project_pk>/reports/material-components-progress/",
        views.MaterialComponentReportView.as_view(),
        kwargs={"variant": "progress"},
        name="report_material_components_progress",
    ),
    path(
        "project/<int:project_pk>/reports/material-components-forecast/",
        views.MaterialComponentReportView.as_view(),
        kwargs={"variant": "forecast"},
        name="report_material_components_forecast",
    ),
    path(
        "project/<int:project_pk>/reports/labour-skills-baseline/",
        views.LabourSkillReportView.as_view(),
        kwargs={"variant": "baseline"},
        name="report_labour_skills_baseline",
    ),
    path(
        "project/<int:project_pk>/reports/labour-skills-progress/",
        views.LabourSkillReportView.as_view(),
        kwargs={"variant": "progress"},
        name="report_labour_skills_progress",
    ),
    path(
        "project/<int:project_pk>/reports/labour-skills-forecast/",
        views.LabourSkillReportView.as_view(),
        kwargs={"variant": "forecast"},
        name="report_labour_skills_forecast",
    ),
    path(
        "project/<int:project_pk>/reports/plant-components-baseline/",
        views.PlantComponentReportView.as_view(),
        kwargs={"variant": "baseline"},
        name="report_plant_components_baseline",
    ),
    path(
        "project/<int:project_pk>/reports/plant-components-progress/",
        views.PlantComponentReportView.as_view(),
        kwargs={"variant": "progress"},
        name="report_plant_components_progress",
    ),
    path(
        "project/<int:project_pk>/reports/plant-components-forecast/",
        views.PlantComponentReportView.as_view(),
        kwargs={"variant": "forecast"},
        name="report_plant_components_forecast",
    ),
    # ── System Library ────────────────────────────────────────────
    path("system/", views.SystemTradeCodeListView.as_view(), name="sys_trade_codes"),
    # System Trade Codes
    path(
        "system/trade-codes/",
        views.SystemTradeCodeListView.as_view(),
        name="sys_trade_codes",
    ),
    path(
        "system/trade-codes/upload/",
        views.SystemTradeCodeUploadView.as_view(),
        name="sys_trade_code_upload",
    ),
    path(
        "system/trade-codes/download-template/",
        views.DownloadSystemTradeCodeTemplateView.as_view(),
        name="sys_download_trade_code_template",
    ),
    # System Municipalities
    path(
        "system/municipalities/",
        views.SystemMunicipalityListView.as_view(),
        name="sys_municipalities",
    ),
    path(
        "system/municipalities/upload/",
        views.SystemMunicipalityUploadView.as_view(),
        name="sys_municipality_upload",
    ),
    path(
        "system/municipalities/download-template/",
        views.DownloadSystemMunicipalityTemplateView.as_view(),
        name="sys_download_municipality_template",
    ),
    # System Materials
    path(
        "system/materials/",
        views.SystemMaterialListView.as_view(),
        name="sys_materials",
    ),
    path(
        "system/materials/upload/",
        views.SystemMaterialUploadView.as_view(),
        name="sys_material_upload",
    ),
    path(
        "system/materials/download-template/",
        views.DownloadSystemMaterialTemplateView.as_view(),
        name="sys_download_material_template",
    ),
    # System Material Specs
    path(
        "system/material-specs/",
        views.SysMaterialSpecListView.as_view(),
        name="sys_material_specs",
    ),
    path(
        "system/material-specs/upload/",
        views.SystemMaterialSpecUploadView.as_view(),
        name="sys_material_spec_upload",
    ),
    path(
        "system/material-specs/download-template/",
        views.DownloadSystemMaterialSpecTemplateView.as_view(),
        name="sys_download_material_spec_template",
    ),
    # System Labour Crews
    path(
        "system/labour-crews/",
        views.SystemLabourCrewListView.as_view(),
        name="sys_labour_crews",
    ),
    path(
        "system/labour-crews/upload/",
        views.SystemLabourCrewUploadView.as_view(),
        name="sys_labour_crew_upload",
    ),
    path(
        "system/labour-crews/download-template/",
        views.DownloadSystemLabourCrewTemplateView.as_view(),
        name="sys_download_labour_crew_template",
    ),
    # System Labour Specs
    path(
        "system/labour-specs/",
        views.SystemLabourSpecListView.as_view(),
        name="sys_labour_specs",
    ),
    path(
        "system/labour-specs/upload/",
        views.SystemLabourSpecUploadView.as_view(),
        name="sys_labour_spec_upload",
    ),
    path(
        "system/labour-specs/download-template/",
        views.DownloadSystemLabourSpecTemplateView.as_view(),
        name="sys_download_labour_spec_template",
    ),
    # System AJAX
    path(
        "system/api/material/<int:pk>/update/",
        views.UpdateSystemMaterialView.as_view(),
        name="sys_update_material",
    ),
    path(
        "system/api/spec-component/<int:pk>/update/",
        views.UpdateSysSpecComponentView.as_view(),
        name="sys_update_spec_component",
    ),
    path(
        "system/api/spec/<int:pk>/components/add/",
        views.AddSysSpecComponentView.as_view(),
        name="sys_add_spec_component",
    ),
    path(
        "system/api/spec-component/<int:pk>/delete/",
        views.DeleteSysSpecComponentView.as_view(),
        name="sys_delete_spec_component",
    ),
    path(
        "system/api/spec/<int:pk>/delete/",
        views.DeleteSystemSpecificationView.as_view(),
        name="sys_delete_specification",
    ),
    path(
        "system/api/spec/<int:pk>/update/",
        views.UpdateSystemSpecificationView.as_view(),
        name="sys_update_specification",
    ),
    path(
        "system/api/labour-crew/<int:pk>/update/",
        views.UpdateSystemLabourCrewView.as_view(),
        name="sys_update_labour_crew",
    ),
    path(
        "system/api/labour-spec/<int:pk>/update/",
        views.UpdateSystemLabourSpecView.as_view(),
        name="sys_update_labour_spec",
    ),
    # System Plant Costs
    path(
        "system/plant-costs/",
        views.SystemPlantCostListView.as_view(),
        name="sys_plant_costs",
    ),
    path(
        "system/plant-costs/upload/",
        views.SystemPlantCostUploadView.as_view(),
        name="sys_plant_cost_upload",
    ),
    path(
        "system/plant-costs/download-template/",
        views.DownloadSystemPlantCostTemplateView.as_view(),
        name="sys_download_plant_cost_template",
    ),
    # System Plant Specs
    path(
        "system/plant-specs/",
        views.SystemPlantSpecListView.as_view(),
        name="sys_plant_specs",
    ),
    path(
        "system/plant-specs/upload/",
        views.SystemPlantSpecUploadView.as_view(),
        name="sys_plant_spec_upload",
    ),
    path(
        "system/plant-specs/download-template/",
        views.DownloadSystemPlantSpecTemplateView.as_view(),
        name="sys_download_plant_spec_template",
    ),
    # System Preliminary Costs
    path(
        "system/preliminary-costs/",
        views.SystemPreliminaryCostListView.as_view(),
        name="sys_preliminary_costs",
    ),
    path(
        "system/preliminary-costs/upload/",
        views.SystemPreliminaryCostUploadView.as_view(),
        name="sys_preliminary_cost_upload",
    ),
    path(
        "system/preliminary-costs/download-template/",
        views.DownloadSystemPreliminaryCostTemplateView.as_view(),
        name="sys_download_preliminary_cost_template",
    ),
    # System Preliminary Specs
    path(
        "system/preliminary-specs/",
        views.SystemPreliminarySpecListView.as_view(),
        name="sys_preliminary_specs",
    ),
    path(
        "system/preliminary-specs/upload/",
        views.SystemPreliminarySpecUploadView.as_view(),
        name="sys_preliminary_spec_upload",
    ),
    path(
        "system/preliminary-specs/download-template/",
        views.DownloadSystemPreliminarySpecTemplateView.as_view(),
        name="sys_download_preliminary_spec_template",
    ),
    # System AJAX (plant & preliminary)
    path(
        "system/api/plant-cost/<int:pk>/update/",
        views.UpdateSystemPlantCostView.as_view(),
        name="sys_update_plant_cost",
    ),
    path(
        "system/api/plant-spec/<int:pk>/update/",
        views.UpdateSystemPlantSpecView.as_view(),
        name="sys_update_plant_spec",
    ),
    path(
        "system/api/plant-spec/<int:pk>/components/add/",
        views.AddSystemPlantSpecComponentView.as_view(),
        name="sys_add_plant_spec_component",
    ),
    path(
        "system/api/plant-spec-component/<int:pk>/update/",
        views.UpdateSystemPlantSpecComponentView.as_view(),
        name="sys_update_plant_spec_component",
    ),
    path(
        "system/api/plant-spec-component/<int:pk>/delete/",
        views.DeleteSystemPlantSpecComponentView.as_view(),
        name="sys_delete_plant_spec_component",
    ),
    path(
        "system/api/plant-spec/<int:pk>/delete/",
        views.DeleteSystemPlantSpecificationView.as_view(),
        name="sys_delete_plant_specification",
    ),
    path(
        "system/api/preliminary-cost/<int:pk>/update/",
        views.UpdateSystemPreliminaryCostView.as_view(),
        name="sys_update_preliminary_cost",
    ),
    path(
        "system/api/preliminary-spec/<int:pk>/update/",
        views.UpdateSystemPreliminarySpecView.as_view(),
        name="sys_update_preliminary_spec",
    ),
    # System Item Library
    path(
        "system/item-library/",
        views.SystemItemLibraryListView.as_view(),
        name="sys_item_library",
    ),
    path(
        "system/item-library/upload/",
        views.SystemItemLibraryUploadView.as_view(),
        name="sys_item_library_upload",
    ),
    path(
        "system/item-library/download-template/",
        views.DownloadSystemItemLibraryTemplateView.as_view(),
        name="sys_download_item_library_template",
    ),
    path(
        "system/item-library/create/",
        views.CreateSystemItemLibraryEntryView.as_view(),
        name="sys_item_library_create",
    ),
    path(
        "system/item-library/<int:pk>/delete/",
        views.DeleteSystemItemLibraryEntryView.as_view(),
        name="sys_item_library_delete",
    ),
    path(
        "system/item-library/bulk-delete/",
        views.BulkDeleteSystemItemLibraryEntriesView.as_view(),
        name="sys_item_library_bulk_delete",
    ),
    path(
        "system/api/item-library/<int:pk>/update/",
        views.UpdateSystemItemLibraryEntryView.as_view(),
        name="sys_update_item_library_entry",
    ),
    # ── Contractor Library ────────────────────────────────────────
    path(
        "contractor/",
        views.ContractorTradeCodeListView.as_view(),
        name="ctr_trade_codes",
    ),
    # Contractor Trade Codes
    path(
        "contractor/trade-codes/",
        views.ContractorTradeCodeListView.as_view(),
        name="ctr_trade_codes",
    ),
    path(
        "contractor/trade-codes/upload/",
        views.ContractorTradeCodeUploadView.as_view(),
        name="ctr_trade_code_upload",
    ),
    path(
        "contractor/trade-codes/download-template/",
        views.DownloadContractorTradeCodeTemplateView.as_view(),
        name="ctr_download_trade_code_template",
    ),
    # Contractor Materials
    path(
        "contractor/materials/",
        views.ContractorMaterialListView.as_view(),
        name="ctr_materials",
    ),
    path(
        "contractor/materials/upload/",
        views.ContractorMaterialUploadView.as_view(),
        name="ctr_material_upload",
    ),
    path(
        "contractor/materials/download-template/",
        views.DownloadContractorMaterialTemplateView.as_view(),
        name="ctr_download_material_template",
    ),
    # Contractor Material Specs
    path(
        "contractor/material-specs/",
        views.ContractorMaterialSpecListView.as_view(),
        name="ctr_material_specs",
    ),
    path(
        "contractor/material-specs/upload/",
        views.ContractorMaterialSpecUploadView.as_view(),
        name="ctr_material_spec_upload",
    ),
    path(
        "contractor/material-specs/download-template/",
        views.DownloadContractorMaterialSpecTemplateView.as_view(),
        name="ctr_download_material_spec_template",
    ),
    # Contractor Labour Crews
    path(
        "contractor/labour-crews/",
        views.ContractorLabourCrewListView.as_view(),
        name="ctr_labour_crews",
    ),
    path(
        "contractor/labour-crews/upload/",
        views.ContractorLabourCrewUploadView.as_view(),
        name="ctr_labour_crew_upload",
    ),
    path(
        "contractor/labour-crews/download-template/",
        views.DownloadContractorLabourCrewTemplateView.as_view(),
        name="ctr_download_labour_crew_template",
    ),
    # Contractor Labour Specs
    path(
        "contractor/labour-specs/",
        views.ContractorLabourSpecListView.as_view(),
        name="ctr_labour_specs",
    ),
    path(
        "contractor/labour-specs/upload/",
        views.ContractorLabourSpecUploadView.as_view(),
        name="ctr_labour_spec_upload",
    ),
    path(
        "contractor/labour-specs/download-template/",
        views.DownloadContractorLabourSpecTemplateView.as_view(),
        name="ctr_download_labour_spec_template",
    ),
    # Contractor Plant Costs
    path(
        "contractor/plant-costs/",
        views.ContractorPlantCostListView.as_view(),
        name="ctr_plant_costs",
    ),
    path(
        "contractor/plant-costs/upload/",
        views.ContractorPlantCostUploadView.as_view(),
        name="ctr_plant_cost_upload",
    ),
    path(
        "contractor/plant-costs/download-template/",
        views.DownloadContractorPlantCostTemplateView.as_view(),
        name="ctr_download_plant_cost_template",
    ),
    # Contractor Plant Specs
    path(
        "contractor/plant-specs/",
        views.ContractorPlantSpecListView.as_view(),
        name="ctr_plant_specs",
    ),
    path(
        "contractor/plant-specs/upload/",
        views.ContractorPlantSpecUploadView.as_view(),
        name="ctr_plant_spec_upload",
    ),
    path(
        "contractor/plant-specs/download-template/",
        views.DownloadContractorPlantSpecTemplateView.as_view(),
        name="ctr_download_plant_spec_template",
    ),
    # Contractor Preliminary Costs
    path(
        "contractor/preliminary-costs/",
        views.ContractorPreliminaryCostListView.as_view(),
        name="ctr_preliminary_costs",
    ),
    path(
        "contractor/preliminary-costs/upload/",
        views.ContractorPreliminaryCostUploadView.as_view(),
        name="ctr_preliminary_cost_upload",
    ),
    path(
        "contractor/preliminary-costs/download-template/",
        views.DownloadContractorPreliminaryCostTemplateView.as_view(),
        name="ctr_download_preliminary_cost_template",
    ),
    # Contractor Preliminary Specs
    path(
        "contractor/preliminary-specs/",
        views.ContractorPreliminarySpecListView.as_view(),
        name="ctr_preliminary_specs",
    ),
    path(
        "contractor/preliminary-specs/upload/",
        views.ContractorPreliminarySpecUploadView.as_view(),
        name="ctr_preliminary_spec_upload",
    ),
    path(
        "contractor/preliminary-specs/download-template/",
        views.DownloadContractorPreliminarySpecTemplateView.as_view(),
        name="ctr_download_preliminary_spec_template",
    ),
    # Contractor AJAX (material & spec components)
    path(
        "contractor/api/material/<int:pk>/update/",
        views.UpdateContractorMaterialView.as_view(),
        name="ctr_update_material",
    ),
    path(
        "contractor/api/spec-component/<int:pk>/update/",
        views.UpdateCtrSpecComponentView.as_view(),
        name="ctr_update_spec_component",
    ),
    path(
        "contractor/api/spec/<int:pk>/components/add/",
        views.AddCtrSpecComponentView.as_view(),
        name="ctr_add_spec_component",
    ),
    path(
        "contractor/api/spec-component/<int:pk>/delete/",
        views.DeleteCtrSpecComponentView.as_view(),
        name="ctr_delete_spec_component",
    ),
    path(
        "contractor/api/spec/<int:pk>/delete/",
        views.DeleteContractorSpecificationView.as_view(),
        name="ctr_delete_specification",
    ),
    path(
        "contractor/api/spec/<int:pk>/update/",
        views.UpdateContractorSpecificationView.as_view(),
        name="ctr_update_specification",
    ),
    path(
        "contractor/api/labour-crew/<int:pk>/update/",
        views.UpdateContractorLabourCrewView.as_view(),
        name="ctr_update_labour_crew",
    ),
    path(
        "contractor/api/labour-spec/<int:pk>/update/",
        views.UpdateContractorLabourSpecView.as_view(),
        name="ctr_update_labour_spec",
    ),
    # Contractor AJAX (plant & preliminary)
    path(
        "contractor/api/plant-cost/<int:pk>/update/",
        views.UpdateContractorPlantCostView.as_view(),
        name="ctr_update_plant_cost",
    ),
    path(
        "contractor/api/plant-spec/<int:pk>/update/",
        views.UpdateContractorPlantSpecView.as_view(),
        name="ctr_update_plant_spec",
    ),
    path(
        "contractor/api/plant-spec/<int:pk>/components/add/",
        views.AddContractorPlantSpecComponentView.as_view(),
        name="ctr_add_plant_spec_component",
    ),
    path(
        "contractor/api/plant-spec-component/<int:pk>/update/",
        views.UpdateContractorPlantSpecComponentView.as_view(),
        name="ctr_update_plant_spec_component",
    ),
    path(
        "contractor/api/plant-spec-component/<int:pk>/delete/",
        views.DeleteContractorPlantSpecComponentView.as_view(),
        name="ctr_delete_plant_spec_component",
    ),
    path(
        "contractor/api/plant-spec/<int:pk>/delete/",
        views.DeleteContractorPlantSpecificationView.as_view(),
        name="ctr_delete_plant_specification",
    ),
    path(
        "contractor/api/preliminary-cost/<int:pk>/update/",
        views.UpdateContractorPreliminaryCostView.as_view(),
        name="ctr_update_preliminary_cost",
    ),
    path(
        "contractor/api/preliminary-spec/<int:pk>/update/",
        views.UpdateContractorPreliminarySpecView.as_view(),
        name="ctr_update_preliminary_spec",
    ),
    # Contractor Item Library
    path(
        "contractor/item-library/",
        views.ContractorItemLibraryListView.as_view(),
        name="ctr_item_library",
    ),
    path(
        "contractor/item-library/upload/",
        views.ContractorItemLibraryUploadView.as_view(),
        name="ctr_item_library_upload",
    ),
    path(
        "contractor/item-library/download-template/",
        views.DownloadContractorItemLibraryTemplateView.as_view(),
        name="ctr_download_item_library_template",
    ),
    path(
        "contractor/item-library/create/",
        views.CreateContractorItemLibraryEntryView.as_view(),
        name="ctr_item_library_create",
    ),
    path(
        "contractor/item-library/<int:pk>/delete/",
        views.DeleteContractorItemLibraryEntryView.as_view(),
        name="ctr_item_library_delete",
    ),
    path(
        "contractor/item-library/bulk-delete/",
        views.BulkDeleteContractorItemLibraryEntriesView.as_view(),
        name="ctr_item_library_bulk_delete",
    ),
    path(
        "contractor/api/item-library/<int:pk>/update/",
        views.UpdateContractorItemLibraryEntryView.as_view(),
        name="ctr_update_item_library_entry",
    ),
]
