# Generated by Django 6.0.2 on 2026-02-25 19:36

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("Project", "0040_alter_project_end_date_alter_project_start_date"),
    ]

    operations = [
        migrations.CreateModel(
            name="DailyDiary",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When this record was created"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="When this record was last modified"
                    ),
                ),
                (
                    "deleted",
                    models.BooleanField(default=False, help_text="Soft delete flag"),
                ),
                ("date", models.DateField(help_text="Date of diary entry")),
                (
                    "weather",
                    models.CharField(help_text="Weather conditions", max_length=100),
                ),
                (
                    "work_activities",
                    models.TextField(help_text="Work activities performed"),
                ),
                ("visitors", models.TextField(blank=True, help_text="Site visitors")),
                (
                    "issues_delays",
                    models.TextField(
                        blank=True, help_text="Issues or delays encountered"
                    ),
                ),
                (
                    "site_instructions",
                    models.TextField(blank=True, help_text="Site instructions given"),
                ),
                (
                    "remarks",
                    models.TextField(blank=True, help_text="Additional remarks"),
                ),
                (
                    "project",
                    models.ForeignKey(
                        help_text="Project this diary entry belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="daily_diaries",
                        to="Project.project",
                    ),
                ),
            ],
            options={
                "verbose_name": "Daily Diary",
                "verbose_name_plural": "Daily Diaries",
                "ordering": ["-date", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="DelayLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When this record was created"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="When this record was last modified"
                    ),
                ),
                (
                    "deleted",
                    models.BooleanField(default=False, help_text="Soft delete flag"),
                ),
                ("date", models.DateField(help_text="Date of delay")),
                (
                    "delay_description",
                    models.TextField(help_text="Description of the delay"),
                ),
                ("cause", models.TextField(help_text="Cause of the delay")),
                ("impact", models.TextField(help_text="Impact of the delay")),
                ("duration", models.PositiveIntegerField(help_text="Duration in days")),
                (
                    "claim_status",
                    models.CharField(
                        choices=[
                            ("NOT_CLAIMED", "Not Claimed"),
                            ("PENDING", "Pending"),
                            ("APPROVED", "Approved"),
                            ("REJECTED", "Rejected"),
                        ],
                        default="NOT_CLAIMED",
                        help_text="Claim status",
                        max_length=20,
                    ),
                ),
                (
                    "remarks",
                    models.TextField(blank=True, help_text="Additional remarks"),
                ),
                (
                    "project",
                    models.ForeignKey(
                        help_text="Project this delay log belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="delay_logs",
                        to="Project.project",
                    ),
                ),
            ],
            options={
                "verbose_name": "Delay Log",
                "verbose_name_plural": "Delay Logs",
                "ordering": ["-date", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="DeliveryTracker",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When this record was created"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="When this record was last modified"
                    ),
                ),
                (
                    "deleted",
                    models.BooleanField(default=False, help_text="Soft delete flag"),
                ),
                (
                    "item",
                    models.CharField(help_text="Item description", max_length=255),
                ),
                (
                    "supplier",
                    models.CharField(help_text="Supplier name", max_length=255),
                ),
                ("ordered_date", models.DateField(help_text="Date ordered")),
                (
                    "expected_delivery_date",
                    models.DateField(
                        blank=True, help_text="Expected delivery date", null=True
                    ),
                ),
                (
                    "actual_delivery_date",
                    models.DateField(
                        blank=True, help_text="Actual delivery date", null=True
                    ),
                ),
                (
                    "delivered_quantity",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Quantity delivered",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "remarks",
                    models.TextField(blank=True, help_text="Additional remarks"),
                ),
                (
                    "project",
                    models.ForeignKey(
                        help_text="Project this delivery belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="delivery_trackers",
                        to="Project.project",
                    ),
                ),
            ],
            options={
                "verbose_name": "Delivery Tracker",
                "verbose_name_plural": "Delivery Trackers",
                "ordering": ["-ordered_date", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="LabourLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When this record was created"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="When this record was last modified"
                    ),
                ),
                (
                    "deleted",
                    models.BooleanField(default=False, help_text="Soft delete flag"),
                ),
                ("date", models.DateField(help_text="Date of work")),
                (
                    "person_name",
                    models.CharField(help_text="Person's name", max_length=255),
                ),
                ("id_number", models.CharField(help_text="ID number", max_length=100)),
                (
                    "trade",
                    models.CharField(help_text="Trade/specialty", max_length=100),
                ),
                (
                    "hours_worked",
                    models.DecimalField(
                        decimal_places=2, help_text="Hours worked", max_digits=6
                    ),
                ),
                (
                    "task_activity",
                    models.CharField(
                        help_text="Task/Activity performed", max_length=255
                    ),
                ),
                (
                    "remarks",
                    models.TextField(blank=True, help_text="Additional remarks"),
                ),
                (
                    "project",
                    models.ForeignKey(
                        help_text="Project this labour log belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="labour_logs",
                        to="Project.project",
                    ),
                ),
            ],
            options={
                "verbose_name": "Labour Log",
                "verbose_name_plural": "Labour Logs",
                "ordering": ["-date", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="MaterialsLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When this record was created"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="When this record was last modified"
                    ),
                ),
                (
                    "deleted",
                    models.BooleanField(default=False, help_text="Soft delete flag"),
                ),
                (
                    "date_received",
                    models.DateField(help_text="Date materials were received"),
                ),
                (
                    "supplier",
                    models.CharField(help_text="Supplier name", max_length=255),
                ),
                (
                    "invoice_number",
                    models.CharField(
                        blank=True, help_text="Invoice number", max_length=100
                    ),
                ),
                (
                    "items_received",
                    models.TextField(help_text="Description of items received"),
                ),
                (
                    "quantity",
                    models.DecimalField(
                        decimal_places=2, help_text="Quantity received", max_digits=10
                    ),
                ),
                (
                    "unit",
                    models.CharField(help_text="Unit of measurement", max_length=50),
                ),
                (
                    "intended_usage",
                    models.TextField(
                        blank=True, help_text="Intended usage of materials"
                    ),
                ),
                (
                    "comments",
                    models.TextField(blank=True, help_text="Additional comments"),
                ),
                (
                    "project",
                    models.ForeignKey(
                        help_text="Project this material log belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="materials_logs",
                        to="Project.project",
                    ),
                ),
            ],
            options={
                "verbose_name": "Materials Log",
                "verbose_name_plural": "Materials Logs",
                "ordering": ["-date_received", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="OffsiteLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When this record was created"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="When this record was last modified"
                    ),
                ),
                (
                    "deleted",
                    models.BooleanField(default=False, help_text="Soft delete flag"),
                ),
                ("date_removed", models.DateField(help_text="Date removed from site")),
                ("item_description", models.TextField(help_text="Description of item")),
                (
                    "quantity",
                    models.DecimalField(
                        decimal_places=2, help_text="Quantity removed", max_digits=10
                    ),
                ),
                (
                    "reason_for_removal",
                    models.TextField(help_text="Reason for removal"),
                ),
                (
                    "removed_by",
                    models.CharField(
                        help_text="Person who removed item", max_length=255
                    ),
                ),
                (
                    "condition",
                    models.CharField(
                        choices=[
                            ("GOOD", "Good Condition"),
                            ("FAIR", "Fair Condition"),
                            ("POOR", "Poor Condition"),
                            ("DAMAGED", "Damaged"),
                        ],
                        default="GOOD",
                        help_text="Condition of equipment/material",
                        max_length=20,
                    ),
                ),
                (
                    "remarks",
                    models.TextField(blank=True, help_text="Additional remarks"),
                ),
                (
                    "project",
                    models.ForeignKey(
                        help_text="Project this off-site log belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="offsite_logs",
                        to="Project.project",
                    ),
                ),
            ],
            options={
                "verbose_name": "Off-Site Log",
                "verbose_name_plural": "Off-Site Logs",
                "ordering": ["-date_removed", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PhotoLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When this record was created"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="When this record was last modified"
                    ),
                ),
                (
                    "deleted",
                    models.BooleanField(default=False, help_text="Soft delete flag"),
                ),
                ("date", models.DateField(help_text="Date photo was taken")),
                (
                    "photo_reference",
                    models.CharField(
                        help_text="Photo reference or file name", max_length=255
                    ),
                ),
                (
                    "photo",
                    models.ImageField(
                        blank=True,
                        help_text="Photo file",
                        null=True,
                        upload_to="site_photos/%Y/%m/%d/",
                    ),
                ),
                ("description", models.TextField(help_text="Description of photo")),
                (
                    "location",
                    models.CharField(
                        help_text="Location where photo was taken", max_length=255
                    ),
                ),
                (
                    "taken_by",
                    models.CharField(
                        help_text="Person who took the photo", max_length=255
                    ),
                ),
                (
                    "remarks",
                    models.TextField(blank=True, help_text="Additional remarks"),
                ),
                (
                    "project",
                    models.ForeignKey(
                        help_text="Project this photo log belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="photo_logs",
                        to="Project.project",
                    ),
                ),
            ],
            options={
                "verbose_name": "Photo Log",
                "verbose_name_plural": "Photo Logs",
                "ordering": ["-date", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PlantEquipment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When this record was created"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="When this record was last modified"
                    ),
                ),
                (
                    "deleted",
                    models.BooleanField(default=False, help_text="Soft delete flag"),
                ),
                ("date", models.DateField(help_text="Date of record")),
                (
                    "equipment_name",
                    models.CharField(help_text="Plant/Equipment name", max_length=255),
                ),
                (
                    "supplier",
                    models.CharField(
                        blank=True, help_text="Supplier/Owner", max_length=255
                    ),
                ),
                (
                    "usage_hours",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Usage hours",
                        max_digits=8,
                        null=True,
                    ),
                ),
                (
                    "breakdown_status",
                    models.CharField(
                        choices=[
                            ("OPERATIONAL", "Operational"),
                            ("BREAKDOWN", "Breakdown"),
                            ("UNDER_MAINTENANCE", "Under Maintenance"),
                            ("RETIRED", "Retired"),
                        ],
                        default="OPERATIONAL",
                        help_text="Breakdown status",
                        max_length=20,
                    ),
                ),
                (
                    "maintenance_done",
                    models.TextField(
                        blank=True, help_text="Maintenance work performed"
                    ),
                ),
                (
                    "remarks",
                    models.TextField(blank=True, help_text="Additional remarks"),
                ),
                (
                    "project",
                    models.ForeignKey(
                        help_text="Project this equipment belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="plant_equipment",
                        to="Project.project",
                    ),
                ),
            ],
            options={
                "verbose_name": "Plant & Equipment",
                "verbose_name_plural": "Plant & Equipment",
                "ordering": ["-date", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ProcurementTracker",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When this record was created"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="When this record was last modified"
                    ),
                ),
                (
                    "deleted",
                    models.BooleanField(default=False, help_text="Soft delete flag"),
                ),
                (
                    "item",
                    models.CharField(help_text="Item description", max_length=255),
                ),
                (
                    "supplier",
                    models.CharField(help_text="Supplier name", max_length=255),
                ),
                ("ordered_date", models.DateField(help_text="Date ordered")),
                (
                    "invoice_number",
                    models.CharField(
                        blank=True, help_text="Invoice number", max_length=100
                    ),
                ),
                (
                    "quantity",
                    models.DecimalField(
                        decimal_places=2, help_text="Quantity ordered", max_digits=10
                    ),
                ),
                (
                    "delivery_status",
                    models.CharField(
                        choices=[
                            ("ORDERED", "Ordered"),
                            ("IN_TRANSIT", "In Transit"),
                            ("DELIVERED", "Delivered"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="ORDERED",
                        help_text="Delivery status",
                        max_length=20,
                    ),
                ),
                (
                    "payment_status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("PARTIAL", "Partial"),
                            ("PAID", "Paid"),
                        ],
                        default="PENDING",
                        help_text="Payment status",
                        max_length=20,
                    ),
                ),
                (
                    "remarks",
                    models.TextField(blank=True, help_text="Additional remarks"),
                ),
                (
                    "project",
                    models.ForeignKey(
                        help_text="Project this procurement belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="procurement_trackers",
                        to="Project.project",
                    ),
                ),
            ],
            options={
                "verbose_name": "Procurement Tracker",
                "verbose_name_plural": "Procurement Trackers",
                "ordering": ["-ordered_date", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ProductivityLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When this record was created"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="When this record was last modified"
                    ),
                ),
                (
                    "deleted",
                    models.BooleanField(default=False, help_text="Soft delete flag"),
                ),
                ("date", models.DateField(help_text="Date of work")),
                (
                    "task",
                    models.CharField(help_text="Task description", max_length=255),
                ),
                (
                    "crew_size",
                    models.PositiveIntegerField(help_text="Number of workers"),
                ),
                (
                    "hours_worked",
                    models.DecimalField(
                        decimal_places=2, help_text="Total hours worked", max_digits=6
                    ),
                ),
                (
                    "output",
                    models.DecimalField(
                        decimal_places=2, help_text="Output achieved", max_digits=10
                    ),
                ),
                (
                    "output_unit",
                    models.CharField(help_text="Unit of output", max_length=50),
                ),
                (
                    "productivity",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Productivity (Output/Hour)",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "remarks",
                    models.TextField(blank=True, help_text="Additional remarks"),
                ),
                (
                    "project",
                    models.ForeignKey(
                        help_text="Project this productivity log belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="productivity_logs",
                        to="Project.project",
                    ),
                ),
            ],
            options={
                "verbose_name": "Productivity Log",
                "verbose_name_plural": "Productivity Logs",
                "ordering": ["-date", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ProgressTracker",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When this record was created"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="When this record was last modified"
                    ),
                ),
                (
                    "deleted",
                    models.BooleanField(default=False, help_text="Soft delete flag"),
                ),
                (
                    "activity",
                    models.CharField(help_text="Activity name", max_length=255),
                ),
                (
                    "planned_start_date",
                    models.DateField(help_text="Planned start date"),
                ),
                ("planned_end_date", models.DateField(help_text="Planned end date")),
                (
                    "actual_start_date",
                    models.DateField(
                        blank=True, help_text="Actual start date", null=True
                    ),
                ),
                (
                    "actual_end_date",
                    models.DateField(
                        blank=True, help_text="Actual end date", null=True
                    ),
                ),
                (
                    "completion_percentage",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Percentage completion (0-100)",
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                (
                    "remarks",
                    models.TextField(blank=True, help_text="Additional remarks"),
                ),
                (
                    "project",
                    models.ForeignKey(
                        help_text="Project this progress tracker belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="progress_trackers",
                        to="Project.project",
                    ),
                ),
            ],
            options={
                "verbose_name": "Progress Tracker",
                "verbose_name_plural": "Progress Trackers",
                "ordering": ["planned_start_date", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="QualityControl",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When this record was created"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="When this record was last modified"
                    ),
                ),
                (
                    "deleted",
                    models.BooleanField(default=False, help_text="Soft delete flag"),
                ),
                ("date", models.DateField(help_text="Date of inspection")),
                (
                    "qc_item",
                    models.CharField(help_text="Quality control item", max_length=255),
                ),
                (
                    "area_location",
                    models.CharField(help_text="Area/Location", max_length=255),
                ),
                (
                    "inspector",
                    models.CharField(help_text="Inspector name", max_length=255),
                ),
                (
                    "result",
                    models.CharField(
                        choices=[
                            ("PASS", "Pass"),
                            ("FAIL", "Fail"),
                            ("CONDITIONAL", "Conditional Pass"),
                            ("PENDING", "Pending"),
                        ],
                        default="PENDING",
                        help_text="Inspection result",
                        max_length=20,
                    ),
                ),
                (
                    "rectification_needed",
                    models.TextField(blank=True, help_text="Rectification work needed"),
                ),
                (
                    "remarks",
                    models.TextField(blank=True, help_text="Additional remarks"),
                ),
                (
                    "project",
                    models.ForeignKey(
                        help_text="Project this QC record belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="quality_controls",
                        to="Project.project",
                    ),
                ),
            ],
            options={
                "verbose_name": "Quality Control",
                "verbose_name_plural": "Quality Control Records",
                "ordering": ["-date", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SafetyObservation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When this record was created"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="When this record was last modified"
                    ),
                ),
                (
                    "deleted",
                    models.BooleanField(default=False, help_text="Soft delete flag"),
                ),
                ("date", models.DateField(help_text="Date of observation")),
                (
                    "observation",
                    models.TextField(help_text="Safety observation details"),
                ),
                (
                    "location",
                    models.CharField(
                        help_text="Location of observation", max_length=255
                    ),
                ),
                (
                    "raised_by",
                    models.CharField(
                        help_text="Person who raised observation", max_length=255
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("UNSAFE_ACT", "Unsafe Act"),
                            ("UNSAFE_CONDITION", "Unsafe Condition"),
                            ("NEAR_MISS", "Near Miss"),
                            ("GOOD_PRACTICE", "Good Practice"),
                            ("HAZARD", "Hazard"),
                        ],
                        help_text="Category of observation",
                        max_length=20,
                    ),
                ),
                (
                    "corrective_action",
                    models.TextField(blank=True, help_text="Corrective action taken"),
                ),
                (
                    "closed_out",
                    models.BooleanField(
                        default=False,
                        help_text="Whether observation has been closed out",
                    ),
                ),
                (
                    "remarks",
                    models.TextField(blank=True, help_text="Additional remarks"),
                ),
                (
                    "project",
                    models.ForeignKey(
                        help_text="Project this safety observation belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="safety_observations",
                        to="Project.project",
                    ),
                ),
            ],
            options={
                "verbose_name": "Safety Observation",
                "verbose_name_plural": "Safety Observations",
                "ordering": ["-date", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SnagList",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When this record was created"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="When this record was last modified"
                    ),
                ),
                (
                    "deleted",
                    models.BooleanField(default=False, help_text="Soft delete flag"),
                ),
                ("date_raised", models.DateField(help_text="Date issue was raised")),
                (
                    "location",
                    models.CharField(help_text="Location of issue", max_length=255),
                ),
                (
                    "issue_description",
                    models.TextField(help_text="Description of the issue"),
                ),
                (
                    "raised_by",
                    models.CharField(
                        help_text="Person who raised the issue", max_length=255
                    ),
                ),
                (
                    "assigned_to",
                    models.CharField(
                        blank=True, help_text="Person assigned to fix", max_length=255
                    ),
                ),
                (
                    "deadline",
                    models.DateField(
                        blank=True, help_text="Deadline for resolution", null=True
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("OPEN", "Open"),
                            ("IN_PROGRESS", "In Progress"),
                            ("RESOLVED", "Resolved"),
                            ("CLOSED", "Closed"),
                        ],
                        default="OPEN",
                        help_text="Current status",
                        max_length=20,
                    ),
                ),
                (
                    "remarks",
                    models.TextField(blank=True, help_text="Additional remarks"),
                ),
                (
                    "project",
                    models.ForeignKey(
                        help_text="Project this snag belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="snag_lists",
                        to="Project.project",
                    ),
                ),
            ],
            options={
                "verbose_name": "Snag List",
                "verbose_name_plural": "Snag Lists",
                "ordering": ["-date_raised", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SubcontractorLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When this record was created"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="When this record was last modified"
                    ),
                ),
                (
                    "deleted",
                    models.BooleanField(default=False, help_text="Soft delete flag"),
                ),
                (
                    "name",
                    models.CharField(help_text="Subcontractor name", max_length=255),
                ),
                (
                    "trade",
                    models.CharField(help_text="Trade/specialty", max_length=100),
                ),
                ("scope", models.TextField(help_text="Scope of work")),
                ("start_date", models.DateField(help_text="Start date")),
                (
                    "planned_finish_date",
                    models.DateField(
                        blank=True, help_text="Planned finish date", null=True
                    ),
                ),
                (
                    "actual_finish_date",
                    models.DateField(
                        blank=True, help_text="Actual finish date", null=True
                    ),
                ),
                ("task", models.CharField(help_text="Current task", max_length=255)),
                (
                    "hours_worked",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Hours worked",
                        max_digits=8,
                        null=True,
                    ),
                ),
                (
                    "output",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Output achieved",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "output_unit",
                    models.CharField(
                        blank=True, help_text="Unit of output", max_length=50
                    ),
                ),
                (
                    "productivity",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Productivity (Output/Hour)",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "remarks",
                    models.TextField(blank=True, help_text="Additional remarks"),
                ),
                (
                    "project",
                    models.ForeignKey(
                        help_text="Project this subcontractor log belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subcontractor_logs",
                        to="Project.project",
                    ),
                ),
            ],
            options={
                "verbose_name": "Subcontractor Log",
                "verbose_name_plural": "Subcontractor Logs",
                "ordering": ["-start_date", "-created_at"],
            },
        ),
    ]
