# Generated by Django 6.0.2 on 2026-02-26 20:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import app.SiteManagement.models.early_warning
import app.SiteManagement.models.site_instruction


class Migration(migrations.Migration):
    dependencies = [
        ("Project", "0042_update_risk_model"),
        ("SiteManagement", "0002_earlywarning"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="earlywarning",
            name="attachment",
            field=models.FileField(
                blank=True,
                help_text="Supporting attachment from submitter",
                null=True,
                upload_to=app.SiteManagement.models.early_warning.EarlyWarning.upload_to,
            ),
        ),
        migrations.CreateModel(
            name="SiteInstruction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When this record was created"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="When this record was last modified"
                    ),
                ),
                (
                    "deleted",
                    models.BooleanField(default=False, help_text="Soft delete flag"),
                ),
                (
                    "reference_number",
                    models.CharField(
                        editable=False,
                        help_text="Auto-generated reference number",
                        max_length=50,
                        unique=True,
                    ),
                ),
                (
                    "date_notified",
                    models.DateField(
                        auto_now_add=True,
                        help_text="Date this site instruction was issued",
                    ),
                ),
                (
                    "subject",
                    models.CharField(
                        help_text="Subject of the site instruction", max_length=255
                    ),
                ),
                (
                    "instruction",
                    models.TextField(help_text="Detailed instruction content"),
                ),
                (
                    "attachment",
                    models.FileField(
                        blank=True,
                        help_text="Supporting attachment",
                        null=True,
                        upload_to=app.SiteManagement.models.site_instruction.SiteInstruction.upload_to,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("OPEN", "Open"), ("CLOSED", "Closed")],
                        default="OPEN",
                        help_text="Current status of this site instruction",
                        max_length=10,
                    ),
                ),
                (
                    "date_closed",
                    models.DateField(
                        blank=True,
                        editable=False,
                        help_text="Date this instruction was closed (auto-set)",
                        null=True,
                    ),
                ),
                (
                    "issued_by",
                    models.ForeignKey(
                        editable=False,
                        help_text="User who issued this site instruction",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="site_instructions_issued",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        help_text="Project this site instruction belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="site_instructions",
                        to="Project.project",
                    ),
                ),
                (
                    "to_user",
                    models.ForeignKey(
                        blank=True,
                        help_text="User this instruction is addressed to",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="site_instructions_received",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Site Instruction",
                "verbose_name_plural": "Site Instructions",
                "ordering": ["-created_at"],
            },
        ),
    ]
