# Generated by Django 6.0.2 on 2026-02-26 20:32

import app.SiteManagement.models.rfi
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Project', '0042_update_risk_model'),
        ('SiteManagement', '0003_add_site_instruction'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RFI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When this record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When this record was last modified')),
                ('deleted', models.BooleanField(default=False, help_text='Soft delete flag')),
                ('reference_number', models.CharField(editable=False, help_text='Auto-generated reference number', max_length=50, unique=True)),
                ('date_issued', models.DateField(auto_now_add=True, help_text='Date this RFI was issued')),
                ('subject', models.CharField(help_text='Subject of the RFI', max_length=255)),
                ('message', models.TextField(help_text='Detailed description or question')),
                ('attachment', models.FileField(blank=True, help_text='Supporting attachment', null=True, upload_to=app.SiteManagement.models.rfi.RFI.upload_to)),
                ('respond_by_date', models.DateField(help_text='Date by which a response is required')),
                ('response', models.TextField(blank=True, help_text='Response to this RFI')),
                ('response_attachment', models.FileField(blank=True, help_text='Supporting attachment for response', null=True, upload_to='rfis/responses/')),
                ('response_date', models.DateField(blank=True, editable=False, help_text='Date the response was submitted (auto-set)', null=True)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('CLOSED', 'Closed')], default='OPEN', help_text='Current status of this RFI', max_length=10)),
                ('date_closed', models.DateField(blank=True, editable=False, help_text='Date this RFI was closed (auto-set)', null=True)),
                ('issued_by', models.ForeignKey(editable=False, help_text='User who issued this RFI', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rfis_issued', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(help_text='Project this RFI belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='rfis', to='Project.project')),
                ('to_user', models.ForeignKey(blank=True, help_text='User this RFI is addressed to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rfis_received', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Request for Information',
                'verbose_name_plural': 'Requests for Information',
                'ordering': ['-created_at'],
            },
        ),
    ]
