# Generated by Django 6.0.2 on 2026-02-26 20:41

import django.db.models.deletion
from django.db import migrations, models

import app.SiteManagement.models.meeting


class Migration(migrations.Migration):
    dependencies = [
        ("Project", "0042_update_risk_model"),
        ("SiteManagement", "0004_add_rfi"),
    ]

    operations = [
        migrations.CreateModel(
            name="Meeting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When this record was created"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="When this record was last modified"
                    ),
                ),
                (
                    "deleted",
                    models.BooleanField(default=False, help_text="Soft delete flag"),
                ),
                (
                    "meeting_type",
                    models.CharField(
                        choices=[
                            ("PROGRESS", "Progress"),
                            ("CONTRACTUAL", "Contractual"),
                            ("RISK", "Risk"),
                            ("OTHER", "Other"),
                        ],
                        help_text="Type of meeting",
                        max_length=20,
                    ),
                ),
                ("date", models.DateField(help_text="Date of the meeting")),
                (
                    "key_decisions",
                    models.TextField(
                        blank=True, help_text="Key decisions made during the meeting"
                    ),
                ),
                (
                    "attachment",
                    models.FileField(
                        blank=True,
                        help_text="Meeting minutes or other supporting documents",
                        null=True,
                        upload_to=app.SiteManagement.models.meeting.Meeting.upload_to,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("OPEN", "Open"), ("CLOSED", "Closed")],
                        default="OPEN",
                        help_text="Current status of this meeting",
                        max_length=10,
                    ),
                ),
                (
                    "date_closed",
                    models.DateField(
                        blank=True,
                        editable=False,
                        help_text="Date this meeting was closed (auto-set)",
                        null=True,
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        help_text="Project this meeting belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="meetings",
                        to="Project.project",
                    ),
                ),
            ],
            options={
                "verbose_name": "Meeting",
                "verbose_name_plural": "Meetings",
                "ordering": ["-date", "-created_at"],
            },
        ),
    ]
