# Generated by Django 6.0.3 on 2026-03-18 13:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Project", "0050_projectdocument_project_category_and_more"),
        ("SiteManagement", "0005_add_meeting"),
    ]

    operations = [
        migrations.AddField(
            model_name="rfi",
            name="project_category",
            field=models.ForeignKey(
                blank=True,
                help_text="Project category (e.g., Education, Health, Roads)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="rfis",
                to="Project.projectcategory",
            ),
        ),
        migrations.AddField(
            model_name="rfi",
            name="project_discipline",
            field=models.ForeignKey(
                blank=True,
                help_text="Project discipline",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="rfis",
                to="Project.projectdiscipline",
            ),
        ),
        migrations.AddField(
            model_name="rfi",
            name="project_sub_category",
            field=models.ForeignKey(
                blank=True,
                help_text="Project category (e.g., Education, Health, Roads)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="rfis",
                to="Project.projectsubcategory",
            ),
        ),
    ]
