# Generated by Django 6.0.3 on 2026-03-18 13:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Project", "0050_projectdocument_project_category_and_more"),
        ("SiteManagement", "0006_rfi_project_category_rfi_project_discipline_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rfi",
            name="project_category",
            field=models.ForeignKey(
                blank=True,
                help_text="WBS Level 1 classification",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="rfis",
                to="Project.category",
            ),
        ),
        migrations.AlterField(
            model_name="rfi",
            name="project_discipline",
            field=models.ForeignKey(
                blank=True,
                help_text="WBS Level 3 classification",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="rfis",
                to="Project.discipline",
            ),
        ),
        migrations.AlterField(
            model_name="rfi",
            name="project_sub_category",
            field=models.ForeignKey(
                blank=True,
                help_text="WBS Level 2 classification",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="rfis",
                to="Project.subcategory",
            ),
        ),
    ]
