# Generated by Django 5.2.12 on 2026-03-27 09:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("SiteManagement", "0007_alter_rfi_project_category_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="plantequipment",
            name="hourly_rate",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                default=0,
                help_text="Hourly rate for equipment usage",
                max_digits=12,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="plantequipment",
            name="usage_hours",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                default=0,
                help_text="Usage hours",
                max_digits=8,
                null=True,
            ),
        ),
    ]
