# Generated by Django 6.0.3 on 2026-04-06 19:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import app.SiteManagement.models.non_conformance


class Migration(migrations.Migration):
    dependencies = [
        ("Project", "0061_category_budget_group_budget_subcategory_budget"),
        ("SiteManagement", "0007_alter_rfi_project_category_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Incident",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When this record was created"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="When this record was last modified"
                    ),
                ),
                (
                    "deleted",
                    models.BooleanField(default=False, help_text="Soft delete flag"),
                ),
                (
                    "reference_number",
                    models.CharField(
                        blank=True,
                        editable=False,
                        help_text="Auto-generated reference number",
                        max_length=50,
                    ),
                ),
                (
                    "incident_type",
                    models.CharField(
                        choices=[("INCIDENT", "Incident"), ("NEAR_MISS", "Near Miss")],
                        default="INCIDENT",
                        help_text="Type of incident",
                        max_length=20,
                    ),
                ),
                ("date", models.DateField(help_text="Date the incident occurred")),
                (
                    "description",
                    models.TextField(help_text="Detailed description of the incident"),
                ),
                (
                    "location",
                    models.CharField(
                        blank=True,
                        help_text="Location on site where the incident occurred",
                        max_length=255,
                    ),
                ),
                (
                    "root_cause",
                    models.TextField(blank=True, help_text="Root cause analysis"),
                ),
                (
                    "corrective_action",
                    models.TextField(
                        blank=True, help_text="Corrective action taken or planned"
                    ),
                ),
                (
                    "corrective_action_date",
                    models.DateField(
                        blank=True,
                        help_text="Target / actual date for corrective action completion",
                        null=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("OPEN", "Open"), ("CLOSED", "Closed")],
                        default="OPEN",
                        help_text="Current status of this incident",
                        max_length=10,
                    ),
                ),
                (
                    "date_closed",
                    models.DateField(
                        blank=True,
                        editable=False,
                        help_text="Date this incident was closed (auto-set)",
                        null=True,
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        help_text="Project this incident belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="incidents",
                        to="Project.project",
                    ),
                ),
                (
                    "reported_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Person who reported the incident",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reported_incidents",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Incident",
                "verbose_name_plural": "Incidents",
                "ordering": ["-date", "-created_at"],
                "indexes": [
                    models.Index(
                        fields=["project", "status"],
                        name="SiteManagem_project_186ec3_idx",
                    ),
                    models.Index(
                        fields=["project", "incident_type"],
                        name="SiteManagem_project_f185b4_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="NonConformance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When this record was created"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="When this record was last modified"
                    ),
                ),
                (
                    "deleted",
                    models.BooleanField(default=False, help_text="Soft delete flag"),
                ),
                (
                    "reference_number",
                    models.CharField(
                        blank=True,
                        editable=False,
                        help_text="Auto-generated reference number",
                        max_length=50,
                    ),
                ),
                (
                    "ncr_type",
                    models.CharField(
                        choices=[("SAFETY", "Safety"), ("QUALITY", "Quality")],
                        default="QUALITY",
                        help_text="Type of non-conformance (Safety or Quality)",
                        max_length=10,
                    ),
                ),
                (
                    "date",
                    models.DateField(
                        auto_now_add=True, help_text="Date this NCR was raised"
                    ),
                ),
                (
                    "description",
                    models.TextField(help_text="Description of the non-conformance"),
                ),
                (
                    "defect_description",
                    models.TextField(
                        blank=True,
                        help_text="Detailed description of the defect (Quality NCRs)",
                    ),
                ),
                (
                    "root_cause",
                    models.TextField(blank=True, help_text="Root cause analysis"),
                ),
                (
                    "corrective_action",
                    models.TextField(blank=True, help_text="Corrective action issued"),
                ),
                (
                    "preventative_action",
                    models.TextField(
                        blank=True, help_text="Preventative action to avoid recurrence"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("OPEN", "Open"), ("CLOSED", "Closed")],
                        default="OPEN",
                        help_text="Current status of this NCR",
                        max_length=10,
                    ),
                ),
                (
                    "date_closed",
                    models.DateField(
                        blank=True,
                        editable=False,
                        help_text="Date this NCR was closed (auto-set)",
                        null=True,
                    ),
                ),
                (
                    "photo",
                    models.ImageField(
                        blank=True,
                        help_text="Photographic evidence",
                        null=True,
                        upload_to=app.SiteManagement.models.non_conformance.NonConformance._photo_upload_to,
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        help_text="Project this NCR belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="non_conformances",
                        to="Project.project",
                    ),
                ),
                (
                    "responsible_person",
                    models.ForeignKey(
                        blank=True,
                        help_text="Person responsible for closing out this NCR",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_ncrs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Non-Conformance Report",
                "verbose_name_plural": "Non-Conformance Reports",
                "ordering": ["-date", "-created_at"],
                "indexes": [
                    models.Index(
                        fields=["project", "status"],
                        name="SiteManagem_project_c23a5f_idx",
                    ),
                    models.Index(
                        fields=["project", "ncr_type"],
                        name="SiteManagem_project_d0d54b_idx",
                    ),
                ],
            },
        ),
    ]
