# Generated by Django 6.0.3 on 2026-04-07 07:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Project', '0061_category_budget_group_budget_subcategory_budget'),
        ('SiteManagement', '0008_incident_nonconformance'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BiWeeklyQualityReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When this record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When this record was last modified')),
                ('deleted', models.BooleanField(default=False, help_text='Soft delete flag')),
                ('period_start', models.DateField(help_text='Start of the two-week period')),
                ('period_end', models.DateField(help_text='End of the two-week period')),
                ('notes', models.TextField(blank=True, help_text='Additional notes')),
                ('project', models.ForeignKey(help_text='Project this report belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='biweekly_quality_reports', to='Project.project')),
                ('submitted_by', models.ForeignKey(blank=True, editable=False, help_text='User who submitted this report', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_quality_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Bi-Weekly Quality Report',
                'verbose_name_plural': 'Bi-Weekly Quality Reports',
                'ordering': ['-period_end', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BiWeeklySafetyReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When this record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When this record was last modified')),
                ('deleted', models.BooleanField(default=False, help_text='Soft delete flag')),
                ('period_start', models.DateField(help_text='Start of the two-week period')),
                ('period_end', models.DateField(help_text='End of the two-week period')),
                ('key_concerns', models.TextField(blank=True, help_text='Key safety concerns or observations for this period')),
                ('notes', models.TextField(blank=True, help_text='Additional notes')),
                ('project', models.ForeignKey(help_text='Project this report belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='biweekly_safety_reports', to='Project.project')),
                ('submitted_by', models.ForeignKey(blank=True, editable=False, help_text='User who submitted this report', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_safety_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Bi-Weekly Safety Report',
                'verbose_name_plural': 'Bi-Weekly Safety Reports',
                'ordering': ['-period_end', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='QualityActivityInspection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When this record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When this record was last modified')),
                ('deleted', models.BooleanField(default=False, help_text='Soft delete flag')),
                ('activity_or_work_package', models.CharField(help_text='Activity or work package that was inspected', max_length=255)),
                ('approval_status', models.CharField(choices=[('APPROVED', 'Approved'), ('CONDITIONAL', 'Conditional Approval'), ('REJECTED', 'Rejected'), ('PENDING', 'Pending')], default='PENDING', help_text='Inspection approval status', max_length=20)),
                ('remarks', models.TextField(blank=True)),
                ('report', models.ForeignKey(help_text='Parent quality report', on_delete=django.db.models.deletion.CASCADE, related_name='activity_inspections', to='SiteManagement.biweeklyqualityreport')),
            ],
            options={
                'verbose_name': 'Quality Activity Inspection',
                'verbose_name_plural': 'Quality Activity Inspections',
            },
        ),
        migrations.CreateModel(
            name='QualityMaterialDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When this record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When this record was last modified')),
                ('deleted', models.BooleanField(default=False, help_text='Soft delete flag')),
                ('date', models.DateField(help_text='Date of delivery')),
                ('material', models.CharField(help_text='Material description', max_length=255)),
                ('quantity', models.CharField(help_text='Quantity delivered', max_length=100)),
                ('report', models.ForeignKey(help_text='Parent quality report', on_delete=django.db.models.deletion.CASCADE, related_name='material_deliveries', to='SiteManagement.biweeklyqualityreport')),
            ],
            options={
                'verbose_name': 'Quality Material Delivery',
                'verbose_name_plural': 'Quality Material Deliveries',
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='QualitySiteAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When this record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When this record was last modified')),
                ('deleted', models.BooleanField(default=False, help_text='Soft delete flag')),
                ('date', models.DateField(help_text='Date of inspection/audit')),
                ('inspector', models.CharField(help_text='Name of inspector or auditor', max_length=255)),
                ('audit_findings', models.TextField(help_text='Findings from the inspection or audit')),
                ('report', models.ForeignKey(help_text='Parent quality report', on_delete=django.db.models.deletion.CASCADE, related_name='site_audits', to='SiteManagement.biweeklyqualityreport')),
            ],
            options={
                'verbose_name': 'Quality Site Audit',
                'verbose_name_plural': 'Quality Site Audits',
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='QualityWorkmanship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When this record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When this record was last modified')),
                ('deleted', models.BooleanField(default=False, help_text='Soft delete flag')),
                ('activity', models.CharField(help_text='Activity checked', max_length=255)),
                ('is_compliant', models.BooleanField(default=True, help_text='Compliant with drawings and specifications')),
                ('snag_defect', models.TextField(blank=True, help_text='Snag or defect identified (if non-compliant)')),
                ('snag_date', models.DateField(blank=True, help_text='Date the snag/defect was identified', null=True)),
                ('report', models.ForeignKey(help_text='Parent quality report', on_delete=django.db.models.deletion.CASCADE, related_name='workmanship_records', to='SiteManagement.biweeklyqualityreport')),
            ],
            options={
                'verbose_name': 'Quality Workmanship Record',
                'verbose_name_plural': 'Quality Workmanship Records',
            },
        ),
    ]
