# Generated by Django 5.2.12 on 2026-03-27 10:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Project", "0066_alter_productionresource_resource_type_and_more"),
        ("SiteManagement", "0008_plantequipment_hourly_rate_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="SkillType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When this record was created"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="When this record was last modified"
                    ),
                ),
                (
                    "deleted",
                    models.BooleanField(default=False, help_text="Soft delete flag"),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Skill type name (e.g., Skilled, Semi-Skilled, General)",
                        max_length=100,
                    ),
                ),
                (
                    "hourly_rate",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Hourly rate for this skill type",
                        max_digits=12,
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        help_text="Project this skill type belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="skill_types",
                        to="Project.project",
                    ),
                ),
            ],
            options={
                "verbose_name": "Skill Type",
                "verbose_name_plural": "Skill Types",
                "ordering": ["name"],
                "unique_together": {("project", "name")},
            },
        ),
        migrations.AddField(
            model_name="labourlog",
            name="skill_type",
            field=models.ForeignKey(
                blank=True,
                help_text="Skill type of the worker",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="labour_logs",
                to="SiteManagement.skilltype",
            ),
        ),
    ]
