# Generated by Django 5.2.12 on 2026-03-27 10:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Project", "0066_alter_productionresource_resource_type_and_more"),
        ("SiteManagement", "0010_remove_plantequipment_hourly_rate_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="plantequipment",
            name="equipment_name",
            field=models.CharField(
                blank=True,
                help_text="Specific equipment name/ID (optional)",
                max_length=255,
            ),
        ),
        migrations.CreateModel(
            name="PlantType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When this record was created"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="When this record was last modified"
                    ),
                ),
                (
                    "deleted",
                    models.BooleanField(default=False, help_text="Soft delete flag"),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Plant type name (e.g., Excavator, Crane, Generator)",
                        max_length=100,
                    ),
                ),
                (
                    "hourly_rate",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Hourly rate for this equipment type",
                        max_digits=12,
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        help_text="Project this plant type belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="plant_types",
                        to="Project.project",
                    ),
                ),
            ],
            options={
                "verbose_name": "Plant Type",
                "verbose_name_plural": "Plant Types",
                "ordering": ["name"],
                "unique_together": {("project", "name")},
            },
        ),
        migrations.AddField(
            model_name="plantequipment",
            name="plant_type",
            field=models.ForeignKey(
                blank=True,
                help_text="Type of plant/equipment",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="equipment_items",
                to="SiteManagement.planttype",
            ),
        ),
    ]
