# Generated by Django 5.2.12 on 2026-04-06 17:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Project", "0070_journalentry_labourentity_labourcosttracker_and_more"),
        (
            "SiteManagement",
            "0011_alter_plantequipment_equipment_name_planttype_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="labourlog",
            name="labour_entity",
            field=models.ForeignKey(
                blank=True,
                help_text="Link to master labour definition",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="labour_logs",
                to="Project.labourentity",
            ),
        ),
        migrations.AddField(
            model_name="materialslog",
            name="material_entity",
            field=models.ForeignKey(
                blank=True,
                help_text="Link to master material definition",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="materials_logs",
                to="Project.materialentity",
            ),
        ),
        migrations.AddField(
            model_name="plantequipment",
            name="plant_entity",
            field=models.ForeignKey(
                blank=True,
                help_text="Link to master plant definition",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="plant_logs",
                to="Project.plantentity",
            ),
        ),
        migrations.AddField(
            model_name="subcontractorlog",
            name="subcontractor_entity",
            field=models.ForeignKey(
                blank=True,
                help_text="Link to master subcontractor definition",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="subcontractor_logs",
                to="Project.subcontractorentity",
            ),
        ),
        migrations.AlterField(
            model_name="labourlog",
            name="id_number",
            field=models.CharField(blank=True, help_text="ID number", max_length=100),
        ),
        migrations.AlterField(
            model_name="labourlog",
            name="person_name",
            field=models.CharField(
                blank=True, help_text="Person's name", max_length=255
            ),
        ),
        migrations.AlterField(
            model_name="labourlog",
            name="trade",
            field=models.CharField(
                blank=True, help_text="Trade/specialty", max_length=100
            ),
        ),
        migrations.AlterField(
            model_name="materialslog",
            name="supplier",
            field=models.CharField(
                blank=True, help_text="Supplier name", max_length=255
            ),
        ),
        migrations.AlterField(
            model_name="materialslog",
            name="unit",
            field=models.CharField(
                blank=True, help_text="Unit of measurement", max_length=50
            ),
        ),
        migrations.AlterField(
            model_name="subcontractorlog",
            name="name",
            field=models.CharField(
                blank=True, help_text="Subcontractor name", max_length=255
            ),
        ),
        migrations.AlterField(
            model_name="subcontractorlog",
            name="scope",
            field=models.TextField(blank=True, help_text="Scope of work"),
        ),
        migrations.AlterField(
            model_name="subcontractorlog",
            name="trade",
            field=models.CharField(
                blank=True, help_text="Trade/specialty", max_length=100
            ),
        ),
    ]
