# Generated by Django 6.0.4 on 2026-04-09 10:35

import app.SiteManagement.models.non_conformance
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Project', '0070_projectreportsummary'),
        ('SiteManagement', '0011_alter_plantequipment_equipment_name_planttype_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='progresstracker',
            name='impact_description',
            field=models.CharField(blank=True, default='On track', help_text="Impact on milestone (e.g., 'On track', 'At risk', 'Delayed')", max_length=255),
        ),
        migrations.AddField(
            model_name='progresstracker',
            name='milestone',
            field=models.ForeignKey(blank=True, help_text='Milestone this activity contributes to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='progress_activities', to='Project.milestone'),
        ),
        migrations.CreateModel(
            name='BiWeeklyQualityReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When this record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When this record was last modified')),
                ('deleted', models.BooleanField(default=False, help_text='Soft delete flag')),
                ('period_start', models.DateField(help_text='Start of the two-week period')),
                ('period_end', models.DateField(help_text='End of the two-week period')),
                ('notes', models.TextField(blank=True, help_text='Additional notes')),
                ('project', models.ForeignKey(help_text='Project this report belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='biweekly_quality_reports', to='Project.project')),
                ('submitted_by', models.ForeignKey(blank=True, editable=False, help_text='User who submitted this report', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_quality_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Bi-Weekly Quality Report',
                'verbose_name_plural': 'Bi-Weekly Quality Reports',
                'ordering': ['-period_end', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BiWeeklySafetyReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When this record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When this record was last modified')),
                ('deleted', models.BooleanField(default=False, help_text='Soft delete flag')),
                ('period_start', models.DateField(help_text='Start of the two-week period')),
                ('period_end', models.DateField(help_text='End of the two-week period')),
                ('key_concerns', models.TextField(blank=True, help_text='Key safety concerns or observations for this period')),
                ('notes', models.TextField(blank=True, help_text='Additional notes')),
                ('project', models.ForeignKey(help_text='Project this report belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='biweekly_safety_reports', to='Project.project')),
                ('submitted_by', models.ForeignKey(blank=True, editable=False, help_text='User who submitted this report', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_safety_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Bi-Weekly Safety Report',
                'verbose_name_plural': 'Bi-Weekly Safety Reports',
                'ordering': ['-period_end', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='QualityActivityInspection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When this record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When this record was last modified')),
                ('deleted', models.BooleanField(default=False, help_text='Soft delete flag')),
                ('activity_or_work_package', models.CharField(help_text='Activity or work package that was inspected', max_length=255)),
                ('approval_status', models.CharField(choices=[('APPROVED', 'Approved'), ('CONDITIONAL', 'Conditional Approval'), ('REJECTED', 'Rejected'), ('PENDING', 'Pending')], default='PENDING', help_text='Inspection approval status', max_length=20)),
                ('remarks', models.TextField(blank=True)),
                ('report', models.ForeignKey(help_text='Parent quality report', on_delete=django.db.models.deletion.CASCADE, related_name='activity_inspections', to='SiteManagement.biweeklyqualityreport')),
            ],
            options={
                'verbose_name': 'Quality Activity Inspection',
                'verbose_name_plural': 'Quality Activity Inspections',
            },
        ),
        migrations.CreateModel(
            name='QualityMaterialDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When this record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When this record was last modified')),
                ('deleted', models.BooleanField(default=False, help_text='Soft delete flag')),
                ('date', models.DateField(help_text='Date of delivery')),
                ('material', models.CharField(help_text='Material description', max_length=255)),
                ('quantity', models.CharField(help_text='Quantity delivered', max_length=100)),
                ('report', models.ForeignKey(help_text='Parent quality report', on_delete=django.db.models.deletion.CASCADE, related_name='material_deliveries', to='SiteManagement.biweeklyqualityreport')),
            ],
            options={
                'verbose_name': 'Quality Material Delivery',
                'verbose_name_plural': 'Quality Material Deliveries',
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='QualitySiteAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When this record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When this record was last modified')),
                ('deleted', models.BooleanField(default=False, help_text='Soft delete flag')),
                ('date', models.DateField(help_text='Date of inspection/audit')),
                ('inspector', models.CharField(help_text='Name of inspector or auditor', max_length=255)),
                ('audit_findings', models.TextField(help_text='Findings from the inspection or audit')),
                ('report', models.ForeignKey(help_text='Parent quality report', on_delete=django.db.models.deletion.CASCADE, related_name='site_audits', to='SiteManagement.biweeklyqualityreport')),
            ],
            options={
                'verbose_name': 'Quality Site Audit',
                'verbose_name_plural': 'Quality Site Audits',
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='QualityWorkmanship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When this record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When this record was last modified')),
                ('deleted', models.BooleanField(default=False, help_text='Soft delete flag')),
                ('activity', models.CharField(help_text='Activity checked', max_length=255)),
                ('is_compliant', models.BooleanField(default=True, help_text='Compliant with drawings and specifications')),
                ('snag_defect', models.TextField(blank=True, help_text='Snag or defect identified (if non-compliant)')),
                ('snag_date', models.DateField(blank=True, help_text='Date the snag/defect was identified', null=True)),
                ('report', models.ForeignKey(help_text='Parent quality report', on_delete=django.db.models.deletion.CASCADE, related_name='workmanship_records', to='SiteManagement.biweeklyqualityreport')),
            ],
            options={
                'verbose_name': 'Quality Workmanship Record',
                'verbose_name_plural': 'Quality Workmanship Records',
            },
        ),
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When this record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When this record was last modified')),
                ('deleted', models.BooleanField(default=False, help_text='Soft delete flag')),
                ('reference_number', models.CharField(blank=True, editable=False, help_text='Auto-generated reference number', max_length=50)),
                ('incident_type', models.CharField(choices=[('INCIDENT', 'Incident'), ('NEAR_MISS', 'Near Miss')], default='INCIDENT', help_text='Type of incident', max_length=20)),
                ('date', models.DateField(help_text='Date the incident occurred')),
                ('description', models.TextField(help_text='Detailed description of the incident')),
                ('location', models.CharField(blank=True, help_text='Location on site where the incident occurred', max_length=255)),
                ('root_cause', models.TextField(blank=True, help_text='Root cause analysis')),
                ('corrective_action', models.TextField(blank=True, help_text='Corrective action taken or planned')),
                ('corrective_action_date', models.DateField(blank=True, help_text='Target / actual date for corrective action completion', null=True)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('CLOSED', 'Closed')], default='OPEN', help_text='Current status of this incident', max_length=10)),
                ('date_closed', models.DateField(blank=True, editable=False, help_text='Date this incident was closed (auto-set)', null=True)),
                ('project', models.ForeignKey(help_text='Project this incident belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='incidents', to='Project.project')),
                ('reported_by', models.ForeignKey(blank=True, help_text='Person who reported the incident', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reported_incidents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Incident',
                'verbose_name_plural': 'Incidents',
                'ordering': ['-date', '-created_at'],
                'indexes': [models.Index(fields=['project', 'status'], name='SiteManagem_project_186ec3_idx'), models.Index(fields=['project', 'incident_type'], name='SiteManagem_project_f185b4_idx')],
            },
        ),
        migrations.CreateModel(
            name='NonConformance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When this record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When this record was last modified')),
                ('deleted', models.BooleanField(default=False, help_text='Soft delete flag')),
                ('reference_number', models.CharField(blank=True, editable=False, help_text='Auto-generated reference number', max_length=50)),
                ('ncr_type', models.CharField(choices=[('SAFETY', 'Safety'), ('QUALITY', 'Quality')], default='QUALITY', help_text='Type of non-conformance (Safety or Quality)', max_length=10)),
                ('date', models.DateField(auto_now_add=True, help_text='Date this NCR was raised')),
                ('description', models.TextField(help_text='Description of the non-conformance')),
                ('defect_description', models.TextField(blank=True, help_text='Detailed description of the defect (Quality NCRs)')),
                ('root_cause', models.TextField(blank=True, help_text='Root cause analysis')),
                ('corrective_action', models.TextField(blank=True, help_text='Corrective action issued')),
                ('preventative_action', models.TextField(blank=True, help_text='Preventative action to avoid recurrence')),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('CLOSED', 'Closed')], default='OPEN', help_text='Current status of this NCR', max_length=10)),
                ('date_closed', models.DateField(blank=True, editable=False, help_text='Date this NCR was closed (auto-set)', null=True)),
                ('photo', models.ImageField(blank=True, help_text='Photographic evidence', null=True, upload_to=app.SiteManagement.models.non_conformance.NonConformance._photo_upload_to)),
                ('project', models.ForeignKey(help_text='Project this NCR belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='non_conformances', to='Project.project')),
                ('responsible_person', models.ForeignKey(blank=True, help_text='Person responsible for closing out this NCR', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_ncrs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Non-Conformance Report',
                'verbose_name_plural': 'Non-Conformance Reports',
                'ordering': ['-date', '-created_at'],
                'indexes': [models.Index(fields=['project', 'status'], name='SiteManagem_project_c23a5f_idx'), models.Index(fields=['project', 'ncr_type'], name='SiteManagem_project_d0d54b_idx')],
            },
        ),
    ]
