# Generated by Django 5.2.12 on 2026-03-27 10:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("SiteManagement", "0012_skilltype_labourlog_skill_type"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="plantequipment",
            name="hourly_rate",
        ),
        migrations.AlterField(
            model_name="plantequipment",
            name="usage_hours",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Usage hours",
                max_digits=8,
                null=True,
            ),
        ),
    ]
