# Generated by Django 6.0.3 on 2026-04-10 07:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("SiteManagement", "0012_progresstracker_impact_description_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="MeetingDecision",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When this record was created"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="When this record was last modified"
                    ),
                ),
                (
                    "deleted",
                    models.BooleanField(default=False, help_text="Soft delete flag"),
                ),
                (
                    "description",
                    models.TextField(help_text="Description of the decision made"),
                ),
                (
                    "meeting",
                    models.ForeignKey(
                        help_text="Meeting this decision belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="meeting_decisions",
                        to="SiteManagement.meeting",
                    ),
                ),
            ],
            options={
                "verbose_name": "Meeting Decision",
                "verbose_name_plural": "Meeting Decisions",
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="MeetingAction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When this record was created"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="When this record was last modified"
                    ),
                ),
                (
                    "deleted",
                    models.BooleanField(default=False, help_text="Soft delete flag"),
                ),
                ("description", models.TextField(help_text="Action to be performed")),
                (
                    "assigned_to",
                    models.CharField(
                        blank=True,
                        help_text="Person responsible for this action",
                        max_length=255,
                    ),
                ),
                (
                    "due_date",
                    models.DateField(
                        blank=True, help_text="Date this action is due", null=True
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("IN_PROGRESS", "In Progress"),
                            ("COMPLETE", "Complete"),
                        ],
                        default="PENDING",
                        help_text="Current status of the action",
                        max_length=20,
                    ),
                ),
                (
                    "decision",
                    models.ForeignKey(
                        help_text="Decision this action is linked to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="actions",
                        to="SiteManagement.meetingdecision",
                    ),
                ),
            ],
            options={
                "verbose_name": "Meeting Action",
                "verbose_name_plural": "Meeting Actions",
                "ordering": ["due_date", "created_at"],
            },
        ),
    ]
