# Generated by Django 6.0.4 on 2026-04-12 14:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Project", "0071_journalentry_labourentity_labourcosttracker_and_more"),
        ("SiteManagement", "0012_progresstracker_impact_description_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="labourlog",
            name="labour_entity",
            field=models.ForeignKey(
                blank=True,
                help_text="Link to master labour definition",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="labour_logs",
                to="Project.labourentity",
            ),
        ),
        migrations.AddField(
            model_name="materialslog",
            name="material_entity",
            field=models.ForeignKey(
                blank=True,
                help_text="Link to master material definition",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="materials_logs",
                to="Project.materialentity",
            ),
        ),
        migrations.AddField(
            model_name="meeting",
            name="other_meeting_type",
            field=models.CharField(
                blank=True,
                help_text="Custom meeting type if 'Other' is selected",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="plantequipment",
            name="plant_entity",
            field=models.ForeignKey(
                blank=True,
                help_text="Link to master plant definition",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="plant_logs",
                to="Project.plantentity",
            ),
        ),
        migrations.AddField(
            model_name="subcontractorlog",
            name="date",
            field=models.DateField(
                default="2026-04-12", help_text="Date of work entry"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="subcontractorlog",
            name="subcontractor_entity",
            field=models.ForeignKey(
                blank=True,
                help_text="Link to master subcontractor definition",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="subcontractor_logs",
                to="Project.subcontractorentity",
            ),
        ),
        migrations.AlterField(
            model_name="labourlog",
            name="id_number",
            field=models.CharField(
                blank=True, editable=False, help_text="ID number", max_length=100
            ),
        ),
        migrations.AlterField(
            model_name="labourlog",
            name="person_name",
            field=models.CharField(
                blank=True, editable=False, help_text="Person's name", max_length=255
            ),
        ),
        migrations.AlterField(
            model_name="labourlog",
            name="skill_type",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                help_text="Skill type of the worker",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="labour_logs",
                to="SiteManagement.skilltype",
            ),
        ),
        migrations.AlterField(
            model_name="labourlog",
            name="trade",
            field=models.CharField(
                blank=True, editable=False, help_text="Trade/specialty", max_length=100
            ),
        ),
        migrations.AlterField(
            model_name="materialslog",
            name="items_received",
            field=models.TextField(
                editable=False, help_text="Description of items received"
            ),
        ),
        migrations.AlterField(
            model_name="materialslog",
            name="supplier",
            field=models.CharField(
                blank=True, editable=False, help_text="Supplier name", max_length=255
            ),
        ),
        migrations.AlterField(
            model_name="materialslog",
            name="unit",
            field=models.CharField(
                blank=True,
                editable=False,
                help_text="Unit of measurement",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="meeting",
            name="meeting_type",
            field=models.CharField(
                choices=[
                    ("PROGRESS", "Progress"),
                    ("CONTRACTUAL", "Contractual"),
                    ("RISK", "Risk"),
                    ("EARLY_WARNING", "Early Warning"),
                    ("OTHER", "Other"),
                ],
                help_text="Type of meeting",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="plantequipment",
            name="equipment_name",
            field=models.CharField(
                blank=True,
                editable=False,
                help_text="Specific equipment name/ID (optional)",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="plantequipment",
            name="plant_type",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                help_text="Type of plant/equipment",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="equipment_items",
                to="SiteManagement.planttype",
            ),
        ),
        migrations.AlterField(
            model_name="plantequipment",
            name="supplier",
            field=models.CharField(
                blank=True, editable=False, help_text="Supplier/Owner", max_length=255
            ),
        ),
        migrations.AlterField(
            model_name="subcontractorlog",
            name="actual_finish_date",
            field=models.DateField(
                blank=True, editable=False, help_text="Actual finish date", null=True
            ),
        ),
        migrations.AlterField(
            model_name="subcontractorlog",
            name="name",
            field=models.CharField(
                blank=True,
                editable=False,
                help_text="Subcontractor name",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="subcontractorlog",
            name="planned_finish_date",
            field=models.DateField(
                blank=True, editable=False, help_text="Planned finish date", null=True
            ),
        ),
        migrations.AlterField(
            model_name="subcontractorlog",
            name="scope",
            field=models.TextField(
                blank=True, editable=False, help_text="Scope of work"
            ),
        ),
        migrations.AlterField(
            model_name="subcontractorlog",
            name="start_date",
            field=models.DateField(editable=False, help_text="Start date"),
        ),
        migrations.AlterField(
            model_name="subcontractorlog",
            name="trade",
            field=models.CharField(
                blank=True, editable=False, help_text="Trade/specialty", max_length=100
            ),
        ),
        migrations.CreateModel(
            name="MeetingDecision",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When this record was created"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="When this record was last modified"
                    ),
                ),
                (
                    "deleted",
                    models.BooleanField(default=False, help_text="Soft delete flag"),
                ),
                (
                    "description",
                    models.TextField(help_text="Description of the decision made"),
                ),
                (
                    "responsible_person",
                    models.CharField(
                        blank=True,
                        help_text="Person responsible for this decision",
                        max_length=255,
                    ),
                ),
                (
                    "due_date",
                    models.DateField(
                        blank=True,
                        help_text="Date this decision/outcome is due",
                        null=True,
                    ),
                ),
                (
                    "meeting",
                    models.ForeignKey(
                        help_text="Meeting this decision belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="meeting_decisions",
                        to="SiteManagement.meeting",
                    ),
                ),
            ],
            options={
                "verbose_name": "Meeting Decision",
                "verbose_name_plural": "Meeting Decisions",
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="MeetingAction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When this record was created"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="When this record was last modified"
                    ),
                ),
                (
                    "deleted",
                    models.BooleanField(default=False, help_text="Soft delete flag"),
                ),
                ("description", models.TextField(help_text="Action to be performed")),
                (
                    "assigned_to",
                    models.CharField(
                        blank=True,
                        help_text="Person responsible for this action",
                        max_length=255,
                    ),
                ),
                (
                    "due_date",
                    models.DateField(
                        blank=True, help_text="Date this action is due", null=True
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("IN_PROGRESS", "In Progress"),
                            ("COMPLETE", "Complete"),
                        ],
                        default="PENDING",
                        help_text="Current status of the action",
                        max_length=20,
                    ),
                ),
                (
                    "meeting",
                    models.ForeignKey(
                        blank=True,
                        help_text="Meeting this action belongs to",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="meeting_actions",
                        to="SiteManagement.meeting",
                    ),
                ),
                (
                    "decision",
                    models.ForeignKey(
                        blank=True,
                        help_text="Decision this action is linked to",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="decision_actions",
                        to="SiteManagement.meetingdecision",
                    ),
                ),
            ],
            options={
                "verbose_name": "Meeting Action",
                "verbose_name_plural": "Meeting Actions",
                "ordering": ["due_date", "created_at"],
            },
        ),
        migrations.AddField(
            model_name="earlywarning",
            name="source_decision",
            field=models.ForeignKey(
                blank=True,
                help_text="Meeting decision that triggered this early warning",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="linked_early_warnings",
                to="SiteManagement.meetingdecision",
            ),
        ),
        migrations.AddField(
            model_name="nonconformance",
            name="source_decision",
            field=models.ForeignKey(
                blank=True,
                help_text="Meeting decision that triggered this NCR",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="linked_ncrs",
                to="SiteManagement.meetingdecision",
            ),
        ),
        migrations.AddField(
            model_name="rfi",
            name="source_decision",
            field=models.ForeignKey(
                blank=True,
                help_text="Meeting decision that triggered this RFI",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="linked_rfis",
                to="SiteManagement.meetingdecision",
            ),
        ),
        migrations.AddField(
            model_name="siteinstruction",
            name="source_decision",
            field=models.ForeignKey(
                blank=True,
                help_text="Meeting decision that triggered this SI",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="linked_site_instructions",
                to="SiteManagement.meetingdecision",
            ),
        ),
        migrations.CreateModel(
            name="OverheadDailyLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When this record was created"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="When this record was last modified"
                    ),
                ),
                (
                    "deleted",
                    models.BooleanField(default=False, help_text="Soft delete flag"),
                ),
                ("date", models.DateField(help_text="Date of overhead activity")),
                (
                    "category",
                    models.CharField(
                        blank=True,
                        editable=False,
                        help_text="Overhead category",
                        max_length=100,
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True,
                        editable=False,
                        help_text="Brief description",
                        max_length=255,
                    ),
                ),
                (
                    "quantity",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Quantity/Days tracked",
                        max_digits=10,
                    ),
                ),
                (
                    "remarks",
                    models.TextField(blank=True, help_text="Additional remarks"),
                ),
                (
                    "overhead_entity",
                    models.ForeignKey(
                        blank=True,
                        help_text="Link to master overhead definition",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="overhead_daily_logs",
                        to="Project.overheadentity",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        help_text="Project this overhead log belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="overhead_daily_logs",
                        to="Project.project",
                    ),
                ),
            ],
            options={
                "verbose_name": "Overhead Daily Log",
                "verbose_name_plural": "Overhead Daily Logs",
                "ordering": ["-date", "-created_at"],
            },
        ),
    ]
