# Generated by Django 5.2.12 on 2026-04-07 01:47

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "SiteManagement",
            "0012_labourlog_labour_entity_materialslog_material_entity_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="subcontractorlog",
            name="date",
            field=models.DateField(
                default=django.utils.timezone.now, help_text="Date of work entry"
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="labourlog",
            name="id_number",
            field=models.CharField(
                blank=True, editable=False, help_text="ID number", max_length=100
            ),
        ),
        migrations.AlterField(
            model_name="labourlog",
            name="person_name",
            field=models.CharField(
                blank=True, editable=False, help_text="Person's name", max_length=255
            ),
        ),
        migrations.AlterField(
            model_name="labourlog",
            name="skill_type",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                help_text="Skill type of the worker",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="labour_logs",
                to="SiteManagement.skilltype",
            ),
        ),
        migrations.AlterField(
            model_name="labourlog",
            name="trade",
            field=models.CharField(
                blank=True, editable=False, help_text="Trade/specialty", max_length=100
            ),
        ),
        migrations.AlterField(
            model_name="materialslog",
            name="items_received",
            field=models.TextField(
                editable=False, help_text="Description of items received"
            ),
        ),
        migrations.AlterField(
            model_name="materialslog",
            name="supplier",
            field=models.CharField(
                blank=True, editable=False, help_text="Supplier name", max_length=255
            ),
        ),
        migrations.AlterField(
            model_name="materialslog",
            name="unit",
            field=models.CharField(
                blank=True,
                editable=False,
                help_text="Unit of measurement",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="plantequipment",
            name="equipment_name",
            field=models.CharField(
                blank=True,
                editable=False,
                help_text="Specific equipment name/ID (optional)",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="plantequipment",
            name="plant_type",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                help_text="Type of plant/equipment",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="equipment_items",
                to="SiteManagement.planttype",
            ),
        ),
        migrations.AlterField(
            model_name="plantequipment",
            name="supplier",
            field=models.CharField(
                blank=True, editable=False, help_text="Supplier/Owner", max_length=255
            ),
        ),
        migrations.AlterField(
            model_name="subcontractorlog",
            name="actual_finish_date",
            field=models.DateField(
                blank=True, editable=False, help_text="Actual finish date", null=True
            ),
        ),
        migrations.AlterField(
            model_name="subcontractorlog",
            name="name",
            field=models.CharField(
                blank=True,
                editable=False,
                help_text="Subcontractor name",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="subcontractorlog",
            name="planned_finish_date",
            field=models.DateField(
                blank=True, editable=False, help_text="Planned finish date", null=True
            ),
        ),
        migrations.AlterField(
            model_name="subcontractorlog",
            name="scope",
            field=models.TextField(
                blank=True, editable=False, help_text="Scope of work"
            ),
        ),
        migrations.AlterField(
            model_name="subcontractorlog",
            name="start_date",
            field=models.DateField(editable=False, help_text="Start date"),
        ),
        migrations.AlterField(
            model_name="subcontractorlog",
            name="trade",
            field=models.CharField(
                blank=True, editable=False, help_text="Trade/specialty", max_length=100
            ),
        ),
    ]
