# Generated by Django 5.2.12 on 2026-04-08 15:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Project", "0077_labourentity_unit_of_measure_and_more"),
        (
            "SiteManagement",
            "0013_subcontractorlog_date_alter_labourlog_id_number_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="OverheadDailyLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When this record was created"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="When this record was last modified"
                    ),
                ),
                (
                    "deleted",
                    models.BooleanField(default=False, help_text="Soft delete flag"),
                ),
                ("date", models.DateField(help_text="Date of overhead activity")),
                (
                    "category",
                    models.CharField(
                        blank=True,
                        editable=False,
                        help_text="Overhead category",
                        max_length=100,
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True,
                        editable=False,
                        help_text="Brief description",
                        max_length=255,
                    ),
                ),
                (
                    "quantity",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Quantity/Days tracked",
                        max_digits=10,
                    ),
                ),
                (
                    "remarks",
                    models.TextField(blank=True, help_text="Additional remarks"),
                ),
                (
                    "overhead_entity",
                    models.ForeignKey(
                        blank=True,
                        help_text="Link to master overhead definition",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="overhead_daily_logs",
                        to="Project.overheadentity",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        help_text="Project this overhead log belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="overhead_daily_logs",
                        to="Project.project",
                    ),
                ),
            ],
            options={
                "verbose_name": "Overhead Daily Log",
                "verbose_name_plural": "Overhead Daily Logs",
                "ordering": ["-date", "-created_at"],
            },
        ),
    ]
