# Generated by Django 6.0.3 on 2026-04-10 08:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("SiteManagement", "0013_meetingdecision_meetingaction"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="meetingaction",
            name="decision",
        ),
        migrations.AddField(
            model_name="meeting",
            name="other_meeting_type",
            field=models.CharField(
                blank=True,
                help_text="Custom meeting type if 'Other' is selected",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="meetingaction",
            name="meeting",
            field=models.ForeignKey(
                help_text="Meeting this action belongs to",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="meeting_actions",
                to="SiteManagement.meeting",
            ),
        ),
        migrations.AddField(
            model_name="meetingdecision",
            name="due_date",
            field=models.DateField(
                blank=True, help_text="Date this decision/outcome is due", null=True
            ),
        ),
        migrations.AddField(
            model_name="meetingdecision",
            name="responsible_person",
            field=models.CharField(
                blank=True,
                help_text="Person responsible for this decision",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="meeting",
            name="meeting_type",
            field=models.CharField(
                choices=[
                    ("PROGRESS", "Progress"),
                    ("CONTRACTUAL", "Contractual"),
                    ("RISK", "Risk"),
                    ("EARLY_WARNING", "Early Warning"),
                    ("OTHER", "Other"),
                ],
                help_text="Type of meeting",
                max_length=20,
            ),
        ),
    ]
