# Generated by Django 5.2.12 on 2026-04-10 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("SiteManagement", "0012_progresstracker_impact_description_and_more"),
        ("SiteManagement", "0014_overheaddailylog"),
    ]

    operations = []
