# Generated by Django 6.0.3 on 2026-04-10 10:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("SiteManagement", "0014_remove_meetingaction_decision_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="earlywarning",
            name="source_decision",
            field=models.ForeignKey(
                blank=True,
                help_text="Meeting decision that triggered this early warning",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="linked_early_warnings",
                to="SiteManagement.meetingdecision",
            ),
        ),
        migrations.AddField(
            model_name="meetingaction",
            name="decision",
            field=models.ForeignKey(
                blank=True,
                help_text="Decision this action is linked to",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="decision_actions",
                to="SiteManagement.meetingdecision",
            ),
        ),
        migrations.AddField(
            model_name="nonconformance",
            name="source_decision",
            field=models.ForeignKey(
                blank=True,
                help_text="Meeting decision that triggered this NCR",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="linked_ncrs",
                to="SiteManagement.meetingdecision",
            ),
        ),
        migrations.AddField(
            model_name="rfi",
            name="source_decision",
            field=models.ForeignKey(
                blank=True,
                help_text="Meeting decision that triggered this RFI",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="linked_rfis",
                to="SiteManagement.meetingdecision",
            ),
        ),
        migrations.AddField(
            model_name="siteinstruction",
            name="source_decision",
            field=models.ForeignKey(
                blank=True,
                help_text="Meeting decision that triggered this SI",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="linked_site_instructions",
                to="SiteManagement.meetingdecision",
            ),
        ),
        migrations.AlterField(
            model_name="meetingaction",
            name="meeting",
            field=models.ForeignKey(
                blank=True,
                help_text="Meeting this action belongs to",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="meeting_actions",
                to="SiteManagement.meeting",
            ),
        ),
    ]
