# Generated by Django 5.2.12 on 2026-04-12 07:57

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("SiteManagement", "0014_overheaddailylog"),
        (
            "SiteManagement",
            "0015_earlywarning_source_decision_meetingaction_decision_and_more",
        ),
    ]

    operations = []
