from .activity_views import (
    GetProjectLaborActivitiesAjaxView,
    LaborActivityDetailView,
    LaborActivityListView,
)
from .dashboard_views import (
    PlanProductivityDashboardView,
    ProductionActivityDetailView,
    ProductionProgressDashboardView,
)
from .planning_views import (
    GetProjectBillsAjaxView,
    GetProjectItemsAjaxView,
    ProductionCashflowForecastView,
    ProductionCostBreakdownDetailView,
    ProductionCostBreakdownView,
    ProductionPlanAjaxDetailView,
    ProductionPlanAutofillView,
    ProductionPlanCreateView,
    ProductionPlanDeleteView,
    ProductionPlanDetailView,
    ProductionPlanGanttView,
    ProductionPlanListView,
    ProductionPlanRefreshAjaxView,
    ProductionPlanUpdateView,
    ProductionResourceCreateView,
)
from .productivity_views import (
    DailyActivityEntryUpdateView,
    DailyLogActivityDataAjaxView,
    DailyProductionCreateView,
    ProductionDailyLogCreateView,
    ProductionDailyLogDeleteView,
    ProductionDailyLogDetailView,
    ProductionDailyLogListView,
    ProductionDailyLogUpdateView,
)
from .reports_views import (
    ProductionControllerView,
    ProductionForecastDashboardView,
    ProductionPerformanceReportView,
    ProductionProductivityReportView,
    ProductionProgressReportView,
    ProductivityLogsView,
)
from .tracking_views import ProgressTrackingView

__all__ = [
    "ProductionProgressDashboardView",
    "ProductionActivityDetailView",
    "PlanProductivityDashboardView",
    "ProductionPlanCreateView",
    "ProductionPlanGanttView",
    "ProductionPlanListView",
    "ProductionPlanDetailView",
    "ProductionPlanUpdateView",
    "ProductionPlanDeleteView",
    "ProductionCostBreakdownView",
    "ProductionCostBreakdownDetailView",
    "ProductionResourceCreateView",
    "DailyProductionCreateView",
    "ProductivityLogsView",
    "ProductionForecastDashboardView",
    "ProgressTrackingView",
    "ProductionPlanAjaxDetailView",
    "GetProjectBillsAjaxView",
    "GetProjectItemsAjaxView",
    "LaborActivityListView",
    "LaborActivityDetailView",
    "GetProjectLaborActivitiesAjaxView",
    "ProductionDailyLogListView",
    "ProductionDailyLogCreateView",
    "ProductionDailyLogDetailView",
    "DailyLogActivityDataAjaxView",
    "ProductionPlanRefreshAjaxView",
    "ProductionDailyLogUpdateView",
    "ProductionDailyLogDeleteView",
    "ProductionPlanAutofillView",
    "ProductionCashflowForecastView",
    "ProductionPerformanceReportView",
    "ProductionProductivityReportView",
    "ProductionProgressReportView",
    "DailyActivityEntryUpdateView",
    "ProductionControllerView",
]
