# Generated by Django 6.0.2 on 2026-02-13 13:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("BillOfQuantities", "0019_alter_claim_period"),
        ("Project", "0037_alter_projectdocument_category"),
    ]

    operations = [
        migrations.CreateModel(
            name="Vat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When this record was created"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="When this record was last modified"
                    ),
                ),
                (
                    "deleted",
                    models.BooleanField(default=False, help_text="Soft delete flag"),
                ),
                ("rate", models.DecimalField(decimal_places=2, max_digits=5)),
                ("name", models.CharField(max_length=100)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
            ],
            options={
                "verbose_name": "VAT",
                "verbose_name_plural": "VATs",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Ledger",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When this record was created"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="When this record was last modified"
                    ),
                ),
                (
                    "deleted",
                    models.BooleanField(default=False, help_text="Soft delete flag"),
                ),
                (
                    "financial_statement",
                    models.CharField(
                        choices=[
                            ("balance_sheet", "Balance Sheet"),
                            ("income_statement", "Income Statement"),
                            ("cash_flow_statement", "Cash Flow Statement"),
                            (
                                "statement_of_changes_in_equity",
                                "Statement of Changes in Equity",
                            ),
                        ],
                        default="balance_sheet",
                        max_length=35,
                    ),
                ),
                ("code", models.CharField(max_length=10)),
                ("name", models.CharField(max_length=100)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Project.company",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ledger",
                "verbose_name_plural": "Ledgers",
                "ordering": ["financial_statement", "code", "name"],
            },
        ),
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When this record was created"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="When this record was last modified"
                    ),
                ),
                (
                    "deleted",
                    models.BooleanField(default=False, help_text="Soft delete flag"),
                ),
                ("date", models.DateField()),
                (
                    "type",
                    models.CharField(
                        choices=[("debit", "Debit"), ("credit", "Credit")],
                        max_length=20,
                    ),
                ),
                (
                    "amount_excl_vat",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "amount_incl_vat",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("vat", models.BooleanField(default=False)),
                (
                    "ledger",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="Ledger.ledger",
                    ),
                ),
                (
                    "package",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="BillOfQuantities.package",
                    ),
                ),
                (
                    "vat_rate",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="Ledger.vat",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
