# Generated by Django 6.0.2 on 2026-02-16 10:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Ledger", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vat",
            name="end_date",
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name="vat",
            name="start_date",
            field=models.DateField(null=True),
        ),
    ]
