# Generated by Django 6.0.2 on 2026-02-16 11:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("BillOfQuantities", "0019_alter_claim_period"),
        ("Ledger", "0003_seed_default_vat_rates"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="package",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="BillOfQuantities.bill",
            ),
        ),
    ]
