# Generated by Django 6.0.2 on 2026-02-16 12:13

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("Ledger", "0004_alter_transaction_package"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="vat",
            options={
                "ordering": ["-start_date"],
                "verbose_name": "VAT",
                "verbose_name_plural": "VATs",
            },
        ),
        migrations.RenameField(
            model_name="transaction",
            old_name="package",
            new_name="bill",
        ),
    ]
