# Generated by Django 6.0.2 on 2026-02-16 14:28

import django.db.models.deletion
from django.db import migrations, models


def validate_company_from_bill(apps, schema_editor):
    """
    Validate company field from bill.structure.project.company.
    This will be run before making the field non-nullable.
    """
    Transaction = apps.get_model("Ledger", "Transaction")

    # Get all transactions that have a bill but no company
    transactions = Transaction.objects.all()

    for transaction in transactions:
        try:
            # Get company through bill -> structure -> project -> contractor
            company = transaction.ledger.company
            if not company:
                raise ValueError("Company not found")
        except Exception as e:
            # If we can't trace the company, we'll leave it as null
            # and handle it in the next step
            raise ValueError("Company not found") from e


def populate_company_from_bill(apps, schema_editor):
    """
    Populate company field from bill.structure.project.company.
    This will be run before making the field non-nullable.
    """
    Transaction = apps.get_model("Ledger", "Transaction")
    Bill = apps.get_model("BillOfQuantities", "Bill")
    Structure = apps.get_model("BillOfQuantities", "Structure")

    # Get all transactions that have a bill but no company
    transactions = Transaction.objects.filter(company__isnull=True, bill__isnull=False)

    for transaction in transactions:
        try:
            # Get company through bill -> structure -> project -> company
            company = transaction.ledger.company
            transaction.company = company
            transaction.save(update_fields=["company"])
        except (Bill.DoesNotExist, Structure.DoesNotExist, AttributeError):
            # If we can't trace the company, we'll leave it as null
            # and handle it in the next step
            pass


class Migration(migrations.Migration):
    dependencies = [
        ("Ledger", "0005_alter_vat_options_rename_package_transaction_bill"),
        ("Project", "0037_alter_projectdocument_category"),
    ]

    operations = [
        # Step 0: Validate company exists
        migrations.RunPython(
            validate_company_from_bill, reverse_code=migrations.RunPython.noop
        ),
        # Step 1: Add company field as nullable (allowing null values)
        migrations.AddField(
            model_name="transaction",
            name="company",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="Project.company",
            ),
        ),
        # Step 2: Run data migration to populate company from bill.structure.project.company
        migrations.RunPython(
            populate_company_from_bill, reverse_code=migrations.RunPython.noop
        ),
        # Step 3: Make the company field non-nullable
        migrations.AlterField(
            model_name="transaction",
            name="company",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="Project.company"
            ),
        ),
    ]
