# Generated by Django 6.0.2 on 2026-02-17 08:20
import django.db.models.deletion
from django.db import migrations, models
from django.db.models import QuerySet

from app.Ledger.models import Transaction


def populate_new_fields(apps, schema_editor):
    """
    Validate company field from bill.structure.project.company.
    This will be run before making the field non-nullable.
    """
    # Get all transactions that have a bill but no company
    transactions: QuerySet[Transaction] = Transaction.objects.all()

    for transaction in transactions:
        if all(
            [
                transaction.bill,
                transaction.bill.structure,
                transaction.bill.structure.project,
            ]
        ):
            transaction.project = transaction.bill.structure.project
            transaction.structure = transaction.bill.structure
            transaction.save()


class Migration(migrations.Migration):
    dependencies = [
        ("BillOfQuantities", "0019_alter_claim_period"),
        ("Ledger", "0006_transaction_company"),
        ("Project", "0037_alter_projectdocument_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="project",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="Project.project",
            ),
        ),
        migrations.AddField(
            model_name="transaction",
            name="structure",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="BillOfQuantities.structure",
            ),
        ),
        migrations.RunPython(
            populate_new_fields,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
