# Generated by Django 6.0.2 on 2026-02-19 07:13

from django.db import migrations, models


def seed_financial_statements(apps, schema_editor):
    FinancialStatement = apps.get_model("Ledger", "FinancialStatement")
    statements = [
        "Balance Sheet",
        "Income Statement",
        "Cash Flow Statement",
        "Statement of Changes in Equity",
    ]
    for name in statements:
        FinancialStatement.objects.get_or_create(name=name)


class Migration(migrations.Migration):
    dependencies = [
        ("Ledger", "0007_transaction_project_transaction_structure"),
    ]

    operations = [
        migrations.CreateModel(
            name="FinancialStatement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When this record was created"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="When this record was last modified"
                    ),
                ),
                (
                    "deleted",
                    models.BooleanField(default=False, help_text="Soft delete flag"),
                ),
                ("name", models.CharField(max_length=100)),
            ],
            options={
                "verbose_name": "Financial Statement",
                "verbose_name_plural": "Financial Statements",
                "ordering": ["name"],
            },
        ),
        migrations.RunPython(
            seed_financial_statements,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
