# Generated by Django 6.0.2 on 2026-02-22 11:52

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("Ledger", "0009_migrate_financial_statement_to_fk"),
    ]

    operations = [
        migrations.RenameField(
            model_name="transaction",
            old_name="ledger",
            new_name="debit_ledger",
        ),
    ]
