# Generated by Django 6.0.2 on 2026-02-22 11:54

import django.db.models.deletion
from django.db import migrations, models


def populate_credit_ledger_with_suspense(apps, schema_editor):
    """Populate credit_ledger with the Suspense Account ledger."""
    Transaction = apps.get_model("Ledger", "Transaction")
    Ledger = apps.get_model("Ledger", "Ledger")
    FinancialStatement = apps.get_model("Ledger", "FinancialStatement")
    balance_sheet, _ = FinancialStatement.objects.get_or_create(name="Balance Sheet")
    Ledger.objects.filter(name="Suspense_account").delete()
    for transaction in Transaction.objects.filter(credit_ledger__isnull=True):
        suspense_ledger, _ = Ledger.objects.get_or_create(
            company=transaction.company,
            financial_statement=balance_sheet,
            name="Suspense Account",
            code="9999",
        )
        transaction.credit_ledger = suspense_ledger
        transaction.save(update_fields=["credit_ledger"])


class Migration(migrations.Migration):
    dependencies = [
        ("Ledger", "0010_rename_ledger_transaction_debit_ledger"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="credit_ledger",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="credit_transactions",
                to="Ledger.ledger",
            ),
        ),
        migrations.RunPython(
            populate_credit_ledger_with_suspense,
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.AlterField(
            model_name="transaction",
            name="debit_ledger",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="debit_transactions",
                to="Ledger.ledger",
            ),
        ),
    ]
