# Generated by Django 6.0.2 on 2026-02-22 11:54

import django.db.models.deletion
from django.db import migrations, models


def populate_credit_ledger_with_suspense(apps, schema_editor):
    """Populate credit_ledger with the Suspense Account ledger."""
    Ledger = apps.get_model("Ledger", "Ledger")
    FinancialStatement = apps.get_model("Ledger", "FinancialStatement")
    balance_sheet, _ = FinancialStatement.objects.get_or_create(name="Balance Sheet")
    ledgers = Ledger.objects.filter(
        financial_statement=balance_sheet, name="Suspense Account"
    )
    for ledger in ledgers:
        ledger.code = "9999"
        ledger.save()


class Migration(migrations.Migration):
    dependencies = [
        ("Ledger", "0011_transaction_credit_ledger_and_more"),
    ]

    operations = [
        migrations.RunPython(
            populate_credit_ledger_with_suspense,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
