# Generated by Django 6.0.2 on 2026-02-22 12:09

import django.db.models.deletion
from django.db import migrations, models


def handle_duplicate_ledgers(apps, schema_editor):
    """Handle duplicate ledger codes and names before adding unique constraints."""
    Ledger = apps.get_model("Ledger", "Ledger")

    # Handle duplicate codes
    ledgers_by_company_code = {}
    for ledger in Ledger.objects.all().order_by("id"):
        key = (ledger.company_id, ledger.code)
        if key not in ledgers_by_company_code:
            ledgers_by_company_code[key] = []
        ledgers_by_company_code[key].append(ledger)

    # Append suffix to duplicate codes
    for (_company_id, code), duplicates in ledgers_by_company_code.items():
        if len(duplicates) > 1:
            for i, ledger in enumerate(duplicates[1:], start=1):
                ledger.code = f"{code}-{i}"
                ledger.save()

    # Handle duplicate names
    ledgers_by_company_name = {}
    for ledger in Ledger.objects.all().order_by("id"):
        key = (ledger.company_id, ledger.name)
        if key not in ledgers_by_company_name:
            ledgers_by_company_name[key] = []
        ledgers_by_company_name[key].append(ledger)

    # Append suffix to duplicate names
    for (_company_id, name), duplicates in ledgers_by_company_name.items():
        if len(duplicates) > 1:
            for i, ledger in enumerate(duplicates[1:], start=1):
                ledger.name = f"{name}-{i}"
                ledger.save()


class Migration(migrations.Migration):
    dependencies = [
        ("Ledger", "0012_fix_suspense"),
        ("Project", "0037_alter_projectdocument_category"),
    ]

    operations = [
        # Handle duplicates before adding constraints
        migrations.RunPython(handle_duplicate_ledgers, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="financialstatement",
            name="name",
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AddConstraint(
            model_name="ledger",
            constraint=models.UniqueConstraint(
                fields=("company", "code"), name="unique_ledger_code"
            ),
        ),
        migrations.AddConstraint(
            model_name="ledger",
            constraint=models.UniqueConstraint(
                fields=("company", "name"), name="unique_ledger_name"
            ),
        ),
    ]
