# Generated by Django 6.0.2 on 2026-02-22 14:31

from django.db import migrations


def set_missing_ledgers_to_suspense(apps, schema_editor):
    """Set missing debit/credit ledgers to company's suspense account."""
    Transaction = apps.get_model("Ledger", "Transaction")
    Ledger = apps.get_model("Ledger", "Ledger")
    FinancialStatement = apps.get_model("Ledger", "FinancialStatement")

    # Get or create Balance Sheet financial statement
    balance_sheet, _ = FinancialStatement.objects.get_or_create(name="Balance Sheet")

    # Process each company
    companies = Transaction.objects.values_list("company_id", flat=True).distinct()

    for company_id in companies:
        # Get or create suspense account for this company
        suspense_ledger, created = Ledger.objects.get_or_create(
            company_id=company_id,
            name="Suspense Account",
            defaults={
                "code": "9999",
                "financial_statement": balance_sheet,
            },
        )

        # Update transactions with missing debit_ledger
        Transaction.objects.filter(
            company_id=company_id, debit_ledger__isnull=True
        ).update(debit_ledger=suspense_ledger)

        # Update transactions with missing credit_ledger
        Transaction.objects.filter(
            company_id=company_id, credit_ledger__isnull=True
        ).update(credit_ledger=suspense_ledger)


class Migration(migrations.Migration):
    dependencies = [
        ("Ledger", "0013_transaction_credit_ledger_and_more"),
    ]

    operations = [
        migrations.RunPython(
            set_missing_ledgers_to_suspense,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
