# Generated by Django 6.0.2 on 2026-02-22 12:54

from django.db import migrations

# Standard chart of accounts data (imported from chart_data.py)
STANDARD_CHART_OF_ACCOUNTS = [
    # Assets (Balance Sheet) - 1000-1999
    ("1000", "Cash and Cash Equivalents", "Balance Sheet"),
    ("1100", "Accounts Receivable", "Balance Sheet"),
    ("1200", "Inventory", "Balance Sheet"),
    ("1300", "Prepaid Expenses", "Balance Sheet"),
    ("1400", "Property, Plant and Equipment", "Balance Sheet"),
    ("1500", "Accumulated Depreciation", "Balance Sheet"),
    ("1600", "Intangible Assets", "Balance Sheet"),
    # Liabilities (Balance Sheet) - 2000-2999
    ("2000", "Accounts Payable", "Balance Sheet"),
    ("2100", "Accrued Expenses", "Balance Sheet"),
    ("2200", "Taxes Payable", "Balance Sheet"),
    ("2300", "Short-term Debt", "Balance Sheet"),
    ("2400", "Long-term Debt", "Balance Sheet"),
    ("2500", "Deferred Revenue", "Balance Sheet"),
    # Equity (Balance Sheet) - 3000-3999
    ("3000", "Share Capital", "Balance Sheet"),
    ("3100", "Retained Earnings", "Balance Sheet"),
    ("3200", "Additional Paid-in Capital", "Balance Sheet"),
    ("3300", "Dividends Paid", "Balance Sheet"),
    # Revenue (Income Statement) - 4000-4999
    ("4000", "Sales Revenue", "Income Statement"),
    ("4100", "Service Revenue", "Income Statement"),
    ("4200", "Interest Income", "Income Statement"),
    ("4300", "Other Income", "Income Statement"),
    ("4400", "Sales Returns and Allowances", "Income Statement"),
    ("4500", "Sales Discounts", "Income Statement"),
    # Cost of Goods Sold (Income Statement) - 5000-5999
    ("5000", "Cost of Goods Sold", "Income Statement"),
    ("5100", "Purchase Returns", "Income Statement"),
    ("5200", "Purchase Discounts", "Income Statement"),
    ("5300", "Freight-in", "Income Statement"),
    # Operating Expenses (Income Statement) - 6000-6999
    ("6000", "Salaries and Wages", "Income Statement"),
    ("6100", "Rent Expense", "Income Statement"),
    ("6200", "Utilities Expense", "Income Statement"),
    ("6300", "Insurance Expense", "Income Statement"),
    ("6400", "Depreciation Expense", "Income Statement"),
    ("6500", "Bad Debt Expense", "Income Statement"),
    ("6600", "Marketing and Advertising", "Income Statement"),
    ("6700", "Office Supplies", "Income Statement"),
    ("6800", "Professional Fees", "Income Statement"),
    ("6900", "Travel and Entertainment", "Income Statement"),
    # Other Expenses (Income Statement) - 7000-7999
    ("7000", "Interest Expense", "Income Statement"),
    ("7100", "Tax Expense", "Income Statement"),
    ("7200", "Loss on Sale of Assets", "Income Statement"),
    ("7300", "Other Operating Expenses", "Income Statement"),
    # Non-operating Items (Income Statement) - 8000-8999
    ("8000", "Gain on Sale of Assets", "Income Statement"),
    ("8100", "Loss on Sale of Assets", "Income Statement"),
    ("8200", "Other Non-operating Income", "Income Statement"),
    ("8300", "Other Non-operating Expenses", "Income Statement"),
    # Suspense Account (Balance Sheet) - 9999
    ("9999", "Suspense Account", "Balance Sheet"),
]

# Create a mapping of ledger code to financial statement name
CODE_TO_STATEMENT = {
    code: statement_name for code, name, statement_name in STANDARD_CHART_OF_ACCOUNTS
}


def create_financial_statements(apps, schema_editor):
    """Create the required financial statement types."""
    FinancialStatement = apps.get_model("Ledger", "FinancialStatement")

    # Create Balance Sheet and Income Statement if they don't exist
    for statement_name in ["Balance Sheet", "Income Statement"]:
        FinancialStatement.objects.get_or_create(name=statement_name)


def fix_ledger_financial_statements(apps, schema_editor):
    """Update existing ledgers to have the correct financial statements."""
    Ledger = apps.get_model("Ledger", "Ledger")
    FinancialStatement = apps.get_model("Ledger", "FinancialStatement")

    # Get the financial statements
    balance_sheet = FinancialStatement.objects.get(name="Balance Sheet")
    income_statement = FinancialStatement.objects.get(name="Income Statement")

    # Update ledgers based on their codes
    for ledger in Ledger.objects.all():
        if ledger.code in CODE_TO_STATEMENT:
            statement_name = CODE_TO_STATEMENT[ledger.code]
            if statement_name == "Balance Sheet":
                ledger.financial_statement = balance_sheet
            elif statement_name == "Income Statement":
                ledger.financial_statement = income_statement
            ledger.save()


class Migration(migrations.Migration):
    dependencies = [
        ("Ledger", "0014_set_missing_ledgers_to_suspense"),
    ]

    operations = [
        migrations.RunPython(create_financial_statements),
        migrations.RunPython(fix_ledger_financial_statements),
    ]
