# Generated by Django 6.0.2 on 2026-02-22 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Ledger', '0015_fix_financial_statements'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='type',
        ),
    ]
