# Generated by Django 6.0.3 on 2026-03-31 08:14

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("Ledger", "0016_remove_transaction_type"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="transaction",
            options={"base_manager_name": "objects"},
        ),
    ]
