from django.urls import path

from ..views import production_views as views

urlpatterns = [
    path(
        "<int:project_pk>/dashboard/",
        views.ProductionDashboardView.as_view(),
        name="production-dashboard",
    ),
    path(
        "<int:project_pk>/planning/",
        views.ProductionPlanningView.as_view(),
        name="production-planning",
    ),
    path(
        "<int:project_pk>/cost-breakdown/",
        views.ProductionCostBreakdownView.as_view(),
        name="production-cost-breakdown",
    ),
    path(
        "<int:project_pk>/plan/<int:pk>/",
        views.ProductionPlanDetailView.as_view(),
        name="production-plan-detail",
    ),
    path(
        "<int:project_pk>/plan/<int:pk>/edit/",
        views.ProductionPlanUpdateView.as_view(),
        name="production-plan-edit",
    ),
    path(
        "<int:project_pk>/plan/<int:pk>/delete/",
        views.ProductionPlanDeleteView.as_view(),
        name="production-plan-delete",
    ),
    path(
        "<int:project_pk>/logs/",
        views.ProductivityLogsView.as_view(),
        name="production-list",
    ),
    path(
        "<int:project_pk>/productivity/add/",
        views.DailyProductivityCreateView.as_view(),
        name="production-create",
    ),
    path(
        "<int:project_pk>/tracking/",
        views.ProgressTrackingView.as_view(),
        name="production-tracking",
    ),
    path(
        "<int:project_pk>/resource/add/",
        views.ProductionResourceCreateView.as_view(),
        name="production-resource-add",
    ),
    path(
        "<int:project_pk>/progress-dashboard/",
        views.ProductionProgressDashboardView.as_view(),
        name="production-progress-dashboard",
    ),
    path(
        "<int:project_pk>/activity/<int:pk>/",
        views.ProductionActivityDetailView.as_view(),
        name="activity-detail",
    ),
    path(
        "<int:project_pk>/plan-productivity-dashboard/",
        views.PlanProductivityDashboardView.as_view(),
        name="plan-productivity-dashboard",
    ),
    path(
        "<int:project_pk>/forecast-dashboard/",
        views.ProductionForecastDashboardView.as_view(),
        name="production-forecast-dashboard",
    ),
    path(
        "<int:project_pk>/productivity/resources/ajax/",
        views.PlanResourcesAjaxView.as_view(),
        name="plan-resources-ajax",
    ),
]
