# Generated by Django 5.2.6 on 2025-11-20 08:17

import django.db.models.deletion
from django.db import migrations, models

import app.Inventories.models
import app.Inventories.models_suppliers


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Bank",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("bank", models.CharField(max_length=100)),
                ("branch", models.CharField(max_length=6)),
            ],
        ),
        migrations.CreateModel(
            name="Inventory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.CharField(max_length=240)),
                ("active", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="Note",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.CharField(max_length=240)),
            ],
        ),
        migrations.CreateModel(
            name="Supplier",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.CharField(max_length=65)),
                ("company_registration", models.CharField(max_length=65)),
                ("vat", models.BooleanField(default=True)),
                ("vat_number", models.BigIntegerField(blank=True, null=True)),
                ("primary_contact", models.BigIntegerField()),
                ("email", models.CharField(max_length=100)),
                ("active", models.BooleanField(default=True)),
                ("address", models.CharField(blank=True, max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name="Type",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.CharField(max_length=240)),
            ],
        ),
        migrations.CreateModel(
            name="VAT",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.CharField(max_length=240)),
                ("percentage", models.DecimalField(decimal_places=2, max_digits=3)),
            ],
        ),
        migrations.CreateModel(
            name="Warehouse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.CharField(max_length=240)),
            ],
        ),
        migrations.CreateModel(
            name="OrderComposition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("qty_ordered", models.DecimalField(decimal_places=3, max_digits=10)),
                (
                    "qty_delivered",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=10, null=True
                    ),
                ),
                (
                    "qty_returned",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=10, null=True
                    ),
                ),
                ("price_excl", models.DecimalField(decimal_places=3, max_digits=10)),
                ("price_incl", models.DecimalField(decimal_places=3, max_digits=10)),
                (
                    "inventory",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="Inventories.inventory",
                    ),
                ),
                (
                    "vat",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="Inventories.vat",
                    ),
                ),
                (
                    "warehouse",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="Inventories.warehouse",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateTimeField()),
                (
                    "status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Pending", "Pending"),
                            ("Delivered", "Delivered"),
                            ("Returned", "Returned"),
                            ("Completed", "Completed"),
                        ],
                        default="Pending",
                        max_length=20,
                    ),
                ),
                (
                    "quote",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to=app.Inventories.models.quote_upload_path,
                    ),
                ),
                ("note", models.ManyToManyField(to="Inventories.note")),
                ("order", models.ManyToManyField(to="Inventories.ordercomposition")),
                (
                    "supplier",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="Inventories.supplier",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="BankingDetail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("account", models.CharField(max_length=25)),
                ("account_holder", models.CharField(max_length=100)),
                (
                    "bank",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="Inventories.bank",
                    ),
                ),
                (
                    "supplier",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Inventories.supplier",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateTimeField()),
                ("description", models.CharField(max_length=100)),
                (
                    "category",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Invoice", "Invoice"),
                            ("Credit Note", "Credit Note"),
                            ("Debit Note", "Debit Note"),
                        ],
                        default="Invoice",
                        max_length=20,
                    ),
                ),
                ("amount_excl", models.DecimalField(decimal_places=3, max_digits=10)),
                ("amount_incl", models.DecimalField(decimal_places=3, max_digits=10)),
                (
                    "supplier",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="transactions",
                        to="Inventories.supplier",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Invoice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateTimeField()),
                (
                    "invoice",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to=app.Inventories.models_suppliers.supplier_invoice_upload_path,
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="Inventories.order",
                    ),
                ),
                (
                    "supplier",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="Inventories.supplier",
                    ),
                ),
                ("tx", models.ManyToManyField(to="Inventories.transaction")),
            ],
        ),
        migrations.AddField(
            model_name="inventory",
            name="type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="Inventories.type",
            ),
        ),
        migrations.CreateModel(
            name="InventoryTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateTimeField()),
                (
                    "type",
                    models.CharField(
                        blank=True,
                        choices=[("In", "In"), ("Out", "Out")],
                        default="In",
                        max_length=20,
                    ),
                ),
                ("qty", models.DecimalField(decimal_places=3, max_digits=10)),
                ("price_excl", models.DecimalField(decimal_places=3, max_digits=10)),
                ("price_incl", models.DecimalField(decimal_places=3, max_digits=10)),
                (
                    "delivery_note",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to=app.Inventories.models.delivery_note_upload_path,
                    ),
                ),
                (
                    "bookings",
                    models.ManyToManyField(to="Inventories.inventorytransaction"),
                ),
                (
                    "inventory",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="Inventories.inventory",
                    ),
                ),
                (
                    "order_composition",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="Inventories.ordercomposition",
                    ),
                ),
                (
                    "supplier_invoice",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="Inventories.transaction",
                    ),
                ),
                (
                    "warehouse",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="Inventories.warehouse",
                    ),
                ),
            ],
        ),
    ]
