# Generated by Django 5.2.6 on 2025-10-13 08:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Account", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="account",
            name="ownership",
        ),
        migrations.AddField(
            model_name="account",
            name="type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Contractor", "Contractor"),
                    ("Client", "Client"),
                    ("Consultant", "Consultant"),
                ],
                default="Contractor",
                max_length=50,
            ),
        ),
    ]
