# Generated by Django 5.2.6 on 2026-01-22 08:48

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("Account", "0003_group"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Group",
        ),
    ]
