# Generated by Django 6.0.2 on 2026-02-11 07:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Account", "0004_delete_group"),
    ]

    operations = [
        migrations.AddField(
            model_name="account",
            name="email_verified",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="account",
            name="email_verified_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
