# Generated by Django 6.0.2 on 2026-03-02 08:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Account", "0005_account_email_verified_account_email_verified_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="account",
            name="subscription",
            field=models.CharField(
                choices=[
                    ("FREE_TIER", "Free Tier"),
                    ("PAYMENTS_AND_INVOICES", "Payments and Invoices"),
                    ("PROFIT_AND_LOSS", "Profit and Loss"),
                    ("SITE_MANAGEMENT", "Site Management"),
                    ("PROJECT_ESTIMATOR", "Project Estimator"),
                ],
                default="FREE_TIER",
                help_text="Subscription tier",
                max_length=50,
            ),
        ),
    ]
