# Generated by Django 6.0.2 on 2026-03-02 20:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Account", "0007_alter_account_subscription"),
    ]

    operations = [
        migrations.AlterField(
            model_name="account",
            name="subscription",
            field=models.CharField(
                choices=[
                    ("FREE_TIER", "Free Tier"),
                    ("BUSINESS_MANAGEMENT", "Business Management Module"),
                    ("PAYMENTS_AND_INVOICES", "Payments and Invoices"),
                    ("PROFIT_AND_LOSS", "Profit and Loss"),
                    ("SITE_MANAGEMENT", "Site Management"),
                    ("PROJECT_ESTIMATOR", "Project Estimator"),
                    ("ADMINISTRATION", "Administration"),
                ],
                default="FREE_TIER",
                help_text="Subscription tier",
                max_length=50,
            ),
        ),
    ]
