# Generated by Django 6.0.4 on 2026-04-20 08:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Account", "0009_set_superusers_to_administration"),
    ]

    operations = [
        migrations.CreateModel(
            name="Municipality",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When this record was created"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="When this record was last modified"
                    ),
                ),
                (
                    "deleted",
                    models.BooleanField(default=False, help_text="Soft delete flag"),
                ),
                ("province", models.CharField(max_length=255)),
                ("municipality_name", models.CharField(max_length=255)),
                ("code", models.CharField(max_length=10)),
                ("district", models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                "verbose_name": "Municipality",
                "verbose_name_plural": "Municipalities",
                "ordering": ["province", "municipality_name"],
                "unique_together": {("province", "municipality_name", "code")},
            },
        ),
    ]
