# Generated by Django 6.0.3 on 2026-04-20 10:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Account", "0010_municipality"),
    ]

    operations = [
        migrations.AlterField(
            model_name="municipality",
            name="district",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
    ]
