# Generated by Django 5.2.12 on 2026-05-14 06:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Account", "0011_alter_municipality_district"),
    ]

    operations = [
        migrations.AddField(
            model_name="account",
            name="subscription_expires_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Expiry date for demo/trial subscriptions",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="account",
            name="subscription",
            field=models.CharField(
                choices=[
                    ("FREE_TIER", "Free Tier"),
                    ("BUSINESS_MANAGEMENT", "Business Management Module"),
                    ("PAYMENTS_AND_INVOICES", "Payments and Invoices"),
                    ("PROFIT_AND_LOSS", "Profit and Loss"),
                    ("SITE_MANAGEMENT", "Site Management"),
                    ("PROJECT_ESTIMATOR", "Project Estimator"),
                    ("ADMINISTRATION", "Administration"),
                    ("DEMO_TIER", "Demo"),
                ],
                default="FREE_TIER",
                help_text="Subscription tier",
                max_length=50,
            ),
        ),
    ]
