# Generated by Django 5.2.12 on 2026-05-16 15:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Account", "0012_account_subscription_expires_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="account",
            name="subscription",
            field=models.CharField(
                choices=[
                    ("FREE_TIER", "Free Tier"),
                    ("BUSINESS_MANAGEMENT", "Business Management Module"),
                    ("PAYMENTS_AND_INVOICES", "Payments and Invoices"),
                    ("PROFIT_AND_LOSS", "Profit and Loss"),
                    ("SITE_MANAGEMENT", "Project Management"),
                    ("PROJECT_ESTIMATOR", "Project Estimator"),
                    ("ADMINISTRATION", "Administration"),
                    ("DEMO_TIER", "Demo"),
                ],
                default="DEMO_TIER",
                help_text="Subscription tier",
                max_length=50,
            ),
        ),
    ]
