# Generated by Django 5.2.12 on 2026-06-25 10:01

import django.db.models.deletion
from django.db import migrations, models


def _generate_province_code(Province, province_name):
    """Generate a unique province code using initials, with numeric fallback."""
    # Build initials from each word (e.g. "Northern Cape" -> "NC")
    words = province_name.split()
    initials = "".join(w[0].upper() for w in words if w)
    candidate = initials or province_name[:3].upper()

    if not Province.objects.filter(code=candidate).exists():
        return candidate

    # Fall back: try initials + counter suffix
    counter = 2
    while True:
        suffixed = f"{candidate}{counter}"
        if not Province.objects.filter(code=suffixed).exists():
            return suffixed
        counter += 1


def migrate_provinces(apps, schema_editor):
    Province = apps.get_model("Account", "Province")
    Municipality = apps.get_model("Account", "Municipality")

    for mun in Municipality.objects.all():
        if mun.old_province:
            province_name = mun.old_province.strip()
            province_obj, created = Province.objects.get_or_create(name=province_name)
            if created:
                province_obj.code = _generate_province_code(Province, province_name)
                province_obj.save()
            mun.province = province_obj
            mun.save()


class Migration(migrations.Migration):
    dependencies = [
        ("Account", "0016_province"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="municipality",
            options={
                "ordering": ["province__name", "municipality_name"],
                "verbose_name": "Municipality",
                "verbose_name_plural": "Municipalities",
            },
        ),
        # 1. Drop unique_together constraint
        migrations.AlterUniqueTogether(
            name="municipality",
            unique_together=set(),
        ),
        # 2. Rename province column to old_province
        migrations.RenameField(
            model_name="municipality",
            old_name="province",
            new_name="old_province",
        ),
        # 3. Add nullable ForeignKey field province
        migrations.AddField(
            model_name="municipality",
            name="province",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="municipalities",
                to="Account.province",
            ),
        ),
        # 4. Migrate data
        migrations.RunPython(migrate_provinces, reverse_code=migrations.RunPython.noop),
        # 5. Remove old_province CharField
        migrations.RemoveField(
            model_name="municipality",
            name="old_province",
        ),
        # 6. Make province ForeignKey non-nullable
        migrations.AlterField(
            model_name="municipality",
            name="province",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="municipalities",
                to="Account.province",
            ),
        ),
        # 7. Re-create unique_together constraint referencing ForeignKey province
        migrations.AlterUniqueTogether(
            name="municipality",
            unique_together={("province", "municipality_name", "code")},
        ),
    ]
