# Generated by Django 5.2.12 on 2026-07-01 05:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "Account",
            "0017_alter_municipality_options_municipality_old_province_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="account",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                help_text="User who created/invited this account",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_accounts",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
