# Generated by Django 5.2.6 on 2025-10-21 06:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import app.BillOfQuantities.models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("Project", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Bill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When this record was created"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="When this record was last modified"
                    ),
                ),
                (
                    "deleted",
                    models.BooleanField(default=False, help_text="Soft delete flag"),
                ),
                ("name", models.CharField(max_length=100)),
            ],
            options={
                "verbose_name": "Bill",
                "verbose_name_plural": "Bills",
            },
        ),
        migrations.CreateModel(
            name="Package",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When this record was created"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="When this record was last modified"
                    ),
                ),
                (
                    "deleted",
                    models.BooleanField(default=False, help_text="Soft delete flag"),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "bill",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="packages",
                        to="BillOfQuantities.bill",
                    ),
                ),
            ],
            options={
                "verbose_name": "Package",
                "verbose_name_plural": "Packages",
            },
        ),
        migrations.CreateModel(
            name="LineItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When this record was created"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="When this record was last modified"
                    ),
                ),
                (
                    "deleted",
                    models.BooleanField(default=False, help_text="Soft delete flag"),
                ),
                ("row_index", models.IntegerField()),
                ("item_number", models.CharField(blank=True, max_length=100)),
                ("payment_reference", models.CharField(blank=True, max_length=100)),
                ("description", models.TextField(blank=True)),
                ("is_work", models.BooleanField(default=False)),
                ("unit_measurement", models.CharField(blank=True, max_length=10)),
                (
                    "unit_price",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=10),
                ),
                (
                    "budgeted_quantity",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=10),
                ),
                (
                    "total_price",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=10),
                ),
                ("addendum", models.BooleanField(default=False)),
                (
                    "bill",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="line_items",
                        to="BillOfQuantities.bill",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="line_items",
                        to="Project.project",
                    ),
                ),
                (
                    "package",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="line_items",
                        to="BillOfQuantities.package",
                    ),
                ),
            ],
            options={
                "verbose_name": "Line Item",
                "verbose_name_plural": "Line Items",
                "ordering": ["row_index"],
            },
        ),
        migrations.CreateModel(
            name="PaymentCertificate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When this record was created"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="When this record was last modified"
                    ),
                ),
                (
                    "deleted",
                    models.BooleanField(default=False, help_text="Soft delete flag"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("SUBMITTED", "Submitted"),
                            ("APPROVED", "Approved"),
                            ("REJECTED", "Rejected"),
                        ],
                        default="DRAFT",
                        max_length=10,
                    ),
                ),
                ("certificate_number", models.IntegerField()),
                (
                    "notes",
                    models.TextField(
                        blank=True, default="", help_text="Additional notes or comments"
                    ),
                ),
                (
                    "pdf",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to=app.BillOfQuantities.models.PaymentCertificate.upload_to,
                    ),
                ),
                (
                    "abridged_pdf",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to=app.BillOfQuantities.models.PaymentCertificate.upload_to,
                    ),
                ),
                ("pdf_generating", models.BooleanField(default=False)),
                ("abridged_pdf_generating", models.BooleanField(default=False)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payment_certificates",
                        to="Project.project",
                    ),
                ),
            ],
            options={
                "verbose_name": "Payment Certificate",
                "verbose_name_plural": "Payment Certificates",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ActualTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When this record was created"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="When this record was last modified"
                    ),
                ),
                (
                    "deleted",
                    models.BooleanField(default=False, help_text="Soft delete flag"),
                ),
                ("quantity", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "unit_price",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=10),
                ),
                (
                    "total_price",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=10),
                ),
                ("approved", models.BooleanField(default=False)),
                ("claimed", models.BooleanField(default=False)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_actual_transactions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "captured_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="captured_actual_transactions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "line_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="actual_transactions",
                        to="BillOfQuantities.lineitem",
                    ),
                ),
                (
                    "payment_certificate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="actual_transactions",
                        to="BillOfQuantities.paymentcertificate",
                    ),
                ),
            ],
            options={
                "verbose_name": "Actual Transaction",
                "verbose_name_plural": "Actual Transactions",
                "ordering": ["line_item__row_index"],
            },
        ),
        migrations.CreateModel(
            name="Structure",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When this record was created"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="When this record was last modified"
                    ),
                ),
                (
                    "deleted",
                    models.BooleanField(default=False, help_text="Soft delete flag"),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, default="")),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="structures",
                        to="Project.project",
                    ),
                ),
            ],
            options={
                "verbose_name": "Structure",
                "verbose_name_plural": "Structures",
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="lineitem",
            name="structure",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="line_items",
                to="BillOfQuantities.structure",
            ),
        ),
        migrations.AddField(
            model_name="bill",
            name="structure",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bills",
                to="BillOfQuantities.structure",
            ),
        ),
        migrations.AddIndex(
            model_name="paymentcertificate",
            index=models.Index(
                fields=["certificate_number", "status"],
                name="BillOfQuant_certifi_388239_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="paymentcertificate",
            index=models.Index(
                fields=["project", "certificate_number"],
                name="BillOfQuant_project_b1ec90_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="paymentcertificate",
            unique_together={("project", "certificate_number")},
        ),
        migrations.AddIndex(
            model_name="actualtransaction",
            index=models.Index(
                fields=["payment_certificate", "line_item"],
                name="BillOfQuant_payment_cd40f6_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="actualtransaction",
            index=models.Index(
                fields=["line_item", "claimed"], name="BillOfQuant_line_it_de920d_idx"
            ),
        ),
    ]
