# Generated by Django 5.2.6 on 2025-10-21 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BillOfQuantities', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lineitem',
            name='special_item',
            field=models.BooleanField(default=False),
        ),
    ]
