# Generated by Django 5.2.6 on 2025-10-06 08:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("BillOfQuantities", "0002_bill_package_lineitem"),
    ]

    operations = [
        migrations.AddField(
            model_name="lineitem",
            name="bill",
            field=models.ForeignKey(
                default="",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="line_items",
                to="BillOfQuantities.bill",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="lineitem",
            name="structure",
            field=models.ForeignKey(
                default="",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="line_items",
                to="BillOfQuantities.structure",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="lineitem",
            name="package",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="line_items",
                to="BillOfQuantities.package",
            ),
        ),
    ]
