# Generated by Django 5.2.6 on 2025-10-09 13:30

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("BillOfQuantities", "0003_alter_actualtransaction_approved_by_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="actualtransaction",
            options={
                "ordering": ["line_item__row_index"],
                "verbose_name": "Actual Transaction",
                "verbose_name_plural": "Actual Transactions",
            },
        ),
    ]
