# Generated by Django 5.2.6 on 2025-10-06 08:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("BillOfQuantities", "0003_lineitem_bill_lineitem_structure_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lineitem",
            name="budgeted_quantity",
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name="lineitem",
            name="description",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="lineitem",
            name="payment_reference",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="lineitem",
            name="total_price",
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name="lineitem",
            name="unit_measurement",
            field=models.CharField(
                blank=True,
                choices=[
                    ("m", "Meters"),
                    ("m2", "Square Meters"),
                    ("m3", "Cubic Meters"),
                    ("m3.km", "Cubic Meters per Kilometer"),
                    ("g", "Grams"),
                    ("kg", "Kilograms"),
                    ("l", "Liters"),
                    ("t", "Tons"),
                    ("%", "Percentage"),
                    ("q", "Quantity"),
                ],
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="lineitem",
            name="unit_price",
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10),
        ),
    ]
