# Generated by Django 5.2.6 on 2025-10-06 08:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("BillOfQuantities", "0004_alter_lineitem_budgeted_quantity_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lineitem",
            name="item_number",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
