# Generated by Django 5.2.6 on 2025-10-13 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BillOfQuantities', '0004_alter_actualtransaction_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentcertificate',
            name='notes',
            field=models.TextField(blank=True, default='', help_text='Additional notes or comments'),
        ),
    ]
