# Generated by Django 5.2.6 on 2025-10-14 08:13

from django.db import migrations, models

import app.BillOfQuantities.models


class Migration(migrations.Migration):
    dependencies = [
        ("BillOfQuantities", "0005_paymentcertificate_notes"),
    ]

    operations = [
        migrations.AddField(
            model_name="paymentcertificate",
            name="pdf",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to=app.BillOfQuantities.models.PaymentCertificate.upload_to,
            ),
        ),
    ]
