# Generated by Django 5.2.6 on 2025-10-06 09:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BillOfQuantities', '0005_alter_lineitem_item_number'),
        ('Project', '0002_project_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='lineitem',
            name='project',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='line_items', to='Project.project'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='lineitem',
            name='unit_measurement',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
