# Generated by Django 5.2.6 on 2025-11-25 08:01

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("BillOfQuantities", "0006_forecast_forecasttransaction_and_more"),
        ("Project", "0008_project_end_date_project_start_date_plannedvalue"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="forecast",
            unique_together={("project", "period")},
        ),
    ]
