# Generated by Django 5.2.6 on 2025-10-21 06:35

import app.BillOfQuantities.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BillOfQuantities', '0006_paymentcertificate_pdf'),
        ('Project', '0006_project_contract_clause_project_contract_number_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentcertificate',
            name='abridged_pdf',
            field=models.FileField(blank=True, null=True, upload_to=app.BillOfQuantities.models.PaymentCertificate.upload_to),
        ),
        migrations.AddField(
            model_name='paymentcertificate',
            name='abridged_pdf_generating',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='paymentcertificate',
            name='pdf_generating',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterUniqueTogether(
            name='paymentcertificate',
            unique_together={('project', 'certificate_number')},
        ),
        migrations.AddIndex(
            model_name='actualtransaction',
            index=models.Index(fields=['payment_certificate', 'line_item'], name='BillOfQuant_payment_cd40f6_idx'),
        ),
        migrations.AddIndex(
            model_name='actualtransaction',
            index=models.Index(fields=['line_item', 'claimed'], name='BillOfQuant_line_it_de920d_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentcertificate',
            index=models.Index(fields=['certificate_number', 'status'], name='BillOfQuant_certifi_388239_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentcertificate',
            index=models.Index(fields=['project', 'certificate_number'], name='BillOfQuant_project_b1ec90_idx'),
        ),
    ]
