# Generated by Django 5.2.6 on 2025-10-20 07:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("BillOfQuantities", "0006_paymentcertificate_pdf"),
    ]

    operations = [
        migrations.AlterField(
            model_name="paymentcertificate",
            name="certificate_number",
            field=models.IntegerField(unique=True),
        ),
    ]
