# Generated by Django 5.2.6 on 2025-11-28 11:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("BillOfQuantities", "0007_alter_forecast_unique_together"),
    ]

    operations = [
        migrations.AddField(
            model_name="forecast",
            name="notes",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="forecasttransaction",
            name="notes",
            field=models.TextField(blank=True),
        ),
    ]
