# Generated by Django 5.2.6 on 2025-10-20 14:37

from django.db import migrations, models

import app.BillOfQuantities.models


class Migration(migrations.Migration):
    dependencies = [
        (
            "BillOfQuantities",
            "0008_actualtransaction_billofquant_payment_cd40f6_idx_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="paymentcertificate",
            name="abridged_pdf",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to=app.BillOfQuantities.models.PaymentCertificate.upload_to,
            ),
        ),
    ]
