# Generated by Django 5.2.6 on 2025-10-20 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BillOfQuantities', '0009_paymentcertificate_abridged_pdf'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentcertificate',
            name='abridged_pdf_generating',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='paymentcertificate',
            name='pdf_generating',
            field=models.BooleanField(default=False),
        ),
    ]
