# Generated by Django 5.2.6 on 2025-12-01 14:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import app.BillOfQuantities.models.contract_models


class Migration(migrations.Migration):
    dependencies = [
        ("BillOfQuantities", "0009_add_is_final_to_payment_certificate"),
        ("Project", "0011_project_advance_payment_percentage_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ContractVariation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When this record was created"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="When this record was last modified"
                    ),
                ),
                (
                    "deleted",
                    models.BooleanField(default=False, help_text="Soft delete flag"),
                ),
                (
                    "variation_number",
                    models.CharField(
                        help_text="Unique variation reference number", max_length=50
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Brief title describing the variation", max_length=255
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Detailed description of the variation",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("SCOPE_CHANGE", "Scope Change"),
                            ("DESIGN_CHANGE", "Design Change"),
                            ("SITE_CONDITIONS", "Unforeseen Site Conditions"),
                            ("CLIENT_REQUEST", "Client Request"),
                            ("REGULATORY", "Regulatory Requirement"),
                            ("ERROR_OMISSION", "Error/Omission in Documents"),
                            ("FORCE_MAJEURE", "Force Majeure"),
                            ("OTHER", "Other"),
                        ],
                        default="OTHER",
                        help_text="Category of variation",
                        max_length=30,
                    ),
                ),
                (
                    "variation_type",
                    models.CharField(
                        choices=[
                            ("TIME", "Time Extension"),
                            ("AMOUNT", "Cost Variation"),
                            ("BOTH", "Time and Cost"),
                        ],
                        default="AMOUNT",
                        help_text="Whether this is a time, cost, or combined variation",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("SUBMITTED", "Submitted"),
                            ("UNDER_REVIEW", "Under Review"),
                            ("APPROVED", "Approved"),
                            ("REJECTED", "Rejected"),
                        ],
                        default="DRAFT",
                        help_text="Current status of the variation",
                        max_length=20,
                    ),
                ),
                (
                    "time_extension_days",
                    models.IntegerField(
                        blank=True,
                        help_text="Number of days for time extension",
                        null=True,
                    ),
                ),
                (
                    "original_completion_date",
                    models.DateField(
                        blank=True,
                        help_text="Original project completion date before this variation",
                        null=True,
                    ),
                ),
                (
                    "revised_completion_date",
                    models.DateField(
                        blank=True,
                        help_text="Revised completion date after this variation",
                        null=True,
                    ),
                ),
                (
                    "variation_amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Amount of cost variation (positive for increase, negative for decrease)",
                        max_digits=15,
                        null=True,
                    ),
                ),
                (
                    "date_identified",
                    models.DateField(
                        blank=True,
                        help_text="Date the variation was identified",
                        null=True,
                    ),
                ),
                (
                    "date_submitted",
                    models.DateField(
                        blank=True,
                        help_text="Date variation was submitted for approval",
                        null=True,
                    ),
                ),
                (
                    "date_approved",
                    models.DateField(
                        blank=True, help_text="Date variation was approved", null=True
                    ),
                ),
                (
                    "attachment",
                    models.FileField(
                        blank=True,
                        help_text="Supporting documentation for the variation",
                        null=True,
                        upload_to=app.BillOfQuantities.models.contract_models.ContractVariation.upload_to,
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True, default="", help_text="Additional notes or comments"
                    ),
                ),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_variations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        help_text="Project this variation belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contract_variations",
                        to="Project.project",
                    ),
                ),
                (
                    "submitted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="submitted_variations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Contract Variation",
                "verbose_name_plural": "Contract Variations",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Escalation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When this record was created"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="When this record was last modified"
                    ),
                ),
                (
                    "deleted",
                    models.BooleanField(default=False, help_text="Soft delete flag"),
                ),
                (
                    "transaction_type",
                    models.CharField(
                        choices=[
                            ("DEBIT", "Debit (Add)"),
                            ("CREDIT", "Credit (Subtract)"),
                        ],
                        default="DEBIT",
                        help_text="Whether this adds to or subtracts from the balance",
                        max_length=10,
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Transaction amount (always positive)",
                        max_digits=15,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Description of the transaction",
                    ),
                ),
                (
                    "date",
                    models.DateField(
                        blank=True, help_text="Date of the transaction", null=True
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True, default="", help_text="Additional notes"
                    ),
                ),
                (
                    "escalation_type",
                    models.CharField(
                        choices=[
                            ("LABOUR", "Labour Cost Escalation"),
                            ("MATERIAL", "Material Cost Escalation"),
                            ("FUEL", "Fuel Cost Escalation"),
                            ("COMBINED", "Combined Escalation"),
                            ("INDEX_BASED", "Index-Based Escalation"),
                        ],
                        default="COMBINED",
                        help_text="Type of escalation",
                        max_length=20,
                    ),
                ),
                (
                    "base_date",
                    models.DateField(
                        blank=True,
                        help_text="Base date for escalation calculation",
                        null=True,
                    ),
                ),
                (
                    "current_date",
                    models.DateField(
                        blank=True,
                        help_text="Current/calculation date for escalation",
                        null=True,
                    ),
                ),
                (
                    "base_index",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        help_text="Base index value",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "current_index",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        help_text="Current index value",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "escalation_factor",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        help_text="Calculated escalation factor",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "work_value_basis",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Work value escalation is applied to",
                        max_digits=15,
                        null=True,
                    ),
                ),
                (
                    "formula_reference",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Reference to contract escalation formula",
                        max_length=100,
                    ),
                ),
                (
                    "captured_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="captured_%(class)s_transactions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "payment_certificate",
                    models.ForeignKey(
                        help_text="Payment certificate this transaction is linked to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_transactions",
                        to="BillOfQuantities.paymentcertificate",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        help_text="Project this item belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_items",
                        to="Project.project",
                    ),
                ),
            ],
            options={
                "verbose_name": "Escalation",
                "verbose_name_plural": "Escalations",
                "ordering": ["payment_certificate__certificate_number", "created_at"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="MaterialsOnSite",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When this record was created"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="When this record was last modified"
                    ),
                ),
                (
                    "deleted",
                    models.BooleanField(default=False, help_text="Soft delete flag"),
                ),
                (
                    "transaction_type",
                    models.CharField(
                        choices=[
                            ("DEBIT", "Debit (Add)"),
                            ("CREDIT", "Credit (Subtract)"),
                        ],
                        default="DEBIT",
                        help_text="Whether this adds to or subtracts from the balance",
                        max_length=10,
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Transaction amount (always positive)",
                        max_digits=15,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Description of the transaction",
                    ),
                ),
                (
                    "date",
                    models.DateField(
                        blank=True, help_text="Date of the transaction", null=True
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True, default="", help_text="Additional notes"
                    ),
                ),
                (
                    "material_status",
                    models.CharField(
                        choices=[
                            ("CLAIMED", "Claimed"),
                            ("INCORPORATED", "Incorporated into Works"),
                            ("REMOVED", "Removed from Site"),
                        ],
                        default="CLAIMED",
                        help_text="Current status of the material",
                        max_length=20,
                    ),
                ),
                (
                    "material_description",
                    models.CharField(
                        help_text="Description of the material", max_length=500
                    ),
                ),
                (
                    "quantity",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        help_text="Quantity of material",
                        max_digits=15,
                        null=True,
                    ),
                ),
                (
                    "unit",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Unit of measurement",
                        max_length=20,
                    ),
                ),
                (
                    "unit_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Unit price of material",
                        max_digits=15,
                        null=True,
                    ),
                ),
                (
                    "delivery_note_reference",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Delivery note or invoice reference",
                        max_length=100,
                    ),
                ),
                (
                    "storage_location",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Location where material is stored on site",
                        max_length=255,
                    ),
                ),
                (
                    "captured_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="captured_%(class)s_transactions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "payment_certificate",
                    models.ForeignKey(
                        help_text="Payment certificate this transaction is linked to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_transactions",
                        to="BillOfQuantities.paymentcertificate",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        help_text="Project this item belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_items",
                        to="Project.project",
                    ),
                ),
            ],
            options={
                "verbose_name": "Materials on Site",
                "verbose_name_plural": "Materials on Site",
                "ordering": ["payment_certificate__certificate_number", "created_at"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Retention",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When this record was created"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="When this record was last modified"
                    ),
                ),
                (
                    "deleted",
                    models.BooleanField(default=False, help_text="Soft delete flag"),
                ),
                (
                    "transaction_type",
                    models.CharField(
                        choices=[
                            ("DEBIT", "Debit (Add)"),
                            ("CREDIT", "Credit (Subtract)"),
                        ],
                        default="DEBIT",
                        help_text="Whether this adds to or subtracts from the balance",
                        max_length=10,
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Transaction amount (always positive)",
                        max_digits=15,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Description of the transaction",
                    ),
                ),
                (
                    "date",
                    models.DateField(
                        blank=True, help_text="Date of the transaction", null=True
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True, default="", help_text="Additional notes"
                    ),
                ),
                (
                    "retention_type",
                    models.CharField(
                        choices=[
                            ("WITHHELD", "Retention Withheld"),
                            ("RELEASE_PRACTICAL", "Release at Practical Completion"),
                            ("RELEASE_FINAL", "Release at Final Completion"),
                            ("RELEASE_PARTIAL", "Partial Release"),
                        ],
                        default="WITHHELD",
                        help_text="Type of retention transaction",
                        max_length=30,
                    ),
                ),
                (
                    "retention_percentage",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Retention percentage applied",
                        max_digits=5,
                        null=True,
                    ),
                ),
                (
                    "work_value_basis",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Work value this retention is calculated from",
                        max_digits=15,
                        null=True,
                    ),
                ),
                (
                    "release_certificate_reference",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Certificate reference for retention release",
                        max_length=100,
                    ),
                ),
                (
                    "captured_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="captured_%(class)s_transactions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "payment_certificate",
                    models.ForeignKey(
                        help_text="Payment certificate this transaction is linked to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_transactions",
                        to="BillOfQuantities.paymentcertificate",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        help_text="Project this item belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_items",
                        to="Project.project",
                    ),
                ),
            ],
            options={
                "verbose_name": "Retention",
                "verbose_name_plural": "Retentions",
                "ordering": ["payment_certificate__certificate_number", "created_at"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="RevisedBaseline",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When this record was created"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="When this record was last modified"
                    ),
                ),
                (
                    "deleted",
                    models.BooleanField(default=False, help_text="Soft delete flag"),
                ),
                (
                    "revision_number",
                    models.IntegerField(default=1, help_text="Revision number"),
                ),
                ("revision_date", models.DateField(help_text="Date of this revision")),
                (
                    "revision_reason",
                    models.CharField(
                        choices=[
                            ("VARIATION", "Contract Variation"),
                            ("EXTENSION", "Time Extension"),
                            ("ACCELERATION", "Acceleration"),
                            ("RE_SEQUENCE", "Re-sequencing of Works"),
                            ("OTHER", "Other"),
                        ],
                        default="OTHER",
                        help_text="Reason for revising the baseline",
                        max_length=30,
                    ),
                ),
                (
                    "reason_description",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Detailed description of revision reason",
                    ),
                ),
                (
                    "original_start_date",
                    models.DateField(
                        blank=True, help_text="Original project start date", null=True
                    ),
                ),
                (
                    "original_completion_date",
                    models.DateField(
                        blank=True,
                        help_text="Original project completion date",
                        null=True,
                    ),
                ),
                (
                    "revised_start_date",
                    models.DateField(
                        blank=True, help_text="Revised project start date", null=True
                    ),
                ),
                (
                    "revised_completion_date",
                    models.DateField(
                        blank=True,
                        help_text="Revised project completion date",
                        null=True,
                    ),
                ),
                (
                    "original_contract_value",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Original contract value before revision",
                        max_digits=15,
                        null=True,
                    ),
                ),
                (
                    "revised_contract_value",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Revised contract value after this revision",
                        max_digits=15,
                        null=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("SUBMITTED", "Submitted for Approval"),
                            ("APPROVED", "Approved"),
                            ("REJECTED", "Rejected"),
                        ],
                        default="DRAFT",
                        max_length=20,
                    ),
                ),
                ("notes", models.TextField(blank=True, default="")),
                ("submitted_on", models.DateTimeField(blank=True, null=True)),
                ("approved_on", models.DateTimeField(blank=True, null=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_revised_baselines",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "linked_variation",
                    models.ForeignKey(
                        blank=True,
                        help_text="Variation that triggered this baseline revision",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="revised_baselines",
                        to="BillOfQuantities.contractvariation",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        help_text="Project this revised baseline belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="revised_baselines",
                        to="Project.project",
                    ),
                ),
                (
                    "submitted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="submitted_revised_baselines",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Revised Baseline",
                "verbose_name_plural": "Revised Baselines",
                "ordering": ["-revision_date", "-revision_number"],
            },
        ),
        migrations.CreateModel(
            name="RevisedBaselineDetail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When this record was created"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="When this record was last modified"
                    ),
                ),
                (
                    "deleted",
                    models.BooleanField(default=False, help_text="Soft delete flag"),
                ),
                ("period", models.DateField(help_text="Period (month) for this value")),
                (
                    "planned_value",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Planned value for this period",
                        max_digits=15,
                    ),
                ),
                (
                    "cumulative_value",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Cumulative planned value up to this period",
                        max_digits=15,
                        null=True,
                    ),
                ),
                ("notes", models.TextField(blank=True, default="")),
                (
                    "revised_baseline",
                    models.ForeignKey(
                        help_text="Parent revised baseline",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="details",
                        to="BillOfQuantities.revisedbaseline",
                    ),
                ),
            ],
            options={
                "verbose_name": "Revised Baseline Detail",
                "verbose_name_plural": "Revised Baseline Details",
                "ordering": ["period"],
            },
        ),
        migrations.CreateModel(
            name="ScheduleForecast",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When this record was created"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="When this record was last modified"
                    ),
                ),
                (
                    "deleted",
                    models.BooleanField(default=False, help_text="Soft delete flag"),
                ),
                (
                    "forecast_date",
                    models.DateField(help_text="Date when this forecast was created"),
                ),
                (
                    "reporting_period",
                    models.DateField(
                        help_text="Reporting period (month) for this forecast"
                    ),
                ),
                (
                    "planned_project_completion",
                    models.DateField(
                        help_text="Current contractual/planned completion date"
                    ),
                ),
                (
                    "forecast_project_completion",
                    models.DateField(
                        help_text="Forecast completion date based on current progress"
                    ),
                ),
                (
                    "overall_percentage_complete",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Overall project percentage complete",
                        max_digits=5,
                        null=True,
                    ),
                ),
                (
                    "planned_percentage_complete",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Planned percentage complete for this date",
                        max_digits=5,
                        null=True,
                    ),
                ),
                (
                    "original_duration_days",
                    models.IntegerField(
                        blank=True,
                        help_text="Original project duration in days",
                        null=True,
                    ),
                ),
                (
                    "elapsed_days",
                    models.IntegerField(
                        blank=True,
                        help_text="Days elapsed since project start",
                        null=True,
                    ),
                ),
                (
                    "remaining_days",
                    models.IntegerField(
                        blank=True,
                        help_text="Remaining days to forecast completion",
                        null=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("SUBMITTED", "Submitted"),
                            ("APPROVED", "Approved"),
                        ],
                        default="DRAFT",
                        max_length=20,
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Analysis notes and observations",
                    ),
                ),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_schedule_forecasts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "captured_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="captured_schedule_forecasts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        help_text="Project this forecast belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="schedule_forecasts",
                        to="Project.project",
                    ),
                ),
            ],
            options={
                "verbose_name": "Schedule Forecast",
                "verbose_name_plural": "Schedule Forecasts",
                "ordering": ["-forecast_date", "-reporting_period"],
            },
        ),
        migrations.CreateModel(
            name="SectionalCompletionDate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When this record was created"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="When this record was last modified"
                    ),
                ),
                (
                    "deleted",
                    models.BooleanField(default=False, help_text="Soft delete flag"),
                ),
                (
                    "section_name",
                    models.CharField(
                        help_text="Name or identifier of the section", max_length=255
                    ),
                ),
                (
                    "section_description",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Description of what this section covers",
                    ),
                ),
                (
                    "section_reference",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Contract clause/reference for this section",
                        max_length=100,
                    ),
                ),
                (
                    "planned_start_date",
                    models.DateField(
                        blank=True,
                        help_text="Planned start date for this section",
                        null=True,
                    ),
                ),
                (
                    "planned_completion_date",
                    models.DateField(
                        help_text="Contractual/planned completion date for this section"
                    ),
                ),
                (
                    "forecast_start_date",
                    models.DateField(
                        blank=True, help_text="Forecast/actual start date", null=True
                    ),
                ),
                (
                    "forecast_completion_date",
                    models.DateField(
                        blank=True, help_text="Forecast completion date", null=True
                    ),
                ),
                (
                    "actual_completion_date",
                    models.DateField(
                        blank=True,
                        help_text="Actual completion date (when completed)",
                        null=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("NOT_STARTED", "Not Started"),
                            ("IN_PROGRESS", "In Progress"),
                            ("COMPLETED", "Completed"),
                            ("DELAYED", "Delayed"),
                        ],
                        default="NOT_STARTED",
                        max_length=20,
                    ),
                ),
                (
                    "section_value",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Value of work in this section",
                        max_digits=15,
                        null=True,
                    ),
                ),
                (
                    "percentage_complete",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Percentage complete (0-100)",
                        max_digits=5,
                        null=True,
                    ),
                ),
                (
                    "has_penalty",
                    models.BooleanField(
                        default=False,
                        help_text="Whether penalties apply for late completion",
                    ),
                ),
                (
                    "penalty_rate",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Penalty rate per day/week",
                        max_digits=15,
                        null=True,
                    ),
                ),
                (
                    "penalty_period",
                    models.CharField(
                        blank=True,
                        default="DAY",
                        help_text="Period for penalty calculation (DAY, WEEK, MONTH)",
                        max_length=20,
                    ),
                ),
                (
                    "penalty_cap",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Maximum penalty amount",
                        max_digits=15,
                        null=True,
                    ),
                ),
                ("notes", models.TextField(blank=True, default="")),
                (
                    "project",
                    models.ForeignKey(
                        help_text="Project this section belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sectional_completion_dates",
                        to="Project.project",
                    ),
                ),
            ],
            options={
                "verbose_name": "Sectional Completion Date",
                "verbose_name_plural": "Sectional Completion Dates",
                "ordering": ["planned_completion_date"],
            },
        ),
        migrations.CreateModel(
            name="ScheduleForecastSection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When this record was created"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="When this record was last modified"
                    ),
                ),
                (
                    "deleted",
                    models.BooleanField(default=False, help_text="Soft delete flag"),
                ),
                (
                    "forecast_completion_date",
                    models.DateField(
                        help_text="Forecast completion date for this section"
                    ),
                ),
                (
                    "percentage_complete",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Percentage complete at forecast date",
                        max_digits=5,
                        null=True,
                    ),
                ),
                ("notes", models.TextField(blank=True, default="")),
                (
                    "schedule_forecast",
                    models.ForeignKey(
                        help_text="Parent schedule forecast",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="section_forecasts",
                        to="BillOfQuantities.scheduleforecast",
                    ),
                ),
                (
                    "sectional_completion",
                    models.ForeignKey(
                        help_text="Sectional completion date being forecast",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="forecast_entries",
                        to="BillOfQuantities.sectionalcompletiondate",
                    ),
                ),
            ],
            options={
                "verbose_name": "Schedule Forecast Section",
                "verbose_name_plural": "Schedule Forecast Sections",
                "ordering": ["sectional_completion__planned_completion_date"],
            },
        ),
        migrations.CreateModel(
            name="SpecialItemTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When this record was created"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="When this record was last modified"
                    ),
                ),
                (
                    "deleted",
                    models.BooleanField(default=False, help_text="Soft delete flag"),
                ),
                (
                    "transaction_type",
                    models.CharField(
                        choices=[
                            ("DEBIT", "Debit (Add)"),
                            ("CREDIT", "Credit (Subtract)"),
                        ],
                        default="DEBIT",
                        help_text="Whether this adds to or subtracts from the balance",
                        max_length=10,
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Transaction amount (always positive)",
                        max_digits=15,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Description of the transaction",
                    ),
                ),
                (
                    "date",
                    models.DateField(
                        blank=True, help_text="Date of the transaction", null=True
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True, default="", help_text="Additional notes"
                    ),
                ),
                (
                    "special_item_type",
                    models.CharField(
                        choices=[
                            ("DAYWORK", "Daywork"),
                            ("PRIME_COST", "Prime Cost Sum"),
                            ("PROVISIONAL", "Provisional Sum"),
                            ("CONTINGENCY", "Contingency"),
                            ("PENALTY", "Penalty/Liquidated Damages"),
                            ("BONUS", "Bonus/Incentive"),
                            ("INSURANCE", "Insurance"),
                            ("OTHER", "Other"),
                        ],
                        default="OTHER",
                        help_text="Type of special item",
                        max_length=20,
                    ),
                ),
                (
                    "item_reference",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Reference to contract clause or BOQ item",
                        max_length=100,
                    ),
                ),
                (
                    "budget_amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Original budget/provisional amount",
                        max_digits=15,
                        null=True,
                    ),
                ),
                (
                    "captured_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="captured_%(class)s_transactions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "payment_certificate",
                    models.ForeignKey(
                        help_text="Payment certificate this transaction is linked to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_transactions",
                        to="BillOfQuantities.paymentcertificate",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        help_text="Project this item belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_items",
                        to="Project.project",
                    ),
                ),
            ],
            options={
                "verbose_name": "Special Item Transaction",
                "verbose_name_plural": "Special Item Transactions",
                "ordering": ["payment_certificate__certificate_number", "created_at"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="AdvancePayment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When this record was created"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="When this record was last modified"
                    ),
                ),
                (
                    "deleted",
                    models.BooleanField(default=False, help_text="Soft delete flag"),
                ),
                (
                    "transaction_type",
                    models.CharField(
                        choices=[
                            ("DEBIT", "Debit (Add)"),
                            ("CREDIT", "Credit (Subtract)"),
                        ],
                        default="DEBIT",
                        help_text="Whether this adds to or subtracts from the balance",
                        max_length=10,
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Transaction amount (always positive)",
                        max_digits=15,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Description of the transaction",
                    ),
                ),
                (
                    "date",
                    models.DateField(
                        blank=True, help_text="Date of the transaction", null=True
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True, default="", help_text="Additional notes"
                    ),
                ),
                (
                    "original_advance_amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Original total advance amount (for reference)",
                        max_digits=15,
                        null=True,
                    ),
                ),
                (
                    "recovery_method",
                    models.CharField(
                        choices=[
                            ("PERCENTAGE", "Percentage per Certificate"),
                            ("FIXED", "Fixed Amount per Certificate"),
                            ("MANUAL", "Manual Recovery"),
                        ],
                        default="PERCENTAGE",
                        help_text="How the advance will be recovered",
                        max_length=20,
                    ),
                ),
                (
                    "recovery_percentage",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Percentage to recover per certificate (if percentage method)",
                        max_digits=5,
                        null=True,
                    ),
                ),
                (
                    "guarantee_reference",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Bank guarantee or security reference",
                        max_length=100,
                    ),
                ),
                (
                    "guarantee_expiry",
                    models.DateField(
                        blank=True,
                        help_text="Expiry date of advance payment guarantee",
                        null=True,
                    ),
                ),
                (
                    "captured_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="captured_%(class)s_transactions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "payment_certificate",
                    models.ForeignKey(
                        help_text="Payment certificate this transaction is linked to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_transactions",
                        to="BillOfQuantities.paymentcertificate",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        help_text="Project this item belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_items",
                        to="Project.project",
                    ),
                ),
            ],
            options={
                "verbose_name": "Advance Payment",
                "verbose_name_plural": "Advance Payments",
                "ordering": ["payment_certificate__certificate_number", "created_at"],
                "abstract": False,
                "indexes": [
                    models.Index(
                        fields=["project", "payment_certificate"],
                        name="BillOfQuant_project_1322ce_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="BaselineCashflow",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When this record was created"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="When this record was last modified"
                    ),
                ),
                (
                    "deleted",
                    models.BooleanField(default=False, help_text="Soft delete flag"),
                ),
                (
                    "version",
                    models.IntegerField(
                        default=1, help_text="Version number of this baseline"
                    ),
                ),
                (
                    "period",
                    models.DateField(
                        help_text="Period (month) for this cashflow value"
                    ),
                ),
                (
                    "planned_value",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Planned value for this period",
                        max_digits=15,
                    ),
                ),
                (
                    "cumulative_value",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Cumulative planned value up to this period",
                        max_digits=15,
                        null=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("APPROVED", "Approved"),
                            ("SUPERSEDED", "Superseded"),
                        ],
                        default="DRAFT",
                        max_length=20,
                    ),
                ),
                ("notes", models.TextField(blank=True, default="")),
                ("approved_on", models.DateTimeField(blank=True, null=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_baseline_cashflows",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        help_text="Project this cashflow belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="baseline_cashflows",
                        to="Project.project",
                    ),
                ),
            ],
            options={
                "verbose_name": "Baseline Cashflow",
                "verbose_name_plural": "Baseline Cashflows",
                "ordering": ["period"],
                "indexes": [
                    models.Index(
                        fields=["project", "version"],
                        name="BillOfQuant_project_3c502c_idx",
                    ),
                    models.Index(
                        fields=["period"], name="BillOfQuant_period_b1140f_idx"
                    ),
                ],
                "unique_together": {("project", "version", "period")},
            },
        ),
        migrations.CreateModel(
            name="CashflowForecast",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When this record was created"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="When this record was last modified"
                    ),
                ),
                (
                    "deleted",
                    models.BooleanField(default=False, help_text="Soft delete flag"),
                ),
                (
                    "forecast_date",
                    models.DateField(help_text="Date when this forecast was created"),
                ),
                (
                    "forecast_period",
                    models.DateField(help_text="Period (month) being forecast"),
                ),
                (
                    "forecast_value",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Forecasted value for this period",
                        max_digits=15,
                    ),
                ),
                (
                    "cumulative_forecast",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Cumulative forecast up to this period",
                        max_digits=15,
                        null=True,
                    ),
                ),
                (
                    "baseline_value",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Original baseline value for comparison",
                        max_digits=15,
                        null=True,
                    ),
                ),
                (
                    "variance",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Variance from baseline (forecast - baseline)",
                        max_digits=15,
                        null=True,
                    ),
                ),
                (
                    "forecast_completion_date",
                    models.DateField(
                        blank=True,
                        help_text="Forecasted project completion date",
                        null=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("SUBMITTED", "Submitted"),
                            ("APPROVED", "Approved"),
                        ],
                        default="DRAFT",
                        max_length=20,
                    ),
                ),
                ("notes", models.TextField(blank=True, default="")),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_cashflow_forecasts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "captured_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="captured_cashflow_forecasts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        help_text="Project this forecast belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cashflow_forecasts",
                        to="Project.project",
                    ),
                ),
            ],
            options={
                "verbose_name": "Cashflow Forecast",
                "verbose_name_plural": "Cashflow Forecasts",
                "ordering": ["forecast_period"],
                "indexes": [
                    models.Index(
                        fields=["project", "forecast_date"],
                        name="BillOfQuant_project_2b3289_idx",
                    ),
                    models.Index(
                        fields=["forecast_period"],
                        name="BillOfQuant_forecas_c7a57c_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="ContractualCorrespondence",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When this record was created"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="When this record was last modified"
                    ),
                ),
                (
                    "deleted",
                    models.BooleanField(default=False, help_text="Soft delete flag"),
                ),
                (
                    "reference_number",
                    models.CharField(
                        help_text="Correspondence reference number", max_length=100
                    ),
                ),
                (
                    "subject",
                    models.CharField(
                        help_text="Subject of the correspondence", max_length=500
                    ),
                ),
                (
                    "correspondence_type",
                    models.CharField(
                        choices=[
                            ("LETTER", "Letter"),
                            ("EMAIL", "Email"),
                            ("NOTICE", "Formal Notice"),
                            ("INSTRUCTION", "Site Instruction"),
                            ("REQUEST", "Request for Information"),
                            ("CLAIM", "Claim Submission"),
                            ("RESPONSE", "Response"),
                            ("MEETING_MINUTES", "Meeting Minutes"),
                            ("REPORT", "Report"),
                            ("OTHER", "Other"),
                        ],
                        default="LETTER",
                        help_text="Type of correspondence",
                        max_length=30,
                    ),
                ),
                (
                    "direction",
                    models.CharField(
                        choices=[
                            ("INCOMING", "Incoming"),
                            ("OUTGOING", "Outgoing"),
                            ("INTERNAL", "Internal"),
                        ],
                        default="OUTGOING",
                        help_text="Direction of correspondence",
                        max_length=20,
                    ),
                ),
                (
                    "date_of_correspondence",
                    models.DateField(help_text="Date of the correspondence"),
                ),
                (
                    "date_received",
                    models.DateField(
                        blank=True,
                        help_text="Date correspondence was received (for incoming)",
                        null=True,
                    ),
                ),
                (
                    "sender",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Name/organization of sender",
                        max_length=255,
                    ),
                ),
                (
                    "recipient",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Name/organization of recipient",
                        max_length=255,
                    ),
                ),
                (
                    "summary",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Brief summary of the correspondence content",
                    ),
                ),
                (
                    "attachment",
                    models.FileField(
                        blank=True,
                        help_text="Attached document",
                        null=True,
                        upload_to=app.BillOfQuantities.models.contract_models.ContractualCorrespondence.upload_to,
                    ),
                ),
                (
                    "requires_response",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this correspondence requires a response",
                    ),
                ),
                (
                    "response_due_date",
                    models.DateField(
                        blank=True,
                        help_text="Due date for response if required",
                        null=True,
                    ),
                ),
                (
                    "response_sent",
                    models.BooleanField(
                        default=False, help_text="Whether response has been sent"
                    ),
                ),
                (
                    "response_date",
                    models.DateField(
                        blank=True, help_text="Date response was sent", null=True
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True, default="", help_text="Additional notes"
                    ),
                ),
                (
                    "logged_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="logged_correspondences",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        help_text="Project this correspondence belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contractual_correspondences",
                        to="Project.project",
                    ),
                ),
                (
                    "related_correspondence",
                    models.ForeignKey(
                        blank=True,
                        help_text="Related correspondence (e.g., original letter this responds to)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="follow_up_correspondences",
                        to="BillOfQuantities.contractualcorrespondence",
                    ),
                ),
            ],
            options={
                "verbose_name": "Contractual Correspondence",
                "verbose_name_plural": "Contractual Correspondences",
                "ordering": ["-date_of_correspondence", "-created_at"],
                "indexes": [
                    models.Index(
                        fields=["project", "correspondence_type"],
                        name="BillOfQuant_project_de2121_idx",
                    ),
                    models.Index(
                        fields=["date_of_correspondence"],
                        name="BillOfQuant_date_of_80fd24_idx",
                    ),
                    models.Index(
                        fields=["requires_response", "response_sent"],
                        name="BillOfQuant_require_7b4077_idx",
                    ),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="contractvariation",
            index=models.Index(
                fields=["project", "status"], name="BillOfQuant_project_f48e94_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="contractvariation",
            index=models.Index(
                fields=["category"], name="BillOfQuant_categor_92af30_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="contractvariation",
            unique_together={("project", "variation_number")},
        ),
        migrations.AddIndex(
            model_name="escalation",
            index=models.Index(
                fields=["project", "escalation_type"],
                name="BillOfQuant_project_040ba5_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="materialsonsite",
            index=models.Index(
                fields=["project", "material_status"],
                name="BillOfQuant_project_11447f_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="retention",
            index=models.Index(
                fields=["project", "retention_type"],
                name="BillOfQuant_project_ceb303_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="revisedbaseline",
            index=models.Index(
                fields=["project", "status"], name="BillOfQuant_project_f9228b_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="revisedbaseline",
            unique_together={("project", "revision_number")},
        ),
        migrations.AlterUniqueTogether(
            name="revisedbaselinedetail",
            unique_together={("revised_baseline", "period")},
        ),
        migrations.AddIndex(
            model_name="scheduleforecast",
            index=models.Index(
                fields=["project", "forecast_date"],
                name="BillOfQuant_project_988d3f_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="scheduleforecast",
            index=models.Index(
                fields=["reporting_period"], name="BillOfQuant_reporti_2ee86e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="sectionalcompletiondate",
            index=models.Index(
                fields=["project", "status"], name="BillOfQuant_project_b73d16_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="sectionalcompletiondate",
            index=models.Index(
                fields=["planned_completion_date"],
                name="BillOfQuant_planned_892bfe_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="specialitemtransaction",
            index=models.Index(
                fields=["project", "special_item_type"],
                name="BillOfQuant_project_fe908c_idx",
            ),
        ),
    ]
