# Generated by Django 5.2.6 on 2025-12-03 09:30

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "BillOfQuantities",
            "0010_contractvariation_escalation_materialsonsite_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="forecast",
            options={
                "ordering": ["-period"],
                "verbose_name": "Forecast",
                "verbose_name_plural": "Forecasts",
            },
        ),
    ]
