# Generated by Django 5.2.6 on 2025-12-03 12:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("BillOfQuantities", "0011_alter_forecast_options"),
        ("Project", "0013_alter_signatories_options_remove_signatories_email_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="paymentcertificate",
            name="status",
            field=models.CharField(
                choices=[
                    ("DRAFT", "Draft"),
                    ("SUBMITTED", "Submitted"),
                    ("APPROVED", "Approved"),
                    ("REJECTED", "Rejected"),
                    ("SIGNATORIES_APPROVED", "Signatories Approved"),
                ],
                default="DRAFT",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="Signatory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When this record was created"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="When this record was last modified"
                    ),
                ),
                (
                    "deleted",
                    models.BooleanField(default=False, help_text="Soft delete flag"),
                ),
                ("approved", models.BooleanField(default=False)),
                ("comments", models.TextField(blank=True, default="")),
                (
                    "payment_certificate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="signatories",
                        to="BillOfQuantities.paymentcertificate",
                    ),
                ),
                (
                    "signatory",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="signatories",
                        to="Project.signatories",
                    ),
                ),
            ],
            options={
                "verbose_name": "Signatory",
                "verbose_name_plural": "Signatories",
                "ordering": ["payment_certificate"],
                "indexes": [
                    models.Index(
                        fields=["payment_certificate", "signatory"],
                        name="BillOfQuant_payment_d609d6_idx",
                    ),
                    models.Index(
                        fields=["signatory", "approved"],
                        name="BillOfQuant_signato_192657_idx",
                    ),
                ],
            },
        ),
    ]
