# Generated by Django 6.0.1 on 2026-01-26 09:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("BillOfQuantities", "0012_alter_paymentcertificate_status_signatory"),
        ("Project", "0030_project_logo"),
    ]

    operations = [
        migrations.CreateModel(
            name="PaymentCertificatePayment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When this record was created"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="When this record was last modified"
                    ),
                ),
                (
                    "deleted",
                    models.BooleanField(default=False, help_text="Soft delete flag"),
                ),
                ("date", models.DateField()),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Project.project",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
