# Generated by Django 6.0.1 on 2026-01-29 17:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import app.BillOfQuantities.models.payment_certificate_models


class Migration(migrations.Migration):
    dependencies = [
        ("BillOfQuantities", "0014_alter_paymentcertificate_options_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PaymentCertificatePhoto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When this record was created"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="When this record was last modified"
                    ),
                ),
                (
                    "deleted",
                    models.BooleanField(default=False, help_text="Soft delete flag"),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Photo title or description", max_length=255
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        help_text="Upload photo file",
                        upload_to=app.BillOfQuantities.models.payment_certificate_models.PaymentCertificatePhoto.upload_to,
                    ),
                ),
                (
                    "payment_certificate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="photos",
                        to="BillOfQuantities.paymentcertificate",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Payment Certificate Photo",
                "verbose_name_plural": "Payment Certificate Photos",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PaymentCertificateWorking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When this record was created"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="When this record was last modified"
                    ),
                ),
                (
                    "deleted",
                    models.BooleanField(default=False, help_text="Soft delete flag"),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Document title or description", max_length=255
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        help_text="Upload working document",
                        upload_to=app.BillOfQuantities.models.payment_certificate_models.PaymentCertificateWorking.upload_to,
                    ),
                ),
                (
                    "payment_certificate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="workings",
                        to="BillOfQuantities.paymentcertificate",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Payment Certificate Working",
                "verbose_name_plural": "Payment Certificate Workings",
                "ordering": ["-created_at"],
            },
        ),
    ]
