# Generated by Django 6.0.1 on 2026-02-02 08:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("BillOfQuantities", "0015_paymentcertificatephoto_paymentcertificateworking"),
    ]

    operations = [
        migrations.AddField(
            model_name="paymentcertificate",
            name="assessment_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
