# Generated by Django 6.0.1 on 2026-02-10 09:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("BillOfQuantities", "0016_paymentcertificate_assessment_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="paymentcertificate",
            name="certificate_number",
            field=models.IntegerField(),
        ),
    ]
