# Generated by Django 6.0.2 on 2026-02-12 09:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("BillOfQuantities", "0017_alter_paymentcertificate_certificate_number"),
        ("Project", "0035_alter_company_tax_number"),
    ]

    operations = [
        migrations.CreateModel(
            name="Claim",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When this record was created"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="When this record was last modified"
                    ),
                ),
                (
                    "deleted",
                    models.BooleanField(default=False, help_text="Soft delete flag"),
                ),
                ("period", models.CharField(max_length=20)),
                (
                    "estimated_claim",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True, default="", help_text="Additional notes or comments"
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="claims",
                        to="Project.project",
                    ),
                ),
            ],
            options={
                "verbose_name": "Claim",
                "verbose_name_plural": "Claims",
                "ordering": ["-period"],
            },
        ),
    ]
