# Generated by Django 6.0.2 on 2026-02-12 09:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("BillOfQuantities", "0018_claim"),
    ]

    operations = [
        migrations.AlterField(
            model_name="claim",
            name="period",
            field=models.DateField(),
        ),
    ]
