# Generated by Django 6.0.2 on 2026-02-22 18:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import app.BillOfQuantities.models.contract_models


class Migration(migrations.Migration):
    dependencies = [
        ("BillOfQuantities", "0019_alter_claim_period"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="contractualcorrespondence",
            name="recipient_user",
            field=models.ForeignKey(
                help_text="Name/organization of recipient",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="correspondence_receivers",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="contractualcorrespondence",
            name="sender_user",
            field=models.ForeignKey(
                help_text="Name/organization of sender",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="correspondence_senders",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.CreateModel(
            name="CorrespondenceDialog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When this record was created"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="When this record was last modified"
                    ),
                ),
                (
                    "deleted",
                    models.BooleanField(default=False, help_text="Soft delete flag"),
                ),
                (
                    "sender",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Name/organization of sender",
                        max_length=255,
                    ),
                ),
                (
                    "recipient",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Name/organization of recipient",
                        max_length=255,
                    ),
                ),
                ("message", models.TextField()),
                (
                    "correspondence",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dialogs",
                        to="BillOfQuantities.contractualcorrespondence",
                    ),
                ),
                (
                    "receiver_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="correspondence_dialog_receivers",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "sender_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="correspondence_dialog_senders",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="CorrespondenceDialogFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When this record was created"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="When this record was last modified"
                    ),
                ),
                (
                    "deleted",
                    models.BooleanField(default=False, help_text="Soft delete flag"),
                ),
                (
                    "file",
                    models.FileField(
                        upload_to=app.BillOfQuantities.models.contract_models.CorrespondenceDialogFile.correspondence_dialog_file_upload_to
                    ),
                ),
                (
                    "dialog",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attachments",
                        to="BillOfQuantities.correspondencedialog",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
