# Generated by Django 6.0.2 on 2026-03-09 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BillOfQuantities', '0021_clear_receivers_senders'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Claim',
        ),
    ]
