# Generated by Django 6.0.3 on 2026-03-31 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BillOfQuantities', '0022_delete_claim'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='forecasttransaction',
            options={'base_manager_name': 'objects'},
        ),
        migrations.AlterModelOptions(
            name='paymentcertificatepayment',
            options={'base_manager_name': 'objects'},
        ),
    ]
