# Generated by Django 5.2.12 on 2026-06-11 11:38

from django.db import migrations, models

import app.BillOfQuantities.models.payment_certificate_models


class Migration(migrations.Migration):
    dependencies = [
        ("BillOfQuantities", "0024_alter_specialitemtransaction_special_item_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="paymentcertificate",
            name="abridged_xlsx",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to=app.BillOfQuantities.models.payment_certificate_models.PaymentCertificate.upload_to,
            ),
        ),
        migrations.AddField(
            model_name="paymentcertificate",
            name="abridged_xlsx_generating",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="paymentcertificate",
            name="xlsx",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to=app.BillOfQuantities.models.payment_certificate_models.PaymentCertificate.upload_to,
            ),
        ),
        migrations.AddField(
            model_name="paymentcertificate",
            name="xlsx_generating",
            field=models.BooleanField(default=False),
        ),
    ]
