# Generated by Django 5.2.12 on 2026-06-18 10:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("BillOfQuantities", "0025_paymentcertificate_abridged_xlsx_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="bill",
            name="bill_number",
            field=models.CharField(blank=True, default="", max_length=50),
        ),
    ]
