# Generated by Django 5.2.12 on 2026-06-25 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("BillOfQuantities", "0026_bill_bill_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="actualtransaction",
            name="quantity",
            field=models.DecimalField(decimal_places=10, max_digits=20),
        ),
        migrations.AlterField(
            model_name="forecasttransaction",
            name="quantity",
            field=models.DecimalField(decimal_places=10, max_digits=20),
        ),
        migrations.AlterField(
            model_name="lineitem",
            name="budgeted_quantity",
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=20),
        ),
    ]
