# Generated by Django 5.2.6 on 2025-10-29 12:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("BillOfQuantities", "0005_paymentcertificate_approved_by_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Cost",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When this record was created"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="When this record was last modified"
                    ),
                ),
                (
                    "deleted",
                    models.BooleanField(default=False, help_text="Soft delete flag"),
                ),
                ("date", models.DateField()),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("MATERIAL", "Material"),
                            ("LABOUR", "Labour"),
                            ("EQUIPMENT", "Equipment"),
                            ("PLANT", "Plant"),
                            ("OTHER", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                ("description", models.CharField(max_length=100)),
                ("quantity", models.DecimalField(decimal_places=2, max_digits=10)),
                ("unit_price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("gross", models.DecimalField(decimal_places=2, max_digits=10)),
                ("vat", models.BooleanField(default=True)),
                ("vat_amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("net", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "bill",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="costs",
                        to="BillOfQuantities.bill",
                    ),
                ),
            ],
            options={
                "verbose_name": "Cost",
                "verbose_name_plural": "Costs",
            },
        ),
        migrations.CreateModel(
            name="ActualCost",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When this record was created"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="When this record was last modified"
                    ),
                ),
                (
                    "deleted",
                    models.BooleanField(default=False, help_text="Soft delete flag"),
                ),
                ("date", models.DateField()),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("MATERIAL", "Material"),
                            ("LABOUR", "Labour"),
                            ("EQUIPMENT", "Equipment"),
                            ("PLANT", "Plant"),
                            ("OTHER", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                ("description", models.CharField(max_length=100)),
                ("quantity", models.DecimalField(decimal_places=2, max_digits=10)),
                ("unit_price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("gross", models.DecimalField(decimal_places=2, max_digits=10)),
                ("vat", models.BooleanField(default=True)),
                ("vat_amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("net", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "bill",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="actual_costs",
                        to="BillOfQuantities.bill",
                    ),
                ),
                (
                    "cost",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="actual_costs",
                        to="Cost.cost",
                    ),
                ),
            ],
            options={
                "verbose_name": "Actual Cost",
                "verbose_name_plural": "Actual Costs",
            },
        ),
    ]
